### PR TITLE
[bitnami/harbor] fix: core-secret-envvars.yaml now handles variables individually

### LINKED ISSUE #27483: [bitnami/harbor]  exporter.existingEnvVarsSecret should be core.existingEnvVarsSecret
### Name and Version

bitnami/harbor 21.4.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Create the following resource:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret-vars
  namespace: harbor
type: Opaque
stringData:
  CSRF_KEY: "YxBzUfRn+Wa9hTVDJzLYDEH0W9syZuodXCmPwo6POYw="
  HARBOR_ADMIN_PASSWORD: "12345678Test"
  POSTGRESQL_PASSWORD: "secure-postgres-password"
  REGISTRY_CREDENTIAL_USERNAME: "registryuser"
  REGISTRY_CREDENTIAL_PASSWORD: "passwordfortest"

```
2. Install the chart with the values.yaml below overriding the default values of the upstream values.yaml

### Are you using any custom parameters or values?

```yaml
harbor:
 
  nameOverride: "harbor"

  externalURL: https://core.harbor.example.com

  logLevel: warn

  exposureType: ingress

  service:
    ports:
      http: 80
      https: 443

  core:
    existingEnvVarsSecret: "harbor-secret-vars"

  # exporter: # will be removed when and if https://github.com/bitnami/charts/pull/27451 is merged
  #   existingEnvVarsSecret: "harbor-secret-vars"

  trivy:
    existingEnvVarsSecret: "harbor-secret-vars"

  jobservice:
    existingEnvVarsSecret: "harbor-secret-vars"

  ingress:
    core:
      ingressClassName: "nginx"
      pathType: Prefix
      hostname: core.harbor.example.com
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"     
      tls:
        - hosts:
          - harbor.example.com
          secretName: harbor.example.com

  persistence:
    enabled: true
    resourcePolicy: "keep"
    persistentVolumeClaim:
      registry:
        existingClaim: ""
        storageClass: ""
        subPath: ""
        accessModes:
          - ReadWriteOnce
        size: 20Gi
        annotations: {}
        selector: {}
      jobservice:
        existingClaim: ""
        storageClass: ""
        subPath: ""
        accessModes:
          - ReadWriteOnce
        size: 1Gi
        annotations: {}
        selector: {}
      trivy:
        storageClass: ""
        accessModes:
          - ReadWriteOnce
        size: 5Gi
        annotations: {}
        selector: {}

  postgresql:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 13.15.0-debian-12-r2
      digest: ""
    auth:
      enablePostgresUser: true
      postgresPassword: not-secure-database-password
      existingSecret: ""
    architecture: standalone
    primary:
      extendedConfiguration: |
        max_connections = 1024
      initdb:
        scripts:
          initial-registry.sql: |
            CREATE DATABASE registry ENCODING 'UTF8';
            \c registry;
            CREATE TABLE schema_migrations(version bigint not null primary key, dirty boolean not null);
      resourcesPreset: "nano"
      resources: {}

  metrics:
    enabled: true
    path: /metrics
    serviceMonitor:
      enabled: false
      namespace: ""
      interval: ""
      scrapeTimeout: ""
      labels: {}
      selector: {}
      relabelings: []
      metricRelabelings: []
      honorLabels: false
      jobLabel: ""
```

### What is the expected behavior?

The cluster should deploy with the correct passwords and environment variable set. It does but a container goes into crashloopbackoff

### What do you see instead?

exporter pods throw the following error and the deployment cannot continue
```
2024-06-19T16:20:38Z [INFO] [/common/dao/base.go:67]: Registering database: type-PostgreSQL host-harbor-postgresql port-5432 database-registry sslmode-"disable"
[ORM]2024/06/19 16:20:38 register db Ping `default`, failed to connect to `host=harbor-postgresql user=postgres database=registry`: server error (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))
2024-06-19T16:20:38Z [FATAL] [/cmd/exporter/main.go:56]: failed to initialize database: register db Ping `default`, failed to connect to `host=harbor-postgresql user=postgres database=registry`: server error (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))
```

### Additional information

I would do a PR but I noticed that this bug is not so straightforward and would like to let the Bitnami team handle it since I do not have time to set up a testing environment to conduct further testing. 

exporter.existingEnvVarsSecret should be core.existingEnvVarsSecret in the templates but the templating logic also needs to be fixed because only fixing exporter.existingEnvVarsSecret will result to 
```
2024-06-19T16:20:38Z [INFO] [/common/dao/base.go:67]: Registering database: type-PostgreSQL host-harbor-postgresql port-5432 database-registry sslmode-"disable"
[ORM]2024/06/19 16:20:38 register db Ping `default`, failed to connect to `host=harbor-postgresql user=postgres database=registry`: server error (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))
2024-06-19T16:20:38Z [FATAL] [/cmd/exporter/main.go:56]: failed to initialize database: register db Ping `default`, failed to connect to `host=harbor-postgresql user=postgres database=registry`: server error (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))
```

For a start, please refer to the comments on https://github.com/bitnami/charts/pull/27451

### LINKED ISSUE #28190: [bitnami/harbor] failed to initialize cache: cache type  not support when using provided values.yaml
### Name and Version

bitnami/harbor 22.0.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I use the following that I `kubectl apply -f` (of course that automatically takes care of base64enc nowadays):

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret-vars
  namespace: harbor
type: Opaque
stringData:
  CSRF_KEY: "Whateverthiscanbe"
  HARBOR_ADMIN_PASSWORD: "12345678Test"
  HARBOR_DATABASE_PASSWORD: "secure-postgres-password"
  POSTGRESQL_PASSWORD: "secure-postgres-password"
  REGISTRY_CREDENTIAL_USERNAME: "registryuser"
  REGISTRY_CREDENTIAL_PASSWORD: "passwordfortest"
  postgres-password: "secure-postgres-password"
```

and the values.yaml mentioned after.

I get the following error:

```console
$ kubectl logs pod/harbor-core-7c94cd87f5-rlm48 -n harbor  
 08:55:51.60 INFO  ==> 
 08:55:51.60 INFO  ==> Welcome to the Bitnami harbor-core container
 08:55:51.61 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
 08:55:51.61 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
 08:55:51.61 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
 08:55:51.62 INFO  ==> 
 08:55:51.62 INFO  ==> ** Starting harbor-core setup **
harbor-core 08:55:51.65 INFO  ==> Validating Core settings...
harbor-core 08:55:51.73 INFO  ==> No custom certificates were installed in the system
 08:55:51.74 INFO  ==> ** harbor-core setup finished! **

harbor-core 08:55:51.76 INFO  ==> ** Starting harbor-core **
2024/07/22 08:55:51.858 [D]  init global config instance failed. If you do not use this, just ignore it.  open conf/app.conf: no such file or directory
2024-07-22T08:55:51Z [INFO] [/controller/artifact/annotation/parser.go:85]: the annotation parser to parser artifact annotation version v1alpha1 registered
2024-07-22T08:55:51Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cncf.helm.config.v1+json registered
2024-07-22T08:55:51Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cnab.manifest.v1 registered
2024-07-22T08:55:51Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.index.v1+json registered
2024-07-22T08:55:51Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.list.v2+json registered
2024-07-22T08:55:51Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.v1+prettyjws registered
2024-07-22T08:55:51Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.config.v1+json registered
2024-07-22T08:55:51Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.container.image.v1+json registered
2024-07-22T08:55:51Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.goharbor.harbor.sbom.v1 registered
2024-07-22T08:55:51Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.wasm.config.v1+json registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/aliacr/adapter.go:44]: the factory for adapter ali-acr registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/awsecr/adapter.go:44]: the factory for adapter aws-ecr registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/azurecr/adapter.go:29]: Factory for adapter azure-acr registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/dockerhub/adapter.go:40]: Factory for adapter docker-hub registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/dtr/adapter.go:36]: the factory of dtr adapter was registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/githubcr/adapter.go:43]: the factory for adapter github-ghcr registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/gitlab/adapter.go:33]: the factory for adapter gitlab registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/googlegcr/adapter.go:37]: the factory for adapter google-gcr registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/huawei/huawei_adapter.go:40]: the factory of Huawei adapter was registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/jfrog/adapter.go:42]: the factory of jfrog artifactory adapter was registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/quay/adapter.go:53]: the factory of Quay adapter was registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/tencentcr/adapter.go:55]: the factory for adapter tencent-tcr registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/volcenginecr/adapter.go:40]: the factory for adapter volcengine-cr registered
2024-07-22T08:55:51Z [INFO] [/pkg/reg/adapter/harbor/adaper.go:31]: the factory for adapter harbor registered
2024-07-22T08:55:51Z [INFO] [/core/controllers/base.go:159]: Config path: /etc/core/app.conf
2024-07-22T08:55:51Z [INFO] [/core/main.go:145]: initializing cache ...
2024-07-22T08:55:51Z [FATAL] [/core/main.go:156]: failed to initialize cache: cache type  not support
```

### Are you using any custom parameters or values?

```
harbor:
  nameOverride: "harbor"
  externalURL: https://harbor.example.com
  logLevel: warn
  exposureType: ingress
  service:
    ports:
      http: 80
      https: 443

  core:
    existingEnvVarsSecret: "harbor-secret-vars"

  trivy:
    existingEnvVarsSecret: "harbor-secret-vars"

  jobservice:
    existingEnvVarsSecret: "harbor-secret-vars"

  ingress:
    core:
      ingressClassName: "nginx"
      pathType: Prefix
      hostname: harbor.example.com
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"     
      tls:
        - hosts:
          - harbor.example.com
          secretName: harbor.example.local

  persistence:
    enabled: true
    resourcePolicy: "keep"
    persistentVolumeClaim:
      registry:
        existingClaim: ""
        storageClass: ""
        subPath: ""
        accessModes:
          - ReadWriteOnce
        size: 20Gi
        annotations: {}
        selector: {}
      jobservice:
        existingClaim: ""
        storageClass: ""
        subPath: ""
        accessModes:
          - ReadWriteOnce
        size: 1Gi
        annotations: {}
        selector: {}
      trivy:
        storageClass: ""
        accessModes:
          - ReadWriteOnce
        size: 5Gi
        annotations: {}
        selector: {}

  postgresql:
    enabled: true
    auth:
      existingSecret: "harbor-secret-vars"

  metrics:
    enabled: true
    path: /metrics
    serviceMonitor:
      enabled: false
      namespace: ""
      interval: ""
      scrapeTimeout: ""
      labels: {}
      selector: {}
      relabelings: []
      metricRelabelings: []
      honorLabels: false
      jobLabel: ""
```

### What is the expected behavior?

The core pod should just be running fine since I did not modify any default options related to the cache.

### What do you see instead?

I get failed to initialize cache: cache type  not support and it prevents the other dependable pods to run. Of course, nothing runs.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jdaln**
### Description of the change
- core-secret-envvars.yaml now handles variables individually
- Improve documentation regarding Postgres password requirements when using `core.existingEnvVarsSecret`.

### Benefits

Users will not get an error when deploying with their own database password. Neither will they when not setting the REDIS_URL (that can only correctly be set automatically when not using an external one anyway)

### Possible drawbacks

None that I can think of.

### Applicable issues

- fixes #27483
- fixes #28190

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your contribution, please note it is needed to bump the chart version in the _Chart.yaml_ even for this kind of change. Only changes in the README are exempt

**Comment by jdaln** [comment]
I would say that merging this should wait for answers and discussion on how to proceed with https://github.com/bitnami/charts/issues/28190 @carrodher

**Comment by jdaln** [comment]
Updated for https://github.com/bitnami/charts/issues/28190. 
Please run the CI again

**Comment by jdaln** [comment]
Please note that both CSRF_KEY and HARBOR_ADMIN_PASSWORD now use b64enc for consistency

**Comment by carrodher** [comment]
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

**Comment by jdaln** [comment]
Sorry @carrodher, this was due to a bug. Can you squash when merging? Alternatively, I can put all in one and force-push signed commits with the changes.

**Comment by carrodher** [comment]
Yes, please follow the steps at https://github.com/bitnami/charts/pull/28191/checks?check_run_id=27843347080

**Comment by jdaln** [comment]
hmm I guess this did not work as expected. I will open another one

**Pull request closed without merging**
