### PR TITLE
[bitnami/mongodb] Fix configmap usage after #2918

### LINKED ISSUE #3082: [Bitnami/mongodb] Question on custom configuration
I see that there's "configuration" setting in value.yaml, and the type is String, but I don't understand how to use it. Is there any detail explanation? The same question is on existingConfigmap. Hope someone helps

### PR DESCRIPTION
**Pull request by marcosbc**
**Description of the change**

In https://github.com/bitnami/charts/pull/2918 we introduced some major changes with respect to how the chart is structured. However, between all those changes, the usage of config maps were broken because of using invalid paths, causing errors such as:

```
Error: template: mongodb/templates/standalone/dep-sts.yaml:39:35: executing "mongodb/templates/standalone/dep-sts.yaml" at <include (print $.Template.BasePath "/mongodb/configmap.yaml") .>: error calling include: template: no template "mongodb/templates/mongodb/configmap.yaml" associated with template "gotpl"
```

**Benefits**

Fixes configmaps usage

**Possible drawbacks**

None

**Applicable issues**

  - fixes #3082

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by Starfox64** [comment]
Has this truly been merged into the repository ?

When I download version 8.1.1 (this version?) from the repository it still contains this bug `/mongodb/configmap.yaml` instead of `/configmap.yaml`.

**Comment by franklin432** [comment]
@marcosbc thanks for fixing the configMap broken path. I noticed yesterday it was not consuming the ConfigMap when I would include it in the values.yaml file. Now I can see it creating the ConfigMap for it however the pod crashes and the logs are not helpful. In the values.yaml file under the configuration section I am using my own mongodb conf, I can see it being consumed as a ConfigMap but it does not run the pod. Mind you this is literally the same mongodb conf as the default  if you were to install the chart, I just wanted to try it with the configuration parameters listed in the values.yaml

```
[ec2-user@ip-172-31-48-60 mongodb]$ kubectl get cm
NAME                                              DATA                    AGE
mymongo-mongodb                          1                         13s
mymongo-mongodb-init-scripts      1                         13s
mymongo-mongodb-scripts             1                         13s
```

```
[ec2-user@ip-172-31-48-60 mongodb]$ kubectl get all
NAME                            READY   STATUS             RESTARTS   AGE
pod/mymongo-mongodb-0           0/1     CrashLoopBackOff   2          87s
pod/mymongo-mongodb-arbiter-0   1/1     Running            0          87s

NAME                                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
service/kubernetes                         ClusterIP   100.64.0.1       <none>        443/TCP     5h35m
service/mymongo-mongodb-arbiter-headless   ClusterIP   None             <none>        27017/TCP   100s
service/mymongo-mongodb-headless           ClusterIP   None             <none>        27017/TCP   100s
service/mymongo-mongodb-metrics            ClusterIP   100.66.210.255   <none>        9216/TCP    100s

NAME                                       READY   AGE
statefulset.apps/mymongo-mongodb           0/2     100s
statefulset.apps/mymongo-mongodb-arbiter   1/1     100s
[ec2-user@ip-172-31-48-60 mongodb]$ 
```

```
[ec2-user@ip-172-31-48-60 mongodb]$ kubectl logs pod/mymongo-mongodb-0
Advertised Hostname: mymongo-mongodb-0.mymongo-mongodb-headless.default.svc.cluster.local
Pod name matches initial primary pod name, configuring node as a primary
mongodb 19:08:21.37 
mongodb 19:08:21.37 Welcome to the Bitnami mongodb container
mongodb 19:08:21.37 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 19:08:21.37 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 19:08:21.37 
mongodb 19:08:21.38 INFO  ==> ** Starting MongoDB setup **
mongodb 19:08:21.39 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 19:08:21.40 INFO  ==> Initializing MongoDB...
mongodb 19:08:21.40 INFO  ==> Deploying MongoDB from scratch...
[ec2-user@ip-172-31-48-60 mongodb]$ 
```

THE configuration parameters from the values-production.yaml file

```
configuration: |
        storage:
          dbPath: /bitnami/mongodb/data/db
          journal:
            enabled: true
        directoryPerDB: false
        systemLog:
          destination: file
          quiet: false
          logAppend: true
          logRotate: reopen
          path: /opt/bitnami/mongodb/logs/mongodb.log
          verbosity: 0
        net:
          port: 27017
          unixDomainSocket:
            enabled: true
            pathPrefix: /opt/bitnami/mongodb/tmp
          ipv6: false
          bindIpAll: true
        replication:
          replSetName: rs0
          enableMajorityReadConcern: true
        processManagement:
          fork: false
          pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
        setParameter:
           enableLocalhostAuthBypass: true
        security:
          authorization: enabled
          keyFile: /opt/bitnami/mongodb/conf/keyfile
```

**Comment by joancafom** [comment]
Hi @Starfox64 

Could you verify that again? Sometimes the repo takes some time to update, but the latest release (8.1.3) should definitely contain your changes.

Thanks!

**Comment by joancafom** [comment]
Hi @franklin432 ,

Are you still facing the problem? If so, would you mind creating a new issue so that we can give you assistance and comment on related findings there?

Thanks!

**Comment by Starfox64** [comment]
@joancafom 8.1.3 is properly up to date now, thanks.

**Comment by kwill4026** [comment]
@joancafom I am but I'll go ahead and create a new issue. I noticed when you helm install a default chart, then proceed with a helm upgrade of that same deployment but with the "configuration" details uncommented, it will upgrade and install fine. But if you decide to first uncomment those values and helm install, the pod wont load. Why is this? I assumed I could uncomment the configuration section in the values-production.yaml file and helm install right away, without having to first install the default chart first.

**Comment by joancafom** [comment]
Hi @kwill4026 , 

Okay, let's move the conversation to the issue where you can provide us with some steps to reproduce the use case.

Thanks!

**Comment by kwill4026** [comment]
@joancafom opened #3213 explaining this

**Comment by joancafom** [comment]
Thanks @kwill4026 ! One of our engineers will take care of it soon to provide with some advice 😃

**Pull request merged**
