### PR TITLE
[bitnami/sonarqube] Fix updateStrategy.type option comment in default values

### PR DESCRIPTION
**Pull request by IQNeoXen**
### Description of the change

A comment in the values.yaml mentions that possible values for the update strategy of the deployment are ```RollingUpdate``` and ```OnDelete```.

Using  ```OnDelete``` leads to invalid manifests though:

```
spec.strategy: Unsupported value: apps.DeploymentStrategy{Type:"OnDelete", RollingUpdate:(*apps.RollingUpdateDeployment)(nil)}: supported values: "Recreate", "RollingUpdate"
```

This fix just corrects the comment in values.yaml to show ```RollingUpdate``` and ```Recreate``` as possible options.

### Benefits

Correct docs ;)

### Possible drawbacks

None

### Applicable issues

None

### Additional information

None

### Checklist

- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by IQNeoXen** [comment]
Didn't bump the chart version as neither default values nor templates have been changed, only comments. Is this still needed though?

**Comment by carrodher** [comment]
Thanks for your contribution, to perform a new release, the chart version should be bumped when there are changes in any file different from the README. Could you please bump it? Thanks again

**Comment by IQNeoXen** [comment]
@carrodher done :)

**Review by FraPazGal — APPROVED** [review]
LGTM!

**Pull request merged**
