### PR TITLE
[bitnami/kibana] Add configurable server.basePath

### PR DESCRIPTION
**Pull request by SylvainVISSIERE-GUERINET**
**Describe the changes**

Add possibility to configure kibana server.basePath and handle accordingly liveness and readyness probes

**Benefits**

The chart becomes more customizable

**Possible drawbacks**

Default values correspond to Kibana 6.8 version

**Applicable issues**

N/A

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the PR! Could you bump the chart minor version? It is adding a new feature

**Comment by SylvainVISSIERE-GUERINET** [comment]
Thanks, out of curiosity, is it needed to push a bump on ES chart to adjust the version of its kibana version or it is done automaticaly?

**Comment by javsalgar** [comment]
Hi, 

I think it would also require a `helm dependency update` in the Elasticsearch chart. When we release a new version of the chart this would be done automatically.

**Comment by tahsinrahman** [comment]
hi @SylvainVISSIERE-GUERINET @javsalgar `configuration.server.basePath` is not added in values.yaml, only `rewriteBasePath` is added

**Comment by javsalgar** [comment]
Hi,

True, I think it should be added as well. cc @SylvainVISSIERE-GUERINET

**Comment by tahsinrahman** [comment]
also, in liveness and readiness probe section, we should be changing the path if `rewriteBasePath` is true, because

> Specifies whether Kibana should rewrite requests that are prefixed with server.basePath or require that they are rewritten by your reverse proxy. In Kibana 6.3 and earlier, the default is false. In Kibana 7.x, the setting is deprecated. In Kibana 8.0 and later, the default is true. Default: deprecated
https://www.elastic.co/guide/en/kibana/7.x/settings.html

```
            {{- if .Values.configuration.server.rewriteBasePath }}
              path: {{ .Values.configuration.server.basePath }}/app/kibana
            {{ else }}
              path: /app/kibana
            {{- end }}
```

**Comment by javsalgar** [comment]
Hi,

Thanks for the input! Feel free to add a new PR fixing this if you want to speed up the process

**Comment by tahsinrahman** [comment]
@javsalgar https://github.com/bitnami/charts/pull/3105

**Pull request merged**
