### PR TITLE
[bitnami/discourse] #3199 - Fix DISCOURSE_SKIP_INSTALL

### PR DESCRIPTION
**Pull request by LucaPrete**

### CODE REVIEW

**Comment by LucaPrete** [comment]
I've bumped the chart version to `0.2.1` considering the changes that will be hopefully merged soon from #3036 . I plan to rebase it on it anyway, as soon as the former gets merged

**Comment by rafariossaa** [comment]
Hi @LucaPrete ,
  Thanks for the PR ! 
  Let's wait until #3036 gets merged and this PR is rebased from there.

**Comment by rafariossaa** [comment]
Hi @LucaPrete ,
  #3306 was merged, could you check it and rebase this PR

**Comment by LucaPrete** [comment]
@rafariossaa for sure. Done! :)

**Pull request merged**
