### PR TITLE
[bitnami/kube-prometheus] prometheus-operator use podLabels helper

### LINKED ISSUE #19199: [bitnami/kube-prometheus] Operator Deployment uses labels instead of podLabels as pod labels
### Name and Version

bitnami/kube-prometheus 8.18.3
up to
bitnami/kube-prometheus 8.21.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Configuration
```yaml
operator:
  podLabels:
    label1: value1
```

### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

I expect that the operator pod gets the label `label1: value1`.

### What do you see instead?

The pod gets the labels of the deployment instead.

### Additional information

The error is in that line:
https://github.com/bitnami/charts/blob/ff8121ee686f7547142342f2b394fc97640080a8/bitnami/kube-prometheus/templates/prometheus-operator/deployment.yaml#L22

There should be a call to `kube-prometheus.operator.podLabels` instead of `kube-prometheus.operator.labels` at that point. That define was added to `_helpers.tpl` in #18616 but unfortunately the newly created named template was not used in `prometheus-operator/deployment.yaml`.

Versions before 8.18.0 were not affected by this issue because the inner function of the name template `kube-prometheus.operator.labels` was different at that point.

### PR DESCRIPTION
**Pull request by migruiz4**
### Description of the change

Replaces `kube-prometheus.operator.labels` with `kube-prometheus.operator.podLabels`.

### Applicable issues

- fixes #19199

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by rafariossaa — APPROVED** [review]

**Comment by BernhardGruen** [comment]
It unfortunately seems that the version number has to be increased again as it currently conflicts with `main`.

**Review by rafariossaa — APPROVED** [review]
LGTM

**Comment by BernhardGruen** [comment]
The version number still needs to be increased. Please do not merge.

**Comment by BernhardGruen** [comment]
This MR again needs a version bump.

**Comment by BernhardGruen** [comment]
@carrodher 
Carlos, you kindly did a version bump two weeks ago. Would you mind doing that again to resolve the conflict with the version number?
Thanks in advance

**Review by BernhardGruen — APPROVED** [review]
LGTM
Version number bumped :+1: 
Patch itself lgtm

Thank you!

**Review by rafariossaa — APPROVED** [review]

**Pull request merged**
