### PR TITLE
[bitnami/mongodb] feat: add node affinity templating for standalone chart

### PR DESCRIPTION
**Pull request by mvoitko**
Signed-off-by: Maksym Voitko <max.voitko@gmail.com>

**Description of the change**

Add mongodb standalone chart node affinity values templating

**Benefits**

It's possible to use values in node affinity values

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

Could you check the errors in the action?

```

2022-03-09T23:46:09.079+0000 [    main][ INFO][RunAction][helm-package] Generating template of mongodb-11.0.7-1646869555147, attempt 4
2022-03-09T23:46:11.404+0000 [    main][ WARN][RunAction][helm-package] Couldn't generate template of chart mongodb-11.0.7-1646869555147. Error: template: mongodb/templates/standalone/dep-sts.yaml:74:152: executing "mongodb/templates/standalone/dep-sts.yaml" at <tpl>: wrong number of args for tpl: want 2 got 0

Use --debug flag to render out invalid YAML


```

**Comment by javsalgar** [comment]
Hi,

Could  you merge with the latest upstream version of the repository?

**Comment by mvoitko** [comment]
will do in the nearest days

**Pull request closed without merging**
