### PR TITLE
[bitnami/airflow] Add support for CeleryKubernetesExecutor

### PR DESCRIPTION
**Pull request by migruiz4**
**Description of the change**

This PR adds support for the Airflow CeleryKubernetesExecutor.

In the latest version of Airflow 2 (2.0.1), the CeleryKubernetesExecutor is broken because of this critical issue: https://github.com/apache/airflow/pull/13247

Although the issue is fixed, it hasn't been released yet so this feature will have to wait until a new version of Airflow is released.

**Possible drawbacks**

None known.

**Applicable issues**

- https://github.com/bitnami/charts/issues/5646

**Additional information**

Additionally, fixed a typo affecting the CustomReadinessProbe and some references in the README.md

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

### CODE REVIEW

**Comment by migruiz4** [comment]
Making this a draft as this will have to wait until a Airflow version is released

**Comment by izhangzhihao** [comment]
Airflow [2.0.2](https://github.com/apache/airflow/releases/tag/2.0.2) released two days ago with the issue https://github.com/apache/airflow/pull/13247 fixed:

> [The fix will be available in Airflow 2.0.2 -- which should be released in a week or so](https://github.com/apache/airflow/issues/13805#issuecomment-817723855)

I think we still need this issue fixed: https://github.com/bitnami/bitnami-docker-airflow-worker/issues/11

**Comment by migruiz4** [comment]
Hi @izhangzhihao,

We continue working to release the image for Airflow-2.0.2. 

As soon as it is ready we will pick up on this task and start testing this feature.

**Comment by izhangzhihao** [comment]
I don't know why this PR labeled as "on-hold", [it seems now the airflow component is version 2.0.2](https://github.com/bitnami/charts/commit/1890d5bff55ab910a376bba40dae5da99647f641#diff-dc2e31b4dfae275489844d20920a37dce2db35f6578b2c080722a7c5c3c3566b)

**Comment by migruiz4** [comment]
Tested using the latest Airflow 2.1.0 with a small modification in the images, the CeleryKubernetesExecutor starts without errors.

```
> helm install af bitnami/airflow --set executor=CeleryKubernetesExecutor,scheduler.image.tag=development,worker.image.tag=development,web.image.tag=development,loadExamples=true
```
All pods up and running.
```
> kubectl get pods
NAME                                    READY   STATUS    RESTARTS   AGE
af-airflow-scheduler-546d8ffcdd-lbc6z   1/1     Running   1          5m18s
af-airflow-web-69c658bf5c-6rft7         1/1     Running   1          5m18s
af-airflow-worker-0                     1/1     Running   1          5m18s
af-postgresql-0                         1/1     Running   0          5m18s
af-redis-master-0                       1/1     Running   0          5m18s
```

Nevertheless, the Celery worker is having issues because of the problem described in Section 3 (https://github.com/apache/airflow/pull/13247).

All the DAGs fail with the following error message in the worker:
```
[2021-06-07 15:39:57,797: ERROR/ForkPoolWorker-16] Failed to execute task daemonic processes are not allowed to have children.
```

The fix described in the PR requires configuring the workers with CeleryExecutor instead of CeleryKubernetesExecutor.

Although Airflow resolution about this is not clear yet, I will add the workaround with a comment to review it in the future if needed.

**Pull request merged**
