### PR TITLE
[bitnami/redis] Adding ExternalIPs Feature

### PR DESCRIPTION
**Pull request by dboc**
Signed-off-by: Daniel Carvalho <danielbrito.oc@gmail.com>

### Description of the change

Include Service ExternalIPs for Master Service. Another way to expose Redis is ExternalIPs, follow the Kubernetes Docs:
https://kubernetes.io/docs/concepts/services-networking/service/#external-ips

### Benefits

Another way to expose Service Redis is ExternalIPs, follow the Kubernetes Docs:
https://kubernetes.io/docs/concepts/services-networking/service/#external-ips

### Possible drawbacks

Just not use the value master.service.externalIPs.

### Applicable issues

  - fixes #https://github.com/bitnami/charts/issues/13961

### Additional information

This pull request is a update from another one:  https://github.com/bitnami/charts/pull/13981
I've never did a contribution before, please make intensive tests. 

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by fmulero — COMMENTED** [review]
Hi @dboc, thanks a lot for the contribution!

I only have a quick doubt, Is it worth to implement this feature also for the replica service?

**Comment by dboc** [comment]
Hi @fmulero , it is my pleasure.

The ExternalIPs feature is interesting when it is necessary to publish a service outside the Kubernetes cluster. I don't know the structure of Redis multireplica or multimaster, for my use case (standalone mode) I just need it to be in the master service. I think it's best to wait the need arises to add this feature to other Redis uses cases.
We are studying new ways to use Redis and if this need arises I will make myself a new pull request to add this feature.

**Comment by dboc** [comment]
@fmulero @carrodher , Hello guys...
I have to rebase again? if yes, how do i do? Last time i made a sync fork and the pull request was automatically closed.

**Comment by fmulero** [comment]
> @fmulero @carrodher , Hello guys... I have to rebase again? if yes, how do i do? Last time i made a sync fork and the pull request was automatically closed.

It's OK, I've just fix the conflicts. To avoid that kind of issues while syncing your fork, please use a branch different than `main` in your developments.

**Review by fmulero — APPROVED** [review]
LGTM

**Pull request merged**
