### PR TITLE
[bitnami/common] Fixed an helm error when using HPA and VPA capabilities.

### PR DESCRIPTION
**Pull request by earljon**
### Description of the change

Fixed an error that prevents the user to use the `hpa` and `vpa` capabilities

### Benefits

User will be able to use and includes `common.capabilities.[hpa|vpa].apiVersion` without the helm throwing error.

The template or helm install will proceed as expected
```
helm template test-release ./wordpress -f ./values.yaml --debug
```

### Applicable issues

- Fixes https://github.com/bitnami/charts/issues/17414 and this specific error:
```
install.go:200: [debug] Original chart version: ""
install.go:217: [debug] CHART PATH: /wordpress

Error: template: wordpress/templates/hpa.yaml:2:15: executing "wordpress/templates/hpa.yaml" at <include "common.capabilities.hpa.apiVersion" .>: error calling include: template: wordpress/charts/common/templates/_capabilities.tpl:133:7: executing "common.capabilities.hpa.apiVersion" at <semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .context)>: error calling semverCompare: Invalid Semantic Version
helm.go:84: [debug] template: wordpress/templates/hpa.yaml:2:15: executing "wordpress/templates/hpa.yaml" at <include "common.capabilities.hpa.apiVersion" .>: error calling include: template: wordpress/charts/common/templates/_capabilities.tpl:133:7: executing "common.capabilities.hpa.apiVersion" at <semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .context)>: error calling semverCompare: Invalid Semantic Version
```

### Additional information

Nothing more, only the `hpa` and `vpa` capabilities are affected for this change.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

**Comment by earljon** [comment]
There's already a version bump from 2.5.x to 2.6.0. I have already updated my PR to include this change, appending 2.6.1 in the process.

**Comment by earljon** [comment]
Hi @carrodher , any chance to review this PR?

**Review by migruiz4 — CHANGES_REQUESTED** [review]
Hi @earljon,

I'm sorry but I can't accept these changes as the change from `.context` to `.` is not correct.

The common helpers `common.capabilities.hpa.apiVersion` and `common.capabilities.vpa.apiVersion` use the following format to be called:
```
{{- include "common.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
{{- include "common.capabilities.vpa.apiVersion" ( dict "context" $ ) }}
```

You may be using an old version of either the Wordpres chart or the Common chart, but the rendering issue you mention in the description was fixed about a year ago: https://github.com/bitnami/charts/pull/10334/files

**Comment by earljon** [comment]
Hi @migruiz4 ,

Thank you for your response. Yes, you're correct I have overlooked that part of the fix way back. I have updated and test it and it worked as expected.

Happy to close this PR.

**Pull request closed without merging**
