### PR TITLE
[bitnami/jenkins] feat: allow config service account

### LINKED ISSUE #6983: Jenkins allow for selection of serviceAccount jenkins runs on.
**Which chart**:
Jenkins 2.289.2 

**Is your feature request related to a problem? Please describe.**
When deploying jenkins recently with the bitnami chart, I ended up having to fork the chart so I could change the service account that the app runs on could be changed.  When using using Kubernetes as a build agent the user the service account uses must be able to launch pods.

**Describe the solution you'd like**
Allow specification of a specific service account in the container pod. 

**Additional context**

```
spec:
  serviceAccountName: kpack-deploy-sa

### PR DESCRIPTION
**Pull request by tonyhhyip**
**Description of the change**

Add values for Jenkins Helm chart to be able to specify service account

**Benefits**

User are able to input service account for Jenkins' pod

**Possible drawbacks**

**Applicable issues**

  - fixes #6983

**Additional information**

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by marcosbc** [comment]
Thanks for the contribution! In general the changes look good to more, however there seem to be conflicts. Could you fix those?

**Comment by tonyhhyip** [comment]
Just rebased, should resolved issue

**Review by Stark-X — COMMENTED** [review]
LGTM

**Review by Stark-X — APPROVED** [review]

**Review by Stark-X — DISMISSED** [review]

**Review by marcosbc — APPROVED** [review]
LGTM! Thanks for the contribution!

**Pull request merged**
