### PR TITLE
add kafka acl config param

### PR DESCRIPTION
**Pull request by lrc0**
**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Comment by lrc0** [comment]
this PR just added some configuration parameters to enable the acl. The document has been added

**Comment by migruiz4** [comment]
Hi @lrc0,

Tried to deploy Kafka with your PR changes, but Kafka is failing with the following error:

```
[2021-09-23 06:54:59,718] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Invalid value  for configuration zookeeper.set.acl: Expected value to be either true or false
        at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:665)
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1386)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1389)
        at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1327)
        at kafka.Kafka$.buildServer(Kafka.scala:67)
        at kafka.Kafka$.main(Kafka.scala:87)
        at kafka.Kafka.main(Kafka.scala)
```
 
Other change suggestions:
  - Install instructions are incorrect, please replace them with:
    ```
    replicaCount=2
    auth.clientProtocol=sasl
    auth.interBrokerProtocol=sasl_tls
    auth.tls.existingSecret=kafka-jks
    auth.tls.password=jksPassword
    'auth.sasl.jaas.clientUsers[0]=brokerUser'
    'auth.sasl.jaas.clientPasswords[0]=brokerPassword'
    auth.sasl.jaas.zookeeperUser=zookeeperUser
    auth.sasl.jaas.zookeeperPassword=zookeeperPassword
    zookeeper.auth.enabled=true
    zookeeper.auth.serverUsers=zookeeperUser
    zookeeper.auth.serverPasswords=zookeeperPassword
    zookeeper.auth.clientUser=zookeeperUser
    zookeeper.auth.clientPassword=zookeeperPassword
    authorizerClassName=kafka.security.authorizer.AclAuthorizer
    allowEveryoneIfNoAclFound=false
    superUsers=User:admin
    ```
  - Chart minor version bump required at `bitnami/kafka/Chart.yaml`, in this case, version would be `14.2.0`.

**Comment by lrc0** [comment]
> * Install instructions

Thanks for your review， I have made the changes according to your reply

**Review by migruiz4 — APPROVED** [review]
Hi @lrc0,

Manually tested and it is working fine for me.

Thank you for your contribution and applying the suggestions!

**Pull request merged**
