### PR TITLE
[bitnami/contour] allow customizing lifecycle hooks for envoy containers

### PR DESCRIPTION
**Pull request by therealak12**
### Description of the change

Adds a new value to the contour's chart to allow customizing lifecycle hooks in the Envoy and shutdown manager containers.

### Benefits

When using `hostNetwork: true`, the `httpGet` probe must be customized by adding a `Host` header or a `host` field. Obviously, this is not the only benefit of allowing this customization.

### Possible drawbacks

Users may set random lifecycle hooks and unintentionally disable or disrupt the shutdown manager functionality.

### Additional information

The change is only made on the Envoy deployment template. The daemonset already allows customizing lifecycle hooks for the shutdown manager container but not the Envoy container. Changing the daemonset template makes the chart backward-incompatible.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! Could you grant write permissions so the bitnami-bot can update the changelog and the values.yaml file?

**Comment by therealak12** [comment]
> Hi!
> 
> Thank you so much for the PR! Could you grant write permissions so the bitnami-bot can update the changelog and the values.yaml file?

Sure. Should I invite the bitnami bot with the `Write` permission?

**Comment by javsalgar** [comment]
Hi,

I don't fully recall how it's done but you I think it is in the forked repository settings.

**Comment by therealak12** [comment]
> Hi,
> 
> I don't fully recall how it's done but you I think it is in the forked repository settings. I know it's not an invitation to bitnami-bot.

Dear @javsalgar,
I reviewed the settings several times. I see no other options to grant write access to the bitnami-bot. Any suggestions?

**Comment by therealak12** [comment]
Dear @javsalgar,
I see other people have granted the permission in the same way. Like in [pr#24586](https://github.com/bitnami/charts/pull/24586#issuecomment-2012565996).

**Review by andresbono — APPROVED** [review]
LGTM, thank you for your contribution! 🎉

**Pull request merged**
