### PR TITLE
[bitnami/keycloak]: adjust default service to ClusterAPI

### PR DESCRIPTION
**Pull request by mweibel**
### Description of the change

Exposing keycloak by default as a LoadBalancer might not be the best option since people unaware expose keycloak to the internet without an ingress in front which is what people would want usually.

### Benefits

Slightly better defaults. Most people running keycloak will run it behind an ingress anyway. 

### Possible drawbacks

It's a breaking change of the chart.

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

Please let me know if this is something you'd accept - if yes I'll update the Chart.yaml and README files accordingly.

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

Thank you for creating the ticket. Could you bump the version of the chart? Otherwise the action will continue failing.

**Comment by mweibel** [comment]
Thanks @javsalgar for your reply. Yeah I don't mind doing that - I didn't do it because I wasn't sure if you'd accept this PR. 

Given that this is a potential breaking change to change the default - would you agree I'd need to bump the major version?

**Comment by rafariossaa** [comment]
In this case I would bump the major version and add a note in the README so users would know about this change.

**Comment by mweibel** [comment]
@rafariossaa @javsalgar thanks for the feedback - Chart version and README is updated.

**Comment by rafariossaa** [comment]
Hi, 
  I seems you need to rebase your changes.

**Review by rafariossaa — APPROVED** [review]
LGTM

**Pull request merged**
