### PR TITLE
[bitnami/contour]: fix for #8174

### PR DESCRIPTION
**Pull request by tricky42**
**Description of the change**
- Change default config in `values.yaml` to not specify a `ingressClass.name`. 
- Changed helper function `isIngressClassNameDefined` to only return `true` if `ingressClass.name` has explicitly configured.

These changes ensure that using the default config `contour server` will be started without the `--ingress-class-name` flag and therefore Contour will reconcile `httpproxy` instances which do not explicitly specify an `ingressClassName` under `spec`.

**Benefits**
FIx for #8174 
Contour installed with the Helm chart uses the same config / behaves the same as Contour installed via the other methods described on the Contour website. E.g. config examples from the Contour documentation work without changes...

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Comment by juan131** [comment]
Related to [this PR](https://github.com/bitnami/charts/pull/8046)

**Comment by tricky42** [comment]
Tricky thing is contour helm chart behaves differently for 
```
contour.ingressClass.name: ""

vs. 

contour.ingressClass.name: contour
```

Although even is "" is configured (as the new default config), `contour` will be used as the name of the ingressControllerClass. But there will be no `ingress-class-name` argument passed on when starting contour binary and therefore contour will automatically pick up `httpproxy` instances which do not specify the `ingressClassName`.

Not sure where to put this explanation as descriptions are very brief right now. Details can be found here: https://projectcontour.io/docs/main/config/ingress/#ingressclass-and-ingressclass-name

**Comment by tricky42** [comment]
It would be great if the full error message of the lintyaml would be displayed. The line / pos details are missing:

image

Running this locally displays all the details:
```
❯ yamllint --config-file lintconf.yaml values.yaml 
values.yaml
  386:98    error    trailing spaces  (trailing-spaces)
```

**Review by juan131 — APPROVED** [review]
LGTM

**Pull request merged**
