### PR TITLE
[bitnami/grafana-operator]  add ClusterRole list and watch verbs for namespaces

### PR DESCRIPTION
**Pull request by rasebo**
### Description of the change

This change adds the `list` and `watch` verbs to the `namespaces` resource under the `""` apiGroup for the bitnami/grafana-operator chart.

### Benefits

Listing and watching namespaces needs to be allowed when scanAllNamespaces is set to true or scanNamespaces is defined. Otherwise, iterating through all/defined namespaces is not possible, and grafana-operator logs the following error messages:

```
[2.7.25-grafana-operator-79d86fb8-7g6vm] W0503 14:27:10.451811       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:grafana:grafana-operator" cannot list resource "namespaces" in API group "" at the cluster scope
[2.7.25-grafana-operator-79d86fb8-7g6vm] E0503 14:27:10.451834       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:grafana:grafana-operator" cannot list resource "namespaces" in API group "" at the cluster scope
[2.7.25-grafana-operator-79d86fb8-7g6vm] E0503 15:35:19.962541       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1.Namespace: unknown (get namespaces)
```

### Possible drawbacks

n/a

### Applicable issues

n/a

### Additional information

n/a

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by rasebo** [comment]
> Hi!
> 
> Thank you so much for the PR! Could you fix the DCO issue?

Done!

**Comment by CeliaGMqrz** [comment]
Hi @rasebo, 
Thanks for your contribution! Looks good to me, but can you update the chart version?

@Yaytay, thanks for your comments, this change could also be considered.

**Comment by rasebo** [comment]
I updated the chart version. 

I can test & include the requested change as well, if needed, or a new PR can be raised to address it specifically. 

Since this is my first contribution to this project, I'd need some guidance from the maintainers on which of these two options (or others) would be best.

**Comment by Yaytay** [comment]
I've been trying to confirm that dashboardNamespaceSelectors need "get" as well as "list"/"watch", and I think I've confirmed the opposite.
This https://kubernetes.io/docs/reference/access-authn-authz/authorization/ makes it clear that all three verbs provide complete access to the resource, the only difference is how the callers chooses to access them.
Right now it seems that list & watch is adequate, but a change to the operator might break that unexpectedly.

**Review by CeliaGMqrz — APPROVED** [review]
@rasebo LGTM! Let's accept the main change, I think the change suggested by @Yaytay should be reviewed in a new PR. Feel free to create it, the team will be happy to review it. Thanks for your contribution!

**Pull request merged**
