### PR TITLE
[bitnami/wordpress] Change in the command of apache-exporter

### LINKED ISSUE #2274: apache_exporter failed to start
**Which chart**:
wordpress 9.1.3

**Describe the bug**
`apache_exporter` failed to start with error
`apache_exporter: error: unknown short flag '-s', try --help`

**To Reproduce**
`helm install my-release bitnami/wordpress` with values
```
metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.8.0-debian-10-r3
```

**Expected behavior**
`apache_exporter` run without error

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
According to the README in https://github.com/Lusitaniae/apache_exporter , the correct way to use apache_exporter is `--scrape` but in https://github.com/bitnami/charts/blob/8f3b7cea39cd7994156a5f251f0dce1c0bb3e51e/bitnami/wordpress/templates/deployment.yaml#L185-L188
it's using `-scrape`

### PR DESCRIPTION
**Pull request by Mauraza**
**Description of the change**

Add `-` to the command in metrics

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #2274

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by yeouchien** [comment]
thanks for fixing it in wordpress. https://github.com/bitnami/charts/search?q=apache_exporter&unscoped_q=apache_exporter shows that there're other deployments using wrong command flag. Should we fix all of them in one PR?

**Comment by juan131** [comment]
Wait for CI/CD to test you change and update image tags

**Comment by juan131** [comment]
As @yeouchien mentioned, we need to update this on several charts since several web apps use this Apache exporter. Could you please create the corresponding PRs @Mauraza ?

**Comment by Mauraza** [comment]
Yeah, I'll take care of the PR.

**Pull request merged**
