### PR TITLE
[bitnami/rabbitmq] Error on network policy definition

### PR DESCRIPTION
**Pull request by EnriqueLop**
**Description of the change**

Change network policy definition in values.yaml to make it works

**Benefits**

Applying network policies works.

**Possible drawbacks**

N/A

**Applicable issues**

**Additional information**

No code is changed, only commented network policy definition. I have dump version, but I don't know if it is necessary if I haven't changed the code.

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Review by Mauraza — COMMENTED** [review]
Hi @EnriqueLop,

Could you add more information about the change?

**Comment by EnriqueLop** [comment]
Hi @Mauraza,
Network policy definition are correctly implemented but example in vaules.yaml file do not work. If you uncomment 'additionalRules' field as shown on values.yaml it does not work. 

I have only change comment the commented example.

**Comment by Mauraza** [comment]
Hi @EnriqueLop,

Thanks for the contribution, LGTM!, but before merging it, could you resolve the conflicts?

**Comment by Mauraza** [comment]
Hi @EnriqueLop,

Could you resolve the conflicts?

**Pull request closed without merging**
