### PR TITLE
[bitnami/metallb] Bugfix tolerations for speaker DaemonSet.

### PR DESCRIPTION
**Pull request by Cellebyte**
**Description of the change**

**Benefits**

It removes the duplicated tolerations key from the manifests.

**Possible drawbacks**

**Applicable issues**

**Additional information**

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Comment by migruiz4** [comment]
Hi @Cellebyte,

I'm sorry but not familiar with MetalLB, is the `tolerations` field no longer needed for the MetalLB Speaker?

```
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
```

If it is still needed, I'd suggest modifying the default value for `speaker.tolerations` to maintain the same behavior.

Additionally, I see your PR contains many commits unrelated to this feature. Could you please use a new branch?

**Comment by Cellebyte** [comment]
@migruiz4 it is not needed it was just hardcoded in and if a user needs it he can specifically configure it.
Also duplicated keys are not a good thing.

For the other thing I will create a new branch.

**Review by migruiz4 — APPROVED** [review]
Understood! Thank you for your answer.

I wanted to double-check if the `tolerations` removed in this PR were required by MetalLB or unintentionally hardcoded.

In that case, it looks good to me.

Please fix the branch issues and I will merge it.

**Comment by Cellebyte** [comment]
#7044 is successor will close this one.

**Pull request closed without merging**
