### PR TITLE
[bitnami/elasticsearch] allow for custom volumeClaimTemplate selectors

### PR DESCRIPTION
**Pull request by MatthiasLohr**
**Description of the change**

The current version of the elasticsearch helm chart only allows for the hard-coded volume selector label name `volume`. Adding the new options `master.persistence.existingVolumeSelector` and `data.persistence.existingVolumeSelector`, it gives users the freedom to define custom selectors using their own labels.

**Benefits**

With this pull request, instead of only having a hardcoded label named `volume` as volume selector, users can define their own custom selectors for `existingVolumeClaimTemplates`.

**Possible drawbacks**

Nothing known.

**Applicable issues**

*N.A.*

**Additional information**

In a future major rewrite of this helm chart (targeting a new major version), it should be considered to improve the structure of settings for existing volumes/claimes. However, this will break downwards compatibility, so this is not a real solution for minor updates.

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by FraPazGal** [comment]
Hello @MatthiasLohr,

Thank you so much for the PR! I agree this would be a good addition to our chart, but I have doubts about the parameters' name. If I'm not wrong, we will be adding selectors to the pvc, regardless if one of those is `volume` for an existingVolume. As such, I think `master.persistence.selector` would be closer the actual definition, wouldn't it?

**Comment by MatthiasLohr** [comment]
@FraPazGal, thank you for your comment. I have no strong opinion about the parameter's name. However, what, if not an existing volume, can you select using these selectors? As to my knowledge, that's only matching to existing volumes, or am I wrong here?

**Comment by FraPazGal** [comment]
That is a good point, you are right. I thought this could cause misunderstandings as we always use `persistence.selector` in our charts for this functionality. It really shouldn't, so I would say that standarisations is the only reason I'll change to `.selector`.

**Comment by MatthiasLohr** [comment]
> [...] so I would say that standarisations is the only reason I'll change to `.selector`.

I agree, done.

**Comment by Doca** [comment]
That's exactly what I need!

**Review by FraPazGal — APPROVED** [review]
LGTM! Thanks!!

**Pull request merged**
