### PR TITLE
update indentation set for extra init container

### PR DESCRIPTION
**Pull request by Ankitchandre**
The indentation is set to {{ tpl .Values.master.extraInitContainers . | indent 8 }} in master which woprks fine , but on adding extra init container , slave statefull set fails due to {{ tpl .Values.master.extraInitContainers . | indent 6}}. Thus its a bug and need to be changed to {{ tpl .Values.master.extraInitContainers . | indent 8 }}

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thank you for the Pull Request! Could you bump the patch version of the chart?

**Comment by Ankitchandre** [comment]
Hey, I didn't get what exactly "bump the patch version of the chart" means . DO i need to change the chart version from 7.3.21 to 7.3.22 ?? is that what you mean ?

**Comment by javsalgar** [comment]
Hi! Yes, that's exactly what I mean

**Comment by Ankitchandre** [comment]
Done. Bumped chart the version

**Pull request merged**
