### PR TITLE
[bitnami/spring-cloud-dataflow] Add common application properties configuration

### LINKED ISSUE #8955: [bitnami/spring-cloud-dataflow] Add SCDF common application properties configuration
### Name and Version

 [bitnami/spring-cloud-dataflow] 5.1.0

### What is the problem this feature will solve?

Today it is not possible to configure SCDF [common application properties](https://docs.spring.io/spring-cloud-dataflow/docs/2.9.1/reference/htmlsingle/#spring-cloud-dataflow-global-properties) with the chart

### What is the feature you are proposing to solve the problem?

Add SCDF common application properties configuration with the chart

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by CEDDM**
**Description of the change**

Change values.yml and server/configmap.yml

**Benefits**

Allow common application properties configuration in SCDF server configmap

**Applicable issues**

  - fixes #8955 

**Checklist**
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by alemorcuq — CHANGES_REQUESTED** [review]
Thanks for the PR! Please, increase a minor instead.

**Comment by CEDDM** [comment]
Pfff DCO is painfull ....

**Comment by alemorcuq** [comment]
What happened, @CEDDM ?

**Comment by CEDDM** [comment]
@alemorcuq I had a commit rejected by DCO and I couldn't find a way to modify the commit message so I had to redo my PR ... again ... because the first time I didn't see this new resquirement and didn't signed my commit.
I submitted a new PR #8982 
Hope this time it will be OK

**Pull request closed without merging**
