### PR TITLE
[bitnami/moodle] Add support for non-root approach

### PR DESCRIPTION
**Pull request by marcosbc**
**Description of the change**

We are working on releasing the Moodle Docker image with a non-root approach. As part of that, we need to update the chart to use the new port numbers used by the container image.

**Benefits**

Support for environments such as OpenShift, where a non-root UID is required to run a container.

**Possible drawbacks**

Breaking change with previous chart versions, as the default HTTP/HTTPS ports are changed to 8080/8443 (previously 80/443).

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by carrodher** [comment]
Changes in terms of code LGTM, but the `helm install` GH action is failing. In the logs this is the error:
```
WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
INFO  ==> Starting gosu... 
ln: failed to create symbolic link '/etc/cron.d/moodle': Permission denied
cron: can't open or create /var/run/crond.pid: Permission denied
Starting Apache...
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 10.244.0.7. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
```
Not sure if now you need to set some extra parameters when installing the chart (it shouldn't, but if it's the case you can do it by creating a `ci` folder)

**Comment by marcosbc** [comment]
@carrodher That is because we have still not published the non-root Moodle container.

NOTE: @javsalgar is expected to make a few additional changes soon.

**Comment by fle108** [comment]
is there a way to solve this warning ? :
`Skipping cron configuration for Moodle because of running as a non-root`

**Comment by juan131** [comment]
Hi @fle108 

Please refer to https://github.com/bitnami/bitnami-docker-moodle/issues/148

**Pull request merged**
