### PR TITLE
bitnami/redmine Fixing 8314: point to correct externalDatabase name

### PR DESCRIPTION
**Pull request by avkoval**
fixing
https://github.com/bitnami/charts/issues/8314

**Description of the change**

Tried to fix the problem.

**Applicable issues**

https://github.com/bitnami/charts/issues/8314

**Additional information**

I expect some number of users already figured it out and used externalDatabase.name instead, so to be fully backward
compatible I would rather fix the documentation BUT the issue is that bitnami uses `externalDatabase.database` everywhere except here, so since its common I decided to change the template

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Review by carrodher — COMMENTED** [review]
Thanks for your PR, changes LGTM but you need to bump the chart version in the _Chart.yaml_ (see linter errors)

**Comment by juan131** [comment]
@avkoval friendly reminder to bump the chart version as pointed by @carrodher

**Comment by avkoval** [comment]
@juan131 and @carrodher - I've bumped minor version of chart, thank you!

**Review by alemorcuq — COMMENTED** [review]
Thanks!

**Review by alemorcuq — APPROVED** [review]

**Pull request merged**
