### PR TITLE
[bitnami/matomo] Optimize deployment template pod annos

### PR DESCRIPTION
**Pull request by cleverhu**
### Description of the change
Optimize deployment template pod annos. 

### Applicable issues

  - fixes #

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by migruiz4 — COMMENTED** [review]
Hi @cleverhu,

Could you please provide more information about why this approach is more optimal?

As far as I know, there is no functional difference between using the extra if or not:
```diff
+      {{- if or .Values.podAnnotations .Values.metrics.podAnnotations }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.metrics.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.metrics.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
+      {{- end }}
```

**Comment by cleverhu** [comment]
> Hi @cleverhu,
> 
> Could you please provide more information about why this approach is more optimal?
> 
> As far as I know, there is no functional difference between using the extra if or not:
> 
> ```diff
> +      {{- if or .Values.podAnnotations .Values.metrics.podAnnotations }}
>       annotations:
>         {{- if .Values.podAnnotations }}
>         {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
>         {{- end }}
>         {{- if .Values.metrics.podAnnotations }}
>         {{- include "common.tplvalues.render" (dict "value" .Values.metrics.podAnnotations "context" $) | nindent 8 }}
>         {{- end }}
> +      {{- end }}
> ```
The only difference is that annotations will not be rendered when rendering yaml. And it seems more And it seems more standard.

**Review by migruiz4 — APPROVED** [review]
Thank you for your answer, looks good to me!

**Comment by migruiz4** [comment]
Duplicated of #13122, after rebasing the branch, no changes are applied.

**Pull request closed without merging**
