### PR TITLE
Remove explicit null assignment to nodePort in Kubernetes Service

### LINKED ISSUE #21501: nodePort: null -> Incorrect type. Expected "integer".
### Name and Version

bitnami/rabbitmq

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi!

We're building application.yaml using `helm template rabbitmq`

In the generated file I see that `nodePort: null` is not a valid value according to the schema kubernetes://schema/io.k8s.api.core.v1.serviceport 

Ideally, I prefer that the generated yaml file should be a valid one. Maybe this is an issue not related to the schema itself.  Luckily it doesn't impact the runtime behavior anyhow. But the point is - when I remove `nodePort: null` from the file - the service keeps working identically. Is it needed?

### What do you see instead?

image

### PR DESCRIPTION
**Pull request by opencmit2**
### Description of the change

Remove explicit null assignment to nodePort in Kubernetes Service
### Benefits

In Kubernetes Service, it is not necessary to explicitly set nodePort to null. If nodePort is not set, its value defaults to null. This commit removes the explicit null assignment, simplifying the code.
### Applicable issues

- fixes #21501 

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by ThePlenkov** [comment]
Hi @opencmit2 . Thanks for picking up this issue. I decided to bring few more corrections to get rid also of  `Incorrect type. Expected "array".` error.  I created one PR, which if you approve - will update this one automatically. https://github.com/opencmit2/charts/pulls

**Comment by opencmit2** [comment]
> 嗨 。感谢您发现此问题。我决定再进行一些更正，以消除错误。我创建了一个 PR，如果您批准，它将自动更新这个 PR。https://github.com/opencmit2/charts/pulls`Incorrect type. Expected "array".`
Thank you for your contribution! Could you please include the '-s' command when you make your commit?

**Comment by heyanlong** [comment]
@opencmit2 @ThePlenkov charts is an open source product released under the Apache 2.0 license (see either [the Apache site](https://www.apache.org/licenses/LICENSE-2.0) or the [LICENSE.txt file](https://github.com/heyanlong/OpenSearch/blob/main/LICENSE.txt)). The Apache 2.0 license allows you to freely use, modify, distribute, and sell your own products that include Apache 2.0 licensed software.

We respect intellectual property rights of others and we want to make sure all incoming contributions are correctly attributed and licensed. A Developer Certificate of Origin (DCO) is a lightweight mechanism to do that.

The DCO is a declaration attached to every contribution made by every developer. In the commit message of the contribution, the developer simply adds a Signed-off-by statement and thereby agrees to the DCO, which you can find below or at [DeveloperCertificate.org](http://developercertificate.org/).

**Comment by opencmit2** [comment]
Hi @carrodher 
Since I verified that @ThePlenkov  changes would cause some features to be unavailable, but I had already approved his code, this forced me to delete this PR. I have resubmitted a new one, #21545.

**Pull request closed without merging**
