### PR TITLE
[bitnami/kube-prometheus] Allow override of prometheus.routePrefix

### PR DESCRIPTION
**Pull request by crandles**
Signed-off-by: Chris Randles <randles.chris@gmail.com>

**Description of the change**

This adds support for configuring the [Prometheus](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) `routePrefix` field.

**Benefits**

This allows prometheus to be served from a subpath.

**Possible drawbacks**

N/A

**Applicable issues**

N/A

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by crandles** [comment]
Hold, i need to modify the externalUrl field with this prefix

**Comment by crandles** [comment]
OK, all set now, this is working with the following snippet:

```yaml
prometheus:
  routePrefix: /prometheus
  ingress:
    enabled: true
    annotaions:
      # ...
    hosts:
      - name: example.domain.com
        path: /prometheus
```

**Review by andresbono — APPROVED** [review]
LGTM

**Comment by andresbono** [comment]
Thanks for your contribution, @crandles!!

**Pull request merged**
