### PR TITLE
[bitnami/minio] add app label

### PR DESCRIPTION
**Pull request by lusson-luo**
Signed-off-by: lusson <lusson@foxmail.com>

minio chart add app label, Meet the requirements of Istio labels
https://istio.io/docs/ops/deployment/requirements/
The app label is used to add contextual information in distributed tracing (in Istio).

### Description of the change

minio

### Benefits

The app label is used to add contextual information in distributed tracing (in Istio).

### Possible drawbacks
no

### Applicable issues
no

### Additional information
no

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by rafariossaa — COMMENTED** [review]
Hi,
  I am not sure about this PR because you could use `statefulsetLabels`, `commonLabels` or `podLables` to add that label without the need of hardcoding it.

**Comment by lusson-luo** [comment]
> 你好， 我可以使用这个 PR，因为可以`statefulsetLabels`添加该标签而使用硬编码。`commonLabels``podLables`

I think it's a feature support, or something standardized, so it's more explicit in the code anyway.

I looked at other charts of bitnami, some added app to sts, some did not, does the label of app set a unified addition standard, specified in values, or in sts (such as es)

**Comment by lusson-luo** [comment]
Bitnami other charts use hardcode
image

image

**Comment by lusson-luo** [comment]
@rafariossaa You guys better come up with a standardized rule so I know where to add it

**Comment by rafariossaa** [comment]
Hi,
  From time to time, we review the charts catalog and homogenize it. So, this appearances of the `app:` might be removed.
  Istio has also an open issue regarding the use of standard [kubenernetes labels](https://github.com/istio/istio/issues/10724), so maybe this will change in the istio side too.
  I think it would be better see what happens in the end. Meanwhile, the properties in the values can be used to add the needed labels.

**Pull request closed without merging**
