### PR TITLE
[bitnami/mariadb] Bug/mariadb service fix

### PR DESCRIPTION
**Pull request by prince129**
### Description of the change

Change is made to MariaDB template of primary and secondary svc.yaml where if service type is LoadBalancer then we can specify list of loadBalancerSourceRanges. Current the helm release fails if values provided are in list.
Changes will accommodate those list of IP ranges.

### Benefits
We can pass multiple IP ranges to get whitelisted on loadbalancer end.

### Applicable issues
Same issue is occuring for Mariadb as well

- fixes #18407

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! Could you fix the merge issue?

**Comment by prince129** [comment]
> Hi!
> 
> Thank you so much for the PR! Could you fix the merge issue?

Merge issue is fixed

**Review by corico44 — DISMISSED** [review]
LGTM

**Review by corico44 — APPROVED** [review]
LGTM

**Pull request merged**
