### PR TITLE
[bitnami/external-dns]  Add value for filtering by IngressClass

### PR DESCRIPTION
**Pull request by FalconerTC**
### Description of the change

Add Helm support for filtering the ingresses watched by external-dns by IngressClass (added in https://github.com/kubernetes-sigs/external-dns/pull/3589)

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by FalconerTC** [comment]
Just saw https://github.com/bitnami/charts/issues/17382 and realized this requires external-dns 0.13.5

**Comment by FraPazGal** [comment]
Hello @FalconerTC, our `bitnami/external-dns@0.13.5` is now available with https://github.com/bitnami/charts/pull/17692. Could you please update your branch with `main` changes?

**Comment by fevisera** [comment]
Hi @FalconerTC,

I'm sorry to have to ask you, but I need you to resolve the conflicts again. A new version has been released to fix [one of the steps](https://github.com/bitnami/charts/actions/runs/5678838151/job/15389825367) that was failing.

Thank you.

**Review by fevisera — APPROVED** [review]
LGTM.

Thank you for your contribution!

**Pull request merged**
