### PR TITLE
bitnami/influxdb remove InfluxDB logic for branch 1

### PR DESCRIPTION
**Pull request by gongomgra**
Signed-off-by: Gonzalo Gomez Gracia <gonzalog@vmware.com>

**Description of the change**

Removes logic for InfluxDB branch 1.

**Benefits**

A cleaner logic in InfluxDB charts.

**Possible drawbacks**

InfluxDB container for version 1.x can't be used.

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by jotamartos — APPROVED** [review]
Changes LGTM but wait for others to review the changes. I think it'd be great if you land them using the pipeline to verify everything works as expected.

**Review by carrodher — APPROVED** [review]

**Comment by TK-Khaw** [comment]
Hi @gongomgra I can see that this in PR code with regards to branch 1 had been removed. You did mentioned that possible drawback includes that InfluxDB 1.x will no longer be usable, and indeed from testing that is true. From #6813, we see that high-availability setup not possible at the moment for InfluxDB 2.x. Thus, I think this PR effectively rendered high-availability feature unusable, with default configuration that is. Do you have any advice on how to proceed with this should we still need to use high-availability feature, moving forward?

**Comment by marcosbc** [comment]
Hi @TK-Khaw, thanks for pointing that out. At the moment we are not able to support InfluxDB 1.x anymore, however, we are open to any contribution to add HA features for 2.x. I will make sure to update our internal task as well.

**Comment by TK-Khaw** [comment]
Hi @marcosbc , thanks for shedding a better light on the issue currently. From what I see in the repo for influxdb-relay, it seems like there's been two years since it's last updated. You reckoned that someone should fork the repo and continue the work to support influxdb 2.x?

**Comment by marcosbc** [comment]
Thanks for pointing that out. It seems like it is not supported anymore: https://github.com/influxdata/influxdb-relay/issues/81.

This means that we would need to deprecate it for now. Unfortunately a fork is not something that would work for us at this moment. 

In the case of influxdb-relay it was maintained by the creators of InfluxDB, so adding it was an option. However, if there is no way to keep HA support in the open-source edition anymore, with version 2.x of InfluxDB, it is possible that we will need to close that feature request for now, because it is a product limitation.

**Pull request merged**
