### PR TITLE
[bitnami/node] Remove NodeJS folders

### PR DESCRIPTION
**Pull request by carrodher**
### Description of the change

It Depends on https://github.com/bitnami/charts/pull/13142, we need to do an effective release with the deprecation parameters and then remove the associated folders.

⚠️ It is normal the failure action since we are not bumping any Helm chart version here. This PR should be merged without successful actions

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by marcosbc — DISMISSED** [review]
LGTM!

**Review by joancafom — DISMISSED** [review]
LGTM! Thanks for your PR

**Comment by carrodher** [comment]
The Helm chart was deprecated so we can safely remove its associated code:
```console
$ helm repo update bitnami && helm search repo bitnami/node
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/node         	19.1.7       	16.18.0    	DEPRECATED Node.js is a runtime environment bui...
```

**Comment by itscaro** [comment]
@carrodher Would it be possible to deprecate tomcat as well, as it is a runtime as NodeJS. IMO a chart should be an application deployment.

**Comment by carrodher** [comment]
> @carrodher Would it be possible to deprecate tomcat as well, as it is a runtime as NodeJS. IMO a chart should be an application deployment.

Thanks for the suggestion, at this moment there are no plans to deprecate Tomcat

**Pull request merged**
