### PR TITLE
[bitnami/moodle] Bugfix: container port different from http

### PR DESCRIPTION
**Pull request by rafacouto**
### Description of the change

This change fixes the problem related to issue #16149 and any other when the service is ClusterIP type and the container listening port is not the standard HTTP port (e.g. moodle server running as a non-privileged user on 8080).

### Benefits

With this fix, the service target port gets configured with the value specified on `containerPorts.http` and the container service can be reached by the ingress.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by rafacouto** [comment]
> In this case there is still an issue, see https://github.com/bitnami/charts/pull/16744/checks?check_run_id=13607956236 for more info about the issue and how to fix it.

Fixed! Thank you :+1:

**Comment by carrodher** [comment]
Please note it's needed to bump the chart version in the _Chart.yaml_ file

**Comment by rafacouto** [comment]
Bumped 16.1.2 chart version :)

**Comment by rafacouto** [comment]
Hi @aoterolorenzo ,

You are right, the fix is transversal and it should be modified on every Chart using a custom port for http/https. More over, to include standard http/https ports in the base service template should be reviewed (an application could not use web port services, the postgresql chart for instance).

However, if it implies to review every chart, I suggest to open another issue to do so. Meanwhile, IMO, we can patch the Moodle chart and other known affected charts.

Please, if it looks good to you, discuss this issue with bitnami leaders and proceed with merge or close this PR :smiley_cat:

**Comment by aoterolorenzo** [comment]
Hi [rafacouto](https://github.com/rafacouto),

Would you prepare this PR to fix only Moodle? (changes are still affecting the template, not moodle)

Also, we also should need to file a new issue to properly escalate this to other charts, in case you want to keep contributing. From that point, we should create a PR for each asset.

**Comment by rafacouto** [comment]
Bo día @aoterolorenzo,

- Moodle chart fixed. Please, merge this PR.
- I'll also fix the well-known #16149 with the same problem.
- Please, if it LGTY, open another issue to implement the [solution you've proposed here](https://github.com/bitnami/charts/pull/16744#issuecomment-1556877168).

Thanks for your suggestions :+1:

**Review by aoterolorenzo — APPROVED** [review]
LGTM @rafacouto !

**Comment by aoterolorenzo** [comment]
PS: I just raised an internal task for the team to address this. Your proposal will be referenced there!

**Pull request merged**
