### PR TITLE
[bitnami/valkey-cluster] update metrics-svc template name format

### LINKED ISSUE #27970: [bitnami/valkey-cluster] Error: UPGRADE FAILED: YAML parse error on common/charts/valkey-cluster/templates/metrics-svc.yaml: error converting YAML to JSON: yaml: line 4: mapping values are not allowed in this context
### Name and Version

bitnami/valkey-cluster-0.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

```yaml
metrics:
  enabled: true
```

metric 활성화 후 helm install시 에러가 발생합니다.

### What do you see instead?
```
Error: UPGRADE FAILED: YAML parse error on common/charts/valkey-cluster/templates/metrics-svc.yaml: error converting YAML to JSON: yaml: line 4: mapping values are not allowed in this context
```

### PR DESCRIPTION
**Pull request by sunyeongchoi**
### Description of the change

Changed "`name:`" from being entered twice to entering it only once.

#### before
`name: name: ~~`

#### after
`name: ~~`

### Benefits

we can enable metric in valkey-cluster.

### Possible drawbacks

None.

### Applicable issues

- fixes #27970

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! Could you bump the chart version?

**Comment by sunyeongchoi** [comment]
@jessebot
Thank You! I was confused about what is 'chart version bump', so thank you for letting me know.

**Comment by sunyeongchoi** [comment]
@javsalgar
Thanks for your review.
I just updated chart version now :)

**Review by andresbono — APPROVED** [review]
LGTM! Thank you for your contribution 🎉

**Pull request merged**
