### PR TITLE
[bitnami/etcd] Debug logging added to the pod scripts. Pod affinity fixed

### PR DESCRIPTION
**Pull request by vi7**
**Description of the change**

* `image.debug` chart parameter enables additional debug logging for all the scripts deployed by `templates/scripts-configmap.yaml`
* pod affinity indentation fixed

**Benefits**

ability to enable debug logging in the scripts from the `templates/scripts-configmap.yaml` radically simplifies life of a person who deploys etcd using this chart

**Possible drawbacks**

n/a

**Applicable issues**

n/a

**Additional information**

n/a

**Checklist** [Place an '[X]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by miguelaeh** [comment]
lgtm

**Comment by pantaoran** [comment]
Unfortunately the debug output from `probes.sh` and `prestop-hook.sh` will never appear in any Kubernetes logs because current versions of Kubernetes simply discard output of such scripts rather than sending it to the pod logs. 
But maybe in the future it will work, who knows.

**Comment by vi7** [comment]
> Unfortunately the debug output from `probes.sh` and `prestop-hook.sh` will never appear in any Kubernetes logs because current versions of Kubernetes simply discard output of such scripts rather than sending it to the pod logs.
> But maybe in the future it will work, who knows.

Hi @pantaoran, thanks for you comment. I've noticed that behaviour as well but if I got [that discussion](https://github.com/kubernetes/kubernetes/issues/16412) properly - such kind of logging is performed by kubelet

**Comment by bryanhuntesl** [comment]
+1 - In my case I know exactly what's wrong with my postStart hook - however - out of curiosity I decided I'd investigate what options are available if I didn't know - it doesn't seem like there are many - this is a rough edge.

**Comment by bryanhuntesl** [comment]
+1 - In my case I know exactly what's wrong with my postStart hook - however - out of curiosity I decided I'd investigate what options are available if I didn't know - it doesn't seem like there are many - this is a rough edge.

**Pull request merged**
