### PR TITLE
[bitnami/nginx-ingress-controller]: Disable the requirement for extensions GroupApi

### PR DESCRIPTION
**Pull request by Rubemlrm**
**Description of the change**

This change is relative to the removal of hard coded extensions apiGroup, to be replaced based on a helper that will determine the requirement based on kubernetes version.

**Benefits**

The possibility to use the chart without the need to include apiGroup extensions into role and cluster role when this apiGroup is deprecated

**Possible drawbacks**

NA

**Applicable issues**

NA

**Additional information**

**Checklist**
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by fmulero — APPROVED** [review]
Great! Thanks @Rubemlrm  it looks good to me

**Review by fmulero — CHANGES_REQUESTED** [review]
Sorry, could you resolve the conflicts? I will be on top of this to merge it as soon as possible

**Comment by Rubemlrm** [comment]
> Sorry, could you resolve the conflicts? I will be on top of this to merge it as soon as possible

just submitted a commit with the conflict fix =)

**Comment by fmulero** [comment]
Running tests. If everything goes well in some minutes it will be merged

**Review by fmulero — APPROVED** [review]

**Pull request merged**
