### PR TITLE
[bitnami/influxdb] resources, aws cli cache and service account for the backup part in the helm chart

### LINKED ISSUE #24324: [bitnami/influxdb] resources, aws cli cache and service account for the backup part in the helm chart
### Name and Version

bitnami/influxdb 5.18.1

### What is the problem this feature will solve?

In the backup part of the helm chart, there are multiple Problems when deploying to a restricted OpenShift namespace.

1. You do not have the possibility to set resources in any of the backup containers.
1. Also the aws cli needs an `.aws` folder as its cache.
1. The last Problem is the service account. It is currently not possible to use an other service Account than the default for the name space.

### What is the feature you are proposing to solve the problem?

1. Set up a resources in the chronjob-backup.yaml that are configurable in the values.yaml
2. Add an other empty dir sub-dir for the `.aws` cache
3. Add the influx service account to the backup if it is created or setup a backup service account

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by jeb1jeb2**
### Description of the change

The change fixes multiple problems with the backup part of the influxdb helm chart metioned in #24324.

1. Adding resources to the containers
2. Adding a cache for the aws-cli
3. Adding the service account to the cronjob

### Benefits

The backup is usable in a OpenShift environment where no resources get auto selected.

### Possible drawbacks

The service account can not be different for the deployment and the backup cronjob.

### Applicable issues

- fixes #24324 

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by dgomezleon — APPROVED** [review]
The changes LGTM. Could you pleas update it to resolve the conflicts?

**Review by dgomezleon — APPROVED** [review]

**Comment by jeb1jeb2** [comment]
I made a mistake i tought i corrected. The indentation for the resources should be 16 not 12...

**Comment by dgomezleon** [comment]
Hi @jeb1jeb2 ,

Did you send a new PR?

**Comment by jeb1jeb2** [comment]
I'm on it.

**Comment by jeb1jeb2** [comment]
New PR is #24444

**Comment by dgomezleon** [comment]
> New PR is #24444

Thanks. Accepted and merged.

**Pull request merged**
