### PR TITLE
[bitnami/thanos] Fix autoGenerated GRPC certs by using common CA

### LINKED ISSUE #15974: [bitnami/thanos] Query unable to connect with grpc.server.tls.autoGenerated=true
### Name and Version

bitnami/thanos 12.1.2

### What architecture are you using?

None

### What steps will reproduce the bug?

Deploy chart with following custom config:
  ```
  # Custom values for thanos.
  query:
    enabled: true
    grpc:
      client:
        tls:
          enabled: true
          autoGenerated: true
  storegateway:
    enabled: true
    grpc:
      server:
        tls:
          enabled: true
          autoGenerated: true
  ```

### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

Expected behavior is communication between query/storegateway with TLS enabled, so query could also connect to other stores behind nginx reverse proxy with TLS enabled.

Note that it doesn't work even if extra flag is added to stop validating certs on query:
```
  extraFlags:
  - --grpc-client-tls-skip-verify
```

### What do you see instead?
```
level=warn ts=2023-04-06T07:03:11.196180131Z caller=endpointset.go:446 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from 10.0.85.117:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.0.85.117:10901
```
### Additional information

_No response_

### PR DESCRIPTION
**Pull request by migruiz4**
### Description of the change

Fixes an issue with Thanos when using autoGenerated certs.

The issue was caused by the generated certs not sharing the same CA, causing communication between the Query component and the StoreGateway and Receive components to fail.

This PR reorganizes the templates including the GRPC cert secrets, so autoGenerted certs can share the same CA.

Additionally, adds the flag `--grpc-client-tls-skip-verify` when using autoGenerated certs in the Thanos Query deployment.
Thanos Query uses the Thanos Receive and Thanos StoreGateway IP instead of the service name. It is not possible to know the pod's IP during the certificate generation, therefore the flag is always needed.

### Possible drawbacks

None known

### Applicable issues

- fixes #15974

### Additional information

Similar to other charts, due to the usage of `lookup` function to prevent certificate regeneration on each restart, enabling a new component during an upgrade would require manually removing the secrets before upgrading.

Otherwise, each component's certs would be generated using a different CA.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by pduchnovsky** [comment]
Hey guys, any ETA of merge ?

**Review by aoterolorenzo — APPROVED** [review]
LGTM!

**Comment by g00pix** [comment]
Hello,

If anyone finds this, the commit contains breaking changes as there are now requirements when `query.grpc.client.tls` is set to true.

```
Error: execution error at (thanos/templates/grpc-tls-secrets.yaml:118:15): 'query.grpc.client.tls.cert' is required when 'query.grpc.client.tls=true'
````

**Comment by migruiz4** [comment]
Hi @g00pix,

Could you please provide more details? In what scenario did you find this issue? What are the exact values used to deploy?

The error you shared is not caused by the changes included in this PR, but a check present in previous versions:
```
miruiz@miruiz2MD6T bitnami % helm install test bitnami/thanos --set query.grpc.client.tls.enabled=true --dry-run --version 12.4.3
Error: INSTALLATION FAILED: execution error at (thanos/templates/grpc-tls-secrets.yaml:118:15): 'query.grpc.client.tls.cert' is required when 'query.grpc.client.tls=true'
miruiz@miruiz2MD6T bitnami % helm install test bitnami/thanos --set query.grpc.client.tls.enabled=true --dry-run --version 12.4.1
Error: INSTALLATION FAILED: execution error at (thanos/templates/query/grpc-client-tls-secrets.yaml:26:15): 'query.grpc.client.tls.cert' is required when 'query.grpc.client.tls=true'
```

That error is caused by setting `query.grpc.client.tls.enabled`, but not providing the certificates using any of the following values:
- `query.grpc.client.tls.existingSecret` with the name of the secret containing the TLS certificates.
- `query.grpc.client.tls.cert`,`query.grpc.client.tls.key` and `query.grpc.client.tls.ca` providing your certificates in plain text in your `values.yaml`.
- `query.grpc.client.tls.autoGenerated=true` to autoGenerate the certificates. (Not recommended for production environments).

By default, none of these options are enabled so the chart installation will fail unless you provide one of these options.

**Comment by g00pix** [comment]
Hi,

Thank you for your answer. I figured it was indeed my fault but I thought it was new behavior, I guess it's not. Sorry I wasted your time, in the end the behavior you described makes a lot of sense so I don't think it's worth wasting more time on that.

**Pull request merged**
