### PR TITLE
[bitnami/mongodb] Fix missing generate-certs.sh

### PR DESCRIPTION
**Pull request by jwleon**
### Description of the change

Fixes [Issue #10300](https://github.com/bitnami/charts/issues/10300#issue-1239902095) where setting `autoGenerated` to `false` results in `generate-certs.sh` file not being written. The file is required during pod initialization. There might be better solutions, but since the problem is breaking our complete MongoDB deploy we need an instant fix for this. Feel free to improve on that solution.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by jmConan** [comment]
the given change doesnt change the behaviour for `autoGenerated: true` scenarios at all. for `autoGenerated: false` it runs some unused code which is not doing any harm to a deployment using `existingSecrets` or given `caCert & caKey`. what TLS credentials are used is decided in another logic block.

**Comment by javsalgar** [comment]
Hi! Thanks for the PR! Could you fix the merge issue?

**Comment by jwleon** [comment]
Sure thing, have resolved the merge conflict due to version number

**Comment by jwleon** [comment]
Is that PR still considered @javsalgar ? Have just solved the merge conflict (version number) a second time ;-)

**Review by javsalgar — APPROVED** [review]

**Pull request merged**
