### PR TITLE
bitnami/consul Add activation of gossip encryption when custom key is set

### LINKED ISSUE #20327: [bitnami/consul] Gossip encryption is not activated when specifying custom encryption key
### Name and Version

bitnami/consul 10.13.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Generate a new gossip encryption key using `consul keygen` (`docker run -it bitnami/consul:1.16.2 consul keygen`)
2. Put this encryption key in your consul values.yaml file at `gossipKey: ""`
3. Helm install the chart
4. Inspect the beginning of the log of one of the consul pods. 

### Are you using any custom parameters or values?

`gossipKey: "DVoLa/k99hfBEdIfCLkzSpWg4obElLYVIFDsutKCL/w="`

### What is the expected behavior?

The expected behaviour would be for Consul to start up and show it is using Gossip Encryption.

### What do you see instead?

Consul will start without enabling gossip encryption. It says `Gossip Encryption: false` in the logging:

```
consul 16:53:14.62
consul 16:53:14.62 Welcome to the Bitnami consul container
consul 16:53:14.62 Subscribe to project updates by watching https://github.com/bitnami/containers
consul 16:53:14.62 Submit issues and feature requests at https://github.com/bitnami/containers/issues
consul 16:53:14.62
consul 16:53:14.62 INFO  ==> ** Starting Consul setup **
consul 16:53:14.63 INFO  ==> Validating settings in CONSUL_* env vars..
consul 16:53:14.64 INFO  ==> Initializing Consul...
consul 16:53:14.64 INFO  ==> Deploying consul with persisted data...
consul 16:53:14.64 INFO  ==> No injected configuration files found. Creating default config files...
find: '/docker-entrypoint-initdb.d/': No such file or directory
consul 16:53:14.64 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
consul 16:53:14.64 INFO  ==> ** Consul setup finished! **

consul 16:53:14.65 INFO  ==> ** Starting Consul **
==> Starting Consul agent...
               Version: '1.16.2'
            Build Date: '2023-09-19 19:29:18 +0000 UTC'
               Node ID: 'ea2d2de0-8108-d2e6-3b75-8f56850933db'
             Node name: 'consul-pr-0'
            Datacenter: 'dc1' (Segment: '<all>')
                Server: true (Bootstrap: false)
           Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: -1, gRPC-TLS: 8503, DNS: 8600)
          Cluster Addr: 10.1.0.40 (LAN: 8301, WAN: 8302)
     Gossip Encryption: false
      Auto-Encrypt-TLS: false
           ACL Enabled: false
     Reporting Enabled: false
    ACL Default Policy: allow
             HTTPS TLS: Verify Incoming: false, Verify Outgoing: false, Min Version: TLSv1_2
              gRPC TLS: Verify Incoming: false, Min Version: TLSv1_2
      Internal RPC TLS: Verify Incoming: false, Verify Outgoing: false (Verify Hostname: false), Min Version: TLSv1_2
```

### Additional information

This is caused by a missing `CONSUL_GOSSIP_ENCRYPTION="yes"` environment variable. I'm preparing a PR.

When the PR is merged, the chart will still fail until https://github.com/bitnami/containers/issues/51959 is resolved by merging https://github.com/bitnami/containers/pull/51982

### PR DESCRIPTION
**Pull request by daanknoope**
### Description of the change

This change adds a required environment variable to the consul container to activate gossip encryption when a custom key is set.

### Benefits

This will enable gossip encryption without requiring additional custom environment variables when a custom key is specified.

### Possible drawbacks

Since the underlying consul container contains a bug (https://github.com/bitnami/containers/issues/51959) causing consul to break when using a custom gossip key, merging this PR right now will cause errors. The current chart does not experience this problem, since it does not enable gossip encryption.

It would therefore be a good idea to only merge this chart when https://github.com/bitnami/containers/pull/51982 is merged and a new bitnami/consul container has been released.

### Applicable issues

- fixes #20327

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by juan131** [comment]
Thanks @daanknoope !! I'll wait for @gongomgra to review your contribution in the container before submitting my review of the chart.

**Comment by juan131** [comment]
Now unblocked! @daanknoope could you please update the Consul image version in the `values.yaml`? Thanks in advance.

**Comment by daanknoope** [comment]
> Now unblocked! @daanknoope could you please update the Consul image version in the `values.yaml`? Thanks in advance.

Of course, should be fixed now!

**Review by juan131 — APPROVED** [review]
LGTM

**Pull request merged**
