### PR TITLE
[bitnami/external-dns] fix: add missing api-approved.kubernetes.io annotation to CRD

### PR DESCRIPTION
**Pull request by woehrl01**
### Description of the change

Adds missing annotation `api-approved.kubernetes.io` to CRD, which prevents creation of the CRD if missing because of the k8s.io namespace

### Applicable issues

- fixes #

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by jetersen** [comment]
@woehrl01 FYI https://github.com/bitnami/charts/pull/27434
https://github.com/kubernetes-sigs/external-dns/pull/4488

**Comment by jotamartos** [comment]
Hi @woehrl01,

Thank you for taking the time to create this PR. There is a similar one here and as we mentioned there, CRDs are updated automatically once a new version is released. If we merge this change, it will be automatically removed during the next release of the Bitnami package. You will need to wait for the upstream project to release a new version with the updated CRD for this to be included in the chart. 

https://github.com/bitnami/charts/pull/27434

Thanks

**Comment by woehrl01** [comment]
@jetersen @jotamartos thank you, I understand.

**Comment by jotamartos** [comment]
Closing this PR as there is another one applying the same changes https://github.com/bitnami/charts/pull/27434.

**Pull request closed without merging**
