### PR TITLE
[bitnami/postgresql] Add a NetworkPolicy to allow backup pods to access primary nodes

### PR DESCRIPTION
**Pull request by axelfauvel**
- Fixes https://github.com/bitnami/charts/issues/24286

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by axelfauvel** [comment]
Hi there, any news on this PR ?

**Comment by CeliaGMqrz** [comment]
Hi @axelfauvel 

Sorry for the delay. Thanks for your contribution!

Could you resolve the conflicts?

**Comment by axelfauvel** [comment]
Hi @CeliaGMqrz, conflicts are resolved

**Review by CeliaGMqrz — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
