### PR TITLE
[bitnami/kube-prometheus]Update crd and add configuration

### PR DESCRIPTION
**Pull request by angel7slayer**
**Description of the change**

I updated the crds with the new values

**Benefits**

alertmanagerconfiguration can be set with the update crds
fixes the problem for disabling the matcher for the namespace in which the alertmanager is installed

**Possible drawbacks**

everything is copied from written code

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by yardenshoham** [comment]
Reference: https://github.com/prometheus-operator/prometheus-operator/commit/d41eb193e5bb250e1a1b0c60a120e4e78ab59765

**Comment by yardenshoham** [comment]
@juan131 please review

**Review by yardenshoham — APPROVED** [review]

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the PR. Could you fix the merge issues?

**Comment by angel7slayer** [comment]
> Hi,
> 
> Thank you so much for the PR. Could you fix the merge issues?

Hey, I fixed the merge issue

**Review by yardenshoham — APPROVED** [review]

**Pull request merged**
