### PR TITLE
[bitnami/keycloak] Update ingress.yaml to support optional hostname

### PR DESCRIPTION
**Pull request by turowicz**
Fixing the issue https://github.com/bitnami/charts/issues/6299

### CODE REVIEW

**Comment by turowicz** [comment]
cc @marcosbc

**Comment by turowicz** [comment]
cc @carrodher

**Comment by turowicz** [comment]
cc @miguelaeh

**Review by carrodher — APPROVED** [review]
Thanks for your contribution. LGTM

Once merged the PR, the internal test & release process will be triggered, please note a delay is expected since the changes are merged in GitHub until the chart is pushed to the Bitnami Helm Chart repository, see https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#pr-approval-and-release-process for more information

**Pull request merged**
