### PR TITLE
[bitnami/fluentd] Tidy minor consistency nitpicks in the chart

### PR DESCRIPTION
**Pull request by chadlwilson**
**Description of the change**

Tidies 3 minor nitpicks in the chart

1. moves `priorityClassName` to `forwarder` section in `values.yaml` just under tolerations consistent with other bitnami charts (was incorrectly under the `aggregator` and in a not-so-intuitive location earlier, probably a typo/oversight in #3543)
2. renames `svc-headless.yaml` to `aggregator-svc-headless.yaml` for consistency with the other resource templates
3. Only generates forwarder-related RBAC if `forwarder.enabled=true` (previously these resources would be generated just by enabling the rbac, even if you had disabled the whole forwarder). It's not necessary to check `serviceAccount.create` because this is [validated in _helpers.tpl already](https://github.com/bitnami/charts/blob/591c45810b0756ad8513dd1ea3c0d37be8c81eea/bitnami/fluentd/templates/_helpers.tpl#L154).

**Benefits**

Moves the chart a bit closer towards "principle of least surprise" :-)

**Possible drawbacks**

None known.

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Review by juan131 — APPROVED** [review]
Thanks so much for these fixes!! Approving your changes

**Comment by chadlwilson** [comment]
No problem @juan131 - thank you to you and the team for these excellent charts and regularly rebuilt docker images 👍

**Comment by juan131** [comment]
You're welcome!!
Note: it will take some hours for our pipeline to release the chart version including your changes.

**Comment by chadlwilson** [comment]
Sure thing. Is there somewhere I can read that documents/explains how often & when the pipeline automation runs to update the chart `values.yaml` with a new docker image built off the other upstream image repos?

**Comment by juan131** [comment]
Hi @chadlwilson 

We have a defined policy for that, but there's no current public documentation available at this very moment. I checked our backlog and it seems we already have a task for the docs team to address this specific item. I'll try to raise its priority.

Thanks for your feedback!

**Pull request merged**
