### PR TITLE
[bitnami/geoipupdate] Add geoipupdate chart

### PR DESCRIPTION
**Pull request by LuciferInLove**
**Description of the change**

Add a Helm Chart to install the MaxMind GeoIP Update to a Kubernetes Cluster.

**Benefits**

The GeoIP update provides updates for automatic updates of GeoIP2 and GeoIP Legacy binary databases. These databases can be used, f.e., by Nginx and Logstash.

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Comment by alvneiayu** [comment]
hi @LuciferInLove 

Thanks for your PR and suggestion to add MaxMind GeoIP in our catalog! We will check it internally and evaluate the feasibility but due to limited resources that could take some time.

[Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. If the container image is not part of the Bitnami catalog at this moment, we can work on that part while we review the Chart PR. If you want some example, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.

Álvaro

**Comment by LuciferInLove** [comment]
Hello. Could someone remove the stale label, please? Do I need to do anything else with this chart?

**Comment by alvneiayu** [comment]
hi @LuciferInLove 

I included the on-hold label. We have some concerns because this is not a server per se. Seeing the project, it seems that there are multiple jobs to update several things and it seems that maybe it makes sense to use it like a sidecar in another chart. But this is something that we need to evaluate. I will keep this PR in on-hold until we decide about it.

Thanks a lot

Álvaro

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!

**Pull request closed without merging**
