### PR TITLE
[bitnami/mongodb] Add loadBalancerClass options

### LINKED ISSUE #12603: Allow setting loadBalancerClass on service configurations
### Name and Version

lots; example: bitnami/mongodb 13.1.5

### What is the problem this feature will solve?

If you run multiple LoadBalancer controller implementations in a single cluster, there is currently no way to configure services created by bitnami Helm charts to use specific implementations.

### What is the feature you are proposing to solve the problem?

The [`spec.loadBalancerClass`](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class) lets you specify which implementation to use. I am proposing to add a field similar to `service.loadBalancerIPs` called `service.loadBalancerClass` that is forwarded into the service configuration.

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by oliver-ni**
Signed-off-by: Oliver Ni <oliver.ni@gmail.com>

### Description of the change

This PR adds `loadBalancerClass` options to the bitnami/mongodb chart.

### Benefits

This will allow users to change the loadBalancerClass of the LoadBalancer services deployed by this chart.

### Possible drawbacks

None as far as I can see

### Applicable issues

  - fixes #12603 for bitnami/mongodb

### Additional information

This PR only adds the option for one chart. There are many charts that create LoadBalancer services and it would be nice to have this option for all of them. Is there any easy way to apply these sorts of changes to all charts in bulk?

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by jotamartos — CHANGES_REQUESTED** [review]
Sorry for the delay here and thanks your your contribution. However, we can't accept this because there are errors in our tests. The linter is not passing and there are conflicts too, could you please update the PR with those changes?

```
/tmp/charts/bitnami/mongodb lbc-mongodb                                                                                                                                                                           8s 11:17:47
❯ helm lint
==> Linting .
[ERROR] templates/: parse error at (mongodb/templates/standalone/svc.yaml:29): undefined variable "$root"

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Comment by oliver-ni** [comment]
Hi @jotamartos, sorry I did not see your comment earlier. I've fixed the issue.

**Comment by jotamartos** [comment]
Sorry @oliver-ni,

but the PR still has errors.

```
/tmp/charts/bitnami/mongodb lbc-mongodb                                                                                                                                                                              13:36:10
❯ helm lint
==> Linting .
[ERROR] templates/: parse error at (mongodb/templates/standalone/svc.yaml:29): function "Values" not defined
[WARNING] /tmp/charts/bitnami/mongodb: chart directory is missing these dependencies: common

Error: 1 chart(s) linted, 1 chart(s) failed
```

Please ensure the `helm lint` command succeeds before updating the PR again.

**Comment by cleverhu** [comment]
@jotamartos I create a pr to fix this and optimize some code. PTAL. https://github.com/bitnami/charts/pull/13092

**Comment by cleverhu** [comment]
> Hi @jotamartos, sorry I did not see your comment earlier. I've fixed the issue.

Do you mind if I fix your PR and propose a new one

**Comment by jotamartos** [comment]
Thanks you both for your contributions. I just merged https://github.com/bitnami/charts/pull/13092 so I'll close this one. A new version of the chart should be available soon!

**Pull request closed without merging**
