### PR TITLE
[bitnami/external-dns] Fix #19211 Add traefik-proxy ClusterRole rules

### LINKED ISSUE #19205: [bitnami/external-dns] Update clusterRole template to allow Traefik resouces.
### Name and Version

bitnami/external-dns 6.24.3

### What is the problem this feature will solve?

RBAC support for Traefik CRD resources.
Starting from 0.13.6 version, ExternalDNS supports natively [Traefik Proxy](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/traefik-proxy.md).

clusterRole created from bitnami/external-dns chart doesn't allow Traefik CRD resources.

The only workaround I found is to disable rbac and create `clusterRole` and `clusterRoleBinding` manually,

### What is the feature you are proposing to solve the problem?

Update clusterRole Template to with Traefik `apiGroup` & `resources`.

### What alternatives have you considered?

_No response_

### LINKED ISSUE #19211: [bitnami/external-dns] Add traefik-proxy rules to external-dns helm chart
### Name and Version

bitnami/external-dns 6.24.3

### What is the problem this feature will solve?

To work with traefik, the ClusterRole needs access to its CRDs.

### What is the feature you are proposing to solve the problem?

Add the RBAC as external-dns did in their own helm chart, implemented in this PR: https://github.com/kubernetes-sigs/external-dns/pull/3325

### What alternatives have you considered?

Moving to external-dns own helm charts, but I found rfc2136 bitnami implementation better, and want to stick with it.

### PR DESCRIPTION
**Pull request by trunet**
### Description of the change

Fix #19211 and add traefik-proxy clusterrole rules to allow external-dns to access traefik CRDs annotations.

### Benefits

It'll support to traefik-proxy.

### Possible drawbacks

None

### Applicable issues

- fixes #19211
- fixes #19205 

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by CeliaGMqrz** [comment]
Hi @trunet,

Thanks for your contribution! Can you please resolve the conflicts?

**Comment by trunet** [comment]
@CeliaGMqrz the conflict was due to the Chart version in the yaml. I just resolved, but every time a new release is made, the conflict will happen again.

**Comment by Atoms** [comment]
this is duplicate of https://github.com/bitnami/charts/pull/19168

**Comment by trunet** [comment]
Closing, in favor of the duplicate

**Pull request closed without merging**
