### PR TITLE
[bitnami/zookeeper] Istio service name convention.

### PR DESCRIPTION
**Pull request by TomasKohout**
**Description of the change**

Service port name are changed to be Istio port name complaint. 

**Benefits**

Istio will not complain about bad port name convention. 

**Possible drawbacks**

I do not expect any drawbacks, but I could be wrong. :)

**Applicable issues**

**Additional information**

**Checklist** 
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by TomasKohout** [comment]
Sure I can increase the minor version. :)

**Comment by TomasKohout** [comment]
@marcosbc shall I resolve that conflict or will you take care of it? I'm sorry but I do not know the process yet. :)

**Comment by rafariossaa** [comment]
Hi,
  Yes, you should take care of it.

**Comment by TomasKohout** [comment]
Done. :)

**Comment by rafariossaa** [comment]
Thanks @TomasKohout ,
 Waiting for the CI/CD to test the PR and update the image tags.

**Comment by TomasKohout** [comment]
Thank you very much! :-)

**Pull request merged**
