### PR TITLE
[bitnami/contour]: Updating Contour configuration link because it was moved

### PR DESCRIPTION
**Pull request by steve-fraser**
Updating Contour configuration link because it was moved out of the contour repo into the contour sites repo.

**Description of the change**

Updating  README.md to the correct Contour configuration link because it was moved.

**Possible drawbacks**
Better documentation 

None
**Application issues**

None

### CODE REVIEW

**Comment by randradas** [comment]
thank you! would it be possible to fix the checks that fail?:
* bump up the Chart version following [semver2](https://semver.org/)

Once this is done we can merge the changes :D

**Comment by steve-fraser** [comment]
> thank you! would it be possible to fix the checks that fail?:
> 
>     * bump up the Chart version following [semver2](https://semver.org/)
> 
> 
> Once this is done we can merge the changes :D

I bumped it! Please let me know if there are any issues.

**Comment by randradas** [comment]
Unfortunately other commit bumped the version up on master before you, you need to do it again :(. Please rebase with master en bump it again. It does not happen a lot but today It did.

**Comment by steve-fraser** [comment]
Wr

> Unfortunately other commit bumped the version up on master before you, you need to do it again :(. Please rebase with master en bump it again. It does not happen a lot but today It did.

It's all good. Bumped it again

**Review by carrodher — APPROVED** [review]
Thanks for your contribution. It's not needed to bump the chart version for changes that only affect the README.md (it doesn't matter if the lint GH action is failing due to this).
I just resolved some conflicts due to new versions and now the PR is ready to be merged. Thanks again

**Pull request merged**
