### PR TITLE
[bitnami/kafka] replicate variable logic for keystore

### LINKED ISSUE #19776: Allow for variabilize KeyStore for cert-manager support
### Name and Version

bitnami/kafka:25.3.1

### What is the problem this feature will solve?

I use cert-manager to generate my certs. [Cert-manager](https://cert-manager.io/docs/release-notes/release-notes-0.15/#general-availability-of-jks-and-pkcs12-keystores) provides the variable as keystore.jks to the secret. The kafka chart, requires the keystore to be named `kafka.keystore.jks`:

https://github.com/bitnami/charts/blob/1d30563bf53d4c0ac898cf1070af57aa28a039f1/bitnami/kafka/templates/scripts-configmap.yaml#L242-L248

For the truststore, there is already a variable logic in place, where a user can provide a different name using `tls.jksTruststoreKey`:
https://github.com/bitnami/charts/blob/1d30563bf53d4c0ac898cf1070af57aa28a039f1/bitnami/kafka/templates/scripts-configmap.yaml#L250-L254.

### What is the feature you are proposing to solve the problem?

Replicate the logic to keystores, that is in place for truststores.

### What alternatives have you considered?

Manually update secrets to align with the naming.

### PR DESCRIPTION
**Pull request by danquack**
### Description of the change

Updates the Kafka helm chart to allow the end user to variabilize the keystore secret.

### Benefits

- Allows the user to specify through a variable the name of the secret for which the keystore lives. When using external cert generators (i.e. cert-manager) the key of the secret is not controllable.

### Applicable issues

- closes #19776

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your contribution! Could you please take a look at the [failing action](https://github.com/bitnami/charts/actions/runs/6426450025/job/17450668731?pr=19789)? It seems there is something wrong with the metadata in the _values.yaml_

**Comment by danquack** [comment]
I think it might be because of the readme not updated. I took a stab at that readme update tool, but struggled to get it to work.

**Comment by carrodher** [comment]
The issue is that the parameter is named `jksKeystoreKey` but the metadata is `## @param tls.jksKeystoreSecret` so the name doesn't match

**Comment by danquack** [comment]
@carrodher that should be fixed now.

**Review by joancafom — COMMENTED** [review]
Thanks for your PR! Just a minor comment

**Review by joancafom — APPROVED** [review]
LGTM! Thanks for your changes 🚀

**Pull request merged**
