### PR TITLE
[bitnami/redis] Add annotations on service account.

### PR DESCRIPTION
**Pull request by swbsf**
**Description of the change**
Changes the Service Account creation capability on Redis chart, by adding an option to add annotations to it.

**Possible drawbacks**
I don't see any?

**Applicable issues**
None to my knowledge.

**Checklist**
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by jphilaine** [comment]
Mandatory to use GKE workload identity

**Review by andresbono — APPROVED** [review]
LGTM. Thanks for your contribution!

**Comment by andresbono** [comment]
> Mandatory to use GKE workload identity

Hi @jphilaine, do you mean that the annotation example (commented) should be changed to something else? Can you share a snippet of yaml file with your suggestion? Thanks!

**Comment by jphilaine** [comment]
@andresbono No, it is just fine. You can merge it!

**Comment by andresbono** [comment]
Thanks for the clarification, @jphilaine!

**Comment by andresbono** [comment]
The PR is now merged, @swbsf. Thanks for your contribution!! 🎉

**Pull request merged**
