### PR TITLE
[bitnami/harbor] Fix redis address if using sentinel

### LINKED ISSUE #17704: [bitnami/harbor] Wrong redis address in configmap of registry when using sentinel
### Name and Version

bitnami/harbor 16.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When having redis in a replication setup (sentinel), the address which gets written to the configmap of the registry component has the default port of redis at the end.

Error in logs of registry container:
`redis: error connecting: dial tcp: address release-name-redis-headless:26379/mymaster:6379: too many colons in address`

### Are you using any custom parameters or values?

```
redis:
  enabled: true
  architecture: replication
  sentinel:
    enabled: true
```

### What is the expected behavior?

addr: "release-name-redis-headless:26379/mymaster"

### What do you see instead?

addr: "release-name-redis-headless:26379/mymaster:6379"

### Additional information

":" and port of redis should only be templated when sentinel is disabled.
Currently it's always templated:
`addr: "{{ template "harbor.redis.host" . }}:{{ template "harbor.redis.port" . }}"`

### PR DESCRIPTION
**Pull request by adberger**
### Description of the change

When using sentinel, the current configMap of the harbor registry looks like:
`addr: "release-name-redis-headless:26379/mymaster:6379"`

resulting in the following error in the logs:
`redis: error connecting: dial tcp: address release-name-redis-headless:26379/mymaster:6379: too many colons in address`

### Benefits

harbor registry can connect to redis if using sentinel.

### Possible drawbacks

Not tested yet, as i'm missing the expertise of harbor itself.

### Applicable issues

- fixes #17704

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by Mauraza** [comment]
Hi @adberger,

I tested your changes with the parameters you put in your issue, and the deployment failed:
```bash
2023-07-31T09:09:50Z [ERROR] [/lib/cache/cache.go:114]: failed to ping redis+sentinel://harbor-redis-headless/0, retry after 10s : redis: all sentinels specified in configuration are unreachable
redis: 2023/07/31 09:09:50 sentinel.go:514: sentinel: GetMasterAddrByName master="0" failed: dial tcp: address harbor-redis-headless: missing port in address
redis: 2023/07/31 09:10:00 sentinel.go:514: sentinel: GetMasterAddrByName master="0" failed: dial tcp: address harbor-redis-headless: missing port in address
2023-07-31T09:10:00Z [ERROR] [/lib/cache/cache.go:114]: failed to ping redis+sentinel://harbor-redis-headless/0, retry after 10s : redis: all sentinels specified in configuration are unreachable
2023-07-31T09:10:10Z [DEBUG] [/pkg/permission/evaluator/rbac/casbin_match.go:70]: Starting regexp store purge in 24h0m0s
2023-07-31T09:10:10Z [FATAL] [/core/main.go:143]: failed to initialize cache: retry timeout: redis: all sentinels specified in configuration are unreachable
```
Could you please check it?

**Comment by adberger** [comment]
> Hi @adberger,
> 
> I tested your changes with the parameters you put in your issue, and the deployment failed:
> 
> ```shell
> 2023-07-31T09:09:50Z [ERROR] [/lib/cache/cache.go:114]: failed to ping redis+sentinel://harbor-redis-headless/0, retry after 10s : redis: all sentinels specified in configuration are unreachable
> redis: 2023/07/31 09:09:50 sentinel.go:514: sentinel: GetMasterAddrByName master="0" failed: dial tcp: address harbor-redis-headless: missing port in address
> redis: 2023/07/31 09:10:00 sentinel.go:514: sentinel: GetMasterAddrByName master="0" failed: dial tcp: address harbor-redis-headless: missing port in address
> 2023-07-31T09:10:00Z [ERROR] [/lib/cache/cache.go:114]: failed to ping redis+sentinel://harbor-redis-headless/0, retry after 10s : redis: all sentinels specified in configuration are unreachable
> 2023-07-31T09:10:10Z [DEBUG] [/pkg/permission/evaluator/rbac/casbin_match.go:70]: Starting regexp store purge in 24h0m0s
> 2023-07-31T09:10:10Z [FATAL] [/core/main.go:143]: failed to initialize cache: retry timeout: redis: all sentinels specified in configuration are unreachable
> ```
> 
> Could you please check it?

I surely will.
What values did you use for testing?  
Which components/pods generated these logs?

**Comment by Mauraza** [comment]
Hi @adberger,

I tried with the values of the issue you created:
```
redis:
  enabled: true
  architecture: replication
  sentinel:
    enabled: true
```

**Comment by adberger** [comment]
> Hi @adberger,
> 
> I tried with the values of the issue you created:
> 
> ```
> redis:
>   enabled: true
>   architecture: replication
>   sentinel:
>     enabled: true
> ```

@Mauraza I've made some changes and now it seems to work as intended.  
Can you verify against the new changes?

**Comment by Mauraza** [comment]
Hi @adberger,

Could you solve the conflicts?

**Comment by adberger** [comment]
> Hi @adberger,
> 
> Could you solve the conflicts?

Yes, the pods all were in a running state, when using the values provided.

**Comment by Mauraza** [comment]
Hi @adberger,

I refering to the conficts of the files. 

- bitnami/harbor/Chart.lock
- bitnami/harbor/Chart.yaml

**Review by Mauraza — APPROVED** [review]
Hi @adberger,

Thanks for the contribution. LGTM!

**Pull request merged**
