### PR TITLE
[bitnami/kube-prometheus] fix: Only add metadata keyword if annotation or labels are present

### LINKED ISSUE #19693: [bitnami/kube-prometheus] spec.storage.volumeClaimTemplate.metadata: Invalid value: "null"
### Name and Version

bitnami/kube-prometheus 8.23.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Install `kube-prometheus` with the given `values.yaml` below

### Are you using any custom parameters or values?

```yaml
prometheus:
  persistence:
    enabled: true
    storageClass: csi-cinder-classic-retain
    size: 4Gi
alertmanager:
  persistence:
    enabled: true
    storageClass: csi-cinder-classic-retain
    size: 4Gi
```

### What is the expected behavior?

`kube-prometheus` should be deployed as expected.

### What do you see instead?

The Helm chart installation fails the following error displayed in ArgoCD:

```
Alertmanager.monitoring.coreos.com "prometheus-operator-kube-p-alertmanager" is invalid: spec.storage.volumeClaimTemplate.metadata: Invalid value: "null": spec.storage.volumeClaimTemplate.metadata in body must be of type object: "null"
```
```
Prometheus.monitoring.coreos.com "prometheus-operator-kube-p-prometheus" is invalid: spec.storage.volumeClaimTemplate.metadata: Invalid value: "null": spec.storage.volumeClaimTemplate.metadata in body must be of type object: "null"
```

### Additional information

This problem arises specifically when both `.Values.prometheus.persistence.annotations` and `.Values.commonAnnotations` are not configured. To resolve this issue, a potential solution would involve implementing a validation step to check for the presence of annotations. The `metadata` should be applied only if these annotations are properly configured.

### PR DESCRIPTION
**Pull request by lusu007**
### Description of the change

Before this change, the metadata keyword was always inserted into the volumeClaimTemplate of Prometheus and Alertmanager. This led to an error because the metadata was null.

### Applicable issues

- fixes #19693

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by lusu007** [comment]
Apologies for the interruption, @fevisera. Could you please review this PR when you have a moment?

**Comment by fevisera** [comment]
Hi @lusu007,

Sorry for the delay. I have noticed you created #22561 to fix #22560. Let's wait for that bug to be fixed so I can proceed with this change.

Thanks!

**Comment by fevisera** [comment]
Hi @lusu007,

#22560 has been merged and another #22711 addressing the same problem for this issue has been recently merged.

Closing this issue in favor of #22711.

**Comment by lusu007** [comment]
Hey @fevisera,

Awesome that the issue got fixed! But I’m a bit puzzled about why a newer PR, which does the same thing as mine, got merged instead. It’s a bit of a bummer when you’ve put in the work and then someone else’s PR gets picked.

Just saying, it might not be the best vibe for the open-source community.

**Pull request closed without merging**
