### PR TITLE
[bitnami/common] README: Fixed the desscription for `common.labels.matchLabels`

### LINKED ISSUE #9060: [bitnami/common] README `common.labels.matchLabels` description isn't compatible
### Name and Version

bitnami/common 1.11.1

### What steps will reproduce the bug?

1. Go to [README.md](https://github.com/bitnami/charts/tree/master/bitnami/common#labels);
2. Check the description for `common.labels.matchLabels`: 
    1. _Return the proper Docker Image Registry Secret Names_
3. It matches the description for [pullSecrets/renderPullSecrets](https://github.com/bitnami/charts/tree/master/bitnami/common#images)

### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

The description should be something like -- as seen [here](/bitnami/charts/blob/master/bitnami/common/templates/_labels.tpl#L13):

```
common.labels.matchLabels: Labels to use on deploy.spec.selector.matchLabels and svc.spec.selector
```

### What do you see instead?

The description matches the text for [pullSecrets/renderPullSecrets](https://github.com/bitnami/charts/tree/master/bitnami/common#images): 

```
common.labels.matchLabels: Return the proper Docker Image Registry Secret Names
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by marpontes**
**Description of the change**

Fixes a mismatch description for the parameter `common.labels.matchLabels` on the [bitnami/common] chart.

**Benefits**

People that need to access the documentation of the parameters won't be confused. These descriptions go a long way.

**Possible drawbacks**

Not sure if that should trigger a version bump.

**Applicable issues**

  - fixes #9060

**Additional information**

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Could you merge from master? We just found an issue with the GH action. Sorry for the inconvenience

**Comment by javsalgar** [comment]
Hi! It seems that the branch is still outdated with upstream master

image

That would explain the issue with the action, which is not using the updated version.

**Comment by marpontes** [comment]
Updated

**Comment by marpontes** [comment]
@javsalgar may I suggest reopening this PR? 

I guess it was automatically closed by reference. Then, pushing the newest changes to my repository should now result in a successful run.

**Comment by javsalgar** [comment]
Could you merge from master?

**Pull request merged**
