### PR TITLE
[bitnami/influxdb] Add support custom endpoint s3 for backups

### PR DESCRIPTION
**Pull request by Fenrur**
The `s3` protocol has become the standard in on-premises and the cloud for object storage, and therefore private s3 services.

This just requires adding `backup.uploadProviders.aws.endpoint` to the chart, then an environment variable `AWS_ENDPOINT_URL_S3` to the AWS cli to have its effect. Without value it remains at the public endpoint of AWS S3.

### CODE REVIEW

**Comment by carrodher** [comment]
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute to the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Apart from that, please note it's needed to bump the chart version in the _Chart.yaml_ file so a new release is cut.

Feel free to reach out if you have any questions or need assistance with the signing process.

**Comment by Fenrur** [comment]
@carrodher I think it's good, I signed and changed the chart version.

**Comment by Fenrur** [comment]
@fevisera @carrodher Hello, I don't see any news for my PR?

**Review by fevisera — APPROVED** [review]
Thank you so much for your contribution.
LGTM!

**Pull request merged**
