### PR TITLE
copy eventrouter chart from helm/stable to bitnami

### LINKED ISSUE #4696: [bitnami/eventrouter] move eventrouter from helm/stable to bitnami
**Which chart**:
A new one to be moved to bitnami: eventrouter. See https://github.com/helm/charts/tree/master/stable/eventrouter

**Is your feature request related to a problem? Please describe.**
Yes, helm/stable deprecation, see https://github.com/heptiolabs/eventrouter/issues/121

**Describe the solution you'd like**
Bitnami to provide a new home for the eventrouter helm chart

PR: https://github.com/bitnami/charts/pull/4698

### PR DESCRIPTION
**Pull request by Timvissers**
**Description of the change**
Copied the current eventrouter from https://github.com/helm/charts/tree/master/stable/eventrouter

**Benefits**
Eventrouter helm chart has a home again

**Possible drawbacks**
- Not sure how I can keep the old versions of the eventrouter helm chart. Sorry, I'm new to github collaboration

**Applicable issues**
- Fixes #4696

**Additional information**
Any feedback is welcome

### CODE REVIEW

**Comment by juan131** [comment]
Thanks so much for the PR! We really appreciate it.

I will share your PR with the team, to evaluate if **eventrouter** is a chart that we are interested on maintaining as part of the Bitnami catalog.

As it's explained in the [Contributing Guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md), the are three requirements for a new chart to be added to the catalog:

- The chart should use Bitnami based container images.
- Follow the same structure/patterns that the rest of the Bitnami charts and the Best Practices for Creating Production-Ready Helm charts guide.
- Use an OSI approved license for all the software.

Currently, there is no image for **eventrouter** in the Bitnami catalog, so we'll have to create a task to work on it in case we decided to go ahead. Then, you'll have to adapt the chart structure according to our Best Practices, the folder below contains a template that you can use a reference.

- https://github.com/bitnami/charts/tree/master/template

Regarding the license, I think there won't be issuessince it seems it's Apache2.

**Comment by carrodher** [comment]
We still have this PR on our backlog. Although the PR is open there are some pending items like creating the container and adapt the chart to follow the Bitnami guidelines and best practices, see https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository.

I am adding the `on-hold` label to prevent stale-bot from closing the issue again.

**Comment by juan131** [comment]
Hi @varac 

No news, I'm afraid the associated task is still in our backlog.

We'll notify about our progress. Thanks for you consideration and patience.

**Comment by Timvissers** [comment]
I adapted the chart to pass the PR checks. Not sure if there are more steps to take.

**Comment by carrodher** [comment]
There are three major [requirements to add a new chart to the Bitnami catalog](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository):

- The chart should use Bitnami based container images. If they don't exist, we will need to create an internal task to work on it.
- In the same way, the chart should follow the same structure/patterns that the rest of the Bitnami charts (you can find a basic scaffolding in the [`template` directory](https://github.com/bitnami/charts/tree/master/template)) and the [Best Practices for Creating Production-Ready Helm charts guide](https://docs.bitnami.com/tutorials/production-ready-charts/).
- Use an [OSI approved license](https://opensource.org/licenses) for all the software.

In this case, regarding the first item, it is something that, currently, can't be done by external contributors so we need to plan it accordingly to other priorities, that is why this part can be delayed on our side.

Regarding the second item, this PR doesn't meet the requirements since it was copied from `stable` but it is not following the Bitnami scaffolding and best practices.

**Comment by Timvissers** [comment]
Ok. Thanks for the feedback

**Comment by ndouchin** [comment]
Any news?

**Comment by carrodher** [comment]
No sorry, this is still in the same situation described in this comment (https://github.com/bitnami/charts/pull/4698#issuecomment-796566670). The PR should be updated to follow the Bitnami scaffolding and best practices, and at the same time, we need to internally work on creating the container images.

We have a huge backlog of new charts to be added to the catalog, but internally they are prioritized according to the team capacity and business decision. We added several charts to the catalog in the last months, but unfortunately, this one is still in the TODO list. I'm adding a note into the internal task just to emphasize there is some interest in this asset.

**Comment by recena** [comment]
@Timvissers Hello. Do you plan to address the requirements described [here](https://github.com/bitnami/charts/pull/4698#issuecomment-796566670)?

**Pull request closed without merging**
