### PR TITLE
[bitnami/postgresql-ha]

### LINKED ISSUE #6811: [bitnami/postgres-HA] all the nodes are waiting for primary node to come up
**Which chart**:
postgres-HA  Chart version 7.7.2

**Describe the bug**
I start my postgres-HA deployment with 2 pgpool replicas and 3 postgressql replicas (0,1, and 2) on the Kubernetes cluster.
Initially, everything come up good, Postgresql-0 is primary, and Postgresql-1 and Postgresql-2 are secondary. Now, I delete Postgresql-0(current active) pod.
the Postgresql-1 becomes the new primary and the Postgresql-0 becomes the new standby while the Postgresql-2 remains standby.
Next I delete the Postgresql-0  and Postgresql-1 pods simultaneously. Now, none of the pods are in a running state.
postgresql-0 thinks Postgresql-1 is primary and trying to connect but it errors out that the Name or service couldn't be resolved. The postgresql-1 and Postgresql-2 stuck waiting for the primary node to come up. It is a deadlock. 
```bash
$ k get pods
NAME                                         READY   STATUS             RESTARTS   AGE
kahm-6cf5d5f886-8f7dc                        0/1     CrashLoopBackOff   17         86m
kahm-postgresql-ha-pgpool-68b5965bbf-bgcgx   0/1     CrashLoopBackOff   9          86m
kahm-postgresql-ha-pgpool-68b5965bbf-wq6fc   0/1     CrashLoopBackOff   17         86m
kahm-postgresql-ha-postgresql-0              0/1     CrashLoopBackOff   20         71m
kahm-postgresql-ha-postgresql-1              0/1     Running            17         71m
kahm-postgresql-ha-postgresql-2              0/1     CrashLoopBackOff   16         86m
```

**To Reproduce**

1.  Install postgres-ha 7.7.2 with 2 pgpool replica and 3 postgresql replicas
2.   kill postgresql-0 pod and wait for postgresql-1 to become the new primary
2.   postgresql-0 becomes standby and postgresql-1 is new active while the postgresql-2  remain standby
3.   kubectl delete postgresql-0 and postgresql-1 simultaneously 
4.   None of the postgresql instances is the primary node. Postgresql-0 thinks Postgresql-1 as primary and Postgresql-1 and Postgresql-2 are waiting for the primary node. See the logs below.

**Expected behavior**
since both postgresql-0 and postgresql-1 are killed, postgresql-2 should be new primary and Postgresql-0 and postgresql-1 should be new standby.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ kubectl  get pods
NAME                                         READY   STATUS             RESTARTS   AGE
kahm-6cf5d5f886-8f7dc                        0/1     CrashLoopBackOff   17         86m
kahm-postgresql-ha-pgpool-68b5965bbf-bgcgx   0/1     CrashLoopBackOff   9          86m
kahm-postgresql-ha-pgpool-68b5965bbf-wq6fc   0/1     CrashLoopBackOff   17         86m
kahm-postgresql-ha-postgresql-0              0/1     CrashLoopBackOff   20         71m
kahm-postgresql-ha-postgresql-1              0/1     Running            17         71m
kahm-postgresql-ha-postgresql-2              0/1     CrashLoopBackOff   16         86m

$ kubectl  logs -f kahm-postgresql-ha-postgresql-0
postgresql-repmgr 02:37:39.05 
postgresql-repmgr 02:37:39.05 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 02:37:39.05 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 02:37:39.06 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 02:37:39.06 
postgresql-repmgr 02:37:39.11 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 02:37:39.20 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 02:37:39.21 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 02:37:39.23 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 02:37:47.69 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 02:37:47.71 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 02:37:47.71 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 02:37:48.06 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 02:37:48.07 INFO  ==> Initializing Repmgr...
postgresql-repmgr 02:37:48.09 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 02:37:48.09 INFO  ==> Cleaning stale /kahm/postgresql/data/postmaster.pid file
postgresql-repmgr 02:37:48.11 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 02:37:48.11 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 02:37:48.15 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql-repmgr 02:37:48.23 INFO  ==> Configuring replication parameters
postgresql-repmgr 02:37:48.35 INFO  ==> Configuring fsync
postgresql-repmgr 02:37:48.39 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql-repmgr 02:37:48.47 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2021-07-01 02:37:48.535 GMT [163] LOG:  pgaudit extension initialized
2021-07-01 02:37:48.536 GMT [163] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-07-01 02:37:48.536 GMT [163] LOG:  listening on IPv6 address "::", port 5432
2021-07-01 02:37:48.555 GMT [163] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-07-01 02:37:48.583 GMT [163] LOG:  redirecting log output to logging collector process
2021-07-01 02:37:48.583 GMT [163] HINT:  Future log output will appear in directory "/opt/bitnami/postgresql/logs".
2021-07-01 02:37:48.587 GMT [165] LOG:  database system was interrupted while in recovery at log time 2021-07-01 01:24:42 GMT
2021-07-01 02:37:48.587 GMT [165] HINT:  If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.
2021-07-01 02:37:48.617 GMT [165] LOG:  entering standby mode
2021-07-01 02:37:48.637 GMT [165] LOG:  redo starts at 0/A000140
2021-07-01 02:37:48.740 GMT [165] LOG:  consistent recovery state reached at 0/B105728
2021-07-01 02:37:48.740 GMT [165] LOG:  invalid record length at 0/B105728: wanted 24, got 0
2021-07-01 02:37:48.741 GMT [163] LOG:  database system is ready to accept read only connections
 done
server started
2021-07-01 02:37:48.828 GMT [171] FATAL:  password authentication failed for user "postgres"
2021-07-01 02:37:48.828 GMT [171] DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 10: "local    all              all                    md5"
2021-07-01 02:37:48.829 GMT [171] LOG:  could not send data to client: Broken pipe
postgresql-repmgr 02:37:48.83 INFO  ==> ** Starting repmgrd **
[2021-07-01 02:37:48] [NOTICE] repmgrd (repmgrd 5.2.1) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2021-07-01 02:37:48] [NOTICE] starting monitoring of node "kahm-postgresql-ha-postgresql-0" (ID: 1000)
2021-07-01 02:37:51.893 GMT [169] FATAL:  could not connect to the primary server: could not translate host name "kahm-postgresql-ha-postgresql-1.kahm-postgresql-ha-postgresql-headless.default.svc.cluster.local" to address: Name or service not known
[2021-07-01 02:37:51] [ERROR] connection to database failed
[2021-07-01 02:37:51] [DETAIL] 
could not translate host name "kahm-postgresql-ha-postgresql-1.kahm-postgresql-ha-postgresql-headless.default.svc.cluster.local" to address: Name or service not known

[2021-07-01 02:37:51] [DETAIL] attempted to connect using:
  user=repmgr password=ChangeMe connect_timeout=5 dbname=repmgr host=kahm-postgresql-ha-postgresql-1.kahm-postgresql-ha-postgresql-headless.default.svc.cluster.local port=5432 fallback_application_name=repmgr options=-csearch_path=
[2021-07-01 02:37:51] [ERROR] unable connect to upstream node (ID: 1001), terminating
[2021-07-01 02:37:51] [HINT] upstream node must be running before repmgrd can start

$ kubectl  logs -f kahm-postgresql-ha-postgresql-1
postgresql-repmgr 02:38:42.54 
postgresql-repmgr 02:38:42.54 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 02:38:42.54 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 02:38:42.55 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 02:38:42.55 
postgresql-repmgr 02:38:42.59 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 02:38:42.63 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 02:38:42.64 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 02:38:42.66 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 02:38:47.65 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 02:38:47.66 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 02:38:47.91 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 02:38:47.93 INFO  ==> Initializing Repmgr...
postgresql-repmgr 02:38:47.95 INFO  ==> Waiting for primary node...


$ k logs -f kahm-postgresql-ha-postgresql-2
postgresql-repmgr 02:39:26.58 
postgresql-repmgr 02:39:26.59 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 02:39:26.59 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 02:39:26.59 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 02:39:26.59 
postgresql-repmgr 02:39:26.62 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 02:39:26.69 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 02:39:26.70 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 02:39:26.71 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 02:39:33.49 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 02:39:33.52 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 02:39:33.78 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 02:39:33.81 INFO  ==> Initializing Repmgr...
postgresql-repmgr 02:39:33.83 INFO  ==> Waiting for primary node...
```

**Additional context**

### PR DESCRIPTION
**Pull request by Mauraza**
**Description of the change**

Fix get the postgresql.password

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #6811

**Additional information**

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Review by vgupta-mickey — APPROVED** [review]

**Review by vgupta-mickey — COMMENTED** [review]
{{- ternary (randAlphaNum 10) .Values.postgresql.password (empty .Values.postgresql.password) -}}
    
Don’t this line (line 168) take care what you are trying to achieve ?
If .values.postgresql.password is not empty, then it is not going to generate random password?

**Comment by Mauraza** [comment]
Hi @vgupta-mickey,

You are right, this PR is not valid. I have tested your values and it's working so maybe is related to the persistence.
In case you have run the chart more than once and did not remove the PVC. In that case, exist PVC with other passwords.

**Comment by vgupta-mickey** [comment]
So what is the resolution for this issue? Are you able to reproduce the issue?
Also, I didn’t run the charts with the existed PVC. However, we will run the chart with the existed PVC in future so why the existed PVC stuck with the different password? 
I always supply the same password.

**Comment by Mauraza** [comment]
Hi @vgupta-mickey,

The error was with the password of the user `postgres` it seems because `database system was interrupted ` 
```
2021-07-01 02:37:48.587 GMT [165] LOG:  database system was interrupted while in recovery at log time 2021-07-01 01:24:42 GMT
2021-07-01 02:37:48.587 GMT [165] HINT:  If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.
2021-07-01 02:37:48.617 GMT [165] LOG:  entering standby mode
2021-07-01 02:37:48.637 GMT [165] LOG:  redo starts at 0/A000140
2021-07-01 02:37:48.740 GMT [165] LOG:  consistent recovery state reached at 0/B105728
2021-07-01 02:37:48.740 GMT [165] LOG:  invalid record length at 0/B105728: wanted 24, got 0
2021-07-01 02:37:48.741 GMT [163] LOG:  database system is ready to accept read only connections
 done
server started
2021-07-01 02:37:48.828 GMT [171] FATAL:  password authentication failed for user "postgres"
2021-07-01 02:37:48.828 GMT [171] DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 10: "local    all              all                    md5"
```

I tried to reproduce it today but I am not able to do it.

**Comment by vgupta-mickey** [comment]
This is super easy to reproduce. If you use my settings and make postgresql-0 - standby, 1- primary and 2-standby, and then kill pod postgreql-0 and postgresql-1 simultaneously.

**Comment by Mauraza** [comment]
Hi @vgupta-mickey,

I can get the same error that you get. I follow these steps:
- install the chart
- kill postgresql-0, so the primary is postgresql-1
- when the information has propagated (all the pods are 1/1)
- kill postgresql-0 and postgresql-1  and the postgresql-2 will be the primary 

If all replicas are on standby the any of the replicas can be primary, that cluster is broken as appears in the log `If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.` .

**Comment by vgupta-mickey** [comment]
Hi,
So what is the issue here?
The scenario I did is always possible in the real deployment.
Please suggest if you have any solution?

Thanks,
Vinod

**Pull request closed without merging**
