### PR TITLE
[bitnami/kube-state-metrics] Add leases to kubeResources

### PR DESCRIPTION
**Pull request by Jack296s**
Signed-off-by: Jack Yang qwedd296@gmail.com

### Description of the change

Adds `leases` to the kubeResources for kube-state-metrics

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by Jack296s** [comment]
@joancafom @carrodher please help to review this MR, thanks.

**Comment by Jack296s** [comment]
@joancafom @carrodher please help to review this MR, thanks.

**Comment by Jack296s** [comment]
@joancafom @carrodher please help to review this MR, thanks.

**Comment by Jack296s** [comment]
@joancafom @carrodher please help to review this MR, thanks.

**Review by joancafom — APPROVED** [review]
LGTM! Thanks for your PR 🚀

**Pull request merged**
