### PR TITLE
[bitnami/postgresql] Add extended configuration support for Read replica

### LINKED ISSUE #9472: [bitnami/postgresql] How to pass extendedConfiguration to replication ?
### Name and Version

bitnami/postgresql 11.0.2

### What steps will reproduce the bug?

1. Add Chart as a dependency :
```yaml
dependencies:
  - name: postgresql
    version: 11.0.2
    repository: ${PROXY_REPO_URL}
```
2. Use `architecture: replication` and `primary.extendedConfiguration`
```yaml
architecture: replication

primary:
  extendedConfiguration: |
    listen_addresses='0.0.0.0'
    port=5432
    max_connections=400
    shared_buffers='400MB'
    ...
```

### What is the expected behavior?

_No response_

### What do you see instead?

Note that those settings are only applied on primary and that no replication.extendedConfiguration is available  

Is it a bug or this feature isn't implemented yet ?

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ajammali**
Signed-off-by: Anouar Jammali <jammali.anouar@gmail.com>

### Description of the change

Allow the support for extended configuration to the read replication.

### Benefits

Add the ability to customize the PostgreSQL configuration file on the read replica.

### Possible drawbacks

This still can't ensure that main configuration of the primary and read replicas are the same, which makes it impossible for the read to replace primary.

### Applicable issues

  - fixes #9472
  - This PR replaces the old one: https://github.com/bitnami/charts/pull/9866

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by miguelaeh — APPROVED** [review]
LGTM!

**Comment by carrodher** [comment]
All check and GH actions worked fine but there are some conflicts so we can't merge the PR, can you please solve the conflicts? Thanks!

**Comment by fabiorauber** [comment]
Still needed. Is it possible for others to fix the conflicts? I'm interested.

**Comment by javsalgar** [comment]
cc @ajammali

**Comment by ajammali** [comment]
@javsalgar which branch should I merge in mine ?

**Comment by javsalgar** [comment]
You should merge the master upstream master branch

**Comment by ajammali** [comment]
@javsalgar merge is done but new errors showing up related to bumping version on bitnami/airflow chart which I didn't touch.

**Comment by javsalgar** [comment]
Hi!

The number of files is too high. It seems that something got messed in the PR. Maybe re-creating it would fix the issue?

**Comment by ajammali** [comment]
this is the second time I recreate this PR and it seems endless to get done with it.
if it's not recoverable I suggest to ignore the feature.

**Comment by javsalgar** [comment]
Hi,

Could you share a patch with the exact change so we can try creating the PR ourselves?

**Pull request closed without merging**
