### PR TITLE
[bitnami/mysql] Remove the specified charset config to keep it as default

### PR DESCRIPTION
**Pull request by icefery**
### Description of the change

Removed three specified charset configs in `primary.configuration` and `secondary.configuration`:

1. `character-set-server=UTF8`
2. `collation-server=utf8_general_ci`
3. `default-character-set=UTF8`

### Benefits

This chart has specified `character-set-server=utf8` and `collation-server=utf8_general_ci`, which might be useful for mysql-5.7.

But `utf8mb3` has a lot of problems，so we prefer to use `utf8mb4` now.

Since mysql-8.0, default collation has changed from `utf8mb4_general_ci` to `utf8mb4_0900_ai_ci`.

After this commit, we can just specify `--character-set-server=utf8mb4` in `extraFlags` and no need to override the entire `configuration`.

### Possible drawbacks

There are some defaults:

1. mysql-5.7:

   ```sql
   mysql> show global variables like '%character_set_server%';
   +----------------------+--------+
   | Variable_name        | Value  |
   +----------------------+--------+
   | character_set_server | latin1 |
   +----------------------+--------+
   1 row in set (0.00 sec)

   mysql> show global variables like '%collation_server%';
   +------------------+-------------------+
   | Variable_name    | Value             |
   +------------------+-------------------+
   | collation_server | latin1_swedish_ci |
   +------------------+-------------------+
   1 row in set (0.00 sec)

   mysql> set character_set_server=utf8mb4;
   Query OK, 0 rows affected (0.00 sec)

   mysql> show variables like '%character_set_server%';
   +----------------------+---------+
   | Variable_name        | Value   |
   +----------------------+---------+
   | character_set_server | utf8mb4 |
   +----------------------+---------+
   1 row in set (0.00 sec)

   mysql> show variables like '%collation_server%';
   +------------------+--------------------+
   | Variable_name    | Value              |
   +------------------+--------------------+
   | collation_server | utf8mb4_general_ci |
   +------------------+--------------------+
   1 row in set (0.01 sec)
   ```

2. mysql-8.0:

   ```sql
   mysql> show global variables like '%character_set_server%';
   +----------------------+---------+
   | Variable_name        | Value   |
   +----------------------+---------+
   | character_set_server | utf8mb4 |
   +----------------------+---------+
   1 row in set (0.00 sec)

   mysql> show global variables like '%collation_server%';
   +------------------+--------------------+
   | Variable_name    | Value              |
   +------------------+--------------------+
   | collation_server | utf8mb4_0900_ai_ci |
   +------------------+--------------------+
   1 row in set (0.01 sec)
   ```

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is _not necessary_ when the changes only affect README.md files.
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by jotamartos** [comment]
Hi @icefery,

Thank you for your suggestion and sorry for the delay in reviewing this. I'll update the ticket once I have more information. I'd like to confirm no solutions will break with this change. 

Thanks

**Comment by jotamartos** [comment]
Hi @icefery,

What about if we remove the collation_server line from the configuration but keep the character_set_server one? This way, the chart and all the container's versions will work with the same character_set. According to the documentation, the server will automatically set the collation depending on the version the user is using 

```
The default collation for utf8mb4 differs between MySQL 5.7 and 8.0 (utf8mb4_general_ci for 5.7, utf8mb4_0900_ai_ci for 8.0).
```

https://dev.mysql.com/doc/refman/8.0/en/charset-connection.html

We can apply the same changes in the containers so all solutions will work the same way. If the user needs a different collation for his database, he can modify that using the required env vars.

**Comment by icefery** [comment]
> Hi @icefery,
> 
> What about if we remove the collation_server line from the configuration but keep the character_set_server one? This way, the chart and all the container's versions will work with the same character_set. According to the documentation, the server will automatically set the collation depending on the version the user is using
> 
> ```
> The default collation for utf8mb4 differs between MySQL 5.7 and 8.0 (utf8mb4_general_ci for 5.7, utf8mb4_0900_ai_ci for 8.0).
> ```
> 
> https://dev.mysql.com/doc/refman/8.0/en/charset-connection.html
> 
> * MySQL 5.7
> 
> ```
> mysql> show global variables like '%character_set_server%';
> +----------------------+---------+
> | Variable_name        | Value   |
> +----------------------+---------+
> | character_set_server | utf8mb4 |
> +----------------------+---------+
> 1 row in set (0.05 sec)
> 
> mysql> show global variables like '%collation_server%';
> +------------------+--------------------+
> | Variable_name    | Value              |
> +------------------+--------------------+
> | collation_server | utf8mb4_general_ci |
> +------------------+--------------------+
> 1 row in set (0.03 sec)
> ```
> 
> * MySQL 8.0+
> 
> ```
> 
> mysql> show global variables like '%character_set_server%';
> +----------------------+---------+
> | Variable_name        | Value   |
> +----------------------+---------+
> | character_set_server | utf8mb4 |
> +----------------------+---------+
> 1 row in set (0.01 sec)
> 
> mysql> show global variables like '%collation_server%';
> +------------------+--------------------+
> | Variable_name    | Value              |
> +------------------+--------------------+
> | collation_server | utf8mb4_0900_ai_ci |
> +------------------+--------------------+
> 1 row in set (0.05 sec)
> ```
> 
> We can apply the same changes in the containers so all solutions will work the same way. If the user needs a different collation for his database, he can modify that using the required env vars.

Thanks for your review. That's great, what I'm confused about is `utf8mb4` is more generic but may introduce some breaking changes. Since the specified collation will be removed and no need to override the entire `configuration` any more, it's convenient enough.

I will edit the commit later when free.

**Comment by icefery** [comment]
Hi @jotamartos,
I have re-commited and opened a new PR(https://github.com/bitnami/charts/pull/19766), and only removed the specified `collation-server=utf8_general_ci` config.

**Pull request closed without merging**
