### PR TITLE
[bitnami/mongodb] changed backup cronjob containerSecurityContext

### PR DESCRIPTION
**Pull request by JakobHtz**
Signed-off-by: Jakob Jonathan Heitzmann <jakob.heitzmann@web.de>

### Description of the change

Changed backup.cronjob.containerSecurityContext to more resemble other implementations and make use of the enable field.

### Benefits

Usage stays the same.
Fixes https://github.com/bitnami/charts/issues/20594

### Possible drawbacks

Now the SecurityContext will be parsed directly using the ToYaml function. common.tplvalues.render was used before.

### Applicable issues

- fixes https://github.com/bitnami/charts/issues/20594

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

**Comment by jppdpf** [comment]
Hi guys,

I had the same error and pulled this PR, now I'm getting this one
```

C:\Dev\repos\bitnami-charts>helm upgrade mongodb .\charts\bitnami\mongodb\ --values .\charts\bitnami\mongodb\values.yaml

Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(CronJob.spec.jobTemplate.spec): unknown field "securityContext" in io.k8s.api.batch.v1.JobSpec
```

I'm new to this, is there something wrong on my side or is there a new issue?

Thank you!

**Comment by mkoziel-pfl** [comment]
I ran into the same issue with securityContext not being supported in JobSpec.  According to Kubernetes.io (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#jobspec-v1-batch), securityContext is definitely not allowed to be a child of JobTemplate.spec in the Yaml.  cronjob.yaml in the template folder seems to be the culprit.  Setting podSecurityContext: false in the values.yaml is the only way to get past this issue...unfortunately, I need that setting to remain true for my actual mongodb pods.

Proposed fix to is to remove the offending securityContext declaration in the cronjob.yaml template file

**Comment by carrodher** [comment]
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

**Pull request closed without merging**
