### PR TITLE
Replacing tkg target platform name

### LINKED ISSUE #8838: Renaming job name
**Renaming target platform** 

Replacing _tkg-1.3.0-aws_ with _tkg_

### PR DESCRIPTION
**Pull request by gdelgadot**
**Renaming tkg target platform**

 Replacing _tkg-1.3.0-aws_ with _tkg_

- fixes #8838

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for creating this PR, @gdelgadot . Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/bitnami-docker-ASSET/blob/master/CONTRIBUTING.md#sign-your-work).

About the failing linter, please ignore it, since those changes are not affecting any Helm chart, the output can be safely ignored.

**Comment by gdelgadot** [comment]
@carrodher yes, you are right, I forgot to sign it. Is it possible to do it now?

**Comment by carrodher** [comment]
No problem, you should be able to use something like
```
git commit --amend --signoff
```
But in this case, since it's not a blocking issue, I manually set the DCO to pass

**Comment by gdelgadot** [comment]
Thanks :)

**Review by mpermar — APPROVED** [review]
Looks good.

**Pull request merged**
