### PR TITLE
[bitnami/redis-cluster] Allow set Helm/ArgoCD hook for updateJob

### PR DESCRIPTION
**Pull request by ritmas**
### Description of the change

Ability to setup other Helm hook rather than hard coded one.

### Benefits

On ArgoCD side, a hard coded `"helm.sh/hook": post-upgrade` hook is equivalent to `argocd.argoproj.io/hook: PostSync`, which means, hook will be launched only when ArgoCD application is fully synced.

But it never does as new added node runs in standalone mode and as the default `readinessProbe` is [checking for cluster info](https://github.com/bitnami/charts/blob/main/bitnami/redis-cluster/templates/scripts-configmap.yaml#L52-L77) it will always fail.

Ability to setup other Helm hook would help to launch the script on ArgoCD side.

### Possible drawbacks

N/A

### Applicable issues

- fixes https://github.com/bitnami/charts/issues/18924

### Additional information

N/A

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by rafariossaa — APPROVED** [review]
LGTM

**Comment by nan-coupa** [comment]
@ritmas what do you set the configuration to for ArgoCD? Looks like Argo only maps to pre-sync/post-sync, so unclear how you resolved it.
https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-hooks

**Comment by alcidesmig** [comment]
> @ritmas what do you set the configuration to for ArgoCD deployments? Looks like Argo only maps to pre-sync/post-sync, so unclear how you resolved it. https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-hooks

I couldn't solve it either. When mapping it to pre-sync, it doesn't solve the problem because it runs before the pods change; in post-sync, it never gets executed because the sync action never ends - because it isn't healthy.

**Comment by ritmas** [comment]
@nan-coupa @alcidesmig This PR didn't fixed the issue with ArgoCD. As you've said, ArgoCD has less hooks than Helm and those cannot cope with [bitnami/redis-cluster](https://github.com/bitnami/charts/tree/main/bitnami/redis-cluster) management fluently.

In my experience, cluster looses data, is not accessible for a long time or just corrupts itself. Anyhow, it's not production ready, so I had to ditch it eventually and use manual way.

**Pull request merged**
