### PR TITLE
[bitnami/kafka] Persistence configuration

### PR DESCRIPTION
**Pull request by ArtemTrofimushkin**
### Description of the change

Refactor persistence configuration to accept both persistence and non persistence volumes

### Benefits

Ability to use other types of Kubernetes ephemeral volumes

### Possible drawbacks

Backward incompatible changes 

### Applicable issues

  - fixes #https://github.com/bitnami/charts/issues/10773

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Unfortunately, VMware cannot accept your contribution at this time.

**Comment by ArtemTrofimushkin** [comment]
@carrodher why?

**Comment by kashapovd** [comment]
> @carrodher why?

I think because you are from Russia, like me, you cannot be a full member of Open Source at this time.

**Comment by vitalyu** [comment]
Oh, Maybe @carrodher needs to read opensource.org terms before consider yourself a judge, it is difficult to call it professionalism.

**Pull request closed without merging**
