### PR TITLE
[bitnami/solr] Support for customizing standard labels

### PR DESCRIPTION
**Pull request by juan131**
### Description of the change

This PR follows up #18154 ensuring this chart is adapted to use new helpers' format, hence adding support for customizing standard labels.

### Benefits

User can customize standard labels.

### Possible drawbacks

None

### Applicable issues

N/A

### Additional information

#18154 must be merged **before** this PR

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by CeliaGMqrz — APPROVED** [review]

**Comment by muffl0n** [comment]
This breaks the ServiceMonitor, cause the label `app.kubernetes.io/component: metrics` is missing in `bitnami/solr/templates/metrics-svc.yaml`. 
See: https://github.com/bitnami/charts/pull/18747/files#diff-92a32bb9c7a3c2b3e0220fbad038109d70de501fddce2c173c3fc6c933beba1eL13

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by muffl0n** [comment]
Will check when I find the time. Meanwhile, this is our workaround:
```
metrics:
  service:
    labels:
      app.kubernetes.io/component: metrics
```

**Comment by juan131** [comment]
Thanks for reporting it @muffl0n ! I just created [this PR](https://github.com/bitnami/charts/pull/19122) to address this issue.

**Pull request merged**
