### PR TITLE
[bitnami/owncloud] NEW MAJOR: migrate to non-root + good practices

### PR DESCRIPTION
**Pull request by marcosbc**
**Description of the change**

We are working on releasing the ownCloud Docker image with a non-root approach. As part of that, we need to update the chart to use the new port numbers used by the container image. As part of this change we'll also include support for new features added in the container image version.

**Benefits**

Support for environments such as OpenShift, where a non-root UID is required to run a container.

Also, follow new Bitnami charts good practices: lots of new customization features (container command, support for security contexts...), support for installing with existing DB, SMTP support, and more.

**Possible drawbacks**

May break specific upgrades.

**Applicable issues**

None

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by marcosbc** [comment]
This PR is similar to #4695 but includes more stuff, so once this is merged I'll close the other one.

**Review by javsalgar — APPROVED** [review]

**Comment by javsalgar** [comment]
Please check the test issue

**Comment by javsalgar** [comment]
It's still failing

**Comment by marcosbc** [comment]
@javsalgar It's expected to fail. We still haven't released the new non-root Docker image.

**Comment by marcosbc** [comment]
I just saw that the image is failing because of a typo in `values.yaml`, and have updated it accordingly. In any case, the CI will set the proper image tag when testing/merging.

**Comment by marcosbc** [comment]
Now it is failing because of not using an updated image:
```
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
```

Once the new image gets published, it should work. Our internal CI will take care of that.

**Pull request merged**
