### PR TITLE
[bitnami/redis-cluster] Small typo fix on redis-cluster templates

### PR DESCRIPTION
**Pull request by ssyno**
### Description of the change

- Changes "contanierPorts" to "containerPorts" on `redis-cluster` templates.

### Benefits

- `serviceMonitors` resources fixed

### Applicable issues

- fixes typo on `redis-cluster` helm chart templates

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! Could you fix the DCO issue?

**Comment by javsalgar** [comment]
Could you also bump the chart version?

**Comment by ssyno** [comment]
Sure fixing both

**Review by aoterolorenzo — APPROVED** [review]
Thanks for the contribution and the eagle eye @ssyno !

**Pull request merged**
