### PR TITLE
[bitnami/clickhouse] Fix clickhouse external access annotation assignment 

### PR DESCRIPTION
**Pull request by emmanuelm41**
### Description of the change

Current logic is not assigning correctly pod annotations for external access to each shard-replica. In order to assign a DNS address to each loadbalancer for external access, if we have a cluster with 3 shards and 2 replicas per shard, we need to assign 6 annotations. Currently this process is not possible as they are not being assigned in the correct order. 

### Benefits

Now you can assign annotations in the correct order

### Applicable issues

- fixes #

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by migruiz4** [comment]
Hi @emmanuelm41,

I'm sorry for the late response, could you please resolve the conflicts before we can proceed?

**Review by migruiz4 — CHANGES_REQUESTED** [review]
One request, could you please update the value description to reflect this new feature?

https://github.com/bitnami/charts/blob/b93517abf00b0f0a2ad7b9fc5c028f7711aa9963/bitnami/clickhouse/values.yaml#L737-L743

**Comment by emmanuelm41** [comment]
@migruiz4 I completely forget about this. I just updated the description

**Comment by migruiz4** [comment]
Hi @emmanuelm41, could you please resolve the conflicts?

**Comment by emmanuelm41** [comment]
> Hi @emmanuelm41, could you please resolve the conflicts?

Done!

**Comment by emmanuelm41** [comment]
> I'm sorry @emmanuelm41, I was OOO last week and could not check the PR in time, could you please check the conflicts again?

Done!

**Comment by emmanuelm41** [comment]
@migruiz4 any news on this?

**Review by migruiz4 — APPROVED** [review]

**Pull request merged**
