### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by aude**
Just fixing a small typo.

### CODE REVIEW

**Comment by recena** [comment]
@aude Could you follow the PR template and read this [CONTRIBUTING](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) file?

**Comment by aude** [comment]
@recena Sorry, that's more work than I'm willing to spend to fix one word in the documentation.

Feel free to borrow the change if you or anyone else wants to!

**Comment by recena** [comment]
@aude Thank you.

**Comment by recena** [comment]
@aude FYI https://github.com/bitnami/charts/pull/10922

**Pull request closed without merging**
