### PR TITLE
[bitnami/multiple charts] Fix typo: "NetworkPolice" vs "NetworkPolicy"

### LINKED ISSUE #25347: Typo: "NetworkPolice" vs "NetworkPolicy" (across many charts)
### Name and Version

multiple charts, multiple versions (docs only)

### What architecture are you using?

None

### What steps will reproduce the bug?

This is a documentation-only bug.

I noticed that while browsing through that many items say `Add extra ingress rules to the NetworkPolice`, but right next to it shows `Add extra egress rules to the NetworkPolicy` and the text is often on a property that includes `networkPolicy`. 

I figure I'll do a small PR to cleanup the docs, since I happened to come across it while reading.

https://github.com/search?q=repo%3Abitnami%2Fcharts%20NetworkPolice&type=code

### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

_No response_

### What do you see instead?

`NetworkPolice` when the text means `NetworkPolicy`

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SeanKilleen**
### Description of the change

Docs-only changes to address one specific typo found on many charts: `NetworkPolice` which should be `NetworkPolicy`.

Updates the documentation and the code doc comments. The variable itself is already correct and does not need changing.

### Benefits

* Correct reference to variable
* General correctness of docs
* Not a high impact PR; just happened to notice it.

### Applicable issues

- fixes #25347

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] ~~Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)~~ N/A
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by SeanKilleen** [comment]
There are obviously a lot of charts involved here. Since the README files are not the only things affected -- even though the only things affected in the values.yaml file are comments -- is it still necessary to bump the chart versions?

If so I'll be happy to do so in this PR, but it seems like it might be unnecessary.

**Comment by SeanKilleen** [comment]
Well, the failing CI would seem to indicate that indeed I need to bump the chart values. And so I will!

**Comment by SeanKilleen** [comment]
OK, this is ready for review I believe. 👍

* Values replaced
* Version bumps in all charts that required a replacement
* Self-review to ensure no charts changed without bumps
* Self-review to ensure no charts bumped without changes
* Self-review to ensure bumped versions increment by one patch level.

**Comment by SeanKilleen** [comment]
@juan131 no problem, happy to do it! 

I'll revert the version bumps in about an hour. 👍

**Comment by SeanKilleen** [comment]
@juan131 just got the chance to do a quick rebase and drop those commits. Should be good to go now I think. 👍

**Review by juan131 — APPROVED** [review]
LGTM

**Pull request merged**
