### PR TITLE
[bitnami/prometheus-operator] Support the ThanosSpec of prometheus-operator

### PR DESCRIPTION
**Pull request by Cellebyte**
**Description of the change**

Mimic the behaviour of objectStorageConfig of the ThanosSpec with the support of extraArgs to not drop functionality.

**Benefits**

It now is compliant with the prometheus-operator ThanosSpec.
Regarding [https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#thanosspec](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#thanosspec).

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

Thank you for the PR. Note that, as you are removing a value, then this should be a major version bump of the chart. In addition to this, is there a reason why we cannot support the two options: the extraArgs and the configMap?

**Comment by Cellebyte** [comment]
@javsalgar their is no option in ThanosSpec for extraArgs.
If we want to provide both I think we need to go with the old implementation.
Their you had access to the command line arguments of the thanos container.

**Comment by Cellebyte** [comment]
@javsalgar please don't merge until I added support for the old behaviour. Than it will be a minor improvement.

**Comment by javsalgar** [comment]
Hi,

Sure, it can wait :)

**Comment by javsalgar** [comment]
Please fix the merge issues as well

**Comment by Cellebyte** [comment]
@javsalgar fixed the merge issues and added the option of objectStorageConfig to the template. Don't removed the extraArgs support

**Comment by javsalgar** [comment]
Thank you very much for the contribution!

**Pull request merged**
