### PR TITLE
[bitnami/redis] Updating redis version from 6.0 to 6.2, bumping major version of the chart

### PR DESCRIPTION
**Pull request by bedokuroff**
**Description of the change**

- Updating Redis version from 6.0 to 6.2 using bitnami's docker image;
- Bumping major version of the chart (as the such a big update of underlying image needs a major version bump);
- Adding update to 'Upgrading' section of readme;

**Benefits**

- Keep chart up-to-date with the most version of Redis

**Possible drawbacks**

**Applicable issues**

**Additional information**

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

### CODE REVIEW

**Comment by marcosbc** [comment]
Hi @bedokuroff, thanks for the PR! I've opened an internal task to discuss this, as we would also need to make some internal changes for the automations to work properly.

**Comment by FraPazGal** [comment]
Hello @bedokuroff, we put this update on-hold for #4916 to be finished and avoid conflicts in our internal tests. We are once again working on this and I will update this PR as soon as the change has been approved by our internal testing tools. Thanks again for the PR and for your understanding!

**Review by FraPazGal — APPROVED** [review]
LGTM

**Comment by juan131** [comment]
@FraPazGal we should have taken advantage of this major version to adapt the labels to use the [K8s recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels). Redis is the unique chart currently in our catalog using the old default labels 😞

**Pull request merged**
