### PR TITLE
[bitnami/harbor] Service Account implemitation

### PR DESCRIPTION
**Pull request by iamaverrick**
Added Service Accounts (SA) to each service in harbor. bumped up helm chart version number.

Signed-off-by: Blueamber <contactus@blueamber.io>

### Description of the change

added service accounts to each service on harbor

### Benefits

allows for RBAC, and third party services to work with this service

### Applicable issues

  - fixes #

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by iamaverrick** [comment]
@carrodher 

I'm trying to understand why the chart fails. I did provide work under an organization. What permission is needed for this to work correctly?

```
[harbor-sa 6d91057] Update README.md with readme-generator-for-helm
 1 file changed, 545 insertions(+), 521 deletions(-)
remote: Permission to blueamberio/charts.git denied to bitnami-bot.
fatal: unable to access 'https://github.com/blueamberio/charts/': The requested URL returned error: 403
Error: Process completed with exit code [12](https://github.com/bitnami/charts/actions/runs/3769882312/jobs/6409375537#step:5:13)8.
```

**Comment by carrodher** [comment]
Thanks for creating this PR! It seems what's needed is the @bitnami-bot to write into this PR (in fact in the https://github.com/blueamberio/charts fork).

Apart from that, please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

**Comment by iamaverrick** [comment]
> 

I requested write access from bitnami-bot as you mentioned.

**Comment by corico44** [comment]
@iamaverrick It seems there are problems with the PR branch. It doesn't have the necessary changes from the main branch. Could you fix the conflicts by performing a merge, please?

**Pull request closed without merging**
