### PR TITLE
[bitnami/spring-cloud-dataflow] Scdf proxy configuration

### LINKED ISSUE #5235: [bitnami/spring-cloud-dataflow] Proxy configuration
**Which chart**:
spring-cloud-dataflow

**Is your feature request related to a problem? Please describe.**
Dealing with company proxy is quite painfull to make SCDF communicate with Maven and Docker Hub for starter apps, for instance

**Describe the solution you'd like**
Having parameters in the chart, like the JVM params (proxyHost, proxyPort, proxyUser, proxyPwd, nonProxyHosts) to automatically configure the proxy for SCDF

**Describe alternatives you've considered**
Today we have to edit the SCDF deployment yaml after the installation and modify several parameters to add proxy configuration for Maven metadata jar and Docker Labels.

### PR DESCRIPTION
**Pull request by CEDDM**
**Description of the change**
Adding proxy properties in SCDF server deployment yaml enabling maven metadata retrieval

**Benefits**
Simplifying the proxy configuration with one shot installation

**Possible drawbacks**

**Applicable issues**
  - fixes #5235

**Additional information**
This PR only deals with the Maven proxy configuration. For the new v3 starter apps, metadatas use Docker labels and there is an issue for that : https://github.com/spring-cloud/spring-cloud-dataflow/issues/4295

**Checklist**
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

### CODE REVIEW

**Review by rafariossaa — APPROVED** [review]
Hi,
 Thank you very much for adding this feature.
  LGMT

**Comment by rafariossaa** [comment]
Hi,
  Could you bump the chart version ?

**Comment by CEDDM** [comment]
Hi I already bumped the version to 2.7.2. Isn't it right ? 
Maybe 2.8.0 is better because it's a new feature ?

**Review by rafariossaa — APPROVED** [review]
Thanks you very much.
LGTM,

**Pull request merged**
