### PR TITLE
bitnami/mongodb labeler sidecar and labeler service fix

### PR DESCRIPTION
**Pull request by korenlev**
no need to match by 'instance' name, as this is dynamically changing per namespace

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Comment by korenlev** [comment]
pass pr checks

**Review by miguelaeh — CHANGES_REQUESTED** [review]
Hi @korenlev ,
The changed code is an example, I don't see why it is incorrect

**Comment by korenlev** [comment]
Hi miguel,

If namespace change, the other mongo templates are creating pod names with
mongo-[ns] and service names mongo-[ns] so matching by it is hard, better
to not trust it and only match by simpler attributes

בתאריך יום ב׳, 4 באוק׳ 2021, 11:06, מאת Miguel Ángel Cabrera Miñagorri ‏<
***@***.***>:

**Comment by miguelaeh** [comment]
Hi @korenlev ,
I understand your concern, but the ideal is to set all the labels in order to match only the resources of the release. The comments are an example that users need to edit, they are not though to be used just by uncommenting them. Approving this PR could cause labels confusions since there could be a mismatch of the resources

**Comment by korenlev** [comment]
ok

‫בתאריך יום ג׳, 5 באוק׳ 2021 ב-11:48 מאת ‪Miguel Ángel Cabrera Miñagorri‬‏
***@***.***‬‏>:‬

**Pull request closed without merging**
