### PR TITLE
Improves Apache/MySQL README files

### PR DESCRIPTION
**Pull request by vikram-bitnami**
**Description of the change**

Transfers some content of the READMEs to the Bitnami docs site

**Benefits**

- Reduce the overall length of the README and simplify its structure
- Make it easier for intermediate/advanced users to find key information (chart parameters)

**Possible drawbacks**

**Applicable issues**

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by juan131** [comment]
Blocking this PR for the same concerns I had at https://github.com/bitnami/charts/pull/4155

**Comment by juan131** [comment]
@vikram-bitnami is this already ready to be reviewed?
cc @javsalgar

**Comment by vikram-bitnami** [comment]
> @vikram-bitnami is this already ready to be reviewed?
> cc @javsalgar

Yes

**Review by juan131 — COMMENTED** [review]
The changes LGTM! I guess the referenced sections are already present in the `docs/` folder, right?

**Comment by juan131** [comment]
@javsalgar please also review this

**Comment by vikram-bitnami** [comment]
> The changes LGTM! I guess the referenced sections are already present in the `docs/` folder, right?

Yes

**Comment by juan131** [comment]
> Yes and also on the docs.bitnami.com website

great!! @javsalgar please remember to check this

**Review by juan131 — APPROVED** [review]

**Review by javsalgar — APPROVED** [review]

**Pull request merged**
