### PR TITLE
[bitnami/gitea] Add new customizable environment variables - ENABLE OPENID SIGNIN/SIGNUP

### PR DESCRIPTION
**Pull request by ikamii**
[bitnami/gitea] Add new customizable environment variables

```ini
1. ENABLE_OPENID_SIGNIN (default: false)
2. ENABLE_OPENID_SIGNUP (default: false)
```

### Description of the change

All changes have made after approval of the PR.
- https://github.com/bitnami/containers/pull/66480

Changes have made in:
- `values.yaml` (added 2 new parameters `openid.enableSignIn`, `openid.enableSignUp`)
- templates/deployment.yaml (To set the custom environment variables.)
- README.md
- Chart.yaml (Chart version)

### Possible drawbacks

Users can enable `OpenID sign in` and `OpenID sign up` if necessary. ( I might use it for signing in via Keycloak for example.)
### Applicable issues

- https://github.com/bitnami/charts/issues/25572

### Checklist

- [ x ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ x ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [ x ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ x ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by ikamii** [comment]
I am unfortunately not sure if I did the Chart versioning correctly. If not please tell me to change it thanks!

**Comment by alemorcuq** [comment]
Thanks! Since you did some changes to the container, we need to wait for a new container to be released and then change the image in the chart to the new one.

**Comment by ikamii** [comment]
> Thanks! Since you did some changes to the container, we need to wait for a new container to be released and then change the image in the chart to the new one.

Sure! Do you maybe know how long does it take for a new container to be released?

Should I change the image in the chart then or would someone in the team do it?

Thanks!

**Comment by ikamii** [comment]
Hi @alemorcuq 

I have seen that the gitea image has been updated on Docker Hub so I have updated the values.yaml as expected.

Thanks again!

**Review by alemorcuq — APPROVED** [review]

**Pull request merged**
