### PR TITLE
Change default Jenkins home

### LINKED ISSUE #2361: [bitnami/jenkins] Jenkins home must be /bitnami/jenkins/jenkins_home
**Which chart**:
jenkins (latest/5.0.6)

**Describe the bug**
Overriding the `jenkinsHome` value to some path other than "/bitnami/jenkins/jenkins_home" causes persistence not to work.

When a pod is killed, all configuration and jobs/job history is lost.

**To Reproduce**
1. Install Jenkins Helm chart, with `--set persistence.enabled=true --set jenkins_home="/var/jenkins_home"`
2. Wait for Jenkins to come up, add a new job
3. Manually kill running pod(s) with `kubectl delete pod <podname>`
4. Go to Jenkins UI, see missing state

**Expected behavior**
When pods killed, Jenkins state is maintained.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**Additional context**
My guess is this is a requirement based on the Docker image. If it is truly not configurable, maybe the most straightforward thing to do is to remove it as a chart value.

### PR DESCRIPTION
**Pull request by jdolitsky**
Change default Jenkins home to /bitnami/jenkins/jenkins_home
in order for persistence to work out-of-the-box.

Fixes #2361.

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi, 

Thank you very much for the PR! It looks good to me. I will trigger the automated testing so the tags are updated.

**Comment by javsalgar** [comment]
It seems there was an issue with the automated test system.

In order to update the image tags to point to latest releases, our CI/CD needs to modify you PR (`bitnami-bot` will update `values.yaml` and `values-production.yaml` for you). To do so, it's necessary you allow "edits from maintainers". Find more information in the link below: 
- https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by javsalgar** [comment]
Also, could you fix the chart merge issues?

**Comment by jdolitsky** [comment]
@javsalgar fixed merge issues, but sorry Im not seeing that option for "edits from maintainers"

**Comment by javsalgar** [comment]
Hi,

This is strange, other users did not experience that user allowing edits from maintainers. Could you allow the user `bitnami-bot`to write on your repository?

**Comment by jdolitsky** [comment]
@javsalgar I've just granted access, but I think somebody will need to login and accept the invitation? https://github.com/bloodorangeio/charts/invitations

**Comment by javsalgar** [comment]
Hi, 

Just a note to let you know that I enabled the automatic tests that should update the images.

**Comment by marcosbc** [comment]
@jdolitsky Could you rebase with the latest changes from master? There is a conflict.

Once done, we'll try to accept the invitation sent to bitnami-bot, and proceed to testing in our CI.

**Comment by jdolitsky** [comment]
@marcosbc done! thanks

**Comment by marcosbc** [comment]
Thanks! I'm starting the CI process.

**Comment by marcosbc** [comment]
@jdolitsky Before merging, could you describe if this change fixes any use case?

Note that the current JENKINS_HOME value is persisted properly as long as the default entrypoint/cmd is not overridden.

In fact, I could reproduce this with the current Helm chart by installing, creating a file inside `/opt/bitnami/jenkins/jenkins_home`, deleting the pod (I also deleted the deployment), then running `helm upgrade`. When the container got re-deployed, the file I created was still included.

**Comment by marcosbc** [comment]
Just to clarify, I deployed a Bitnami Jenkins Helm chart with `--set jenkinsHome=/opt/bitnami/jenkins/myjenkinshome`, created a file inside after completed and recreated the pod, and the file was still there. So AFAIK the persistence is working fine.

**Comment by jdolitsky** [comment]
@marcosbc I didn't have such luck - the only thing I can think of that might make a difference here is running w/ escalated privilege:
```
podSecurityContext:
  fsGroup: 0

containerSecurityContext:
  runAsUser: 0
```

Maybe this causes some symlinking to fail? If unable to reproduce I'm happy to close, may have been something else at the time..

**Comment by marcosbc** [comment]
Let me check that and get back to you.

**Comment by marcosbc** [comment]
Hi, it keeps working for me. However, in #2361 you mentioned enabling these options:

```
--set persistence.enabled=true --set jenkins_home="/var/jenkins_home"
```

Note that the proper option for setting JENKINS_HOME is not `jenkins_home`, but `jenkinsHome`.

And when I set that option with the proper name I get this error:
```
nami    INFO  Initializing jenkins
Error executing 'postInstallation': EACCES: permission denied, mkdir '/var/jenkins_home'
```

Which is correct, since "/var/jenkins_home" is not created. To fix this, we could always add support for "extraVolumes" like we have in containers such as Elasticsearch, and do something like this:

```
diff --git a/bitnami/jenkins/templates/deployment.yaml b/bitnami/jenkins/templates/deployment.yaml
index e1c115925..d1ffaebf1 100644
--- a/bitnami/jenkins/templates/deployment.yaml
+++ b/bitnami/jenkins/templates/deployment.yaml
@@ -42,8 +42,8 @@ spec:
           args:
             - -ec
             - |
-              mkdir -p /bitnami/jenkins
-              chown -R "{{ .Values.containerSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }}" "/bitnami/jenkins"
+              mkdir -p "/bitnami/jenkins" "{{ .Values.jenkinsHome }}"
+              chown -R "{{ .Values.containerSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }}" "/bitnami/jenkins" "{{ .Values.jenkinsHome }}"
           securityContext:
             runAsUser: 0
           {{- if .Values.volumePermissions.resources }}
@@ -109,6 +109,9 @@ spec:
           volumeMounts:
             - name: jenkins-data
               mountPath: /bitnami/jenkins
+            {{- if .Values.extraVolumeMounts }}
+            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
+            {{- end }}
           {{- if .Values.metrics.enabled }}
         - name: metrics
           image: {{ template "jenkins.metrics.image" . }}
```

However, that is only to support the case in which the JENKINS_HOME is outside from /bitnami, and we don't know of any use case why this would be needed. But if you think this is worth to add for any of your use cases, feel free to contribute, I would be glad to check it!

**Pull request closed without merging**
