### PR TITLE
[bitnami/elasticsearch] Fix custom config file is not applied

### PR DESCRIPTION
**Pull request by zerda**
Per [libelasticsearch.sh](https://github.com/bitnami/bitnami-docker-elasticsearch/blob/6.4.0-debian-9-r28/6/debian-9/rootfs/libelasticsearch.sh), the configuration directory is specified as `/opt/bitnami/elasticsearch/config` in docker.

The custom config file should be there too.

### CODE REVIEW

**Comment by XBeg9** [comment]
Agree, helm is broken and zen discovery doesn't work without this changes.

**Comment by XBeg9** [comment]
@tompizmor latest version of ElasticSearch is 6.4.1, you did merge `appVersion: 6.4.2`. Not sure if this can break anything, but it looks like it's wrong.

**Comment by tompizmor** [comment]
You're right! I bumped the wrong version in the chart. Fixed here: https://github.com/bitnami/charts/commit/d8a44261f60fffbebf98b732a30ad74c7e2be409

**Comment by XBeg9** [comment]
> You're right! I bumped the wrong version in the chart. Fixed here: [d8a4426](https://github.com/bitnami/charts/commit/d8a44261f60fffbebf98b732a30ad74c7e2be409)

No problem, thanks for fix!

**Pull request merged**
