### PR TITLE
[bitnami/thanos] Fix thanos objstoreConfig and storegatewayConfigMap

### LINKED ISSUE #24536: thanos helm chart does not render with existingObjstoreSecret
### Name and Version

bitnami/thanos 14.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Use the newest thanos helm chart version 14.0.1
2. Configure existingObjstoreSecret

### Are you using any custom parameters or values?
```
existingObjstoreSecret: "custom-s3-config"
```

### What do you see instead?

```
Error: template: thanos/charts/thanos/templates/storegateway/statefulset-sharded.yaml:53:44: executing "thanos/charts/thanos/templates/storegateway/statefulset-sharded.yaml" at <include "thanos.objstoreConfig" .>: error calling include: template: thanos/charts/thanos-query-ssl/templates/_helpers.tpl:127:61: executing "thanos.objstoreConfig" at <.Values.objstoreConfig>: can't evaluate field Values in type int
```

### Additional information

it seems like the following PR https://github.com/bitnami/charts/pull/24014 has introduced this problem.

### PR DESCRIPTION
**Pull request by dragoangel**
### Description of the change

Do not render `checksum/objstore-configuration` annotation if `existingObjstoreSecret` is set, plus move `indexCacheConfig` and `bucketCacheConfig` checksum generation from `objstore-configuration` to `storegateway-configuration` as they only used by storage gateway, and other components of thanos should not be redeployed when they are changed.

### Benefits

Get working deployment when existingObjstoreSecret is set

### Possible drawbacks

None

### Applicable issues

- fixes #24536

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by jotamartos — APPROVED** [review]
Changes LGTM, thank you for you contribution.

**Comment by jkroepke** [comment]
Seems like introduced a breaking-change.

It moved the index-cache.yaml to an different configmap, however the path to that config has been not changed, too:

https://github.com/bitnami/charts/blob/9a0fece43caabdd9fe4de507cf2197945b04ac6d/bitnami/thanos/templates/storegateway/statefulset.yaml#L134

If configured, thanos may not come up, becaue it misses the index.yaml

**Comment by dragoangel** [comment]
> Seems like introduced a breaking-change.
> 
> It moved the index-cache.yaml to an different configmap, however the path to that config has been not changed, too:
> 
> https://github.com/bitnami/charts/blob/9a0fece43caabdd9fe4de507cf2197945b04ac6d/bitnami/thanos/templates/storegateway/statefulset.yaml#L134
> 
> If configured, thanos may not come up, becaue it misses the index.yaml

Why? As it has same dir as was for other configmap:
https://github.com/bitnami/charts/blob/9a0fece43caabdd9fe4de507cf2197945b04ac6d/bitnami/thanos/templates/storegateway/statefulset.yaml#L129

**Comment by jkroepke** [comment]
> Why? As it has same dir as was for other configmap:

Correct, but this PR moves the index-cache.yaml away from objstore.yml into a different ConfigMap

**Comment by dragoangel** [comment]
> > Why? As it has same dir as was for other configmap:
> 
> Correct, but this PR moves the index-cache.yaml away from objstore.yml into a different ConfigMap

Which not mounted... Okay looks I missed this part :((

**Comment by jkroepke** [comment]
An other user hits this error as well https://github.com/bitnami/charts/issues/24678

**Comment by dragoangel** [comment]
My intention was that caches used here should be available only for storegateway and not added where they should not exist, but looks I missed configure mounts and change arguments.

**Comment by jkroepke** [comment]
> My intention was that caches used here should be available only for storegateway

We have already `Values.storegateway.config` which extactly does this. It seems like `indexCacheConfig` is an history implementation

https://github.com/bitnami/charts/blob/9a0fece43caabdd9fe4de507cf2197945b04ac6d/bitnami/thanos/templates/storegateway/statefulset.yaml#L140

In case of `indexCacheConfig`, `storegateway.config` is an drop-in replacement. Only `bucketCacheConfig` is broken for now.

**Comment by jkroepke** [comment]
@dragoangel 

Another issue is that the values inside the configmap are base64 encoded now.

https://github.com/bitnami/charts/blob/4d9c1ab019c483d78f695d5ea1a03792738f4526/bitnami/thanos/templates/_helpers.tpl#L135-L146

@jotamartos FYI: `bucketCacheConfig` and `indexCacheConfig` are broken now.

**Pull request merged**
