### PR TITLE
[bitnami/Keycloak] Improve documentation for tls ingress

### PR DESCRIPTION
**Pull request by fungiboletus**
Setting proxyAddressForwarding to true should work, according to #7734.
It should be configured if one wants to access keycloak's admin console.

**Description of the change**

Documentation.

**Benefits**

It may save time to the readers.

**Possible drawbacks**

It may be wrong and not work.

**Applicable issues**

#7734

**Checklist**

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by javsalgar — COMMENTED** [review]
LGTM. Could you bump the patch version so a new README is packaged inside the chart?

**Comment by fungiboletus** [comment]
> LGTM. Could you bump the patch version so a new README is packaged inside the chart?

I increased a version number, was it the right one ?

**Comment by javsalgar** [comment]
That's correct! Please fix the DCO check

**Comment by fungiboletus** [comment]
Can't you override it ? It complains that my Git email is not the one in the commit message. Can I just make a new commit or should I start from scratch ?

By the way, since this DCO bot is actually capable of reading the email adresses from the git log, why does it need to have the emails again in the git message ?

**Comment by javsalgar** [comment]
Ok, I'll pass the check but could you merge from master so the new Github action is executed?

**Comment by fungiboletus** [comment]
I just merged the upstream master, but I'm not sure why the early feedback check failed.

**Comment by javsalgar** [comment]
Here it says that it is still behind master 
image

**Comment by javsalgar** [comment]
Sorry for the inconvenience, we're working on improving the action.

**Comment by fungiboletus** [comment]
I just merged :)

**Comment by javsalgar** [comment]
Hi,

It seems that it is still not merged to the point where the early feedback action works as expected. Could you merge again? Sorry for the inconvenience. 
image

**Comment by fungiboletus** [comment]
Hi, I merged but this is still crashing. I can merge as many times as you need, it's only 2 clics using github.

**Comment by javsalgar** [comment]
Hi, it doesn't seem that the merge is actually merge the changes from the upstream bitnami/charts repository.

image


As you can see here, it says it's 63 commits behind bitnami/charts

**Comment by fungiboletus** [comment]
I merged again.

**Comment by fungiboletus** [comment]
@javsalgar This time it should be good 🙂

**Review by javsalgar — APPROVED** [review]

**Comment by javsalgar** [comment]
Thanks!

**Pull request merged**
