### PR TITLE
[bitnami/prometheus-operator] adds service monitors for kube-apiserver and kubelet services

### PR DESCRIPTION
**Pull request by sameersbn**
**Description of the change**

adds service monitors for kube-apiserver and kubelet services

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by sameersbn** [comment]
> What do you think about adding some documentation in the README about this new feature?

I am not sure what we can add. We have just adding servicemonitors manifests to scrape the kubelet and apiserver endpoints which users could have created themselves

**Comment by sameersbn** [comment]
@carrodher please note I've added another commit that re-indents all the manifests as per bitnami's standard formatting practices

**Comment by carrodher** [comment]
> > What do you think about adding some documentation in the README about this new feature?
> 
> I am not sure what we can add. We have just adding servicemonitors manifests to scrape the kubelet and apiserver endpoints which users could have created themselves

I was thinking about something if the user need to change anything, I mean, installing the new chart version the metrics from cadvisor will appear in Prometheus without any extra configuration?

Just this case, if users need to change something to make it work

**Comment by sameersbn** [comment]
> Just this case, if users need to change something to make it work
enabled by default!

**Comment by carrodher** [comment]
Then LGTM!

**Pull request merged**
