### PR TITLE
[bitnami/external-dns] Fix reference to TransIP API secret

### PR DESCRIPTION
**Pull request by WebSpider**
**Description of the change**

Fixes an incorrect reference to the TransIP API secret

**Benefits**

Produce a rendering chart when chosing `provider=transip`

**Possible drawbacks**

Not tested for all other providers

**Applicable issues**

None found

**Additional information**

N/A

**Checklist**
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X ] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Review by miguelaeh — CHANGES_REQUESTED** [review]
Hi @WebSpider ,
From https://kubernetes.io/docs/concepts/storage/volumes/:
> For secrets, the secretName field has been changed to name to be consistent with ConfigMap naming.

So I am afraid we can't accept this PR

**Comment by WebSpider** [comment]
The current version of this chart produces a rendering error when trying to use TransIP as provider
Also, this usage is aligned with https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets and with the way other providers use secrets in this chart. This includes alibaba, aws, azure, coredns and google.

**Comment by miguelaeh** [comment]
Hi @WebSpider ,
I have been trying to debug it. It seems we would need to add some logic to set `name` or `secretName` depending on the Kubernetes version. We will implement something similar to what we do with the Ingress.
Thank you for reporting it

**Review by miguelaeh — APPROVED** [review]
Hi @WebSpider,

I rechecked this and the link I shared is for projected volumes, not volumes so I think this PR is correct then.
Sorry for the confusion.
PLease solve the conflicts in the Chart.yaml and we can merge it.
LGTM!

**Comment by carrodher** [comment]
Unfortunately, due to other priorities and the limited bandwidth we have, the work on this PR was not continued and there are no plans to work on it in the mid-term. I'm replacing the `on-hold` label with the `stale` one so the PR will be automatically closed if it is not continued during the following days.

**Comment by WebSpider** [comment]
Thanks for the ping, I will pick this up again

**Pull request closed without merging**
