### PR TITLE
[bitnami/keycloak] switch to default keycloak port 8080, while scraping metrics

### LINKED ISSUE #10936: [bitnami/keycloak] Wrong port on metrics service monitor
### Name and Version

bitnami/keycloak-9.3.2

### What steps will reproduce the bug?

Install chart.
curl http://keycloak_ip:9990/metrics -> no responce
curl http://keycloak_ip:8080/metrics -> metrics are shown

metrics-service exposes 9990 which would be correct port for old keycloak based on widefly, but based on quarkus instance exposes metrics on the same port as the main application.

### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

metrics-service should expose port 8080, not 9990

### What do you see instead?

Nothing is listening on port 9990

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by marknesterovych**
Signed-off-by: Mark Nesterovych <m.nesterovych@kontakt.io>

### Description of the change

Start scraping metrics from main keycloak process port 8080, quarkus based keycloak does not start additional service on 9990

### Benefits

Kubernetes integration with prometheus will be working out of the box

### Applicable issues

  - fixes #10936

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by marcosbc — DISMISSED** [review]
LGTM! Thanks for the contribution!

**Comment by marcosbc** [comment]
@marknesterovych Could you check the conflicts? Unfortunately it is not letting me merge the patch.

**Comment by marknesterovych** [comment]
> @marknesterovych Could you check the conflicts? Unfortunately it is not letting me merge the patch.

Should be OK now

**Comment by alemorcuq** [comment]
Thanks! The [DCO|https://github.com/bitnami/charts/pull/10976/checks?check_run_id=7280014833] is also failing. Can you fix it?

**Comment by marknesterovych** [comment]
> failing. Can you fix it?

I've signed the commit

**Comment by joscabmar** [comment]
I think 9.4.1 is already released, so you will need to step it up to 9.4.2 to avoid conflicts.

**Comment by marknesterovych** [comment]
> I think 9.4.1 is already released, so you will need to step it up to 9.4.2 to avoid conflicts.

Bumped version

**Review by alemorcuq — APPROVED** [review]

**Pull request merged**
