### PR TITLE
[bitnami/kafka] Fix rendering of topologySpreadConstraints

### LINKED ISSUE #9150: [bitnami/kafka] topologySpreadConstraints does not render
### Name and Version

bitnami/kafka 12.0.0

### What steps will reproduce the bug?

Execute

```console
$ helm template kafka ./bitnami-charts/bitnami/kafka -f values-test.yaml > render.yaml
```

values-test.yaml
```yaml
topologySpreadConstraints:
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule
  labelSelector:
    matchLabels:
      app.kubernetes.io/name: kafka
      app.kubernetes.io/component: kafka
      app.kubernetes.io/managed-by: Helm
```

### Are you using any custom parameters or values?

`-f values-test.yaml`

### What is the expected behavior?

topologySpreadConstraints to be rendered

### What do you see instead?

topologySpreadConstraints is not rendered

### Additional information

Fixed in https://github.com/bitnami/charts/pull/9149, but can't sign off using my real name.

### PR DESCRIPTION
**Pull request by JMSwag**
**Description of the change**

The changes fixes the rendering of topologySpreadConstraints.

**Benefits**

Allows usage of topologySpreadConstraints

**Possible drawbacks**

None

**Applicable issues**

- Fixes #9150 

**Additional information**

None

**Checklist**

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Please note you need to bump the chart version in the _Chart.yaml_ file

**Comment by JMSwag** [comment]
@carrodher TY!

**Review by alemorcuq — APPROVED** [review]

**Review by alemorcuq — CHANGES_REQUESTED** [review]
It looks like we already released version 15.3.2. Could you rebase and increase the version again? Thanks!

**Comment by alemorcuq** [comment]
I've just relaunched the CI jobs.

**Review by alemorcuq — APPROVED** [review]

**Pull request merged**
