### PR TITLE
[bitnami/mongodb-sharded] Evaluate *.persistence.subPath as a template

### PR DESCRIPTION
**Pull request by cferns08**
### Description of the change

Evaluate *.persistence.subPath value as a template.

### Benefits

Ability to use dynamic subPath for volume mounts through template evaluation.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

**Comment by CeliaGMqrz** [comment]
Hi @cferns08 

Thanks for your contribution, but I think this could be a breaking change if the value is already set in the values. Could you please give me a usage example of this change? Also, I think this could be a new minor instead of a patch.

**Comment by cferns08** [comment]
Hi @CeliaGMqrz 

I fixed some things my changes had wrong.

In regards to your comment:

> I think this could be a breaking change if the value is already set in the values

Does _common.tplvalues.render_ not work with literals not containing a template?

> Could you please give me a usage example of this change?

The use case is similar to subPathExpr but I thought this would be more flexible (also the commands run from the init containers make it more difficult). For example:

`shardsvr.persistence.subPath: {{ printf "data-%d" $i }}`

> I think this could be a new minor instead of a patch.

OK, do I increment the minor instead then?

**Comment by CeliaGMqrz** [comment]
Hi @cferns08,

Yes, it's clearer now. Great.

> OK, do I increment the minor instead then?

Yes, please. I think this is a new feature so it should be minor.

Thanks.

**Review by CeliaGMqrz — APPROVED** [review]
LGTM! Thanks for your contribution!

**Pull request merged**
