### PR TITLE
[bitnami/ghost] fix #2515.

### LINKED ISSUE #2515: Ghost 10.0.0 Ingress annotations
**Which chart**:
ghost 10.0.0

**Describe the bug**
I think #2044 introduced a bug. The ingress annotations are being set using ```.Values.service.annotations```. Is that the intended behaviour?

**To Reproduce**
https://github.com/bitnami/charts/blame/master/bitnami/ghost/templates/ingress.yaml#L9

**Expected behavior**
To set ingress annotations using ```ingress.annotations``` not ```service.annotations```

### PR DESCRIPTION
**Pull request by rodolfo-picoreti**
**Description of the change**

Fix ingress bug on the ghost chart.

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes ghost ingress annotations.

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by marcosbc** [comment]
Hi, thanks for contributing! In principle this change looks good to us. However, it looks like edits from maintainers are disabled on the forked repository.

In order to update the image tags to point to latest releases, our CI/CD needs to modify you PR (`bitnami-bot` will update `values.yaml` and `values-production.yaml` for you). To do so, it's necessary you allow "edits from maintainers". Find more information in the link below: 
- https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by rodolfo-picoreti** [comment]
Hey Marcos,

Allow edits by maintainers was/is already enabled:
image

Do I need to do something else? Sorry, I am not sure if I understood what you meant.

**Comment by marcosbc** [comment]
Oh I see, you're right! I was checking the permissions on the master branch instead of `issue#2515`, there it is fine.

**Comment by marcosbc** [comment]
I'm going to launch our CI so it updates the Docker image tags before merging this diff, hopefully it will be merged in a couple of hours.

**Pull request merged**
