### PR TITLE
[bitnami/thanos] Drop the replica label on alerts for Ruler

### PR DESCRIPTION
**Pull request by hwoarang**
In case we have multiple replicas of Ruler, then we get multiple alerts
from each ruler pod. As such, we need to drop the 'replica' label before
we send the alert to the alertmanager in order for alertmanager to
perform deduplication and only send the alert once.

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

### CODE REVIEW

**Comment by hwoarang** [comment]
@rafariossaa Is there a valid reason why you want to get duplicate alerts? If we want to hide this fix behind a flag then maybe there is no reason to add the flag in the first case as uses can use the extraFlags variable anyway.

**Comment by rafariossaa** [comment]
Hi, 
  I am not very sure, I am not a thanos expert, but I guess if this is not the default behavior there should be a reason behind.
  Anyway, I will merge your PR and see if there are more comments on this topic.

**Comment by rafariossaa** [comment]
Could you resolve the conflict ?

**Comment by hwoarang** [comment]
> Could you resolve the conflict ?

@rafariossaa done :) Thanks

The reason this appears to not be enabled by default is that when Ruler replica:1 then there is not need for deduplication and dropping the label has no effect. But for multiple Ruler replicas it appears that you need it if you do not want duplicate alerts.

**Comment by rafariossaa** [comment]
Hi,
 It seems that the chart version is not the right one.
  Could you check this ?

**Comment by hwoarang** [comment]
@rafariossaa I have rebased again

**Pull request merged**
