### PR TITLE
[bitnami/cassandra] Add pod disruption budget

### PR DESCRIPTION
**Pull request by javsalgar**
Signed-off-by: Javier J. Salmeron Garcia <jsalmeron@bitnami.com>

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

**Additional information**

### CODE REVIEW

**Comment by carrodher** [comment]
LGTM, only a comment about the file name, should we use camelcase?
```
bitnami/cassandra/templates/poddisruptionbudget.yaml
```
by
```
bitnami/cassandra/templates/podDisruptionBudget.yaml
```

**Comment by javsalgar** [comment]
We don't use camelcase for yaml files.

**Comment by carrodher** [comment]
In that case, can you also rename `networkPolicy.yaml`?

**Comment by carrodher** [comment]
👍

**Pull request merged**
