### PR TITLE
[bitnami/mastodon] Add required LOCAL_DOMAIN env variable

### PR DESCRIPTION
**Pull request by joshleecreates**
Signed-off-by: Josh Lee <joshleecreates@users.noreply.github.com>

### Description of the change

The mastodon application requires that this environment variable be set at startup. With this variable set, `WEB_DOMAIN` is optional but I left both for thoroughness. Ideally this should probably be two separate values options to support Mastodon's built-in option to have the WEB UI hosted at a different URL than the backend API.

### Benefits

This fixes the mastodon chart so that the application actually works after log in.

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for this contribution, feel free to move it from _Draft_ to _Ready for review_ once you consider it is ready for taking a look so the team can provide feedback

**Review by migruiz4 — CHANGES_REQUESTED** [review]
Hi @joshleecreates,

I'm sorry for the late response.

Could you please provide more details about your issues with the Mastodon chart?

While it is true that the LOCAL_DOMAIN variable is required to federate the mastodon instances, we can not accept this PR as it is, because setting it to a default value could be dangerous.

According to Mastodon documentation, the value LOCAL_DOMAIN can't be changed once it is set for the first time, so users could accidentally deploy Mastodon with the wrong LOCAL_DOMAIN value, or even using the default value.

Instead, the chart should include a new env variables `localDomain` set to an empty string, and the LOCAL_DOMAIN should only be set when a value is provided.

**Comment by joshleecreates** [comment]
> Hi @joshleecreates,
> 
> I'm sorry for the late response.
> 
> Could you please provide more details about your issues with the Mastodon chart?
> 
> While it is true that the LOCAL_DOMAIN variable is required to federate the mastodon instances, we can not accept this PR as it is, because setting it to a default value could be dangerous.
> 
> According to Mastodon documentation, the value LOCAL_DOMAIN can't be changed once it is set for the first time, so users could accidentally deploy Mastodon with the wrong LOCAL_DOMAIN value, or even using the default value.
> 
> Instead, the chart should include a new env variables `localDomain` set to an empty string, and the LOCAL_DOMAIN should only be set when a value is provided.

Your proposed solution sounds good to me in the case where users are not ready to commit to their local domain on first launch. I will update the PR when I have time. Thanks!

**Comment by migruiz4** [comment]
Thanks @joshleecreates!

Our goal is to continue providing a non-federated deployment by default but make it as easy as possible to deploy a federated instance. Your contribution is appreciated.

**Pull request closed without merging**
