### PR TITLE
[bitnami/redmine] External MariaDB secret name is wrong fixes #12384

### LINKED ISSUE #12384: External MariaDB secret name is wrong
### Name and Version

bitnami/redmine 20.3.3

### What steps will reproduce the bug?

Make deploy with external MariaDB/MySQL using:
```
databaseType: mariadb
mariadb:
  enabled: false
postgresql:
  enabled: false
externalDatabase:
  host: "XXX.XXX.XXX.XXX"
  port: 3306
  user: not_a_root
  database: Redmine
  password: "XXXX"
  existingSecret: ""
  existingSecretPasswordKey: ""
```
### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

_No response_

### What do you see instead?

Since bug in helpers it tries to use secret for PostgreSQL to MariaDB.
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  74s                default-scheduler  Successfully assigned redmine/redmine-595849d98c-vq2nf to ubuntu-22-04-server-08
  Normal   Pulled     10s (x7 over 74s)  kubelet            Container image "docker.io/bitnami/redmine:5.0.2-debian-11-r23" already present on machine
  Warning  Failed     10s (x7 over 74s)  kubelet            Error: couldn't find key password in Secret redmine/redmine-externaldb
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by LedAlex**
### Applicable issues

  - fixes #12384

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! Could you fix the issues in the checks?

**Comment by LedAlex** [comment]
Can someone merge this?

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the PR! It seems there is an issue with the branch, as it is affecting multiple files, could you fix it?

**Comment by LedAlex** [comment]
> Hi,
> 
> Thank you so much for the PR! It seems there is an issue with the branch, as it is affecting multiple files, could you fix it?

What do you mean "affecting multiple files"? I've changed only two files, helpers and version in chart, all the rest made by your bot in ci/cd.

**Comment by javsalgar** [comment]
The PR shows a substantial amount of files changed

image


Also, I can see merge issues as well.

**Comment by LedAlex** [comment]
> The PR shows a substantial amount of files changed
> 
> image
> 
> Also, I can see merge issues as well.

If you check that files, you'll see that I'm not the  author of these changes. Either bitnami-bot or someone else. I don't know why they appeared in PR after first CI\CD checks fail and I don't know how to solve it (maybe only new branch and PR).

**Comment by javsalgar** [comment]
The issue is that your fork is not synchronized with upstream

image

This should help you: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Pull request closed without merging**
