### PR TITLE
[bitnami/nginx] Support for Non-Bitnami Nginx Images in nginx Helm Chart

### PR DESCRIPTION
**Pull request by qipan2333**
### Description of the change

This modification allows the Bitnami nginx Helm chart to support non-Bitnami nginx images by conditionally executing an initContainer based on the readOnlyRootFilesystem setting. The initContainer is necessary for handling logs via Bitnami-specific scripts, which non-Bitnami images lack. By adding a conditional check, users can deploy with alternative nginx images without encountering errors related to missing Bitnami-specific scripts.

### Benefits

Allows users to use any nginx image, not just those provided by Bitnami.

### Possible drawbacks

None

### Applicable issues

None

### Additional information

This change does not affect the primary operation of nginx within the Helm chart but instead broadens the potential user base by accommodating more image options. It is particularly useful for users who may be operating in environments where Bitnami images are not ideal or preferred.

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thank you for the PR! Could you fix the DCO issue?

**Comment by qipan2333** [comment]
> Hi!
> 
> Thank you for the PR! Could you fix the DCO issue?

Hi javsalgar!

Thank you for the heads-up! I've fixed the DCO issue and pushed the changes. Please let me know if there's anything else I should address.

**Review by juan131 — APPROVED** [review]
LGTM

**Comment by Cogitri** [comment]
@juan131 /  @qipan2333 Hej, this breaks if `.Values.containerSecurityContext.readOnlyRootFilesystem` is false but the git clone container is enabled, because the former removes the `initContainers` key, which the latter expects.

**Comment by juan131** [comment]
Good catch @Cogitri !

Would you like to create a PR addressing this use case? You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

**Pull request merged**
