### PR TITLE
[bitnami/influxdb] extrahosts creates the same paths as hostname

### PR DESCRIPTION
**Pull request by PauloFerreira25**
Hi, please accept my pull request.

**Description of change**

Fixed extraHosts configuration to have the same behavior as the hostname.

Today, if you add an extraHosts, it doesn't build as expected when in high availability mode

**Benefits**

Allows when in high availability mode read and write with more and one hostname.

Today the recording is limited to only the main hostname

**Additional Information**

**Checklist**
- [X] Version of chart collided with `Chart.yaml` according to [semver](http://semver.org/)..
- [X] Variables are documented in README.md
- [X] PR title starts with chart name

### CODE REVIEW

**Review by carrodher — CHANGES_REQUESTED** [review]
Thanks for your contribution. You need to bump the chart version in the _Chart.yaml_.

Apart from that, I have been testing the PR and it seems something doesn't work as expected, please see below my comments.

- I used the default `values.yaml` with the following changes:
```diff
ingress:
  ## @param ingress.enabled Enable ingress controller resource
  ##
- enabled: false
+ enabled: true
...
  ## @param ingress.hostname Default host for the ingress resource
  ##
- hostname: influxdb.local
+ hostname: existing-host
  ## @param ingress.path Ingress path*' in order to use this
  ## with ALB ingress controllers.
  ##
- path: /
+ path: /default-path
...
  ## @param ingress.extraHosts The list of additional hostnames to be covered with this ingress record.
  ## Most likely the hostname above will be enough, but in the event more hosts are needed, this is an array
  ## extraHosts:
  ## - name: influxdb.local
  ##   path: /
- extraHosts: []
+ extraHosts:
+   - name: new-extra-host
+     path: /new-path
```
- Templating the current chart everything seems to be working as expected:
```console
$ helm template influx -s templates/ingress.yaml -f values.yaml bitnami/influxdb
```
```yaml
# Source: influxdb/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influx-influxdb
  labels:
    app.kubernetes.io/name: influxdb
    helm.sh/chart: influxdb-2.3.10
    app.kubernetes.io/instance: influx
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: existing-host
      http:
        paths:
          - path: /default-path
            pathType: ImplementationSpecific
            backend:
              service:
                name: influx-influxdb
                port:
                  name: http
    - host: "new-extra-host"
      http:
        paths:
          - path: /new-path
            pathType: ImplementationSpecific
            backend:
              service:
                name: influx-influxdb
                port:
                  name: http
```
- But doing the same with the changes in this PR something doesn't work:
```console
$ helm template influx -s templates/ingress.yaml -f values.yaml .
Error: template: influxdb/templates/ingress.yaml:50:24: executing "influxdb/templates/ingress.yaml" at <.Values.ingress.extraPaths>: nil pointer evaluating interface {}.ingress
```

**Comment by PauloFerreira25** [comment]
Hi. 

It really was broken, please excuse me. I remade it now using your test template.

Really if the architecture is standalone, the output is the same.
It only changes when the architecture is high-availability

```yaml
## @param architecture InfluxDB&trade; architecture (`standalone` or `high-availability`)
# architecture: standalone
architecture: high-availability
```
Change backend address to influx-influxdb-relay
--- high-availability
```yaml
# Source: influxdb/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influx-influxdb
  labels:
    app.kubernetes.io/name: influxdb
    helm.sh/chart: influxdb-2.3.10
    app.kubernetes.io/instance: influx
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: influxdb.local
      http:
        paths:
          - path: /write
            pathType: ImplementationSpecific
            backend:
              service:
                name: influx-influxdb-relay
                port:
                  name: http
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: influx-influxdb
                port:
                  name: http
    - host: "new-extra-host"
      http:
        paths:
          - path: /write
            pathType: ImplementationSpecific
            backend:
              service:
                name: influx-influxdb-relay
                port:
                  name: http
          - path: /new-path
            pathType: ImplementationSpecific
            backend:
              service:
                name: influx-influxdb
                port:
                  name: http

```
--- standalone
```yaml
# Source: influxdb/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influx-influxdb
  labels:
    app.kubernetes.io/name: influxdb
    helm.sh/chart: influxdb-2.3.11
    app.kubernetes.io/instance: influx
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: influxdb.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: influx-influxdb
                port:
                  name: http
    - host: "new-extra-host"
      http:
        paths:
          - path: /new-path
            pathType: ImplementationSpecific
            backend:
              service:
                name: influx-influxdb
                port:
                  name: http
```

**Review by carrodher — APPROVED** [review]
Thanks, changes LGTM!

**Comment by carrodher** [comment]
@PauloFerreira25 everything looks good, but when trying to rebase the changes before merging there were some conflicts due to a new version was released in the meantime, can you please bump the chart version in the _Chart.yaml_ again? Thanks

**Comment by PauloFerreira25** [comment]
@carrodher Thank you very much for your attention and patience.
I believe it is ok now.

**Pull request merged**
