### PR TITLE
[bitnami/oauth2-proxy] make google-group as list instead of string

### PR DESCRIPTION
**Pull request by omer2500**
Signed-off-by: omer nitzan <omer2500@gmail.com>

### Description of the change

The --google-group flag on oauth2proxy may be given multiple times depends of how many groups you have.
so i converted the variable name to groups(because its already nested inside google property) and made it of type list and not string.

### Benefits

Will give the option to pass multiple google groups without the need to add it as extra args

### Possible drawbacks

None its how oauth2-proxy working

### Applicable issues

- fixes #

### Additional information

image

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by omer2500** [comment]
@carrodher 

Hi,

Im not sure hot to handle the failure on the license headers check
it seems that its not related to my changes 
what should i do?

Thanks

**Comment by carrodher** [comment]
Thanks for the PR, the issue with that action is something unrelated, we are taking a look at it but it shouldn't block this contribution

**Comment by carrodher** [comment]
The failing action should be solved by rebasing from _main_, could you please do that? Thanks!

**Comment by omer2500** [comment]
@corico44 

first, I'm already using this flag with the bitnami chart, but passing multiple --google-group fields to the extraArgs property on the value file.

I tested my change with helm templates command and saw the output
with empty list
and a list with at least 2 items 

let me know if you want me to test this in more ways

**Review by corico44 — APPROVED** [review]
LGTM

**Pull request merged**
