### PR TITLE
bitnami/rabbitmq: Setting target port to equal port

### PR DESCRIPTION
**Pull request by guyarb**
**Description of the change**

GCP k8s does not allow port forwarding to the machine, since it does not recognize amqp as target port.
Setting the target port to equal the port of the relevant protocols.

**Benefits**

GCP k8s will allow port forwarding to the machine

**Possible drawbacks**

None

**Applicable issues**

None 

  - fixes https://github.com/bitnami/charts/issues/4174

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Review by miguelaeh — COMMENTED** [review]
Hi @guyarb ,
In general the target port has not to be the same as the service port. It can be different since it is the pod's port and the labels used should be correct as they are defined here: Setting target port to equal port

**Comment by guyarb** [comment]
> Hi @guyarb ,
> In general the target port has not to be the same as the service port. It can be different since it is the pod's port and the labels used should be correct as they are defined here: Setting target port to equal port

Hey @miguelaeh, thanks for the quick reply. I'm not sure I understood you correctly. I understand your point the target port might be different, but how do you suggest the fix should be?
What about adding the target ports to the values.yaml and allowing users to override them?

**Comment by Spittal** [comment]
Hey just wanna check in here and mention that the headless service yaml file should be edited as part of this PR with the same fix.

**Comment by miguelaeh** [comment]
>What about adding the target ports to the values.yaml and allowing users to override them?

I agree with this, but, in that case it would be needed to set the container port to the same value to be consitent and the proper env vars to configure the ports in container.

I would like to understand better the issue. Why ports can't be set using their names? Is this a limitation of GCP itself? In that case, I think we would need to check all the charts.

**Pull request closed without merging**
