### PR TITLE
[discourse] docs: there is no Redis user

### PR DESCRIPTION
**Pull request by dunglas**
Hi,

Thanks for this chart, it works great! This PR just fixes a tiny typo: there is no concept of user with Redis.

### CODE REVIEW

**Comment by rafariossaa** [comment]
Hi @dunglas ,
  Thanks for your PR!
  Could you take a look to the automatic test that is failing ?

**Comment by dunglas** [comment]
@rafariossaa is it really intended to bump the chart version just for a typo fix?

**Comment by rafariossaa** [comment]
Hi,
  Yes, any change done need to bump the Chart version.

**Comment by rafariossaa** [comment]
Hi @dunglas,
  Could you fix this ?

**Pull request merged**
