### PR TITLE
[bitnami/cassandra] expose metrics through default service and add serviceMonitor

### LINKED ISSUE #3282: [bitnami/cassandra] Port 8080 for integration with Prometheus isn't exposed by the Service
**Which chart**: cassandra

**Description**:
When enabling metrics they couldn't be accessed via Service (port 8080).

**Steps to reproduce:**
1. In values.yaml enable metrics:
```
metrics:
  enabled: true
```
2. Install the chart:
```
helm install cassandra . --namespace default
```
3. Enable Kubernetes proxy:
```
kubectl proxy --port=7777
```
4. Try to gain metrics:
```
http://localhost:7777/api/v1/namespaces/default/services/http:janusgraph-cassandra:8080/proxy
```
5. As a result, you will see the following response:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no service port 8080 found for service \"cassandra-cassandra\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

**Expected behavior**:
1. If I extend the Service with additional "metrics" port:
```
(ommited)
spec:
  ports:
    - name: cql
      protocol: TCP
      port: 9042
      targetPort: cql
    - name: thrift
      protocol: TCP
      port: 9160
      targetPort: thrift
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: metrics
(ommited)
```
then I will be able to receive metrics which could be used in Prometheus:
```
# HELP cassandra_stats node stats
# TYPE cassandra_stats gauge
cassandra_stats{cluster="cassandra",datacenter="datacenter1",keyspace="",table="",name="org:apache:cassandra:metrics:droppedmessage:batch_store:dropped:count",} 0.0
...
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a2cfecc33f6911261fb8a670d2df2714094002a6", GitTreeState:"clean", BuildDate:"2020-05-29T21:50:25Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**:
I didn't get why "bitnami/cassandra-exporter" image is a part of Cassandra pods. Usually in bitnami charts metrics have their own dedicated pod and service. Maybe I missed something and metrics could be used in Prometheus somehow with current version of the chart?..

### PR DESCRIPTION
**Pull request by dani8art**
**Description of the change**

This PR introduces two changes

- Update default Cassandra service adding an entry to expose a port for gathering metric
- Add ServiceMonitor to facilitate the configuration of Prometheus.

**Benefits**

We can monitor Cassandra in an easier way

**Possible drawbacks**

N/A

**Applicable issues**

  - fixes #3282

**Additional information**

N/A

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by ahmgeek** [comment]
@dani8art  when it's gonna be released to bitnami's repo?  🙈

**Comment by dani8art** [comment]
Our CI/CD system is going to push the chart to the Helm registry, in terms of time, may be a slight difference between the appearance of the code in GitHub and the chart in the registry.

**Comment by ahmgeek** [comment]
@dani8art sorry to bother over and over it seems `5.6.0` is not yet in the registry

**Comment by dani8art** [comment]
I'm able to fetch it could you try it again?
```
$ helm repo update
$ helm search repo bitnami/cassandra
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
bitnami/cassandra       5.6.0           3.11.6          Apache Cassandra is a free and open-source dist...
```

**Comment by ahmgeek** [comment]
[
Screenshot 2020-08-05 at 2 24 23 PM
](url)


😢

**Comment by ahmgeek** [comment]
No worries, I re-added the repo and now works fine, lesson learned the hard way

**Pull request merged**
