### PR TITLE
[bitnami/kong] Align role and clusterRole rules with upstream project

### PR DESCRIPTION
**Pull request by fmulero**
Signed-off-by: Fran Mulero <fmulero@vmware.com>

**Description of the change**

Current rbacs rules are not aligned with the kong ingress controller requirements. If we install current bitnami/kong chart (`helm install kong bitnami/kong --version 6.1.10`), the kong-ingress-controller containers will start raising errors about missing permissions:

```shell
$ kubectl logs deploy/kong -c kong-ingress-controller
Found 2 pods, using pod/kong-75757c49b6-dqzmt
Waiting for the Kong container to be ready
Kong container ready
time="2022-04-12T11:40:34Z" level=info msg="diagnostics server disabled"
time="2022-04-12T11:40:34Z" level=info msg="starting controller manager" commit=NOT_SET logger=setup release=NOT_SET repo=NOT_SET
...
time="2022-04-12T11:40:34Z" level=info msg="Starting server" addr="{\"IP\":\"::\",\"Port\":10255,\"Zone\":\"\"}" kind=metrics path=/metrics
time="2022-04-12T11:40:34Z" level=info msg="Starting server" addr="{\"IP\":\"::\",\"Port\":10254,\"Zone\":\"\"}" kind="health probe"
I0412 11:40:34.915674      14 leaderelection.go:248] attempting to acquire leader lease default/kong-ingress-controller-leader-kong...
E0412 11:40:34.921827      14 leaderelection.go:330] error retrieving resource lock default/kong-ingress-controller-leader-kong: leases.coordination.k8s.io "kong-ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:default:kong" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "default"
E0412 11:40:38.950824      14 leaderelection.go:330] error retrieving resource lock default/kong-ingress-controller-leader-kong: leases.coordination.k8s.io "kong-ingress-controller-leader-kong" is forbidden: User "system:serviceaccount:default:kong" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "default"
...
```

**Additional information**

New rules were taken from:
* https://github.com/Kong/kubernetes-ingress-controller/blob/main/config/rbac/role.yaml
* https://github.com/Kong/kubernetes-ingress-controller/blob/main/config/rbac/leader_election_role.yaml

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by FraPazGal — COMMENTED** [review]
I'm missing the rules for the `updroutes` and `udproutes/status` resources as defined by [upstream](https://github.com/Kong/kubernetes-ingress-controller/blob/44e2c77b2987f531aab0014e400f2f941a85a736/config/rbac/role.yaml#L238). Is this a conscious decision?

**Comment by fmulero** [comment]
> I'm missing the rules for the `updroutes` and `udproutes/status` resources as defined by [upstream](https://github.com/Kong/kubernetes-ingress-controller/blob/44e2c77b2987f531aab0014e400f2f941a85a736/config/rbac/role.yaml#L238). Is this a conscious decision?

They are [here](https://github.com/bitnami/charts/pull/9772/files#diff-f6eb6464685558b3ab7e7c5ad33b069d8362a87c054ffd89cbdab04d1ba64be7R330)

**Comment by FraPazGal** [comment]
Sorry for my brain fart, I was actually referring to the `tcproutes` and `tcproutes/status` resources. I ended up writing `udp` by mistake.

**Comment by fmulero** [comment]
No problem, that's a new [feature](https://github.com/Kong/kubernetes-ingress-controller/commit/4ea69833a2267d71cec5ce66b6bda54c0bba152a). Thanks @FraPazGal

**Review by FraPazGal — APPROVED** [review]
LGTM!

**Pull request merged**
