### PR TITLE
bitnami/dataplatform-bp1  metric prefixes were updated to keep in sync with TO platfrom

### PR DESCRIPTION
**Pull request by yogesh-reddy**
…al techs stacks

**Description of the change**
The prefixes for the metrics emitted were changed to have them in sync with individual dashboards of Kafka Spark and Solr on Tanzu Observability platform. 

**Benefits**
Individual Dashboard on wavefront will be lit up and users can use those dashboards once TO platfroms have prometheus exporter dashboards for each tech stack.

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Review by gkulkarni32 — COMMENTED** [review]
Can you please change this as below: 

### To 4.0.0
This major version updates the prefixes of individual applications metrics in Wavefront Collectors which are fed to Tanzu observability in order to light up the individual dashboards of Kafka, Spark and Solr on Tanzu Observability platform.

**Comment by Mauraza** [comment]
Hi @yogesh-reddy,

Thanks for the PR!, could you fix the linter errors?

**Comment by yogesh-reddy** [comment]
Hi @Mauraza 
I have updated the files for lint errors please check it now 

Thank you

**Comment by Mauraza** [comment]
Hi @yogesh-reddy,

Thanks again for PR! LGTM!!

**Review by Mauraza — APPROVED** [review]

**Pull request merged**
