### PR TITLE
[bitnami/postgresql] set some bits compatible with pss restricted

### PR DESCRIPTION
**Pull request by jcpunk**
### Description of the change

These enhanced security defaults bring the chart closer into line with the security best practices.

### Benefits

Better pod security by default following the kubernetes best practices.

### Possible drawbacks

Folks doing local manipulations of the container may encounter surprises.

### Applicable issues

- fixes #

### Additional information

Because the init container requires root, this cannot be fully run within a restricted namespace.

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by jcpunk** [comment]
The CI was passing with `11-debian-11-r120` but failed with the `11-debian-11-r130` that you merged in.  Did something change?

**Comment by andresbono** [comment]
The security context seems to be too strict:

```
[pod_id=postgresql-rtest-0] postgresql 16:08:06.76 INFO  ==> Generating local authentication configuration
[pod_id=postgresql-rtest-0] /opt/bitnami/scripts/libpostgresql.sh: line 234: /opt/bitnami/postgresql/conf/pg_hba.conf: Permission denied
[pod_id=postgresql-rtest-0] /opt/bitnami/scripts/libfile.sh: line 41: /opt/bitnami/postgresql/conf/postgresql.conf: Permission denied
```

Also, as I mentioned in the other PR, I fear possible hidden breaking changes for existing deployments that receive an upgrade...

**Comment by jcpunk** [comment]
The `fsGroup` appears to work differently than I'd expected.  It seems the containers expect group `0` even though `fsGroup` is set to a different value.

In theory I've got this resolved by explicitly setting the group to the default of `0`, but now at least it is clear that this is the expected value for this container.

If you'd prefer I increment the major version to note a possible breaking change I can.

**Comment by andresbono** [comment]
Just a quick update. We would like to unify the rules for all your PRs as much as possible to have some homogeneity. We are still pending to evaluate the regressions and risks this change may carry.

**Review by andresbono — APPROVED** [review]

**Review by andresbono — APPROVED** [review]

**Pull request merged**
