### PR TITLE
[bitnami/postgresql] Fix issues when using enablePostgresUser=false

### PR DESCRIPTION
**Pull request by migruiz4**
### Description of the change

Changes the logic for `auth.enablePostgresUser`, fixing some issues, such as not creating the TLS secret when `enablePostgresUser=false` causing it to be missing if other keys inside the secret where required.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by migruiz4** [comment]
Expect the CI/CD to fail, as this PR depends on https://github.com/bitnami/charts/pull/17397.

Once the changes to bitnami/common are merged, I will update the dependencies and launch the tests again.

**Review by gongomgra — DISMISSED** [review]
LGTM!

**Review by gongomgra — APPROVED** [review]

**Review by Mauraza — DISMISSED** [review]
LGTM!

**Review by Mauraza — APPROVED** [review]
LGTM

**Comment by gongomgra** [comment]
Hi @remotezygote,

Thanks for using Bitnami and for reporting this issue. We are working on a fix for a similar issue at https://github.com/bitnami/charts/pull/17502

**Comment by migruiz4** [comment]
Hi @remotezygote,

Could you please provide more details about your use case?
I wasn't able to reproduce your issue by fresh-installing a chart using the values you provided:
```
helm install test . --set auth.postgresPassword=pass --set auth.database=database
```

We have released a new version of the bitnami/postgresql chart 12.6.4, I would appreciate it if you could try using this new version and provide your feedback, although I'm not sure if the fix is related to your issue.

**Comment by dpulrichth** [comment]
We have the same issue since upgrading to any version higher than 12.6.0. When attempting to install the chart, we get the same error message: 

`Error: couldn't find key password in Secret <namespace>/postgresql`

We do have a secret named postgresql that contains a value for `postgres-password`. Manually adding a value `password` resolves this issue and allows us to deploy.

**Comment by joancafom** [comment]
Hi @dpulrichth 

I'm sorry to hear that you have experienced issues while upgrading. As my colleague said, we have been working on improving the chart and released new versions with fixes. In case the new versions do not resolve the problem, please create a new ticket explaining the details and custom installation params so that we can try to reproduce it and provide feedback.

Thanks 😁 !

**Pull request merged**
