### PR TITLE
[bitnami/influxdb] Set some additional pod security restrictions

### LINKED ISSUE #17292: [bitnami/influxdb] cronjobs compatible with pss-restricted
### Name and Version

bitnami/influxdb 5.6.2

### What is the problem this feature will solve?

When trying to run with the kubernetes pod admission controller set to pss-restricted, the cronjobs do not get scheduled due to missing security restrictions.

https://kubernetes.io/docs/concepts/security/pod-security-standards/

### What is the feature you are proposing to solve the problem?

Update the cronjob templates to run with the enhanced security settings

### What alternatives have you considered?

I tried to update the chart myself, but don't know enough about what those jobs do to feel like it would be safe.

### PR DESCRIPTION
**Pull request by jcpunk**
### Description of the change

Set additional pod security parameters

### Benefits

Better pod security by default following the kubernetes best practices.

### Possible drawbacks

Folks doing local manipulations of the container may encounter suprises.

### Applicable issues

- fixes #17292

### Additional information

This leans towards PSS Restricted, but the cronjobs are not configured for running in that way.

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by fevisera** [comment]
Hi @jcpunk,

I tested your changes but the container crashes:
```
$ helm install influx .
$ kubectl logs -f influx-influxdb-76dd695468-9bg79
influxdb 09:27:02.56 INFO  ==> ** Starting InfluxDB setup **
influxdb 09:27:02.57 INFO  ==> No injected configuration files found. Creating default config files...
touch: cannot touch '/opt/bitnami/influxdb/etc/influxdb.conf': Permission denied
```
Without your changes, the chart is installed fine and the container does not crash. Am I missing something?

**Comment by jcpunk** [comment]
Looks like my local testing was using a forked image, in theory I've just pushed up a fix.

**Comment by jcpunk** [comment]
I'm not totally sure why it wants GID==0...

**Comment by fevisera** [comment]
Hi @jcpunk,

I could run the chart with your changes and they are aligned to the other PR as mentioned https://github.com/bitnami/charts/pull/17387#issuecomment-1643394435.
Please, resolve the conflicts and I will approve it.

Thanks.

**Comment by jcpunk** [comment]
Rebased off HEAD.

**Review by fevisera — APPROVED** [review]
LGTM!
Thank you @jcpunk for your contribution!

**Pull request merged**
