### PR TITLE
[bitnami/influxdb] Feature to restore from AWS S3

### PR DESCRIPTION
**Pull request by shreekumar2901**
### Description of the change

This contribution includes a feature to restore data from AWS S3 endpoint. Whenever influxdb deployment comes up, an initContainer will be spinned up and it will fetch the data from the backup stored in AWS s3. The restored data will be stored in a separate PVC.

### Benefits

Automatic restore of backed up data from AWS S3

### Possible drawbacks

- When no providers are provided(i.e data is stored in PVC itself) ideally restore should happen from backups directory itself. The proposed change does not include this scenario.
- Proposed change is tested only with AWS S3 endpoint

### Applicable issues
When backup and restore is enabled with only PVC(i.e no external providers such as AWS), restore won't work. So, in this scenario, it's not recommended with the proposed change to enable restore.

### Additional information
The restore PVC is mounted to the influxdb deployment. Restore scripts can be included in `custom-init-scripts`

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! Please let us know when it is ready for review.

**Comment by andilar** [comment]
OSPO check successful @shreekumar2901. 🥇

**Comment by shreekumar2901** [comment]
@javsalgar Ready for Review

**Comment by jotamartos** [comment]
Hi @shreekumar2901,

Thank you for your contribution. This is a very specific use-case, highly attached to AWS, and the changes you are applying can be easily deployed using influxdb.initContainers, influxdb.extraVolumeMounts, influxdb.extraVolumes and extraDeploy parameters.

I'm going to close this PR now but I'd like to thank you for taking the time to propose this change. We will revisit this feature in the future if more users request it.

**Pull request closed without merging**
