### PR TITLE
[bitnami/thanos] Fix sharded storegateway cache configs

### PR DESCRIPTION
**Pull request by sgreben**
### Description of the change

Mount the sharded storegateway's cache config under the same conditions as in the unsharded case (i.e. whenever thanos.storegateway.createConfigmap is set). It seems that this was missed in #25242.

### Benefits

Sharded storegateway pods no longer fail to start due to a missing config file when bucketCacheConfig or indexCacheConfig is set.

### Possible drawbacks

N/A

### Applicable issues

- fixes the situation described in #25240 (but for the sharded case)

### Additional information

N/A

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by sgreben** [comment]
@andresbono please ping me when you've had a chance to review, then i'll rebase the branch & re-bump the chart version again :)

**Review by andresbono — APPROVED** [review]
Thank you so much for submitting this fix! It makes total sense. LGTM

**Comment by sgreben** [comment]
Thanks @andresbono!

**Comment by sgreben** [comment]
@andresbono argh, this PR introduces a bug unfortunately. The context at the point where we evaluate the condition isn't the root ($) but the `range` over the shards :/ I had fixed this while testing but forgot to apply it to the fork for the PR.. Followup coming in a minute.

**Comment by andresbono** [comment]
You are right, I missed it. Thank you for following-up with the new PR 🎉

**Pull request merged**
