### PR TITLE
 [bitnami/redis]  add support for headless metrics service

### PR DESCRIPTION
**Pull request by jza0330**
### Description of the change

- fixes incorrect invocation of get_port function inside startup scripts
- fixes incorrect `SENTINEL_SERVICE_PORT` in stop scripts. This is why failover during statefulset restart was not working
- adds new `metrics.service.clusterIP` which allows to configure exporter service Cluster IP

### Benefits
Deployment with Sentinel is now functional
Failover with Sentinel is now functional
Metrics service can now be configured as headless

### Possible drawbacks

None

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Here you can see some details about how to solve this issue: https://github.com/bitnami/charts/pull/16545/checks?check_run_id=13347812654

**Comment by jza0330** [comment]
I added one more commit to this PR since it was not merged.  Thanks

**Comment by carrodher** [comment]
Please note changes for different Helm charts are included in this PR and this is not something supported, could you please fix that and only include changes in a single chart per PR? Thanks

**Comment by jza0330** [comment]
> Please note changes for different Helm charts are included in this PR and this is not something supported, could you please fix that and only include changes in a single chart per PR? Thanks

I'm so sorry. Now it's as required

**Review by dgomezleon — APPROVED** [review]
LGTM. Thanks for contributing

**Pull request merged**
