### PR TITLE
[bitnami/nginx] Remove default value of updateStrategy.RollingUpdate. Ensure users may specify updateStrategy.type = Recreate without fatal errors.

### PR DESCRIPTION
**Pull request by davek804**
### Description of the change

This PR removes `updateStrategy.rollingUpdate`'s default value of `{}` which causes an error when trying to install with `updateStrategy.type` of `Recreate`:

``` 
Error: UPGRADE FAILED: failed to create resource: Deployment.apps "OMITTED" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
helm.go:84: [debug] Deployment.apps "OMITTED" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

### Benefits
This fixes an installation failure when using Recreate strategy. You may still specify a `RollingUpdate` strategy if required with the chart. 

### Possible drawbacks

No known drawbacks as users may still specify RollingUpdate similar to how the readme helptext now describes.

### Applicable issues

I found the same thing over in the Wordpress chart and made the same set of changes as https://github.com/bitnami/charts/issues/8961.

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by davek804** [comment]
@carrodher hi there. I'm not sure I quite see what the remaining issue with the README is. Any chance you can take a look during your review? Thank you!

**Comment by davek804** [comment]
@CeliaGMqrz need any further information to get this merged?

**Comment by CeliaGMqrz** [comment]
Hi @davek804, 

Sorry for my late response. 

Thanks for your contribution. I'm sorry but I don't think it is appropriate to comment this default value. Instead, you could run the chart by setting the value like this `--set updateStrategy.rollingUpdate=null ` could you please try this?

**Comment by CeliaGMqrz** [comment]
Hi @davek804,

Could you please run a resync? I'm getting failed notifications when merging in main to resolve the conflicts from your repository. Thanks.

**Pull request closed without merging**
