### PR TITLE
Add pre-push test to avoid breaking existing schemas

### PR DESCRIPTION
**Pull request by andresmgot**
**Description of the change**

Add a check that, in case the chart to push has a schema, validates that the schema is valid with the default values.

**Applicable issues**

  - ref https://github.com/kubeapps/kubeapps/issues/1182

### CODE REVIEW

**Comment by carrodher** [comment]
This kind of check is executed locally, so we need to ensure that the team has `helm v3` installed and included in the PATH as `helm3` if not, the hook will fail and the PRs will be blocked.
Before merging it, can you update the handbook and sent some messages to the team in order to ensure that they have the correct tools?

**Comment by andresmgot** [comment]
TBH this is a test that can be either bypassed (if the githooks are not enabled) or that will fail and will need to be removed when `helm3` becomes the default. If there is already a test somewhere that check that the charts are compatible with Helm 3 we can skip this. WDYT?

**Comment by carrodher** [comment]
In the content team, everyone should have githooks enabled and it should be executed before each PR (unless someone is bypassing it 🔪). If we want to add this test at this time we need to ensure that the command works for the team. I think the easy way is notifying the team via Slack with a link to the handbook with the instructions.

**Comment by andresmgot** [comment]
> If we want to add this test at this time we need to ensure that the command works for the team

Yes, that's my point. I don't think it's worth it to add the test here because it only affect to half of the charts (not the ones upstreamed) so I'd rather not give a false feeling of testing this when it's only done partially.

**Pull request closed without merging**
