### PR TITLE
[bitnami/postgresql] Fix invalid default custom rules in network policies

### LINKED ISSUE #17465: [bitnami/postgresql] destination for postgresql.networkPolicy.egressRules.customRules is a table. Ignoring non-table value ([])
### Name and Version

bitnami/postgres 12.5.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When upgrading my deployment, the following warnings are displayed:

```
coalesce.go:223: warning: destination for postgresql.networkPolicy.egressRules.customRules is a table. Ignoring non-table value ([])
coalesce.go:223: warning: destination for postgresql.networkPolicy.ingressRules.primaryAccessOnlyFrom.customRules is a table. Ignoring non-table value ([])
coalesce.go:223: warning: destination for postgresql.networkPolicy.ingressRules.readReplicasAccessOnlyFrom.customRules is a table. Ignoring non-table value ([])
```

There is a similar issue with mariadb: https://github.com/bitnami/charts/issues/15821

### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

No warnings regarding invalid ingress/egress customRules.

### What do you see instead?

```
coalesce.go:223: warning: destination for postgresql.networkPolicy.egressRules.customRules is a table. Ignoring non-table value ([])
coalesce.go:223: warning: destination for postgresql.networkPolicy.ingressRules.primaryAccessOnlyFrom.customRules is a table. Ignoring non-table value ([])
coalesce.go:223: warning: destination for postgresql.networkPolicy.ingressRules.readReplicasAccessOnlyFrom.customRules is a table. Ignoring non-table value ([])
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dpulrichth**
### Description of the change
This PR adresses https://github.com/bitnami/charts/issues/17465 which is caused by invalid default values for ingress custom rules. This PR replaces the default custom rules `[]` with `{}`. This kind of issue was previously discussed in https://github.com/bitnami/charts/pull/15638 for the mariadb chart.

### Benefits
This PR replaces the default ingress custom rules `[]` with `{}`, resolving warnings like `coalesce.go:223: warning: destination for postgresql.networkPolicy.egressRules.customRules is a table. Ignoring non-table value ([])`

### Applicable issues

- fixes #17465 

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

**Comment by dpulrichth** [comment]
> Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Thanks for letting me know. I fixed my previous sign-off and the DCO check has succeeded.

**Comment by rafariossaa** [comment]
Hi, 
  Did you have the chance to take a look to my comment on #17465 ?

**Comment by rafariossaa** [comment]
Hi,
  Could yout rebase from main and update the chart version too ?

**Pull request closed without merging**
