### PR TITLE
Optimize mariadb galera cluster split-brain detection, judge whether …

### PR DESCRIPTION
**Pull request by hamishliu**
Please refer to issues details: https://github.com/bitnami/charts/issues/6698.
Mainly optimize galera cluster brain fissure state detection, svc agent back-end traffic failover

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi! The solution looks good to me but I'd like @rafariossaa to check it when he comes back (he is on PTO at the moment)

**Review by javsalgar — APPROVED** [review]

**Comment by javsalgar** [comment]
Could you please bump the chart version?

**Comment by hamishliu** [comment]
apiVersion: v1
appVersion: 10.4.12
description: MariaDB Galera is a multi-master database cluster solution for synchronous
  replication and high availability.
engine: gotpl
home: https://mariadb.org
icon: https://bitnami.com/assets/stacks/mariadb-galera/img/mariadb-galera-stack-220x234.png
keywords:
- mariadb
- mysql
- database
- sql
- prometheus
- galera
- percona
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: mariadb-galera
sources:
- https://github.com/bitnami/bitnami-docker-mariadb-galera
- https://github.com/prometheus/mysqld_exporter
version: 2.0.2

**Comment by hamishliu** [comment]
This problem also exists in the latest version of github.

**Comment by javsalgar** [comment]
It seems that the chart version is still not bumped, could you try bumping it?

**Comment by hamishliu** [comment]
bumping, done

**Comment by javsalgar** [comment]
Thank you! I'll leave it on hold until @rafariossaa returns

**Comment by rafariossaa** [comment]
Hi,
  Maybe I am missing something, I am not sure on how this will improve the detection. 
  I can see that this query is better than the `mysqladmin status` command, but as there is not handling of the output of `mysql ... select * from mysql.wsrep_cluster_members;` the liveness check is based on the exit code from the command executed and even if there are no rows in wsrep_cluster_members it will still return ok.

Here I used `uuid='1'` to simulate a no cluster members output.

```
I have no name!@mygalera-mariadb-galera-0:/$ mysql -u root -pu7TB7utH9K -e "select * from mysql.wsrep_cluster_members;"
+--------------------------------------+--------------------------------------+---------------------------+-----------------------+
| node_uuid                            | cluster_uuid                         | node_name                 | node_incoming_address |
+--------------------------------------+--------------------------------------+---------------------------+-----------------------+
| 0bc2a99c-d976-11eb-836c-bb93807b222f | e364e0b5-d975-11eb-832f-433b30706546 | mygalera-mariadb-galera-1 | AUTO                  |
| 2e540956-d976-11eb-a334-77a6c1a9f43b | e364e0b5-d975-11eb-832f-433b30706546 | mygalera-mariadb-galera-2 | AUTO                  |
| e6a8a757-d975-11eb-8f85-0bad1dfd84e7 | e364e0b5-d975-11eb-832f-433b30706546 | mygalera-mariadb-galera-0 | AUTO                  |
+--------------------------------------+--------------------------------------+---------------------------+-----------------------+
I have no name!@mygalera-mariadb-galera-0:/$ echo $?
0
I have no name!@mygalera-mariadb-galera-0:/$ mysql -u root -pu7TB7utH9K -e "select * from mysql.wsrep_cluster_members where node_uuid='1';"
I have no name!@mygalera-mariadb-galera-0:/$ echo $?
```

**Comment by hamishliu** [comment]
Hello, you may misunderstand the actual function of my adding this SQL query sentence. In fact, I don't care if there is any data in the wsrep_cluster_member table. I can also query other tables here. The actual purpose here is to check whether the mysql is read and written, because when the node is expelled from the cluster, querying any table under mysql will cause an exception of "ERROR 1047 (08S01) at line 1: WSREP has not yet prepared node for application use").

**Comment by hamishliu** [comment]
Let me show you. Please take a look at the output below.


1、This is the output of the normal situation of the cluster
I have no name!@mysql-0:/$ mysql -u root -pcoding123 -e "show status like 'wsrep_cluster%';"
+----------------------------+--------------------------------------+
| Variable_name              | Value                                |
+----------------------------+--------------------------------------+
| wsrep_cluster_weight       | 3                                    |
| wsrep_cluster_capabilities |                                      |
| wsrep_cluster_conf_id      | 18446744073709551615                 |
| wsrep_cluster_size         | 3                                    |
| wsrep_cluster_state_uuid   | a30c16c8-d98b-11eb-a0d9-4a9eb116b95d |
| wsrep_cluster_status       | Primary                              |
+----------------------------+--------------------------------------+
I have no name!@mysql-0:/$ mysql -u root -pcoding123 -e "select * from mysql.wsrep_cluster;"
+--------------------------------------+---------+------------+------------------+--------------+
| cluster_uuid                         | view_id | view_seqno | protocol_version | capabilities |
+--------------------------------------+---------+------------+------------------+--------------+
| a30c16c8-d98b-11eb-a0d9-4a9eb116b95d |       3 |        960 |                4 |       184703 |
+--------------------------------------+---------+------------+------------------+--------------+
I have no name!@mysql-0:/$ echo $?
0
I have no name!@mysql-0:/$ mysql -u root -pcoding123 -e "select * from mysql.wsrep_cluster;"
+--------------------------------------+---------+------------+------------------+--------------+
| cluster_uuid                         | view_id | view_seqno | protocol_version | capabilities |
+--------------------------------------+---------+------------+------------------+--------------+
| a30c16c8-d98b-11eb-a0d9-4a9eb116b95d |       3 |        960 |                4 |       184703 |
+--------------------------------------+---------+------------+------------------+--------------+
I have no name!@mysql-0:/$ echo $?
0


2、This is the cluster brain fissure, the output of the expelled node.
I have no name!@mysql-0:/$ mysql -u root -pcoding123 -e "show status like 'wsrep_cluster%';"
+----------------------------+--------------------------------------+
| Variable_name              | Value                                |
+----------------------------+--------------------------------------+
| wsrep_cluster_weight       | 0                                    |
| wsrep_cluster_capabilities |                                      |
| wsrep_cluster_conf_id      | 18446744073709551615                 |
| wsrep_cluster_size         | 1                                    |
| wsrep_cluster_state_uuid   | a30c16c8-d98b-11eb-a0d9-4a9eb116b95d |
| wsrep_cluster_status       | non-Primary                          |
+----------------------------+--------------------------------------+
I have no name!@mysql-0:/$ mysql -u root -pcoding123 -e "select * from mysql.wsrep_cluster_members;"
ERROR 1047 (08S01) at line 1: WSREP has not yet prepared node for application use
I have no name!@mysql-0:/$ echo $?
1
I have no name!@mysql-0:/$ mysql -u root -pcoding123 -e "show status like 'wsrep_cluster%';"
+----------------------------+--------------------------------------+
| Variable_name              | Value                                |
+----------------------------+--------------------------------------+
| wsrep_cluster_weight       | 0                                    |
| wsrep_cluster_capabilities |                                      |
| wsrep_cluster_conf_id      | 18446744073709551615                 |
| wsrep_cluster_size         | 1                                    |
| wsrep_cluster_state_uuid   | a30c16c8-d98b-11eb-a0d9-4a9eb116b95d |
| wsrep_cluster_status       | non-Primary                          |
+----------------------------+--------------------------------------+
I have no name!@mysql-0:/$ mysql -u root -pcoding123 -e "select * from mysql.wsrep_cluster;"
ERROR 1047 (08S01) at line 1: WSREP has not yet prepared node for application use
I have no name!@mysql-0:/$ echo $?
1


Querying any table under mysql will cause an exception of "ERROR 1047 (08S01) at line 1: WSREP has not yet prepared node for application use"

**Comment by hamishliu** [comment]
Generally speaking, any table in the built-in mysql database can be queried by probing, and whether the table has data can be queried by querying any table in the built-in database.

The wsrep_cluster_members table exists by default, so I directly query the wsrep_cluster_ members table here.

**Comment by hamishliu** [comment]
We have tested it many times, and when I detect that the node query fails, K8s will trigger pod restart and svc will not request traffic to the node of the brain fissure.
image
If the detection and failover is completed within 10 seconds, the production business will not be affected.

**Comment by hamishliu** [comment]
image
You can use the chaos-mesh tool to reproduce the failure scenario, disconnect mariadb-0 and mariadb-1, disconnect mariadb-0 and mariadb-2, and maintain normal network communication between mariadb-1 and mariadb-2, so that mariadb-0 is driven out of the cluster in isolation.
Thanks

**Review by rafariossaa — APPROVED** [review]
This LGTM

**Comment by hamishliu** [comment]
Thank you very much for the community's recognition.

**Comment by rafariossaa** [comment]
You are welcome.
Thanks to you for your time and for sending the PR.

**Pull request merged**
