### PR TITLE
[bitnami/contour] Configurable envoy ports

### PR DESCRIPTION
**Pull request by mkilchhofer**
**Description of the change**

This change adds the ability to customize the ports used for envoy. In detail you now can:
- change the ports which envoy binds to (containerPorts)
- change or disable the hostPort mappings

**Benefits**
- By changing the bind ports we are now able to run envoy as non-root which should be default in my eyes for an exposed container
- Disabling hostPort mappings (when we do not need it) also increases security

**Possible drawbacks**
`-`

**Applicable issues**
`-`

**Additional information**
`-`

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Review by juan131 — APPROVED** [review]
Thanks so much for this great PR!! Everything looks great to me!
Approving it

**Comment by binnythomas-1989** [comment]
@mkilchhofer I just tested your helm. Im my case I had to write psp and then a RBAC and then add the service account to the daemonset (envoy) to get it working. Even though I did so, the loadbalancer is not able to speak on 8443 since its not reachable.

**Comment by juan131** [comment]
Hi @binnythomas-1989 

What version of the chart are you using? Please note that it can take a few hours for the chart to be released and it's very likely these changes are not available yet in the published chart.

**Comment by binnythomas-1989** [comment]
I pulled his changes from his branch and tested it. 

```
apiVersion: v1
name: contour
description: Contour Ingress controller for Kubernetes
version: 2.1.0
appVersion: 1.8.1
```

**Comment by binnythomas-1989** [comment]
So I added these to the values, I had to do a bit of mending.

Added this psp
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: contour-ingress-envoy
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  hostPorts:
  - max: 65535
    min: 1025
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - hostPath
  - secret
  - emptyDir
```

Added the following RBAC
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: envoy-ingress
rules:
- apiGroups:
  - policy
  resourceNames:
  - contour-ingress-envoy
  resources:
  - podsecuritypolicies
  verbs:
  - use

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: envoy-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: envoy-ingress
subjects:
- kind: ServiceAccount
  name: contour-ingress-envoy
  namespace: contour
```

If we don't add this it would fail with the following errors. If there is a cluster restriction which states all pod should run as nonroot.
```
  Warning  FailedCreate  20s (x13 over 40s)  daemonset-controller  Error creating: pods "contour-envoy-" is forbidden: unable to validate against any pod security policy: [spec.containers[1].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden spec.containers[1].hostPort: Invalid value: 80: Host port 80 is not allowed to be used. Allowed ports: [] spec.containers[1].hostPort: Invalid value: 443: Host port 443 is not allowed to be used. Allowed ports: []]
```

Now though I have fixed it. I have issues with my loadbalancer connecting to 8443 on the envoys container. :-(

**Comment by binnythomas-1989** [comment]
One more curious thing is, im not able to view the /cert and /config that is getting mounted.

```I have no name!@contour-ingress-envoy-fmtv6:/$ ls -al
total 72
drwxr-xr-x   1 root root 4096 Sep 15 19:50 .
drwxr-xr-x   1 root root 4096 Sep 15 19:50 ..
-rwxr-xr-x   1 root root    0 Sep 15 19:50 .dockerenv
drwxr-xr-x   1 root root 4096 Sep  3 03:36 bin
drwxr-xr-x   2 root root 4096 Jul 10 21:04 boot
drwxr-xr-x   5 root root  360 Sep 15 19:50 dev
drwxr-xr-x   1 root root 4096 Sep 15 19:50 etc
drwxr-xr-x   2 root root 4096 Jul 10 21:04 home
drwxr-xr-x   1 root root 4096 Sep 25  2017 lib
drwxr-xr-x   2 root root 4096 Jul 21 19:27 lib64
drwxr-xr-x   2 root root 4096 Jul 21 19:27 media
drwxr-xr-x   2 root root 4096 Jul 21 19:27 mnt
drwxrwxr-x   1 root root 4096 Sep  3 03:35 opt
dr-xr-xr-x 492 root root    0 Sep 15 19:50 proc
drwx------   2 root root 4096 Jul 21 19:27 root
drwxr-xr-x   4 root root 4096 Jul 21 19:27 run
drwxr-xr-x   1 root root 4096 Sep  3 03:36 sbin
drwxr-xr-x   2 root root 4096 Jul 21 19:27 srv
dr-xr-xr-x  13 root root    0 Sep 15 19:50 sys
drwxrwxrwt   1 root root 4096 Sep  3 03:36 tmp
drwxrwxr-x   1 root root 4096 Sep  3 03:35 usr
drwxr-xr-x   1 root root 4096 Jul 21 19:27 var
I have no name!@contour-ingress-envoy-fmtv6:/$ cd /cer 

I have no name!@contour-ingress-envoy-fmtv6:/$ id
uid=1001 gid=0(root) groups=0(root),1(daemon)
```

**Comment by mkilchhofer** [comment]
> @mkilchhofer I just tested your helm. Im my case I had to write psp and then a RBAC and then add the service account to the daemonset (envoy) to get it working. Even though I did so, the loadbalancer is not able to speak on 8443 since its not reachable.

Hi @binnythomas-1989 
I prepared this PR to allow my onprem setup to run as non-root. In my setup it does not matter if I run the envoy Pod as root or not - in both usecases I am able to change the ports envoy is listen on.

> I have no name!@contour-ingress-envoy-csbdw:/$ curl localhost:8080
> I have no name!@contour-ingress-envoy-csbdw:/$ curl localhost:8443
> curl: (7) Failed to connect to localhost port 8443: Connection refused

This is absolutely normal, when your envoy pod does not have valid `/cert` and `/config` directory with the needed content in it. Envoy starts without knowing what to do, except a very minimal bootstrap config. All other config (listener, etc.) comes from the contour pods via the xDS API.

My current working non-root setup:
```console
mkilchhofer@sshgw:~/k8s-platform/projectcontour-internal$ helm3 get values projectcontour-internal
USER-SUPPLIED VALUES:
configInline:
  ingress-status-address: '{{ .Values.envoy.service.loadBalancerIP }}'
envoy:
  containerPorts:
    http: 8080
    https: 8443
  containerSecurityContext:
    runAsUser: 1001
  service:
    loadBalancerIP: 192.168.93.83
  useHostPort: false
prometheus:
  serviceMonitor:
    enabled: true
```

**Comment by binnythomas-1989** [comment]
@mkilchhofer Any ideas why the /cert and /config is not being mounted on envoy, I tried running it as root too. Still don't see the volumes mounted.

**Comment by mkilchhofer** [comment]
@binnythomas-1989 Are the secrets `contourcert` and `envoycert` existing? I think I need some infos about your setup:
- kubernetes distro (AWS EKS, Azure AKS, onprem, ...?)
- Output of `kubectl -n <your-contour-namespace> get pods`
- Output of `kubectl describe pod <envoy pod>`
- Output of `kubectl describe pod <envoy pod> envoy`

**Comment by binnythomas-1989** [comment]
Actually its my bad, the files are available
```
bintho01@C02YH0BNJHD5 contour (feature/contour_configurable_envoy_ports) $ kubectl exec -it contour-ingress-envoy-btpqk -c envoy  sh
$ ls -al
total 76
drwxr-xr-x   1 root root   4096 Sep 16 11:09 .
drwxr-xr-x   1 root root   4096 Sep 16 11:09 ..
-rwxr-xr-x   1 root root      0 Sep 16 11:09 .dockerenv
drwxr-xr-x   1 root root   4096 Sep  2 20:55 bin
drwxr-xr-x   2 root root   4096 Jul 10 21:04 boot
drwxrwsrwt   3 root daemon  140 Sep 16 11:07 certs
drwxrwsrwx   3 root daemon 4096 Sep 16 11:07 config
drwxr-xr-x   5 root root    360 Sep 16 11:09 dev
drwxr-xr-x   1 root root   4096 Sep 16 11:09 etc
drwxr-xr-x   2 root root   4096 Jul 10 21:04 home
drwxr-xr-x   1 root root   4096 Sep 25  2017 lib
drwxr-xr-x   2 root root   4096 Jul 21 19:27 lib64
drwxr-xr-x   2 root root   4096 Jul 21 19:27 media
drwxr-xr-x   2 root root   4096 Jul 21 19:27 mnt
drwxrwxr-x   1 root root   4096 Sep  2 20:55 opt
dr-xr-xr-x 536 root root      0 Sep 16 11:09 proc
drwx------   2 root root   4096 Jul 21 19:27 root
drwxr-xr-x   4 root root   4096 Jul 21 19:27 run
drwxr-xr-x   1 root root   4096 Sep  2 20:55 sbin
drwxr-xr-x   2 root root   4096 Jul 21 19:27 srv
dr-xr-xr-x  13 root root      0 Sep 16 11:07 sys
drwxrwxrwt   1 root root   4096 Sep  2 20:55 tmp
drwxrwxr-x   1 root root   4096 Sep  2 20:55 usr
drwxr-xr-x   1 root root   4096 Jul 21 19:27 var
```
The issue is even though its there, nothing is exposed on 8443

```
bin  boot  certs  config  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run	sbin  srv  sys	tmp  usr  var
$ bash
I have no name!@contour-ingress-envoy-btpqk:/$ cd certs/
I have no name!@contour-ingress-envoy-btpqk:/certs$ ls
ca.crt	tls.crt  tls.key
I have no name!@contour-ingress-envoy-btpqk:/certs$ ls -al
total 4
drwxrwsrwt 3 root daemon  140 Sep 16 11:07 .
drwxr-xr-x 1 root root   4096 Sep 16 11:09 ..
drwxr-sr-x 2 root daemon  100 Sep 16 11:07 ..2020_09_16_11_07_19.084239919
lrwxrwxrwx 1 root root     31 Sep 16 11:07 ..data -> ..2020_09_16_11_07_19.084239919
lrwxrwxrwx 1 root root     13 Sep 16 11:07 ca.crt -> ..data/ca.crt
lrwxrwxrwx 1 root root     14 Sep 16 11:07 tls.crt -> ..data/tls.crt
lrwxrwxrwx 1 root root     14 Sep 16 11:07 tls.key -> ..data/tls.key
I have no name!@contour-ingress-envoy-btpqk:/certs$ curl http://localhost:8080/
I have no name!@contour-ingress-envoy-btpqk:/certs$ curl http://localhost:8443/
```

**Comment by binnythomas-1989** [comment]
Kubernetes Version
```
xyz@abc contour (feature/contour_configurable_envoy_ports) $ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
xyz@abc contour (feature/contour_configurable_envoy_ports) $ 
```

Running on OpenStack

Requested Outputs:

```
xyz@abc contour (feature/contour_configurable_envoy_ports) $ kubectl get pods -n contour
NAME                                       READY   STATUS    RESTARTS   AGE
contour-ingress-contour-56dcf6f49b-crkmk   1/1     Running   0          7m31s
contour-ingress-contour-56dcf6f49b-l4vmk   1/1     Running   0          7m31s
contour-ingress-envoy-btpqk                2/2     Running   0          7m31s
contour-ingress-envoy-d4prf                2/2     Running   0          7m31s
contour-ingress-envoy-f9vv9                2/2     Running   0          7m31s
contour-ingress-envoy-nzhrj                2/2     Running   0          7m31s
contour-ingress-envoy-srfnl                2/2     Running   0          7m31s
contour-ingress-envoy-vfkpv                2/2     Running   0          7m31s
contour-ingress-envoy-zm7v6                2/2     Running   0          7m31s
xyz@abc contour (feature/contour_configurable_envoy_ports) $ kubectl describe pod  contour-ingress-envoy-btpqk
Name:         contour-ingress-envoy-btpqk
Namespace:    contour
Priority:     0
Node:         node-nf-5/xxx.xxx.xxx.xxx
Start Time:   Wed, 16 Sep 2020 12:07:19 +0100
Labels:       app.kubernetes.io/component=envoy
              app.kubernetes.io/instance=contour-ingress
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=contour
              controller-revision-hash=59fc8f5c6c
              helm.sh/chart=contour-2.1.0
              pod-template-generation=1
Annotations:  kubernetes.io/psp: contour-ingress-envoy
Status:       Running
IP:           172.26.68.240
IPs:
  IP:           172.26.68.240
Controlled By:  DaemonSet/contour-ingress-envoy
Init Containers:
  envoy-initconfig:
    Container ID:  docker://c45f212bb86bff8575cde9294cd7da6489e6aac1a4d0ad22e6bb8a5599319509
    Image:         docker.io/bitnami/contour:1.8.1-debian-10-r0
    Image ID:      docker-pullable://bitnami/contour@sha256:8dc4278d3486aa21dc47ccd5954aa510c3d1c5fd7a1b55d9c1016d574c642676
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      contour bootstrap /config/envoy.json --xds-address=contour-ingress --xds-port=8001 --resources-dir=/config/resources --envoy-cafile=/certs/ca.crt --envoy-cert-file=/certs/tls.crt --envoy-key-file=/certs/tls.key ; sleep 2m;echo my-init-container-1 complete;
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 16 Sep 2020 12:07:21 +0100
      Finished:     Wed, 16 Sep 2020 12:09:21 +0100
    Ready:          True
    Restart Count:  0
    Environment:
      CONTOUR_NAMESPACE:  contour (v1:metadata.namespace)
    Mounts:
      /certs from envoycert (ro)
      /config from envoy-config (rw)
Containers:
  shutdown-manager:
    Container ID:  docker://1b10de44a84165677906fab860cfe54a1e5e5c61851d1a33ab65c81a002af641
    Image:         docker.io/bitnami/contour:1.8.1-debian-10-r0
    Image ID:      docker-pullable://bitnami/contour@sha256:8dc4278d3486aa21dc47ccd5954aa510c3d1c5fd7a1b55d9c1016d574c642676
    Port:          <none>
    Host Port:     <none>
    Command:
      contour
    Args:
      envoy
      shutdown-manager
    State:          Running
      Started:      Wed, 16 Sep 2020 12:09:21 +0100
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8090/healthz delay=120s timeout=5s period=20s #success=1 #failure=6
    Environment:    <none>
    Mounts:         <none>
  envoy:
    Container ID:  docker://2aec13e3daa7a629ac28313b229ec9957058e286c8825cd65cfd2638c80302f3
    Image:         docker.io/bitnami/envoy:1.15.0-debian-10-r33
    Image ID:      docker-pullable://bitnami/envoy@sha256:dafcac2105aab58338203847e50d6b5dcc84bfd7f2b28ea6996140b4dcf2c364
    Ports:         8080/TCP, 8443/TCP, 8002/TCP
    Host Ports:    8080/TCP, 8443/TCP, 0/TCP
    Command:
      envoy
    Args:
      -c
      /config/envoy.json
      --service-cluster $(CONTOUR_NAMESPACE)
      --service-node $(ENVOY_POD_NAME)
      --log-level info
    State:          Running
      Started:      Wed, 16 Sep 2020 12:09:21 +0100
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8002/ready delay=120s timeout=5s period=20s #success=1 #failure=6
    Readiness:      http-get http://:8002/ready delay=10s timeout=1s period=3s #success=1 #failure=3
    Environment:
      CONTOUR_NAMESPACE:  contour (v1:metadata.namespace)
      ENVOY_POD_NAME:     contour-ingress-envoy-btpqk (v1:metadata.name)
    Mounts:
      /certs from envoycert (rw)
      /config from envoy-config (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  envoy-config:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  envoycert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  envoycert
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type    Reason     Age        From                                 Message
  ----    ------     ----       ----                                 -------
  Normal  Scheduled  <unknown>  default-scheduler                    Successfully assigned contour/contour-ingress-envoy-btpqk to s04eu02-prod-k8s-node-nf-5
  Normal  Pulled     7m46s      kubelet, node-nf-5  Container image "docker.io/bitnami/contour:1.8.1-debian-10-r0" already present on machine
  Normal  Created    7m45s      kubelet, node-nf-5  Created container envoy-initconfig
  Normal  Started    7m45s      kubelet, node-nf-5  Started container envoy-initconfig
  Normal  Pulled     5m45s      kubelet, node-nf-5  Container image "docker.io/bitnami/contour:1.8.1-debian-10-r0" already present on machine
  Normal  Created    5m45s      kubelet, node-nf-5  Created container shutdown-manager
  Normal  Started    5m45s      kubelet, node-nf-5  Started container shutdown-manager
  Normal  Pulled     5m45s      kubelet, node-nf-5  Container image "docker.io/bitnami/envoy:1.15.0-debian-10-r33" already present on machine
  Normal  Created    5m45s      kubelet, node-nf-5  Created container envoy
  Normal  Started    5m45s      kubelet, node-nf-5  Started container envoy
```

**Comment by binnythomas-1989** [comment]
Since 8443 is not reachable the loadbalancer Listeners are under Operating Status : Error
Screenshot 2020-09-16 at 12 21 39

**Comment by mkilchhofer** [comment]
Are your issues only related to the https listener?

curl https does not work this simple. Envoy uses strict SNI. Something like this works for me:
```console
$ curl --write-out "%{http_code}\n" --resolve git.example.com:8443:127.0.0.1 https://git.example.com:8443
```

**Comment by binnythomas-1989** [comment]
Whats the domain equivalent for git.example.com?

```
I have no name!@contour-ingress-envoy-btpqk:/$ curl --write-out "%{http_code}\n" --resolve localhost:8443:127.0.0.1 https://localhost:8443
000
curl: (7) Failed to connect to localhost port 8443: Connection refused
I have no name!@contour-ingress-envoy-btpqk:/$ 
```

**Comment by mkilchhofer** [comment]
One of your defined ingresses or httpproxy resources.
Please start envoy as root again and install some debug tools inside a envoy pod:

```console
$ kubectl exec -ti projectcontour-internal-envoy-j72ph -c envoy -- bash
root@projectcontour-internal-envoy-j72ph:/# apt update
root@projectcontour-internal-envoy-j72ph:/# apt install net-tools jq 

# // check listeners

root@projectcontour-internal-envoy-j72ph:/# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      1/envoy             
tcp        0      0 0.0.0.0:8002            0.0.0.0:*               LISTEN      1/envoy             
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      1/envoy             
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1/envoy             
tcp6       0      0 :::8090                 :::*                    LISTEN      -  

root@projectcontour-internal-envoy-j72ph:/# curl localhost:9001/listeners
ingress_http::0.0.0.0:8080
ingress_https::0.0.0.0:8443
stats-health::0.0.0.0:8002

root@projectcontour-internal-envoy-j72ph:/# curl localhost:9001/config_dump |jq
# // -> maybe we better port-forward and use a browser for this

root@projectcontour-internal-envoy-j72ph:/# exit
mkilchhofer@sshgw:~/k8s-platform/projectcontour-internal$ kubectl port-forward projectcontour-internal-envoy-j72ph 9001:9001
```
image

**Comment by binnythomas-1989** [comment]
Hello @mkilchhofer 

Seems im not able to run commands.

```
xyz@abc contour $ kubectl exec -it contour-envoy-7f9f7  -c envoy sh
# bash
root@contour-envoy-7f9f7:/# apt udpate
E: Invalid operation udpate
root@contour-envoy-7f9f7:/# apt udpate
E: Invalid operation udpate
root@contour-envoy-7f9f7:/# apt update
E: setgroups 65534 failed - setgroups (1: Operation not permitted)
E: setegid 65534 failed - setegid (1: Operation not permitted)
E: seteuid 100 failed - seteuid (1: Operation not permitted)
E: setgroups 0 failed - setgroups (1: Operation not permitted)
Reading package lists... Done
W: chown to _apt:root of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
W: chown to _apt:root of directory /var/lib/apt/lists/auxfiles failed - SetupAPTPartialDirectory (1: Operation not permitted)
E: setgroups 65534 failed - setgroups (1: Operation not permitted)
E: setegid 65534 failed - setegid (1: Operation not permitted)
E: seteuid 100 failed - seteuid (1: Operation not permitted)
E: setgroups 0 failed - setgroups (1: Operation not permitted)
E: Method gave invalid 400 URI Failure message: Failed to setgroups - setgroups (1: Operation not permitted)
E: Method gave invalid 400 URI Failure message: Failed to setgroups - setgroups (1: Operation not permitted)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)
root@contour-envoy-7f9f7:/# id
uid=0(root) gid=0(root) groups=0(root),1(daemon)
root@contour-envoy-7f9f7:/# 
```

**Comment by binnythomas-1989** [comment]
Whats the image that you are using for envoy @mkilchhofer ?

**Comment by mkilchhofer** [comment]
Okay, I am using the default image from bitnami as you can see some posts above (I posted all cusom values). This is something I saw on OpenShift, which enforces non-root workloads by default.

Let's check only this one first:
```console
root@projectcontour-internal-envoy-j72ph:/# curl localhost:9001/listeners
ingress_http::0.0.0.0:8080
ingress_https::0.0.0.0:8443
stats-health::0.0.0.0:8002
```

**Comment by binnythomas-1989** [comment]
please find the output
```
$ kubectl exec -it contour-envoy-7f9f7 -c envoy sh
# curl localhost:9001/listeners
stats-health::0.0.0.0:8002
# 
```

**Comment by binnythomas-1989** [comment]
Seems I don't have  the other listeners for some reason.

**Comment by binnythomas-1989** [comment]
I just ran envoy and root with proper psp and while create the ingress I have received this error.

```

**Comment by binnythomas-1989** [comment]
Detailed Error below
```
[2020-09-16 15:43:09.676][1][warning][misc] [bazel-out/k8-opt/bin/source/extensions/common/_virtual_includes/utility_lib/extensions/common/utility.h:66] Using deprecated extension name 'envoy.gzip' for 'envoy.filters.http.gzip'. This name will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details.
[2020-09-16 15:43:09.676][1][warning][misc] [source/extensions/filters/http/gzip/config.cc:22] Using deprecated extension 'envoy.extensions.filters.http.gzip'. This extension will be removed from Envoy soon. Please use 'envoy.extensions.filters.http.compressor' instead.
[2020-09-16 15:43:09.676][1][warning][misc] [bazel-out/k8-opt/bin/source/extensions/common/_virtual_includes/utility_lib/extensions/common/utility.h:66] Using deprecated extension name 'envoy.grpc_web' for 'envoy.filters.http.grpc_web'. This name will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details.
[2020-09-16 15:43:09.676][1][warning][misc] [bazel-out/k8-opt/bin/source/extensions/common/_virtual_includes/utility_lib/extensions/common/utility.h:66] Using deprecated extension name 'envoy.router' for 'envoy.filters.http.router'. This name will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details.
[2020-09-16 15:43:09.677][1][warning][config] [source/common/config/grpc_subscription_impl.cc:100] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) ingress_http: cannot bind '0.0.0.0:80': Permission denied
ingress_https: cannot bind '0.0.0.0:443': Permission denied

[2020-09-16 15:43:09.679][22][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0x5000000038
[2020-09-16 15:43:09.679][22][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2020-09-16 15:43:09.679][22][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:92] Envoy version: 50ef0945fa2c5da4bff7627c3abf41fdd3b7cffd/1.15.0/Modified/RELEASE/BoringSSL
[2020-09-16 15:43:09.679][22][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:98] #0: [0x5646512a7f13]
[2020-09-16 15:43:09.679][22][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:98] #1: [0x5646516d0c17]
[2020-09-16 15:43:09.679][22][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:98] #2: [0x5646516d12af]
[2020-09-16 15:43:09.679][22][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:98] #3: [0x56465129ea2d]
[2020-09-16 15:43:09.679][22][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:98] #4: [0x56465178bbc5]
[2020-09-16 15:43:09.679][22][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #5: start_thread [0x7fce0e0f6fa3]
```

**Comment by mkilchhofer** [comment]
Hey @binnythomas-1989 
I think we are hunting a ghost lol :laughing: . I started an empty k3d / k3s cluster on my workstation without a Ingress defined. Indeed, if there is no Ingress defined, envoy does not bind to the ports :laughing: 
image
After applying the kuard example from projectcontour.io, envoy immediately binds the confgured ports:
image

**Comment by binnythomas-1989** [comment]
So I created an ingress for "kuard" and I got this error on the envvoy logs.

```
[2020-09-16 15:43:09.677][1][warning][config] [source/common/config/grpc_subscription_impl.cc:100] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) ingress_http: cannot bind '0.0.0.0:80': Permission denied
ingress_https: cannot bind '0.0.0.0:443': Permission denied

[2020-09-16 15:43:09.679][22][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0x5000000038

```

**Comment by mkilchhofer** [comment]
Okay, then it looks like your values does not have taken place for some reason. Have you tried to uninstall the helm release completely and then perform a fresh install? Shall we use a chat tool or do a quick screenshare with MSTeams or Zoom? :-)

**Comment by mkilchhofer** [comment]
Is Zoom okay? https://us02web.zoom.us/j/81595630078?pwd=NHhndXlZckxyRUZZSHlMWmlYaHlLUT09

**Comment by binnythomas-1989** [comment]
yeah

**Comment by juan131** [comment]
@mkilchhofer thanks so much for helping @binnythomas-1989 with this setup!!! We really really appreciate it!!!

@binnythomas-1989 is there anything else we can help you with??

**Comment by binnythomas-1989** [comment]
@juan131 We had a great call. Seems to be the issue is more around how the loadbalancer, We tried to created http and https connections but it was not successful listening to the ports 8443 and 80. Thanks a lot @mkilchhofer  for your help. Really appreciate the time spent.

**Comment by binnythomas-1989** [comment]
@mkilchhofer  finally managed to make it works. But with this Kubernetes manifest https://raw.githubusercontent.com/projectcontour/contour/release-1.8/examples/render/contour.yaml

There is some issue when I use the helm chart. Now I would have to find the difference after helm templating it
Screenshot 2020-09-17 at 11 32 43

**Pull request merged**
