### PR TITLE
[bitnami/{mariadb/mysql}] Fix for secrets

### PR DESCRIPTION
**Pull request by juan131**
Signed-off-by: juan131 <juanariza@vmware.com>

**Description of the change**

At [this PR](https://github.com/bitnami/charts/pull/4694) I included the changes below so the linter didn't complain:

```diff
  ##
-  customPasswordFiles:
  ## Example:
  ## customPasswordFiles:
+ ##
+ customPasswordFiles:
+   root: ""
+    user: ""
+    replicator: ""
```

That's causing this template to return `false` since `Values.auth.customPasswordFiles` is not an empty object:

```
{{/*
Return true if a secret object should be created for MariaDB
*/}}
{{- define "mariadb.createSecret" -}}
{{- if and (not .Values.auth.existingSecret) (not .Values.auth.customPasswordFiles) }}
    {{- true -}}
{{- else -}}
{{- end -}}
{{- end -}}
```

This PR fixes this issue.

**Benefits**

A secret is created when needed.

**Possible drawbacks**

None

**Checklist**

- [x] Variables are documented in the README.md
- [ x Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Review by marcosbc — APPROVED** [review]
LGTM!

**Review by carrodher — APPROVED** [review]
LGTM

**Comment by shibumi** [comment]
@marcosbc @carrodher  Hi, can you schedule a new release for this? This is a blocker for my deployment right now :D

**Comment by juan131** [comment]
@shibumi we're working on this right now
I'll ping you once the chart is released

**Comment by shibumi** [comment]
@juan131  never mind, I just changed the corresponding line in my production-values file :) but would be cool to have a new release for new users

**Comment by juan131** [comment]
@shibumi new versions released:

```console
$ helm repo update >/dev/null 2>&1
$ helm search repo bitnami/mariadb
NAME                   	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/mariadb        	9.1.4        	10.5.8     	Fast, reliable, scalable, and easy to use open-...
$ helm search repo bitnami/mysql
NAME         	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/mysql	8.2.3        	8.0.22     	Chart to create a Highly available MySQL cluster
```

**Comment by shibumi** [comment]
@juan131  thanks for the notification :)

**Pull request merged**
