### PR TITLE
Adding more flexibility to `usePasswordFile` config, passing directories for password files.

### PR DESCRIPTION
**Pull request by alirezarpi**
### Description of the change

In order to not have the password files hardcoded (`MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD_FILE` and `MONGODB_REPLICA_SET_KEY_FILE`), I've added variables into `values.yaml` and changed templates accordingly.
from now the `auth.passwordFile` can be set to a specific file in a directory whenever `auth.usePasswordFile` is set to `true`.

### Benefits

Adding more flexibility to `usePasswordFile` config

### Possible drawbacks

No drawbacks.

### Applicable issues

No issues related.

### Additional information

use example:

```
auth:
  usePasswordFile: "true"
  passwordFile:
    root: /vault/secrets/root
    replica: /vault/secrets/replica
```

### CODE REVIEW

**Comment by fmulero** [comment]
Hi @alirezarpi, thanks a lot for your contribution

Could you review the content of the PR? I think you included changes in `minio` files by mistake

**Comment by alirezarpi** [comment]
Hi @fmulero, I have fixed the conflicts.

**Comment by fmulero** [comment]
Unfortunately, VMware cannot accept your contribution at this time.

**Comment by joadr** [comment]
> fmulero

This is the strangest reason I've seen for denying a PR. Having this PR accepted would help us using a configmap or something rather than using env vars for setting passwords which is very unsecure. Could you explain further how VMware cannot accept the contribution?

**Comment by alirezarpi** [comment]
@joadr Thank you for your comment, actually I've created a better version of the feature in another PR (https://github.com/bitnami/charts/pull/11320) but still no luck ;)

**Pull request closed without merging**
