### PR TITLE
[bitnami/kafka] Support the service "NodePort" feature "externalIPs" for external access

### LINKED ISSUE #14222: [bitnami/kafka] Support the service "NodePort" feature "externalIPs" for external access
### Name and Version

bitnami/kafka 20.0.2

### What is the problem this feature will solve?

We use the chart in a k3s based setup with `NodePort` and the Kubernetes feature to bind the [service to `externalIPs`](https://kubernetes.io/docs/concepts/services-networking/service/#external-ips). This is currently not supported by the chart https://github.com/bitnami/charts/blob/adfe16ed4f115188104e317c89c72b5801938d63/bitnami/kafka/templates/svc-external-access.yaml - there is no `externalIPs` at all in there. 

### What is the feature you are proposing to solve the problem?

I propose to add a setting  `externalIPs: []` under `externalAccess.service` in the `values.yml` 

- in `bitnami/kafka/templates/svc-external-access.yaml` [after line 57](https://github.com/bitnami/charts/blob/adfe16ed4f115188104e317c89c72b5801938d63/bitnami/kafka/templates/svc-external-access.yaml#L57) 
  - insert a conditional block `{{- if eq $root.Values.externalAccess.service.type "NodePort" }}`, containing:
    - a short documenting comment
    - the line `externalIPs: []`
- in  [`bitnami/kafka/values.yml` after line 689](https://github.com/bitnami/charts/blob/adfe16ed4f115188104e317c89c72b5801938d63/bitnami/kafka/values.yaml#L689) insert 
  - a documenting comment
  - `externalIPs: []`
  
- in [`bitnami/kafka/README.md`  section "Accessing Kafka brokers from outside the cluster" -> "Using NodePort services"](https://github.com/bitnami/charts/blob/main/bitnami/kafka/README.md#using-nodeport-services) add an "option C", explaining the new feature.

### What alternatives have you considered?

I do not think there are alternatives, except not using this chart or forking it..

### PR DESCRIPTION
**Pull request by jensens**
Support the Kubernetes feature to bind the Kafka external access [service to `externalIPs`](https://kubernetes.io/docs/concepts/services-networking/service/#external-ips)

### Description of the change

Adds a new configuration value `externalAccess.service.externalIPs`. 
This is an empty list be default.
If given it must contain a list with same length as `replicaCount`

It updates validation of both, `externalAccess.service.externalIPs` and `externalAccess.service.nodePorts` since one of both is enough now.

Slicing validation improved in template.

### Benefits

Supports now another official Kubernetes feature.
E.g. small clusters with fixed IP's can be built this way.

### Possible drawbacks

A cluster with fixed IPs is needed, if this is not the case the service type loadBalancer need to be used.

### Applicable issues

  - fixes #14222

### Additional information

N/A

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by jensens** [comment]
We will check this with our setup the next days and if all works as expected I am going to mark this as ready for review.

**Comment by jensens** [comment]
This works now on our cluster as expected with different settings using this fork/branch. This is ready for review. I am keen to improve the code or answer any questions.

**Review by aoterolorenzo — APPROVED** [review]
Thanks for the contribution!

**Comment by aoterolorenzo** [comment]
@jensens  could you update the branch? I just have not enough permissions to interact with your fork.

**Comment by jensens** [comment]
Looks like I better start over on a fresh branch after the failed rebase. Sorry for the noise.

**Comment by aoterolorenzo** [comment]
> 

No problem! Let me know if you need any help. I just couldn't interact with your fork because of the permissions.

**Comment by marazt** [comment]
H. I've just found this issue and PR and it is something I really needs to prevent manual chart update. Is there any plan to merge it soon :)? Thanks a lot and good job 👍.

**Comment by aoterolorenzo** [comment]
Hi @marazt,

Seems is taken a little longer than expected, but there is an update from @jensens on https://github.com/bitnami/charts/issues/14222#issuecomment-1404820640.

**Pull request closed without merging**
