### PR TITLE
[bitnami/redis] Fix for NetworkPolicy blocking sentinel metrics exporter

### PR DESCRIPTION
**Pull request by ekampf**
**Description of the change**

When sentinel metrics exporter is enabled and we also use a network policy, we need to allow scraping that port on the network policy.
This fixes the new capability added on PR #4916 

**Benefits**

Allows using sentinel metrics exporter option together with network policy

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

### CODE REVIEW

**Comment by ekampf** [comment]
FYI @miguelaeh @migruiz4 @juan131 as you authored\reviewd the original PR adding the Sentinel Reporter...

**Review by migruiz4 — APPROVED** [review]
Hi @ekampf,

Thank you for reporting and fixing this!

**Review by migruiz4 — CHANGES_REQUESTED** [review]
Sorry, one small change request, could you please use `{{ .Values.sentinel.metrics.service.port }}` instead?

**Comment by ekampf** [comment]
@migruiz4 done!

**Review by migruiz4 — APPROVED** [review]
Awesome!
Thank you for applying the requested change!

**Pull request merged**
