### PR TITLE
[bitnami/sonarqube] Fixed incorrect mapping for jvmOpts and jvmCeOpts.

### PR DESCRIPTION
**Pull request by zenigmadev**
Fixed incorrect mapping for jvmOpts and jvmCeOpts.

jvmOptions for sonarqube plugins were not mapped correctly and causing plugins to work inconsistently. Therefore, the need for changes in helper methods arose.

### Applicable issues

- fixes #

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by chrira** [comment]
Thank you!
I had the same problem. My fix is slightly different: https://github.com/chrira/charts/commit/908b4e62f1a3767a226176653132b5b2f6dc92e9

I found out, that the name of the environment variables are incorrect also.
Readme and values.yaml mention `SONARQUBE_WEB_JVM_OPTS` and `SONAR_CE_JAVAOPTS`. But the deployment gets those environment variables: `SONARQUBE_WEB_JAVA_ADD_OPTS` and `SONAR_CE_JAVAADDITIONALOPTS`.
See https://github.com/bitnami/charts/blob/main/bitnami/sonarqube/templates/deployment.yaml#L298

Do you include the renaming or should I base my fix on top of yours?

**Comment by chrira** [comment]
I created a new PR based on this one: #15806
The new PR (#15806) is compliant to the prerequisites for PR's and updates the documentation.

**Review by aoterolorenzo — APPROVED** [review]
LGTM

**Review by aoterolorenzo — CHANGES_REQUESTED** [review]
Hi @zenigmadev 

The changes seems fine but the branch must be updated first. Could you take a look?

**Comment by aoterolorenzo** [comment]
Duplicated merged and just found in #15806. Closing this.

**Pull request closed without merging**
