### PR TITLE
[bitnami/keycloak] Fix default values for keycloak db secret keys

### PR DESCRIPTION
**Pull request by jbbarth**
### Description of the change

Some default values in the "keycloak" chart template helpers were wrong. Both "port", "user" and "database" were pointing to the "db-port" key.

PS: passing by I had to fix the license for Chart.yaml, as the CI was complaining. It still complains but for files _outside_ the "keycloak" chart, I don't think it's a good idea to fix in this PR.

### Benefits

Better default values.

### Possible drawbacks

None.

### Applicable issues

None.

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your contribution, due to some changes in our test suite it is needed to rebase from main and the update the PR, could you please do that? Thanks beforehand and sorry for the inconvenience.

**Comment by juan131** [comment]
Thanks for the fix @jbbarth ! The changes look good, but please ensure you merge the latest changes in `main` branch in your fork's branch as @carrodher mentioned.

**Comment by carrodher** [comment]
I was able to do the rebase by myself. The PR is ready for review! Thanks

**Review by juan131 — APPROVED** [review]
LGTM

**Pull request merged**
