### PR TITLE
[bitnami/etcd] Fix pvc deletion when trying to restore from snapshot

### PR DESCRIPTION
**Pull request by jaysonsantos**
Signed-off-by: Jayson Reis <santosdosreis@gmail.com>

### Description of the change

If you have enabled disaster recovery, pvcs are created with nfs but, if you run an upgrade to try and restore from a specific file, the template removes the pvc definition, and it gets garbage collected by helm thus making the previously attached pvc invalid.

### Benefits
You can use helm upgrade to start from a snapshot

### Possible drawbacks
I cannot foresee one

### Applicable issues

- maybe helps #11697

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by jaysonsantos** [comment]
given the following changes on values.yaml
```diff
diff --git a/bitnami/etcd/values.yaml b/bitnami/etcd/values.yaml
index 3e07422ba..0cdfc6399 100644
--- a/bitnami/etcd/values.yaml
+++ b/bitnami/etcd/values.yaml
@@ -763,13 +763,13 @@ metrics:
 startFromSnapshot:
   ## @param startFromSnapshot.enabled Initialize new cluster recovering an existing snapshot
   ##
-  enabled: false
+  enabled: true
   ## @param startFromSnapshot.existingClaim Existing PVC containing the etcd snapshot
   ##
   existingClaim: ""
   ## @param startFromSnapshot.snapshotFilename Snapshot filename
   ##
-  snapshotFilename: ""
+  snapshotFilename: "xxx"
 ## Enable auto disaster recovery by periodically snapshotting the keyspace:
 ## - It creates a cronjob to periodically snapshotting the keyspace
 ## - It also creates a ReadWriteMany PVC to store the snapshots
@@ -779,7 +779,7 @@ startFromSnapshot:
 disasterRecovery:
   ## @param disasterRecovery.enabled Enable auto disaster recovery by periodically snapshotting the keyspace
   ##
-  enabled: false
+  enabled: true
   cronjob:
     ## @param disasterRecovery.cronjob.schedule Schedule in Cron format to save snapshots
     ## See https://en.wikipedia.org/wiki/Cron
```

you can see the outcome
```
helm template -f values.yaml . | yq '. | select(.kind == "StatefulSet")' | grep -B1 xxx
                "name": "ETCD_INIT_SNAPSHOT_FILENAME",
                "value": "xxx"
```
```
helm template -f values.yaml . | yq '. | select(.kind == "PersistentVolumeClaim")' | head -n 5
{
  "kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "name": "release-name-etcd-snapshotter",
```

**Review by carrodher — APPROVED** [review]
LGTM, thanks

**Comment by jaysonsantos** [comment]
@carrodher funky thing, my commit had a bump for etcd, but master broke because it says it didn't have a bump. Maybe another etcd PR landed with the same version bump?

**Comment by carrodher** [comment]
It seems https://github.com/bitnami/charts/pull/12269 bumped the chart version to the same number and GitHub didn't detect it as a conflict. I just created https://github.com/bitnami/charts/commit/ae3a7d23ccdf9ae61a4d744dea6eb1cad571d76e in order to release a new version containing both changes.

**Pull request merged**
