### PR TITLE
updated Link to new repo name

### PR DESCRIPTION
**Pull request by exocode**
On my journey exploring this repo I stumbled over a dead link. It seems, that the repo was renamed, this PR fix it with the correct and new one

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Review by exocode — COMMENTED** [review]
I think I had taken the wrong link

**Comment by migruiz4** [comment]
Hi @exocode,

Thank you for fixing the broken link. Your first approach was correct, the link should be `https://github.com/bitnami/charts/tree/master/bitnami/kube-prometheus#tldr`.

The `prometheus-operator` Helm chart was renamed as `kube-prometheus`, and some references weren't changed.

Could you please revert this PR back to https://github.com/bitnami/charts/pull/7051/commits/f379e7583273a2dd4bb42438e98b1538879819e7?

**Comment by migruiz4** [comment]
Also, could you please bump a patch version?

**Comment by exocode** [comment]
> Also, could you please bump a patch version?

I am a noob on openSource and pr. Tried to find the "revert" but it seems I don't have privileges to do that. Had a look here. 
https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request 
But there is no "revert" as described in the github docs.

**Review by carrodher — APPROVED** [review]
I just modified the table to reflect the description present in the values.yaml. Thanks for letting us know and creating the pR

**Comment by carrodher** [comment]
Finished at https://github.com/bitnami/charts/commit/3c81dd58d7d73d832e814e6f88172b9755a7b9bd

**Comment by exocode** [comment]
> I just modified the table to reflect the description present in the values.yaml. Thanks for letting us know and creating the pR

Thank you too :-) 
( have to take some additional git sessions )

**Pull request merged**
