### PR TITLE
[bitnami/harbor] initContainer for certificate vol

### LINKED ISSUE #27321: [bitnami/harbor] Setting `internalTLS.enabled: true` results in all harbor pods going into a crash loop.
### Name and Version

bitnami/harbor 21.4.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Set `internalTLS.enabled: true` and deploy the chart.

### Are you using any custom parameters or values?

A redacted values file follows

```yaml
adminPassword: 'REDACTED'

core:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/spot-worker
                operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: core
              app.kubernetes.io/instance: harbor
              app.kubernetes.io/name: harbor
          topologyKey: kubernetes.io/hostname
  csrfKey: 'REDACTED'
  priorityClassName: system-cluster-critical
  replicaCount: 2
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 80Mi
  secret: 'REDACTED'
  secretKey: 'REDACTED'
  serviceAccountName: harbor
  tolerations:
    - key: nidhogg.uswitch.com/fluent-bit.fluent-bit
      operator: Exists
      effect: NoSchedule

exporter:
  replicaCount: 2
  resources:
    limits:
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 16Mi
  serviceAccountName: harbor

exposureType: ingress

externalDatabase:
  coreDatabase: harbor
  host: 'REDACTED'
  password: 'REDACTED'
  sslmode: require
  user: 'REDACTED'

externalRedis:
  host: 'REDACTED'

externalURL: 'https://harbor.REDACTED'

ingress:
  core:
    hostname: 'harbor.REDACTED'
    pathType: Prefix

internalTLS:
  enabled: true

jobservice:
  jobLogger: database
  replicaCount: 2
  resources:
    limits:
      memory: 48Mi
    requests:
      cpu: 3m
      memory: 32Mi
  secret: 'REDACTED'
  serviceAccountName: harbor

logLevel: info

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

persistence:
  enabled: false
  imageChartStorage:
    disableredirect: true
    s3:
      accesskey: REDACTED
      bucket: REDACTED
      region: ap-southeast-2
      secretkey: REDACTED
    type: s3

portal:
  replicaCount: 2
  resources:
    limits:
      memory: 16Mi
    requests:
      cpu: 2m
      memory: 8Mi
  serviceAccountName: harbor

postgresql:
  enabled: false

redis:
  enabled: false

registry:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/spot-worker
                operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: registry
              app.kubernetes.io/instance: harbor
              app.kubernetes.io/name: harbor
          topologyKey: kubernetes.io/hostname
  controller:
    resources:
      limits:
        memory: 32Mi
      requests:
        cpu: 2m
        memory: 24Mi
  credentials:
    htpasswd: 'REDACTED'
    password: 'REDACTED'
    username: 'REDACTED'
  replicaCount: 2
  secret: 'REDACTED'
  server:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 32Mi
  serviceAccountName: harbor

trivy:
  enabled: false
```

### What is the expected behavior?

Pods should not go into a crash loop.

### What do you see instead?

All pods are in a crash loop.
If you look at logs, all of them say the following before exiting:
```
INFO  ==> Appending internalTLS trust CA cert...
/opt/bitnami/scripts/libharbor.sh: line 102: /etc/ssl/certs/ca-certificates.crt: Permission denied
```

### Additional information

We had the above working with chart version `19.6.0`.
From between then and when we upgraded, container SecurityContexts were defined to lock things down.
All the containers now have a read-only filesystem and no longer run as `root`.
The permissions on the `/etc/ssl/certs/ca-certificates.crt` are it is owned and grouped by `root` and has permissions of `664`.

I was able to get things working by slackening off the container SecurityContexts by setting the following for all of the pods:
```yaml
    containerSecurityContext:
      readOnlyRootFilesystem: false
      runAsGroup: 0
```
This is not ideal though as it reduces the security you added by quite a bit.

### PR DESCRIPTION
**Pull request by jim-barber-he**
### Description of the change

Add an init container to copy the /etc/ssl/certs directory to the ephemeral volume using the same user and group that the main container runs as.
Then mount that volume over the /etc/ssl/certs directory within the main container so that the /etc/ssl/certs/ca-certificates.crt can be updated when internalTLS.enabled is set to true.

### Benefits

Fixes issue https://github.com/bitnami/charts/issues/27321 where all pods go into a crash loop if `internalTLS.enabled: true` is set, due to a lack of permissions to update the `/etc/ssl/certs/ca-certificates.crt` file.

### Applicable issues

- fixes #27321 

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by jim-barber-he** [comment]
The CI/CD error for the `[CI/CD] CI Pipeline / Automatically update README, CRDs and CHANGELOG (pull_request_target)` may be unrelated to my change?
```
remote: Permission to HealthengineAU/bitnami-charts.git denied to bitnami-bot.
fatal: unable to access 'https://github.com/HealthengineAU/bitnami-charts/': The requested URL returned error: 403
Error: Process completed with exit code 128.
```

**Comment by carrodher** [comment]
Thank you for initiating this pull request. We appreciate your effort.
There is automation in charge of automatically updating the README, CRDs and CHANGELOG, to be able to do that, it should commit to the branch from where the PR is created.

Usually, forks allow those commits by default, if there is any restriction in place you need to add @bitnami-bot as a collaborator in the [HealthengineAU/bitnami-charts](https://github.com/HealthengineAU/bitnami-charts) repo

**Comment by jim-barber-he** [comment]
Ok I've asked to add `bitnami-bot` as a collaborator to the repo and it is currently waiting on the invite to be accepted.
image

**Comment by jim-barber-he** [comment]
@carrodher The bitnami bot is still `Pending invite` in my repository. I assume someone who looks after the Bitnami charts repository needs to do something?

**Comment by jim-barber-he** [comment]
The force-push is me rebasing against main again to solve conflicts.

**Comment by jim-barber-he** [comment]
@fmulero They should be good again until another PR beats me and causes a clash with the chart version again :smile:

**Review by fmulero — APPROVED** [review]
Thanks a lot @jim-barber-he 

LGTM

**Pull request merged**
