### PR TITLE
[bitnami/spring-cloud-dataflow] Update dependencies

### PR DESCRIPTION
**Pull request by jotamartos**
### Description of the change

This PR updates the dependencies of the chart

### Applicable issues

- fixes #

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [NA] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by jotamartos** [comment]
We can't merge these changes till the pipeline releases the new version of the solution. That will fix the MariaDB version to 10.11, the solution doesn't work with MariaDB 11.0

**Review by dgomezleon — CHANGES_REQUESTED** [review]
You forgot the upgrade notes.

**Comment by jotamartos** [comment]
> You forgot the upgrade notes.

This chart won't update the MariaDB version. It will continue using 10.11 but as we do with Magento and others, it will use the latest changes of the chart (but the image's version)

**Review by dgomezleon — APPROVED** [review]
LGTM

**Pull request merged**
