### PR TITLE
[bitnami/postgresql] Add pre-init scripts

### PR DESCRIPTION
**Pull request by onichandame**
### Description of the change

This PR brings the possibility to define pre-init scripts in postgresql chart

### Benefits

The order of execution is as follows:
1. pre-init scripts
2. postgresql startup
3. init scripts

There are some tasks that cannot be run in the init scripts. such as copying over some .so files for extensions to work. Without these dynamic libraries the startup would fail, thus blocking the execution of init scripts.

The only way to solve it is to prepare the .so files during pre-init phase.

### Possible drawbacks

Not that I can think of

### Applicable issues

- fixes #
N/A

### Additional information

N/A

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! Could you fix the DCO issue?

**Comment by onichandame** [comment]
> Hi!
> 
> Thank you so much for the PR! Could you fix the DCO issue?

fixed

**Review by rafariossaa — DISMISSED** [review]
Thanks for adding this.
LGTM.

**Comment by onichandame** [comment]
Should I rebase to main?

**Review by rafariossaa — APPROVED** [review]
LGTM

**Pull request merged**
