### PR TITLE
[bitnami/thanos] Compactor cronjob

### PR DESCRIPTION
**Pull request by gjacquet**
### Description of the change

Support running the compactor as a cronjob rather than as a deployment. Compactor supports running as a cronjob. 

### Benefits

Running compactor as a job instead of deployment would allow for more efficient use of resources in Kubernetes as it would be possible to request resources only when the compactor is actively running.

### Possible drawbacks

None as it is still possible to run as a deployment. This new configuration is purely optional.

### Applicable issues

- Fixes https://github.com/bitnami/charts/issues/5509.

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by corico44** [comment]
Hello @gjacquet, could you provide me how you have tested these changes to reproduce it, please?

**Comment by gjacquet** [comment]
@corico44 for this change, I picked 2 of our environments running Thanos and set them up to use the chart with this change.

I configured the first one to use compactor as a cronjob and the second one as a deployment.

Then I ran helm template and compared the new output (with a `git diff`) with what we had previously. Deployment showed no significant difference.

Cronjob change looked fine and I applied it to one of our environment. I checked job log output and it seemed fine, it has been running for nearly a day.

As a reviewer, you might want to compare the new `_pod_template.tpl` with `deployment.yaml` from the main branch. `_pod_template.tpl` is pretty much the pod template from `deployment.yaml` with indentation changes. The idea was that since the pod template is nearly the same for a deployment or a cronjob, it could make sense to move it to a shared template.

**Comment by gjacquet** [comment]
I guess the compactor only makes sense if you are using an object store, in s3 for instance. I have something like this:

```yaml
objstoreConfig: |
        type: S3
        config:
          bucket: "<my s3 bucket>"
          endpoint: "s3.us-west-2.amazonaws.com"
          region: "us-west-3"
          insecure: false
          signature_version2: false
          put_user_metadata: {}
          trace:
            enable: true
```

**Comment by corico44** [comment]
Thank you @gjacquet. Now, I get the following error:
`Error: INSTALLATION FAILED: CronJob.batch "sp-th-thanos-compactor" is invalid: spec.jobTemplate.spec.template.spec.restartPolicy: Required value: valid values: "OnFailure", "Never"`

So, restartPolicy should either have a default value or be no longer required.

**Comment by gjacquet** [comment]
@corico44 thanks for the feedback.
I pushed a change to set a default restart policy if unset.

**Review by corico44 — APPROVED** [review]
LGTM

**Comment by onedr0p** [comment]
@gjacquet if using a cronjob for the compactor is setting any sort of persistence still required?

**Pull request merged**
