### PR TITLE
[bitnami/mongodb] ServiceBinding secrets for custom users 

### LINKED ISSUE #17411: [bitnami/mongodb] serviceBindings not created for custom users
### Name and Version

bitnami/mongodb 13.15.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Helm install with the attached values file

### Are you using any custom parameters or values?

```yaml
architecture: standalone

directoryPerDB: true

useStatefulSet: true

auth:
  rootUser: root
  rootPassword: password
  databases: ["daqconfigdb", "thisone", "and_this"]
  usernames: ["daqconfigdb", "thisone", "and_this"]
  passwords: ["daqconfigdb", "thisone", "and_this"]

serviceBindings:
  enabled: true

persistence:
  enabled: true

metrics:
  enabled: true
  compatibleMode: false # skip old metrics
  username: metrics
  # password:
  collector:
    all: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
  serviceMonitor:
    enabled: true
    labels:
      "prometheus.io/servicemonitor": "dune-metrics"
  prometheusRule: # setup alerting rules here and then enable it
    enabled: false
    rules: []
    additionalLabels:
      "prometheus.io/rule": "dune-metrics"
```

### What is the expected behavior?

Secrets for the service binding should be created:

```shell
kubectl -n mongodb get secret mongodb-svcbind-daqconfigdb
```

### What do you see instead?

```shell
$ kubectl -n mongodb get secrets
NAME                   TYPE                        DATA   AGE
mongodb                Opaque                      3      19m
mongodb-svcbind-root   servicebinding.io/mongodb   8      19m
```

### Additional information

The Secret `mongodb` doesn't appear to have the correct password for the users.

### PR DESCRIPTION
**Pull request by fmulero**
### Description of the change

Initialize users/database/passwords lists  before using it.

### Benefits

With these changes `serviceBinding` secrets will be created for custom users.

### Possible drawbacks

None identified.

### Applicable issues

- fixes #17411

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by jcpunk** [comment]
When I do a local render with the values.yml from the linked issue, the service bindings for custom users are not created.

**Comment by fmulero** [comment]
Hi @jcpunk 

> When I do a local render with the values.yml from the linked issue, the service bindings for custom users are not created.

Are you facing the same issue with this patch?

**Comment by jcpunk** [comment]
I believe the linked PR does not resolve my issue.  My local testing showed the svcbind secrets were not in the rendered templates.

**Comment by fmulero** [comment]
Hi @jcpunk 

These are the steps I followed to test this PR (the content of `../support/charts/17411/mongodb.yaml` is the same content you shared in #17411):

```console
$ gh pr checkout 17463
Switched to branch 'bugfix/mongodb-users-service-binding'
Your branch is up to date with 'origin/bugfix/mongodb-users-service-binding'.
Already up to date.
$ helm dep build bitnami/mongodb
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading common from repo oci://registry-1.docker.io/bitnamicharts
Pulled: registry-1.docker.io/bitnamicharts/common:2.5.0
Digest: sha256:5fa1bf404c5796880bc976568c4e62c91fa96e489bd07970320c2d1d2c6cc37c
Deleting outdated charts
$ helm install mongodb bitnami/mongodb -f ../support/charts/17411/mongodb.yaml 
NAME: mongodb
LAST DEPLOYED: Tue Jul 11 10:48:34 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: mongodb
CHART VERSION: 13.15.5
APP VERSION: 6.0.7

** Please be patient while the chart is being deployed **
...
...
...
$ kubectl get secrets -l app.kubernetes.io/instance=mongodb
NAME                   TYPE                        DATA   AGE
mongodb-svcbind-1      servicebinding.io/mongodb   8      45s
mongodb                Opaque                      3      45s
mongodb-svcbind-0      servicebinding.io/mongodb   8      45s
mongodb-svcbind-2      servicebinding.io/mongodb   8      45s
mongodb-svcbind-root   servicebinding.io/mongodb   8      45s
```

There you can see now 4 service binding secrets, one for root and the rest for the different users:
```console
$ kubectl get secret mongodb-svcbind-0 -o jsonpath={.data.username} | base64 -d
daqconfigdb
$ kubectl get secret mongodb-svcbind-1 -o jsonpath={.data.username} | base64 -d
thisone
$ kubectl get secret mongodb-svcbind-2 -o jsonpath={.data.username} | base64 -d
and_this
```

**Review by rafariossaa — APPROVED** [review]
LGTM

**Comment by jcpunk** [comment]
Ahh I see, I'd expected the svcbind to have the username in the `name` field:

```
[riehecky@leibniz mongodb]$ git log -1
commit 5a56e8962d185b0c7bc15ad480a8009be5bff4b6 (HEAD -> bugfix/mongodb-users-service-binding, origin/bugfix/mongodb-users-service-binding)
Merge: 358330fbc 84b230150
Author: Fran Mulero <fmulero@vmware.com>
Date:   Tue Jul 11 10:59:00 2023 +0200

    Merge remote-tracking branch 'upstream/main' into bugfix/mongodb-users-service-binding
[riehecky@leibniz mongodb]$ helm template mongodb . -f /tmp/bug-17411.yaml |grep mongodb-svcbind-daqconfigdb
```

Having an incrementing integer at the end makes my kubernetes mappings for projects that don't yet support svcbind much more difficult.

Can this patch be adjusted to put the username in the secret name?

**Comment by fmulero** [comment]
Hi @jcpunk, I have mixed feelings about exposing the username in the secret name. I will keep the PR as it is, fixing the current issues but feel free to open a PR with your suggestion, we will be happy to review it.

**Review by migruiz4 — APPROVED** [review]
LGTM

**Pull request merged**
