### PR TITLE
[bitnami/kubernetes-event-exporter]: metrics support

### PR DESCRIPTION
**Pull request by maxime1907**
Signed-off-by: Maxime Leroy <19607336+maxime1907@users.noreply.github.com>

### Description of the change

Add metrics support on port 2112

### Benefits

Expose these metrics:
- events_sent (The total number of events sent)
- events_discarded (The total number of events discarded because of being older than the maxEventAgeSeconds specified)
- watch_errors (The total number of errors received from the informer)
- send_event_errors (The total number of send event errors)

### Possible drawbacks

None

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by marcosbc** [comment]
Hi @maxime1907, there was recently a change in `main` that made an update to the CI pipeline test. Could you rebase your branch with the latest changes and then `git push --force-with-lease`?

**Comment by maxime1907** [comment]
> Hi @maxime1907, there was recently a change in `main` that made an update to the CI pipeline test. Could you rebase your branch with the latest changes and then `git push --force-with-lease`?

Hi @marcosbc, its done!

**Review by marcosbc — APPROVED** [review]
LGTM, thanks!

**Comment by alexfouche** [comment]
FYI the example rule provided as example did not work for me: https://github.com/bitnami/charts/issues/23368
I will provide a merge request

**Pull request merged**
