### PR TITLE
Issue 9040

### PR DESCRIPTION
**Pull request by GrigorievNick**
Fix issue https://github.com/bitnami/charts/issues/9040

**Description of the change**

Fix: take service account name from helm params when specified

**Benefits**

fix a bug

**Possible drawbacks**

No

**Applicable issues**
https://github.com/bitnami/charts/issues/9040

  - fixes 9040

**Additional information**

**Checklist**
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by migruiz4** [comment]
Hi @GrigorievNick,

Could you please update this branch by signing the commits?

The process is simple:

```
git checkout <your_branch>
# Undo commits (Use ~1, ~2, ... depending on the number of commits you want to undo)
git reset --soft HEAD~1 
# Commit again adding '-s'
git commit -s -m "<your_commit_message>"
# Force-push your branch
git push --force
```

**Comment by javsalgar** [comment]
@migruiz4  we need to continue ourselves with the PR as the author cannot work on it.

**Review by migruiz4 — APPROVED** [review]
No further actions are needed. Thank you very much for your contribution!

**Comment by GrigorievNick** [comment]
Thank you, guys, Sorry that I take your time and force you to finish this work.
I just don't have access to my ssh keys and PC in general. Can answer only though email.

**Pull request merged**
