### PR TITLE
[bitnami/postgresql-ha] Fix pgpool deployment init container security context

### PR DESCRIPTION
**Pull request by Stevenpc3**
### Description of the change

Fix pgpool deployment init container security context

### Benefits

Can properly use TLS for pgpool

### Additional information

Current issue is when you enable pgpool.tls.enabled=true it will change securityContext for the init-chmod-container and it injects an extra enabled: true that is not part of the kubernetes api for securityContext https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#securitycontext-v1-core.  In the mildest case this will cause a warning.  In other cases during enforcement, it prevents deployment.

{F2A3B8D1-476E-4A20-8F26-67E6E0B4D2B1}

{13EFDAC7-E689-48D0-81EB-5AF8CA84AC0E}

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your contribution! Could you please bump the chart version in the _Chart.yaml_? This is necessary to test the changes and cut a new release.

**Comment by Stevenpc3** [comment]
yeah sorry.. I added the commit in codespaces, but not sure why it didn't take.  Will update.

**Review by migruiz4 — COMMENTED** [review]
Thank you for your contribution @Stevenpc3!

I have noticed the same issue exists in other templates in the `postgresql-ha` chart, could you please apply the same fix in the `postgresql/statefulset.yaml` and the `postgresql/witness-statefulset.yaml`?

**Comment by Stevenpc3** [comment]
Absolutely.

**Comment by Stevenpc3** [comment]
added

**Comment by Stevenpc3** [comment]
bump

**Review by migruiz4 — APPROVED** [review]
I'm sorry for the late response @Stevenpc3, looks good to me!

**Pull request merged**
