### PR TITLE
[bitnami/external-dns] Major release: drop support for multiple replicas and DaemonSet

### LINKED ISSUE #26682: [bitnami/external-dns] Why bitnami chart allows to modify number of replicas for external dns when external dns does not support multiple replicas
### Name and Version

bitnami/external-dns

### What architecture are you using?

None

### What steps will reproduce the bug?

Bitnami external chart allows to configure number of replicas for external dns when external dns does not support multiple replicas
ref: https://github.com/kubernetes-sigs/external-dns/issues/2430
This impacts multiple things in chart
- Daemonset should not be there
- Pod Disruption Budget should not be enabled by default.
- Deployment strategy. It should be Recreate by default if I am not missing anything.

### What do you see instead?

The chart allows to modify number of replicas for external DNS it also allows to deploy external DNS as a daemonset

### PR DESCRIPTION
**Pull request by migruiz4**
### Description of the change

External DNS does not officially support deploying multiple replicas or DaemonSet architecture, and doing so may cause issues.

References:
- https://github.com/kubernetes-sigs/external-dns/issues/2430
- https://github.com/kubernetes-sigs/external-dns/issues/1089
- [Upstream](https://github.com/kubernetes-sigs/external-dns/blob/v0.14.2/charts/external-dns/templates/deployment.yaml#L14) does not support >1 replicas nor Daemonset 

### Applicable issues

- fixes #26682

### Additional information

Removed values:
- `replicaCount`
- `useDaemonset`
- `revisionHistoryLimit` (DaemonSet-only)
- `podDisruptionBudget` (Previously deprecated in favor of `pdb.*`)
- `metrics.serviceMonitor.additionalLabels` (Previously deprecated in favor of `metrics.serviceMonitor.labels`)

Additionally, I added the missing standard value `metrics.serviceMonitor.annotations`

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by jotamartos — DISMISSED** [review]

**Review by jotamartos — APPROVED** [review]

**Comment by dangmai** [comment]
Hi, not sure why `revisionHistoryLimit` is removed in this PR? As far as I know that's used to determine how many old ReplicaSet that k8s keeps around ([link](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit)), not how many replicas are currently running.
After this PR it will default to `10` and there's no way to customize it.

**Comment by bernermic** [comment]
Hi @migruiz4 and @jotamartos, 
if there can be only one replica of externalDNS wouldn't it make sense to set `pdb.create` to `false` per default?
https://github.com/bitnami/charts/blob/d607a1af7dec0930f5fd730b7de2306ebc936997/bitnami/external-dns/values.yaml#L1203

Thanks for your good work :)

**Comment by bernermic** [comment]
I opened a PR https://github.com/bitnami/charts/pull/27467 which disables the pdb.

**Comment by DrFaust92** [comment]
please rollback the revisionHistoryLimit change 🙏 it is required and unrelated to these changes

**Comment by jetersen** [comment]
Created https://github.com/bitnami/charts/pull/27913 for the `revisionHistoryLimit`

**Pull request merged**
