### PR TITLE
[bitnami/mongodb-sharded]  Add annotation to service

### PR DESCRIPTION
**Pull request by maxisam**
fix missing annotations in service #3695

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

### CODE REVIEW

**Comment by TheHunter** [comment]
Hi everyone,
I'm waiting for this chart update, that fixes the annotation errors.

Could anyone tell when this merge can be done?

Thanks in advance.

**Review by dani8art — CHANGES_REQUESTED** [review]
Hi @maxisam, 

Thank you so much for this PR.

Could you please update the `values.yaml` and the docs and tell there that the annotation value will be handle as a template.

```
  ## Additional service annotations (evaluate as a template)
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  annotations: {}
```

```
| `service.annotations`                         | Kubernetes service annotations (evaluate as a template)                                                                                                                  | `{}`                                                     |

```

**Comment by maxisam** [comment]
I thought they are there already.

doc: https://github.com/maxisam/charts/blob/patch-1/bitnami/mongodb-sharded/README.md

value.yaml: 
https://github.com/maxisam/charts/blob/609d534433394387e2837a8764f9e092651c6d6c/bitnami/mongodb-sharded/values.yaml#L770-L773

**Comment by dani8art** [comment]
Yes, of course, it was more about adding `(evaluate as a template)` this string as it is evaluated as a template we would like the users to know it

**Review by dani8art — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
