### PR TITLE
[bitnami/prometheus-operator] New major version + renaming

### PR DESCRIPTION
**Pull request by juan131**
Signed-off-by: juan131 <juanariza@vmware.com>

**Description of the change**

This PR renames the chart to `bitnami/kube-prometheus` to be more accurate with the actual capabilities of the chart: it does not just deploy the Prometheus operator, it deploys an entire cluster monitoring stack, that includes other components (e.g. NodeExporter or Kube State metrics). Find more information about the reasons behind this decision at [#3490](https://github.com/bitnami/charts/issues/3490).

On the other hand, we introduced changes in the CRDs on this PR (https://github.com/bitnami/charts/pull/3333). Recently, some of the new features included in the new CRDs were added to the chart (see https://github.com/bitnami/charts/pull/3476). This implies a backwards incompatibility when you try to upgrade from previous versions not included these features in the CRDS:

```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Prometheus.spec): unknown field "probeNamespaceSelector" in com.coreos.monitoring.v1.Prometheus.spec, ValidationError(Prometheus.spec): unknown field "probeSelector" in com.coreos.monitoring.v1.Prometheus.spec]
```

That's why I decided to bump the major version and, at the same time, I added bitnami/common library as dependency to simplify the chart.

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

### CODE REVIEW

**Review by carrodher — APPROVED** [review]
LGTM!

**Review by miguelaeh — APPROVED** [review]
LGTM!

**Comment by scottrigby** [comment]
@juan131 are you planning to rename the chart in this PR, per #3490? Are there steps that need to be done (decision from anyone etc) beforehand? If could be done after but would require another MAJOR bump

**Comment by juan131** [comment]
@scottrigby renaming included in the PR

**Pull request merged**
