### PR TITLE
[bitnami/metallb] fix failed-to-call-webhook issue

### LINKED ISSUE #15094: [bitnami/metallb] failed to call webhook 503 Service Unavailable
### Name and Version

bitnami/metallb 4.1.16

### What steps will reproduce the bug?

Install the helm chart with `networkPolicy.enabled: true` on k3s cluster, then apply an `IPAddressPool` resource.

### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

The `IPAddressPool` is created.

### What do you see instead?

```
failed to call webhook: Post "https://metallb-webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-l2advertisement?timeout=10s": proxy error from
│ 127.0.0.1:6443 while dialing 10.42.3.16:9443, code 503: 503 Service Unavailable
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mmianl**
### Applicable issues

- fixes #15094

### Additional information
Related to #15097

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by Mauraza** [comment]
Hi @mmianl,

Thanks for the contribution! Could you share the values are you using when you get the error with webhook?

**Comment by mmianl** [comment]
Sure, here they are:

```yaml
---
rbac:
  create: true
psp:
  create: false
networkPolicy:
  enabled: true
prometheusRule:
  enabled: false

controller:
  image:
    registry: quay.io
    repository: metallb/controller
    tag: "v0.13.9"
    pullPolicy: IfNotPresent
  updateStrategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 0
  rbac:
    create: true
  psp:
    create: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
  serviceAccount:
    create: true
    automountServiceAccountToken: true
  containerPorts:
    metrics: 7472
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  startupProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  metrics:
    enabled: true
    service:
      port: 7472
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7472"
        prometheus.io/path: "/metrics"
    serviceMonitor:
      enabled: true
      namespace: "metallb-system"
      jobLabel: "app.kubernetes.io/name"
      interval: "30s"
      scrapeTimeout: "15s"

speaker:
  image:
    registry: quay.io
    repository: metallb/speaker
    tag: "v0.13.9"
    pullPolicy: IfNotPresent
  updateStrategy:
    type: RollingUpdate
  rbac:
    create: true
  psp:
    create: false
  resources:
    requests:
      cpu: 250m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  serviceAccount:
    create: true
    automountServiceAccountToken: true
  containerPorts:
    metrics: 7472
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  startupProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  metrics:
    enabled: true
    service:
      port: 7472
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7472"
        prometheus.io/path: "/metrics"
    serviceMonitor:
      enabled: true
      namespace: "metallb-system"
      jobLabel: "app.kubernetes.io/name"
      interval: "30s"
      scrapeTimeout: "15s"

```

**Comment by Mauraza** [comment]
Hi @mmianl, 

I'm trying to reproduce the issue but I can't. In the values, I check that you are not using bitnami images. Did you get the same error with bitnami/metallb?

**Comment by mmianl** [comment]
Hi @Mauraza 
I can't test with the bitnami images because they are not available for my platform.

**Comment by mmianl** [comment]
@Mauraza 
Actually, forget what I just said. The same error does indeed occur in a RKE2 environment using `bitnami/metallb-controller` and `bitnami/metallb-speaker` with tag `0.13.7-debian-11-r27`.

**Comment by Mauraza** [comment]
Hi @mmianl,

I think it looks good, cloud you resolve the conflicts?

**Review by Mauraza — APPROVED** [review]
Hi @mmianl,

Thanks again for the contribution! LGTM!

**Pull request merged**
