### PR TITLE
[bitnami/etcd] Reuse etcd jwt token while upgrade

### PR DESCRIPTION
**Pull request by nobiit**
### Description of the change
Reuse JWT Token for Etcd instead of always creating a new one every time you upgrade

### Benefits
Will not cause Recreate statefulset etcd because of changing checksum of JWT token

### Possible drawbacks
None

### Applicable issues
StatefulSet Etcd is always recreated every time upgrade helm

  # - fixes #

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by alemorcuq** [comment]
Thanks for creating this! Why is this creating a new token everytime you upgrade? It should only create a new token if the upgrade changes the secret, but this doesn't always happen, right? Or am I missing something?

**Comment by nobiit** [comment]
Hi @alemorcuq , Please see this file https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/token-secrets.yaml#L1-L14

L1: etcd.token.createSecret -> true (Regardless of whether you are installing or upgrading)
L13: genPrivateKey -> Always generate 1 Privatekey each time it is called

=> Result: It always regenerates the secret token -> It will recreate StatefulSet (https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/statefulset.yaml#L37) -> Users always have downtime/Etcd is always recreated

**Comment by alemorcuq** [comment]
Thank you very much for the explanation and the fix. Could you please resolve the conflicts?

**Comment by nobiit** [comment]
Hey @alemorcuq , Please review the PR again

**Review by alemorcuq — APPROVED** [review]

**Comment by nobiit** [comment]
Thanks @alemorcuq

**Pull request merged**
