### PR TITLE
[bitnami/keycloak] Break reference cycle in ServiceMonitor template

### LINKED ISSUE #12316: keycloak: enabling serviceMonitor breaks helm apply
### Name and Version

bitnami/keycloak 9.8.0

### What steps will reproduce the bug?

Upgrading from keycloak 7.1.14 to 9.8.0, with the serviceMonitor option enabled.

### What do you see instead?

Helm returns `UPGRADE FAILED: create: failed to encode release "keycloak": json: unsupported value: encountered a cycle via map[string]interface {}`.

Isolated it to the single option `metrics.serviceMonitor.enabled`, which when set to true, causes the error. setting it to false works fine.

### PR DESCRIPTION
**Pull request by maxnitze**
### Description of the change

Fix reference cycle in ServiceMonitor template. In #12268 a change was introduced, that merges single endpoints for a service monitor with default values. The default values are part of a parent key of the endpoints, which creates a reference cycle. This cycle is only a problem in `helm upgrade/install`, not in `helm template`.

### Benefits

_Bugfix, see description._

### Possible drawbacks

no limitations known

### Applicable issues

  - fixes #12316

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by marcosbc — APPROVED** [review]
LGTM! Thanks for the fix!

**Review by marcosbc — CHANGES_REQUESTED** [review]
@maxnitze Apparently there is a conflict, which is preventing me from merging these changes. Could you rebase master? I.e. not merge and force-push these changes.

**Comment by maxnitze** [comment]
Hey @marcosbc, so I should rebase and force-push? Or merge and push _regularly_? Sorry, didn't quiet get your comment 🙈

**Comment by maxnitze** [comment]
Hey @marcosbc do you have any idea what is going wrong here? I cannot really see any errors in the log of the check, that failed.

**Comment by maxnitze** [comment]
Hey @FraPazGal,

I just tried to dig around the last commits to the Keycloak chart and saw, that you had similar issues in #12312. Since I rebased to a commit with that PR included, the VIB Verify action fails for this PR.

Do you have any idea what might be wrong here? Thanks in advance!

**Comment by maxnitze** [comment]
As #12423 is also failing, I'd assume there is an issue with the master branch already?

**Comment by marcosbc** [comment]
Hi @maxnitze, I've rebased the branch again, let's see if it succeeds.

If it does not succeed, it's likely that this is breaking the chart. Have you been able to successfully deploy the chart with these changes on your side?

**Comment by marcosbc** [comment]
After many retries, it indeed seems like this PR is causing issues with the charts. When making HTTP requests to keycloak for login we are seeing this error in our test suite:

> Request failed with status code 401

Have you been able to deploy the chart successfully with your changes before?

**Comment by msvechla** [comment]
Can someone take another look at this? We are currently blocked from updating the chart because when service monitors are used the chart can not be installed, see #12316 .

As this PR only adapts the `ServiceMonitor`, it would be unusual to impact keycloak logins. Maybe someone can double-check the CI or post some details error logs from the failing test?

Thanks a lot!

**Comment by msvechla** [comment]
I also just updated our deployment using the chart version from this PR and it works without issues. I tried it both with service monitors enabled and disabled.

**Review by marcosbc — APPROVED** [review]

**Comment by msvechla** [comment]
@marcosbc looks like the release pipeline has similar issues, the new version has not yet been published: https://github.com/bitnami/charts/actions/runs/3141966802/jobs/5105016557

Can you check this one again as well, please?
Thanks a lot for your help

**Comment by maxnitze** [comment]
Hey, sorry for not responding for some time. Was traveling for some time. Thanks a lot for taking care!

**Pull request merged**
