### PR TITLE
[bitnami/tomcat] deployment, statefulset choice

### PR DESCRIPTION
**Pull request by itscaro**
**Description of the change**

Add the possibility to choose statefulset instead of deployment.

```
persistence.enabled == true || persistence.type == "pvc" => deployment + pvc
persistence.enabled == true && persistence.type == "statefulset" && len(existingClaim) == 0 => statefulset + svc-headless
```

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by alvneiayu** [comment]
hi @itscaro 

First of all, thanks for the request and the time spent to do it.

I need to request you something in your changes. The patch looks good to me but to have some consistence with other charts, I need to request you to change the property "persistence.type" to "deployment.type" (as other charts in upstream) or another option is to use the property "useStatefulset" (mongodb chart). Feel free to choose the best one.

Thanks again. Let me know if I can help you with something else.

Álvaro

**Review by alvneiayu — CHANGES_REQUESTED** [review]
To change the property from "persistence.type" to "deployment.type" (same as other charts in upstream) or to use useStatefulset (as we do in mongoDB chart)

**Comment by itscaro** [comment]
@alvneiayu Thank you for the review, I would like to go for `deployment.type` but I couldn't find any example. Could you give me one please?

**Review by alvneiayu — APPROVED** [review]
LGTM

**Comment by alvneiayu** [comment]
hi @itscaro 

Really good job. Thanks a lot for the PR and sorry, I didn't answer you before.

Thanks a lot again

Álvaro

**Comment by itscaro** [comment]
Hi @alvneiayu, do you have any idea why two latest versions of tomcat are not published?

**Comment by alvneiayu** [comment]
hi @itscaro 

I am checking internally. Please, I will come back with some feedback soon.

Thanks

Álvaro

**Pull request merged**
