### PR TITLE
[bitnami/thanos] thanos/receive/ingress.yaml: support custom portName on extraHosts

### PR DESCRIPTION
**Pull request by oliverisaac**
### Description of the change

The receive service has two ports, `http` and `remote`. This should be specifiable using the `.portName` attribute on extraHosts

### Benefits

It is currently not possible to specify multiple hosts for the receive port.

### Possible drawbacks

None, this is backwards compatible. 

### Applicable issues

- fixes #

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

**Comment by oliverisaac** [comment]
Thanks @carrodher , I've updated my commits!

**Comment by rovangju** [comment]
Yes, I need this!

**Comment by corico44** [comment]
Hello @oliverisaac,

Thank you so much for opening this PR. Could you tell me how you tested this change, please?

**Comment by rovangju** [comment]
Unstale-ify.

**Comment by rovangju** [comment]
stalebump

**Review by corico44 — APPROVED** [review]
LGTM

**Pull request merged**
