### PR TITLE
[bitnami/fluentd] feat: allow setting `hostNetwork` and `dnsPolicy` for forwarder

### LINKED ISSUE #12156: [bitnami/fluentd] allow option to set `hostNetwork` and `dnsPolicy` for forwarder deployment
### Name and Version

bitnami/fluend 5.3.4

### What is the problem this feature will solve?

https://aws.amazon.com/blogs/containers/capturing-logs-at-scale-with-fluent-bit-and-amazon-eks/ from this article, I want to allow using the `Use_Kubelet` config for fluent-bit to avoid overloading the kube API server. However, that requires setting the `hostNetwork` and `dnsPolicy` (see https://docs.fluentbit.io/manual/pipeline/filters/kubernetes/).

I am aware that the chart is mainly for fluentd. However, because of the way it was written, it can be easily reused for fluent-bit (was able to successfully deploy a fluent-bit forwarder with fluentd aggregator setup).

I am happy to make and test the changes myself if this is approved.

### What is the feature you are proposing to solve the problem?

Allow setting the `hostNetwork` and `dnsPolicy` for custom forwarders

### What alternatives have you considered?

n/a

### PR DESCRIPTION
**Pull request by PJHRobles**
Signed-off-by: Paul Joshua Robles <joshuahrobles@gmail.com>

### Description of the change
This allows setting `hostNetwork` and `dnsPolicy` for forwarder daemonset. The change is backwards-compatible.

### Benefits

This will allow custom forwarders such as fluent-bit to set the mentioned values. The values are necessary in order to query the kubelet which should reduce the load on the kube API server (see [article](https://aws.amazon.com/blogs/containers/capturing-logs-at-scale-with-fluent-bit-and-amazon-eks/) for more info).

### Possible drawbacks

n/a

### Applicable issues

Closes #12156

### Additional information

Manually tested with the following scenarios:
- [X] default values for `hostNetwork` and `dnsPolicy` (backwards compatibility working)
- [X] default values for `hostNetwork` and `dnsPolicy` with `forwarder.rbac.pspEnabled`
- [X] update values for `hostNetwork` (set to true) and `dnsPolicy` (set to `ClusterFirstWithHostNet`)
- [X] update values for `hostNetwork` (set to true) and `dnsPolicy` (set to `ClusterFirstWithHostNet`) with `forwarder.rbac.pspEnabled`

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by javsalgar — APPROVED** [review]
LGTM! Thanks!

**Comment by PJHRobles** [comment]
#12213 if I understood the problem correct, #12214 should fix the issue

**Comment by PJHRobles** [comment]
From #12214:
> As I already commented in #12213, this does not seem to be related to the tests but to an issue that affected the charts some time ago (see #11828).
> 
> The values used in `vib-verify` change the port the **Service** exposes, but not the Fluentd port itself. Moreover, the `targetPort` defaults to the port named`http`, which is indeed set to `9880`

Any chance we can merge this? Thanks!

**Comment by javsalgar** [comment]
I've click on retry the jobs, because if it does not succeed, the publish process will fail in another action

**Comment by javsalgar** [comment]
The tests are failing because of one goss test

```
command:
  # The Chart is configured to keep track of the logs in the /var/log/containers directory. Creating a log file
  # should trigger the Forwarder to send the contents to the Aggregator.
  #
  # The integration can be verified as the Forwarder pods have access to the logs of every pod in the cluster, so
  # we check that the Aggregator is aware of the newly created file.
  {{ with (printf "test-%s.log" (randAlpha 5)) }}
  forward-aggregator-integration:
    exec: "cd /var/log/containers && echo '{\"time\": \"2022-07-29T11:33:47.408955753Z\", \"data\": \"zwiebel\"}' > {{.}} && sleep 65 && find . -name \"*fluentd-0*\" -exec tail {} \\;"
    exit-status: 0
    stdout:
      - {{.}}
    timeout: 75000
  {{end}}
```

@joancafom  is looking into it

**Comment by joancafom** [comment]
Hi! After some time debugging this I have come to what I think is the root issue.

The tests are designed to verify the integration between _forwarders_ and _aggregators_. In order to do that, it executes the following steps in a _forwarder_ pod:

1.  Create a new log file in a path that *forwarders* are configured to track.
2. The _forwarder_ notices the new file and sends info about it to the _aggregator_.
3. If the _aggregator_ has correctly received the information, a new entry appears in its log. This log is checked for the new entry.

The _forwarder_-_aggregator_ integration can be easily verified as _forwarders_ have access to the logs of the rest of the pods executing *within the same node*.

#### Problem
Nevertheless, this might be problematic for clusters with more than one node, as we should *carefully select the forwarder pod that shares the same aggregator node to have access to its logs*. If the test is executed in a _forwarder_ pod that is not running in the same node, it will report a *failure* as the new entry can not be found.

We have not faced this kind of error in the past with this test, maybe due to a combination of both luck and timing.

#### Solution
I will adapt the verify stage to enforce the provisioning of a cluster with a number of `nodes=1`, ensuring then that _forwarders_ and _aggregators_ pods are scheduled on the same node and then solving the possible issue.

**Review by joancafom — APPROVED** [review]

**Pull request merged**
