### PR TITLE
[bitnami/harbor] Unset updateStrategy.rollingUpdate by default

### LINKED ISSUE #9515: [bitnami/harbor] rollingUpdate may not be specified when strategy `type` is 'Recreate'
### Name and Version

bitnami/harbor 12.1.3

### What steps will reproduce the bug?

Installing the bitnami/harbor chart with `jobservice.updateStrategy.type` set to `Recreate` causes the following error in Kubernetes:

```shell
The Deployment "foo-harbor-jobservice" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

This is because `rollingUpdate` is set to `{}` [here](https://github.com/bitnami/charts/blob/5b159a70ec71d4a59280be1cdb8091660502e51e/bitnami/harbor/values.yaml#L1627) and the entire `jobservice.updateStrategy` [is included in the template](https://github.com/bitnami/charts/blob/5b159a70ec71d4a59280be1cdb8091660502e51e/bitnami/harbor/templates/jobservice/jobservice-dpl.yaml#L20). It would be a much better user experience if `rollingUpdate` was only included if `type=RollingUpdate`.

## MWE

Here's a minimal "working" example of this bug:
 
```shell
helm template foo bitnami/harbor --version 12.1.3 --set 'jobservice.updateStrategy.type=Recreate' | grep '# Source: harbor/templates/jobservice/jobservice-dpl.yaml' -A 123 | kubectl apply --dry-run=server -f -
```

### Are you using any custom parameters or values?

`--set 'jobservice.updateStrategy.type=Recreate'`

(this ought to be true for all `*.updateStrategy.type` fields, but I have only tried it on `jobservice`)

### What is the expected behavior?

Setting `*.updateStrategy.type=Recreate` should be valid without having to do other things to make sure it works.

### What do you see instead?

The Kubernetes server returns the following error:

```
The Deployment "foo-harbor-jobservice" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

## Workaround

This problem can be worked around by setting `jobservice.updateStrategy.rollingUpdate=null`

## `helm version`

```shell
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

## `kubectl version`

```shell
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-17T03:51:50Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by lindhe**
`rollingUpdate: {}` is not compatible with `type: Recreate` – setting `type: Recreate` will give the following error:

    spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'

The Kubernetes API specification says this about strategy.rollingUpdate:

> Present only if DeploymentStrategyType = RollingUpdate.

https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/#DeploymentStrategy

Signed-off-by: Andreas Lindhé <andreas@lindhe.io>
Co-authored-by: Simon Alling <alling.simon@gmail.com>

**Applicable issues**

  - fixes #9515

**Additional information**

Suggested instead of #9529

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the PR!
The metadata present in the values.yaml is used to generate the table with the parameters that appear in the README. If this parameter is removed from the values, the metadata should be removed as well. Then, the README should be regenerated by using https://github.com/bitnami-labs/readme-generator-for-helm

**Comment by lindhe** [comment]
@carrodher  Thanks for clarifying that! Do you prefer that we set `rollingUpdate` to `null` or that we remove it? They are equivalent actions, just a matter of preference.

**Comment by lindhe** [comment]
The commit I just pushed removes the docs. If we want to keep the parameter and documentation, and just set the parameter value to `null` instead, just say so and I'll push anew.

**Comment by carrodher** [comment]
Thanks for the changes, I just rebased from master and fixed some conflicts.
Apart from that, @javsalgar can you please take a look at this PR? Thanks

**Review by carrodher — APPROVED** [review]
LGTM

**Pull request merged**
