### PR TITLE
[bitnami/zookeeper] Introduced .Release.Namespace in objects meta

### PR DESCRIPTION
**Pull request by mandreasik**
**Description of the change**

This PR adds .Release.Namespace to objects meta. Similar to #2159 or #2156 

**Benefits**

Ability to use the helm chart when having declarative definition of all cluster objects rendered using helm template, for example in tools like Spinnaker.

**Possible drawbacks**

none

**Applicable issues**

#2006 

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by dani8art** [comment]
This is not needed, `namespace` is added automatically to the manifest yaml by kubernetes. 

```bash
$ helm install z bitnami/zookeeper
```

```bash
$ kubectl get pod z-zookeeper-0 -o jsonpath={.metadata.namespace}
# default
```

```bash
$ helm install z bitnami/zookeeper -n darteaga
```

```bash
$ kubectl get pod z-zookeeper-0 -o jsonpath={.metadata.namespace} -n darteaga
# darteaga
```

**Comment by mandreasik** [comment]
@dani8art 
Please read this issue, as mentioned in PR: #2006 

@miguelaeh
The version was bumped accordingly to similiar PRs already merged into this repository: #2159 #2156

**Comment by dani8art** [comment]
Waiting for CI/CD

**Comment by mandreasik** [comment]
@dani8art thx :crossed_fingers:

**Pull request merged**
