### PR TITLE
fix: add annotations to volumeClaimTemplates for MySQL

### PR DESCRIPTION
**Pull request by askhalil**
Currently, the chart doesn't add `annotations` from values to the statefulset `volumeClaimTemplates` so I made the changes needed for them to be added.

### CODE REVIEW

**Review by marcosbc — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by marcosbc** [comment]
@askhalil Could you fix the conflicts for this repo? I tried to fix them but lack privileges. You could also enable [Allow edits from maintainers](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) if you prefer.

**Comment by askhalil** [comment]
@marcosbc I have rebased the branch to the latest master so now there are no conflicts

**Comment by marcosbc** [comment]
Thanks! Merging

**Pull request merged**
