### PR TITLE
[bitnami/harbor] Escape | in Values parameter docs

### PR DESCRIPTION
**Pull request by lindhe**
Signed-off-by: Andreas Lindhé <andreas@lindhe.io>

**Description of the change**

There were some pipes in the Values parameter descriptions which were not escaped, which breaks the table rendering in Markdown. This PR fixes this.

Broken formatting of Markdown table

https://artifacthub.io/packages/helm/bitnami/harbor/12.1.0

**Benefits**

Markdown renders correctly.

**Possible drawbacks**

None.

**Applicable issues**

  - related to #9465

**Additional information**

I'd recommend using [markdownlint](https://github.com/DavidAnson/markdownlint) to identify Markdown issues before merging. :) Can this be done after rendering the README? I don't think it's easy to lint the `@param` decorators in `values.yaml`...

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by lindhe** [comment]
1. I bumped the chart version now, since there's technically changes in `values.yaml`. Good?
2. I have not rerendered the README. Should I do that, or is that automated elsewhere?

**Review by carrodher — APPROVED** [review]
Changes LGTM!

> 1. I bumped the chart version now, since there's technically changes in `values.yaml`. Good?
> 2. I have not rerendered the README. Should I do that, or is that automated elsewhere?

It's automated but in a different step, the PR should be manually updated in order to contain the rendered README, otherwise, the README will be updated in the next release performed by our test & release pipeline.

**Comment by rafariossaa** [comment]
Hi,
  You need to add the README.md file. You can use [this tool](https://github.com/bitnami-labs/readme-generator-for-helm/) to generate it from what is the `values.yaml`.

**Comment by lindhe** [comment]
I probably have a bad `npm` version (as per always :/ ). What version do I need?

Screenshot from 2022-03-22 10-28-18

**Comment by lindhe** [comment]
There seems to be some changes to the README not introduced by me. I'll commit those as a separate commit in case you don't want them as part of this PR.

**Review by carrodher — APPROVED** [review]
LGTM, thanks

**Pull request merged**
