### PR TITLE
Runtime class support

### PR DESCRIPTION
**Pull request by mikelsid**
### Benefits

Possibility to specify runtime classes, which is extremely useful for environments with multiple runtime classes enabled

### Possible drawbacks

Some charts might not be compatible with some certain runtime classes

### Applicable issues

  - fixes #10682 

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
HI!

Thank you so much for the PR! I'm afraid that our publishing automations don't allow PRs that affect more than one chart. Do you mind creating multiple PRs instead? You can use the `gh` command line tool https://cli.github.com/manual/gh_pr_create to split and create multiple PRs.

**Comment by mikelsid** [comment]
@javsalgar Sure! But this will lead to a huge number of PR's :) Is it ok?

**Comment by javsalgar** [comment]
That's perfectly fine!

**Comment by mikelsid** [comment]
Closing this one, since new PRs are created

**Pull request closed without merging**
