### PR TITLE
[bitnami/moodle] add optional custom storage class

### PR DESCRIPTION
**Pull request by chrissav**
**Description of the change**

This adds a new parameter `persistence.customStorageClass` to optionally create a custom storage class with the moodle release.  It uses the existing `persistence.storageClass` parameter as the name because that's used by the common chart to set the storage class within the PVC, and these values should match.

**Benefits**

This is useful when using the [aws-efs-csi-driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver).  To connect the EFS volume to the PVC it requires a storage class.  

**Possible drawbacks**

This is adding a new kubernetes resource to the chart but doesn't effect any existing resources or the default deployment.  I also only tested this with the EFS provisioner.

**Applicable issues**

**Additional information**

Tested this with the following persistence settings in a values.yaml:
```
persistence:
  enabled: true
  storageClass: "efs-storage-test"

  customStorageClass:
    provisioner: efs.csi.aws.com
    parameters:
      provisioningMode: efs-ap
      fileSystemId: fs-xxxxxxxx
      directoryPerms: "777"
      gidRangeStart: "100" # optional
      gidRangeEnd: "2000" # optional
      basePath: "/dev"
```

The efs-csi-driver was able to create a PV and the directory for `/dev` and mounted to the moodle pod as expected.

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Comment by randradas** [comment]
Hi @chrissav thank you for your PR! :D. Let me test it in our internal CI/CD system

**Comment by chrissav** [comment]
Hi @randradas anything I can do to help move this forward?  thanks!

**Comment by randradas** [comment]
everything looks good @chrissav! thank you!

**Comment by randradas** [comment]
could check the conflicts please? once done I merge the changes.

**Comment by chrissav** [comment]
@randradas resolved the conflicts.  thank you!

**Pull request merged**
