### PR TITLE
[bitnami/external-dns] Fix Cloudflare existing secret

### PR DESCRIPTION
**Pull request by miguelaeh**
**Description of the change**
We are taking care of https://github.com/bitnami/charts/pull/2132

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by lukasmrtvy** [comment]
when we can expect merge/release? thanks

**Comment by miguelaeh** [comment]
Hi @lukasmrtvy ,
We needed to wait until our CI/CD updates the tags in the images

**Comment by lukasmrtvy** [comment]
@miguelaeh 
seems its not working as expected..
For example:
```
helm template bitnami/external-dns \
--generate-name \
--namespace external-dns \
--set cloudflare.proxied=false \
--set cloudflare.email=aaaa@aaaa.aaaa \
--set cloudflare.secretName=aaaa \
--set provider=cloudflare
```

It will not populate https://github.com/bitnami/charts/blob/master/bitnami/external-dns/templates/deployment.yaml#L273 section

**Comment by miguelaeh** [comment]
Hi @lukasmrtvy 
yes, you are right, there is a `{{end}}` in the wrong position because the email should be set always.  I created a new PR fixing that.

**Pull request merged**
