### PR TITLE
[bitnami/mlflow] MLflow --no-serve-artifacts

### LINKED ISSUE #20892: MLflow --no-serve-artifacts
### Name and Version

bitnami/mlflow:0.2.3

### What is the problem this feature will solve?

The MLflow template chart currently uses the [--serve-artifacts](https://mlflow.org/docs/latest/cli.html#cmdoption-mlflow-server-serve-artifacts) feature on the server. On the [MLflow documentation](https://mlflow.org/docs/latest/tracking.html) this is described as [Scenario 5](https://mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access):
> MLflow Tracking Server enabled with proxied artifact storage access

<details><summary>Scenario 5</summary>
<p>

> MLflow’s Tracking Server supports utilizing the host as a proxy server for operations involving artifacts. Once configured with the appropriate access requirements, an administrator can start the tracking server to enable assumed-role operations involving the saving, loading, or listing of model artifacts, images, documents, and files. This eliminates the need to allow end users to have direct path access to a remote object store (e.g., s3, adls, gcs, hdfs) for artifact handling and eliminates the need for an end-user to provide access credentials to interact with an underlying object store.

image

</p>
</details> 

This means that client doesn't require permissions to access the Artifact storage (like the S3 backend) - and instead those objects are served over HTTP. 

Unfortunately this deployment method doesn't support our use case, we are more interested in [Scenario 4](https://mlflow.org/docs/latest/tracking.html#scenario-4-mlflow-with-remote-tracking-server-backend-and-artifact-stores):
> MLflow with remote Tracking Server, backend and artifact stores

<details><summary>Scenario 4</summary>
<p>

> MLflow also supports distributed architectures, where the tracking server, backend store, and artifact store reside on remote hosts. This example scenario depicts an architecture with a remote MLflow Tracking Server, a Postgres database for backend entity storage, and an S3 bucket for artifact storage.

image

</p>
</details>

In scenario 4 the MLflow tracking server informs the client where the artifacts are located on the S3 remote host and the client itself fetches the artifacts directly from S3. This is nice for a couple of reasons:

1. Performance - we are working with extremely large artifacts - these artifacts are large enough that the tracking server can struggle to handle the serving over HTTP. Relying on the client to handle this improves performance and allows us to only allocate limited resources to the tracking server.
2. Security - relying on both the Client and server to have permissions to the S3 backend resolves some concerns of our security team. 

### What is the feature you are proposing to solve the problem?

The feature I'm suggesting is a feature-flag on the `values.yaml` that would make the `--serve-artifacts` argument optional on the underlying template https://github.com/bitnami/charts/blob/b65f50c0d3853f784c620b629d268ef783f2b33c/bitnami/mlflow/templates/tracking/deployment.yaml#L141-L147

Using (an optional) `--no-serve-artifacts` alongside [--default-artifact-root](https://mlflow.org/docs/latest/cli.html#cmdoption-mlflow-server-default-artifact-root) would make this Chart compatible with both scenarios listed above. 

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by juftin**
### Description of the change

This PR adds a new option, `.Values.externalS3.serveArtifacts`, to enable artifact streaming from an S3 bucket. 

This is described as [Scenario 4](https://mlflow.org/docs/latest/tracking.html#scenario-4-mlflow-with-remote-tracking-server-backend-and-artifact-stores) on the MLflow documentation:
> MLflow with remote Tracking Server, backend and artifact stores

<details><summary>Scenario 4</summary>
<p>

> MLflow also supports distributed architectures, where the tracking server, backend store, and artifact store reside on remote hosts. This example scenario depicts an architecture with a remote MLflow Tracking Server, a Postgres database for backend entity storage, and an S3 bucket for artifact storage.

image

</p>
</details>

Resolves #20892 

### Benefits

Performance improvements and resolving security concerns - see #20892

### Possible drawbacks

Disabling artifact serving means that both the server and client require S3 permissions

### Applicable issues

- Fixers #20892

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by juftin** [comment]
I'm continuing to test this locally but here is an initial screenshot confirming this is working:

<details><summary>Screenshot</summary>
<p>

image

</p>
</details> 

<details><summary>values.yaml</summary>
<p>

```yaml
tracking:
  replicaCount: 1
  metrics:
    enabled: false
  auth:
    enabled: true
    username: admin
  ingress:
    enabled: true
    pathType: ImplementationSpecific
    hostname: xxxxxxxxxx.com
    ingressClassName: nginx
    path: /
  persistence:
    enabled: false
minio:
  enabled: false
externalS3:
  bucket: xxxxxxxxxxxxx
  host: s3.us-east-1.amazonaws.com
  serveArtifacts: false
postgresql:
  auth:
    username: mlflow
    database: mlflow
run:
  enabled: false
```

</p>
</details> 

<details><summary>Command</summary>
<p>

```shell
mlflow server \
  --backend-store-uri=postgresql://mlflow:$(MLFLOW_DATABASE_PASSWORD)@mlflow-postgresql:5432/mlflow \
  --artifacts-destination=s3://xxxxxxxxxxxxx \
  --default-artifact-root=s3://xxxxxxxxxxxxx \
  --no-serve-artifacts \
  --host=0.0.0.0 \
  --port=5000 \
  --app-name=basic-auth
```

</p>
</details>

**Comment by bhack** [comment]
Are we going to support also GCS?

**Comment by aoterolorenzo** [comment]
Hi @juftin ,

Seems a Cypress test is failing. Any change, even working in local, can end up in a test break (maybe because of having mutated some behavior or UI elements). You can see the cypress tests [here](https://github.com/bitnami/charts/tree/main/.vib/mlflow). Notice that the tests are executed with [this  runtime-parameters.yaml](https://github.com/bitnami/charts/blob/main/.vib/mlflow/runtime-parameters.yaml). So any change in this PR has to be taken into account both in the runtime-parameters as in the tests theirselves.

GCS feature would be also welcome, IMO.

**Comment by bhack** [comment]
@aoterolorenzo While testing this I found another unrelated error about installing/removing/re-installing MLflow chart. I suspect it is related to https://github.com/helm/helm/issues/5156.
We are going to have`no topology key found on CSINode` and it only work if you are going to manually remove the PVC (PV) created by the MLflow chart (see also https://github.com/bitnami/charts/issues/19367#issuecomment-1727914886).

**Comment by juftin** [comment]
> Hi @juftin ,
> 
> Seems a Cypress test is failing. Any change, even working in local, can end up in a test break (maybe because of having mutated some behavior or UI elements). You can see the cypress tests [here](https://github.com/bitnami/charts/tree/main/.vib/mlflow). Notice that the tests are executed with [this runtime-parameters.yaml](https://github.com/bitnami/charts/blob/main/.vib/mlflow/runtime-parameters.yaml). So any change in this PR has to be taken into account both in the runtime-parameters as in the tests theirselves.
> 
> GCS feature would be also welcome, IMO.

Hmm, this is a hard one to debug. Not having any experience in Cypress I wouldn't know how to run that locally and the [CI/CD job](https://github.com/bitnami/charts/actions/runs/6846979118/job/18614436916?pr=20895) didn't output any details about the error. FWIW, the change from this PR didn't change any default behavior and nothing in the runtime parameters would've used these changes - they're purely for the external s3 functionality which isn't enabled by the params.  Maybe this is just a flaky test? If someone could get me some error details I'd be happy to dig further.

**Review by rafariossaa — APPROVED** [review]
Thanks for adding this.
LGTM

**Pull request merged**
