### PR TITLE
[bitnami/postgresql-ha] Adds custom service labels

### LINKED ISSUE #4230: [bitnami/postgresql-ha] pgpool-service is missing component-label
**Which chart**:
postgresql-ha

**Is your feature request related to a problem? Please describe.**
We need to find the pgpool-service using labels but the label app.kubernetes.io/component is not present on the pgpool-service. Neither is any other label available which uniquely identifies the service.

**Describe the solution you'd like**
Add a lable similar to the label added to the postgresql-service, e.g. app.kubernetes.io/component: postgresql

**Describe alternatives you've considered**
Another possibility would be to add a parameter "pgpool.serviceLabels" which than can be rendered into the service-template.

### PR DESCRIPTION
**Pull request by rafariossaa**
**Description of the change**

Add support for custom labels for the services.

**Benefits**

The chart user can now configure this.

**Possible drawbacks**

**Applicable issues**

  - fixes #4230

**Additional information**

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Review by dani8art — CHANGES_REQUESTED** [review]
Hi @rafariossaa thanks for the PR

Could we add it as part of the service values?

`service.extraLabels` or `postgresql.service.*`, `pgpool.service.*`?

I think we are doing this way in other charts. Thanks!

**Comment by marcosbc** [comment]
Adding from @stoetti:

> (...) is there a reason that the pgpool-service is not getting the 'component'-label as it is assigned for the postgresql-service itself?

**Comment by stoetti** [comment]
@rafariossaa 
any update on this one

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the long delay. I have just update fixing what @dani8art suggested.

**Comment by stoetti** [comment]
> Hi,
> Sorry for the long delay. I have just update fixing what @dani8art suggested.

The postgresql-service contains a fixed label "app.kubernetes.io/component=postgresql" why does the pgpool-service not have a label "app.kubernetes.io/component=pgpool" by default?

**Comment by rafariossaa** [comment]
Hi @stoetti ,
 Thanks for spotting that, I am adding it to the PR

**Pull request merged**
