### PR TITLE
[bitnami/kubernetes-event-exporter] Add PDB

### PR DESCRIPTION
**Pull request by tommyzli**
### Description of the change

Optionally create a pod disruption budget in the kubernetes-event-exporter chart. To take effect, the forwarder resource needs to be in HA mode (replicaCount > 1) and the pdb has to be explicitly enabled. This way, the default installation does not result in a single undisruptable pod.

### Benefits

PDBs are generally useful for services with availability requirements.

### Applicable issues

- fixes #

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by tommyzli** [comment]
hi @alemorcuq, this change is ready for review

**Comment by alemorcuq** [comment]
Hi @tommyzli. We are in the process of standardizing our PDBs. I'll assign this to @fmulero who is leading that effort.

**Review by fmulero — APPROVED** [review]
Thanks a lot @tommyzli for your contribution!!

I've  just pushed these [changes](https://github.com/bitnami/charts/pull/26145/commits/319609f907a46e33dd3662dd1905e04adf0a7d65) to align this PR with our latest approach about PDBs. We are currently working on it and the template you used is not fully updated, sorry about this.

Please share any doubt or thought, we will be happy to help.

**Comment by tommyzli** [comment]
@fmulero [this](https://github.com/bitnami/charts/pull/26145/commits/319609f907a46e33dd3662dd1905e04adf0a7d65#diff-62098d7b1c9ba9e6a4b48dfe91aa838f825dc1393961ce1f36eb720bc0c269dfR20) is very clever! thank you

**Pull request merged**
