### PR TITLE
[bitnami/argo-cd] Fix application-controller repo-server

### LINKED ISSUE #7173: [bitnami/argo-cd] repo-server configuration error
https://github.com/bitnami/charts/blob/4e6c20d5d5eac90caf257feb516a669854aac0bc/bitnami/argo-cd/templates/application-controller/deployment.yaml#L128

This place may be configured incorrectly

`- {{ include "argocd.repo-server" . }}:{{ .Values.repoServer.service.port }}`

### PR DESCRIPTION
**Pull request by gongyho**
**Description of the change**

Fix application-controller repo-server configuration problem

**Benefits**

**Possible drawbacks**
None

**Applicable issues**

  - fixes #7173 

**Additional information**

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Review by javsalgar — COMMENTED** [review]
Thank you! Could you bump the patch version?

**Comment by gongyho** [comment]
Ok. I upgraded the version.

**Comment by making** [comment]
I was about to send the same pull request 😅
https://github.com/bitnami/charts/compare/master...making:patch-2

**Comment by gongyho** [comment]
Will unlimited redirection occur when you use ingress TLS?
I'm at annotations add `nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"` solved.
I don't know if you also have such a question.

**Comment by making** [comment]
I'm using Contour for ingress.
Here's how I got it working. It works for both browser and cli.

```yaml
cat <<EOF > values.yaml
server:
  service:
    annotations:
      projectcontour.io/upstream-protocol.h2c: https,443 
  ingress:
    enabled: true
    hostname: ${ARGO_CD_HOSTNAME}
    tls: true
    selfSigned: true
  ingressGrpc:
    enabled: true
    hostname: ${ARGO_CD_GRPC_HOSTNAME}
    tls: true
    selfSigned: true    
  insecure: true
redis:
  replica:
    replicaCount: 1
EOF

#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind":"Ingress", "metadata": {"name": "argo-cd-server"}})
---
spec:
  rules:
  #@overlay/match by=overlay.all
  - http:
      paths:
      #@overlay/match by=overlay.all
      - backend:
          service:
            port: 
              name: http
#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata": {"name": "argo-cd-app-controller"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: controller
        args:
        #@overlay/match by=overlay.index(9)
        - argo-cd-repo-server:8081
EOF

cat <<EOF > post-render.sh
#!/bin/bash
ytt -f - -f overlay.yaml
EOF
chmod +x post-render.sh

helm install argo-cd --create-namespace -n argo-cd bitnami/argo-cd --values values.yaml --post-renderer ./post-render.sh --wait
```

**Review by migruiz4 — APPROVED** [review]
Looks good to me!

**Pull request merged**
