### PR TITLE
[bitnami/nats] Fix readiness probe endpoint (#24360)

### LINKED ISSUE #24360: [bitnami/nats] readiness check on wrong endpoint
### Name and Version

bitnami/nats 7.18.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

On my setup with 3 nats instances using Jetstream, one of the instances was restarted. Once nats had started, the pod instantly became ready. However, Jetstream hadn't fully synced yet so my clients connected to a non-ready nats instance 1/3rd of the time. I think this is due to the fact that the wrong endpoint of the monitoring port is probed for readiness.

Currently, the `/` is probed for readiness, which means that as soon as nats has started and exposes the monitoring port (in the chart this is 8222), the pod is considered ready. However, my pod wasn't ready to take traffic because jetstream hadn't fully synced yet. The monitoring service has a "Health probe" on `/healthz` which showed me something like `{"status":"not ok", "error": "JetStream stream '$G > my-stream' is not current"}` (I didn't clip the exact output) and gave a `503 - Service unavailable`. After a while, when jetstream _was_ synced, the output became `{"status":"ok"}` and gave a `200` status.

I think we should update the chart to use `/healthz` as path for the readiness probe instead (or at least make it configurable).

### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

Pod becomes ready once its health check succeeds

### What do you see instead?

Pod instantly becomes ready.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by skoef**
### Description of the change

By probing the `/healthz` endpoint instead of `/` on the Nats monitoring port, the pods only become ready once they are in fact ok, instead of right away after startup. This improves restarts where for instance Jetstream needs to recover first. 

### Benefits

Restarts only progress once Nats pods are actually ready instead of once Nats has started up and starts listening on the monitoring port

### Possible drawbacks

Deployments that used to rollout a restart quite quick may take longer to progress.

### Applicable issues

- fixes #24360 

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by skoef** [comment]
@fevisera could you review this MR before it becomes conflicted again?

**Comment by fevisera** [comment]
Hi @skoef,

Sorry for the delay. Since you are modifying the deployment template, you need to bump a minor version in [Chart.yaml](https://github.com/bitnami/charts/blob/main/bitnami/nats/Chart.yaml#L34). Could you please bump the version?

Thanks!

**Comment by skoef** [comment]
@fevisera you're absolutely right, forgot about that! It's taken care of now!

**Comment by fevisera** [comment]
Hi @skoef,

Sorry, I mistyped the version kind. We are bumping patch since no new feature is being implemented. I have corrected it.

**Review by fevisera — APPROVED** [review]
LGTM!

**Pull request merged**
