### PR TITLE
[bitnami/apache]: Allow git clone again whenever rollout

### PR DESCRIPTION
**Pull request by cuttingedge1109**
Fix https://github.com/bitnami/charts/issues/9546

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi! 

Thank you for the PR! Could you bump the chart.yaml version?

**Comment by javsalgar** [comment]
It seems that the PR was created during the outage of Github actions and now the actions are not being executed. Could you try recreating the PR or updating it to see if the actions get executed?

**Comment by cuttingedge1109** [comment]
> It seems that the PR was created during the outage of Github actions and now the actions are not being executed. Could you try recreating the PR or updating it to see if the actions get executed?

@javsalgar I just recreated a new PR. https://github.com/bitnami/charts/pull/9580

**Comment by rafariossaa** [comment]
Hi,
  Thanks, the new PR will be reviewed and merged.

**Pull request closed without merging**
