### PR TITLE
[bitnami/zookeeper] ServiceMonitor does not discover prometheus target

### PR DESCRIPTION
**Pull request by mandreasik**
**Description of the change**

I've found a bug in metrics service. Due to this issue prometheus drops zookeeper target because of missing label. 

[ServiceMonitor](https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/templates/servicemonitor.yaml#L18) use following selector:
` selector:
    matchLabels: {{- include "zookeeper.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: zookeeper`

but [metrics-svc](https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/templates/metrics-svc.yaml#L7) has only following labels:
` labels: {{- include "zookeeper.labels" . | nindent 4 }}`

This PR adds missing label 

> app.kubernetes.io/component: zookeeper

to [metrics-svc.yaml](https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/templates/metrics-svc.yaml#L7)

**Benefits**

Prometheus will discover zookeeper target properly

**Possible drawbacks**

none

**Applicable issues**

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by juan131** [comment]
Waiting for CI/CD to run tests and update image tags

**Comment by mandreasik** [comment]
@juan131I did helm pull  bitnami/zookeeper. And even though I have newest file zookeeper-5.12.1.tgz this chart does not contain my changes (even though they were merged). Also from my PR disappeared version bump in file Chart.yaml.

Could you please check what's going on?

**Comment by dani8art** [comment]
The changes should be there, I did `helm fetch bitnami/zookeeper` and I can see the changes.

**Comment by mandreasik** [comment]
@dani8art weirdly I can also see changes. Maybe there was some lag in chart publish (I do not know how bitnami does this process and when). Anyways thanks for checking.

**Comment by dani8art** [comment]
yw! thank you for the notification we will check for some issues.

**Pull request merged**
