### PR TITLE
[bitnami/redis-sentinel] Add preExec to start-node.sh

### PR DESCRIPTION
**Pull request by MichaelHudgins**
**Description of the change:**
Added `slave.preExecCmds` into start-node.sh

**Benefits**
start-node.sh currently launches with many of the slave options of the chart.  It is missing the ability to inject preExecCmds.  This allows custom code that in the case of #4970 makes it easier to inject code required enable istio mtls.
**Possible drawbacks**
The only drawback i can think of is if someone had the slave.preExecCmds filled out with sentinel enabled already it would begin injecting the commands into start-node.sh.  This seems an unlikely edge case as this value appears unused if sentinel is enabled but it is the reason for the semvar bump that i did.
**Applicable issues**
additional fix to #4970 

**Checklist**

- [x]  Chart version bumped in Chart.yaml according to semver.
- [x]  Variables are documented in the README.md
- [x]  Title of the PR starts with chart name (e.g. [bitnami/chart])
- [x]  If the chart contains a values-production.yaml apart from values.yaml, ensure that you implement the changes in both files

### CODE REVIEW

**Review by miguelaeh — COMMENTED** [review]
Hi @MichaelHudgins ,
Thank you very much for the PR!
About the version, since this seems to be a fix for a wrong feature I would just bump the patch.

**Comment by MichaelHudgins** [comment]
@miguelaeh Version updated.

**Comment by dani8art** [comment]
Sorry, could you rebase master in order to resolve these conflicts?

**Comment by MichaelHudgins** [comment]
@dani8art Chart version updated to fix conflict

**Review by dani8art — APPROVED** [review]
LGTM!

**Pull request merged**
