### PR TITLE
[bitnami/kubernetes-event-exporter] Avoid unnecessary pod restart on each helm chart version

### PR DESCRIPTION
**Pull request by jkroepke**
### Description of the change

This PR changes the the input of the config checksum which triggers the reload.

On main branch, the whole configmap/secret checksum is included as checksum input. The configmap contains labels which includes the helm chart version. Each new helm chart version forces a pod restart which is not always necessary.

### Benefits

Avoid unnecessary pod restart on each new helm chart version

### Possible drawbacks

N/A

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by FraPazGal** [comment]
Hi @jkroepke, the changes look fine to me but it seems our CI is having some issues. I'll prefer to merge this with the CI green so let us move this to `on-hold` while we work on https://github.com/bitnami/charts/pull/21431 and come back to you once this bug is solved. Sorry for the inconvenience!

**Comment by FraPazGal** [comment]
The issue has now been solved and the PR https://github.com/bitnami/charts/pull/21431 merged, could you please update this PR with the changes in `main`? The CI should run without issues after that.

**Comment by jkroepke** [comment]
@FraPazGal done!

**Comment by jkroepke** [comment]
@FraPazGal please re-chck!

**Review by FraPazGal — APPROVED** [review]
LGTM! Thanks @jkroepke!

**Pull request merged**
