### PR TITLE
[bitnami/etcd] added persistentVolumeClaimRetentionPolicy control to statefulset spec

### PR DESCRIPTION
**Pull request by JamesTGrant**
### Description of the change

Kubernetes 1.23 adds statefulset pvc retention control (in alpha):
https://kubernetes.io/blog/2021/12/16/kubernetes-1-23-statefulset-pvc-auto-deletion/#the-new-statefulset-pvc-retention-policy
This change adds these optional parameters to the statefulset spec, controlled via values in values.yaml

### Possible drawbacks

You must enable the StatefulSetAutoDeletePVC [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) to use this field.

### Applicable issues

  - fixes #

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

**Comment by JamesTGrant** [comment]
> Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

**Comment by JamesTGrant** [comment]
@carrodher - Thank you, it is done!

**Comment by JamesTGrant** [comment]
@carrodher I see the verfiy pipeline has failed: (line 43) Error: Task provisioning has failed. Error: An error occurred invoking TMC API to provision the cluster. Error code: 400 https://github.com/bitnami/charts/runs/6351623983?check_suite_focus=true  don't think this is related to any changes I've made?

**Review by rafariossaa — APPROVED** [review]
Thank you very much for adding this.
LGTM.

**Pull request merged**
