### PR TITLE
bitnami/zookeeper: remove zookeeper-exporter pod from zookeeper service

### PR DESCRIPTION
**Pull request by wuzhihui1123**
service of x-zookeeper and x-zookeeper-headless must not contains the pod of zookeeper-exporter

### CODE REVIEW

**Comment by tompizmor** [comment]
@wuzhihui1123 can you bump the patch chart version in the [Chart.yaml](https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/Chart.yaml#L3) file? 

At this moment the version is `1.5.0` so update it to `1.5.1` please.

**Comment by srueg** [comment]
Any progress on this? I'll gladly take over, if help is needed.

**Comment by tompizmor** [comment]
@wuzhihui1123 do you think you will have time to work on this PR soon?

**Comment by tompizmor** [comment]
The PR https://github.com/bitnami/charts/pull/1144 that implements these same changes has been already merged so I am closing this PR.

**Pull request closed without merging**
