### PR TITLE
[bitnami/netbox] Introuce new Netbox Chart [WiP]

### PR DESCRIPTION
**Pull request by MaxRink**
This adds a Chart for Netbox. As currently no bitnami Image for netbox exists this is using upstream Netbox images.

**Benefits**

This adds Netbox, an very popular IPAM Tool, to the Bitnami charts
This still needs a bitnami Image and then some integration work and rebasing.
**Possible drawbacks**

More Applications to maintain

**Applicable issues**

  - as discussed in #5397 

**Checklist** 
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ ] rebase
- [ ] Integration of Bitnami Image

### CODE REVIEW

**Comment by marcosbc** [comment]
Awesome contribution! I'm adding the `on-hold` label while we review this PR and start working on the Docker image. Unfortunately I cannot give an ETA at this moment.

**Comment by cstisa** [comment]
Hi all, still no ETA for the support of NetBox ?

**Comment by marcosbc** [comment]
Hi @cstisa, as the container image is not yet part of the Bitnami catalog at this moment, we need to analyze this request.  Unfortunately I cannot give an ETA for when that will happen.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!

**Pull request closed without merging**
