### PR TITLE
update hpa.yaml

### PR DESCRIPTION
**Pull request by mike38**
### Description of the change

call for common.capabilities.hpa.apiVersion  need to provide context as parameter

### Benefits

You can activate hpa in the chart, if not the template is not rendered properly

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by aoterolorenzo** [comment]
Hi @mike38 ,

Could you explain the motivation behind this change? We have implemented the same practice in all charts, with no issues reported:

`apiVersion: {{ include "common.capabilities.vpa.apiVersion" . }}`

**Comment by mike38** [comment]
for hpa.yaml without the change the template is failing. I did the same change for vpa.yaml, bit maybe it is not necessary there? I was blocked when using hpa, not vpa.

**Comment by mike38** [comment]
I just removed the modification for vpa.yaml, if you can accept the PR for hpa. Thanks

**Review by aoterolorenzo — APPROVED** [review]

**Comment by aoterolorenzo** [comment]
Merged! Sorry for the waiting! Special days behind, thanks for the contribution!

**Pull request merged**
