### PR TITLE
[bitnami/redis-cluster] Get the external IP from -svc suffixed services

### LINKED ISSUE #17687: [bitnami/redis-cluster] Can not get $SERVICE_IP when externalAccess.enabled=true
### Name and Version

bitnami/redis-cluster 8.6.7

### What architecture are you using?

amd64

### What steps will reproduce the bug?

```
helm install beta . \
	--dependency-update \
	--set password=somerandompassword \
	-n infra-redis-cluster
```
also set externalAccess.enabled: true in values.yaml
```
export REDIS_PASSWORD=xxx
helm upgrade beta . \
	--namespace infra-redis-cluster \
	--set password=$REDIS_PASSWORD \
	--set "cluster.externalAccess.enabled=true,\
cluster.externalAccess.service.type=LoadBalancer,\
cluster.externalAccess.service.loadBalancerIP[0]=20....2,\
cluster.externalAccess.service.loadBalancerIP[1]=20...8,\
cluster.externalAccess.service.loadBalancerIP[2]=20...\
cluster.externalAccess.service.loadBalancerIP[3]=20...,\
cluster.externalAccess.service.loadBalancerIP[4]=20...,\
cluster.externalAccess.service.loadBalancerIP[5]=20..." 
```
### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

redis-cluster README says:
```
To connect to your Redis&reg; server from outside the cluster check the following information:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace infra-redis-cluster -w beta-redis-cluster'

    You will have a different external IP for each Redis&reg; node. Get the external ip from `-external` suffixed services: `kubectl get svc`.
    Redis&reg; port: 6379INFO: The Job to create the cluster will be created.To connect to your database from outside the cluster execute the following commands:

    export SERVICE_IP=$(kubectl get svc --namespace infra-redis-cluster beta-redis-cluster --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
    redis-cli -c -h $SERVICE_IP -p 6379 -a $REDIS_PASSWORD
```
but _kubectl get svc --namespace infra-redis-cluster -w beta-redis-cluster_  nor kubectl get svc --namespace infra-redis-cluster beta-redis-cluster --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}" never return anything useful.

### What do you see instead?
```
$ kubectl get svc --namespace infra-redis-cluster -w beta-redis-cluster
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
beta-redis-cluster   ClusterIP   10.x.1.27    <none>        6379/TCP   3h48m

$ kubectl get svc --namespace infra-redis-cluster beta-redis-cluster --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}"
Error executing template: template: output:1:10: executing "output" at <index .status.loadBalancer.ingress 0>: error calling index: index of untyped nil. Printing more information for debugging the template:
	template was:
		{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}
	raw data was:
		{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"meta.helm.sh/release-name":"beta","meta.helm.sh/release-namespace":"infra-redis-cluster"},"creationTimestamp":"2023-07-13T10:43:25Z","labels":{"app.kubernetes.io/instance":"beta","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"redis-cluster","helm.sh/chart":"redis-cluster-8.6.7"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:meta.helm.sh/release-name":{},"f:meta.helm.sh/release-namespace":{}},"f:labels":{".":{},"f:app.kubernetes.io/instance":{},"f:app.kubernetes.io/managed-by":{},"f:app.kubernetes.io/name":{},"f:helm.sh/chart":{}}},"f:spec":{"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":6379,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}},"manager":"helm","operation":"Update","time":"2023-07-13T10:43:25Z"}],"name":"beta-redis-cluster","namespace":"infra-redis-cluster","resourceVersion":"1517896915","uid":"83748e67-616b-4e30-b1d8-e9cdfaddbfe3"},"spec":{"clusterIP":"10.8.1.27","clusterIPs":["10.8.1.27"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"tcp-redis","port":6379,"protocol":"TCP","targetPort":"tcp-redis"}],"selector":{"app.kubernetes.io/instance":"beta","app.kubernetes.io/name":"redis-cluster"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
	object given to template engine was:
		map[apiVersion:v1 kind:Service metadata:map[annotations:map[meta.helm.sh/release-name:beta meta.helm.sh/release-namespace:infra-redis-cluster] creationTimestamp:2023-07-13T10:43:25Z labels:map[app.kubernetes.io/instance:beta app.kubernetes.io/managed-by:Helm app.kubernetes.io/name:redis-cluster helm.sh/chart:redis-cluster-8.6.7] managedFields:[map[apiVersion:v1 fieldsType:FieldsV1 fieldsV1:map[f:metadata:map[f:annotations:map[.:map[] f:meta.helm.sh/release-name:map[] f:meta.helm.sh/release-namespace:map[]] f:labels:map[.:map[] f:app.kubernetes.io/instance:map[] f:app.kubernetes.io/managed-by:map[] f:app.kubernetes.io/name:map[] f:helm.sh/chart:map[]]] f:spec:map[f:internalTrafficPolicy:map[] f:ports:map[.:map[] k:{"port":6379,"protocol":"TCP"}:map[.:map[] f:name:map[] f:port:map[] f:protocol:map[] f:targetPort:map[]]] f:selector:map[] f:sessionAffinity:map[] f:type:map[]]] manager:helm operation:Update time:2023-07-13T10:43:25Z]] name:beta-redis-cluster namespace:infra-redis-cluster resourceVersion:1517896915 uid:83748e67-616b-4e30-b1d8-e9cdfaddbfe3] spec:map[clusterIP:10.8.1.27 clusterIPs:[10.8.1.27] internalTrafficPolicy:Cluster ipFamilies:[IPv4] ipFamilyPolicy:SingleStack ports:[map[name:tcp-redis port:6379 protocol:TCP targetPort:tcp-redis]] selector:map[app.kubernetes.io/instance:beta app.kubernetes.io/name:redis-cluster] sessionAffinity:None type:ClusterIP] status:map[loadBalancer:map[]]]

error: error executing template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}": template: output:1:10: executing "output" at <index .status.loadBalancer.ingress 0>: error calling index: index of untyped nil
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by vladsf**
### Description of the change

- fixes #17687 

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by vladsf** [comment]
Alternatively I may collect all nodes into array of IPs - `kubectl get svc --namespace infra-redis-cluster -o jsonpath="{.items[*].spec.loadBalancerIP}"`

**Comment by vladsf** [comment]
Ok, fixed sign-off issues.

**Review by corico44 — APPROVED** [review]
LGTM

**Review by fmulero — APPROVED** [review]
LGTM

**Pull request merged**
