### PR TITLE
bitnami/thanos: Remove replica count if HPA is enabled on Thanos Query and Query Front-End

### PR DESCRIPTION
**Pull request by eltalkarim**
According to the HPA [documentation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#flapping), an HPA takes control of `spec.replicas` field of the deployment if it's enabled. So its better to remove it from the deployment if the HPA is taking care of it.

**Description of the change**
Making use of the `Values.query.autoscaling.enabled` flag to remove `spec.replicas`  in case HPA is enabled.

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

Could you check the errors in the checks?

**Comment by eltalkarim** [comment]
> Hi,
> 
> Thanks for the PR! Could you check the errors in the GH action?

Hello,

The errors are handled, can you check my pull request?

**Comment by javsalgar** [comment]
Hi!

Could you merge from master again? It seems that there are commits behind

**Review by javsalgar — DISMISSED** [review]

**Comment by javsalgar** [comment]
It seems that something went wrong with the merge, as it is affecting multiple files. Could you check it?

**Comment by eltalkarim** [comment]
I am going to close this PR and open a new one

**Pull request closed without merging**
