### PR TITLE
[harbor] Add support for providing own root CA

### PR DESCRIPTION
**Pull request by paulczar**
This is a port of the upstream commit found here[1]

[1] https://github.com/goharbor/harbor-helm/commit/782a05418a79d4bc997f03224d0948a462f6b7e4

Signed-off-by: Paul Czarkowski <username.taken@gmail.com>

### CODE REVIEW

**Comment by paulczar** [comment]
HOLD until https://github.com/bitnami/charts/issues/3486

**Comment by carrodher** [comment]
Adding the `/on-hold` label to prevent the stale bot closing the PR

**Comment by andresbono** [comment]
Hi @paulczar, we have implemented the changes in the images and we have released a new version of the `bitnami/harbor` chart:
`[bitnami/harbor] Release 7.2.2 updating components versions` https://github.com/bitnami/charts/commit/f7d7cad8108618ae86e4ccdcb6587fc65c6159cd

Could you please rebase this PR from master and check it everything works as expected for you? Thanks!

**Comment by andresbono** [comment]
Hi again @paulczar, did you have a chance to test the new container images?

`[bitnami/harbor] Release 7.2.2 updating components versions` https://github.com/bitnami/charts/commit/f7d7cad8108618ae86e4ccdcb6587fc65c6159cd

**Pull request merged**
