### PR TITLE
Revert "[bitnami/redis] feat: :lock: Enable networkPolicy"

### PR DESCRIPTION
**Pull request by onedr0p**
https://github.com/bitnami/charts/issues/22934
https://github.com/bitnami/charts/issues/22922
https://github.com/bitnami/charts/pull/22738#issuecomment-1917502517

Reverts bitnami/charts#22738

### CODE REVIEW

**Comment by carrodher** [comment]
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

**Comment by javsalgar** [comment]
Please check if this PR fixes the issue and therefore we do not need to perform the revert https://github.com/bitnami/charts/pull/22955

**Comment by onedr0p** [comment]
@javsalgar did you read all the issues I linked in the description? The issue is not only netpol related.

**Comment by javsalgar** [comment]
Added the metrics port fix here as well  https://github.com/bitnami/charts/pull/22955

**Pull request closed without merging**
