### PR TITLE
[bitnami/chart] Avoid crash when clone/sync git repository

### LINKED ISSUE #6018: [bitnami/airflow] How to avoid  pod restart cause by sync-repositories container sporadic network error
**Which chart**:
bitnami/airflow 2.0.1 (all version should exists this issue)

**Describe the bug**
Sync-repositories container sometimes will encounter network cause synchronize code failed, so that the related pod(airflow-worker/airflow-web/airflow-scheduler) will restart. 
This will greatly affect my work. the airflow web page cannot be opened during restart, and the logs stored on the work will disappear.

**To Reproduce**

**Expected behavior**
Given a parameter to configuration git sync max sync failures just like `kubernetes/git-sync` image `--max-sync-failures` parameter, and support retry forever after the initial sync.  
This will be very useful for users with bad internet

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1", GitCommit:"2cbb16c", GitTreeState:"", BuildDate:"2021-01-27T02:20:04Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I don’t know if it will be work to directly use `kubernetes/git-sync` instead of `bitnami/git`

### PR DESCRIPTION
**Pull request by izhangzhihao**
**Description of the change**

We encountered this error:

```
$ kubectl get pod

airflow-postgresql-0                      1/1     Running            0          32h
airflow-redis-master-0                    1/1     Running            0          32h
airflow-scheduler-6c4bd6775c-7c7m4        2/2     Running            4          32h
airflow-web-67cf848d67-zmkh6              2/2     Running            42         32h
airflow-worker-0                          1/2     CrashLoopBackOff   328        29h
airflow-worker-1                          2/2     Running            28         29h
```

The log shows:

```
$ kubectl logs  -f airflow-worker-0 -c sync-repositories
From https://github.com/username/repo
 * branch            master     -> FETCH_HEAD
Already up to date.
fatal: unable to access 'https://github.com/username/repo.git/': Could not resolve host: github.com
```

This PR add ` || true` at the end of the git command to avoid airflow worker crash caused by temporary network reason.

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #6018

**Additional information**

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by izhangzhihao** [comment]
Related to https://github.com/bitnami/charts/issues/6018

**Review by miguelaeh — COMMENTED** [review]
Hi @izhangzhihao ,
Thank you very much for the PR!
I just have one question about the PR, would it be possible that this causes an unexpected deployment? I mean, I think this could lead to a deployment where you will not see your repos cloned right? So, it would be possible that the chart is deployed by no repos are cloned. Do you think that will be the expected behavior?

**Comment by izhangzhihao** [comment]
Well, good question. 

Current behavior:

1. clone git repo failed
2. pod restart
3. log lost
4. user could not see the logs and don't know what's wrong
5. result: hard to find out the reason


After this or:

1. clone git repo failed
2. pod still there
3. check logs
4. find out why and fix it
5. we are all happy with that.

**Review by miguelaeh — APPROVED** [review]
Hi @izhangzhihao ,
Thank you for answering the question, I agree leaving the pod running with the logs is easier to debug in case you can't see the repo after deploying it.
LGTM!

**Pull request merged**
