### PR TITLE
MetalLB: add configuration example (helm install different)

### PR DESCRIPTION
**Pull request by CSRedRat**
Example from documentation not working

**Description of the change**

Add example configmap for 

**Benefits**

Working documentation

**Additional information**

Official MetalLB documentation not working for metallb from bitnami chart.

### CODE REVIEW

**Review by juan131 — CHANGES_REQUESTED** [review]
We have already documentation about how to use a custom configuration:

- https://github.com/bitnami/charts/tree/master/bitnami/metallb#configuration-and-installation-details

Shouldn't that be enough?

**Comment by CSRedRat** [comment]
@juan131 it not include impotent info about configmap name & namespace to apply metallb config. Bitnami chart has different name configmap and namespace compare official deployment documentation and will not work with metallb website manual, but bitnami haven't correct deploy configmap instruction. I add this PR after select working onfigmap with bitnami helm chart.

**Comment by FraPazGal** [comment]
Hi @CSRedRat,

Using the `configInline ` parameter will create a configmap with `config` as the data key in the same way your example will. The only differences are that we are not using the same configMap name, which our `deployment.yaml` takes into account, and that we are not specifying the `default` namespace as the used one. This last difference should not be important as all of this charts resources are deployed in the `default` namespace. 

Beside those differences, the L2 configuration should be fairly similar and you should be able to use the official documentation as guide. If you are having issues with the deployment, could you paste here or in an associated issue the steps you followed to deploy the chart?

**Comment by worldofgeese** [comment]
Actually, @CSRedRat is correct. It was a terrible bug report (apologies) but this chart is actually broken as is.

Please forgive the Terraform HCL but given the following declaration:
```
resource "helm_release" "metallb" {
  name             = "metallb"
  repository       = "https://charts.bitnami.com/bitnami"
  chart            = "metallb"
  namespace        = "metallb-system"
  create_namespace = true

  set {
    name  = "configInline.address-pools.name"
    value = "default"
  }

  set {
    name  = "configInline.address-pools.protocol"
    value = "layer2"
  }

  set {
    name  = "configInline.address-pools.addresses"
    value = "$IP_RANGE_BEGIN-$IP_RANGE_END"
  }
}
```
MetalLB deploys but remains unaware of a configmap, logging `not processing, still waiting for config`. I assume this is a naming issue since I can confirm my configmap looks good:
```
address-pools:
- name: default
  protocol: layer2
  addresses:
  - $IP_RANGE_BEGIN-$IP_RANGE_END
```

This same configmap works with a straight manifest method of installation, as written in the metallb docs.

To reproduce fire up an nginx pod `kubectl run nginx --image nginx`, then expose `kubectl expose pod nginx --port 80 --type LoadBalancer` and watch it pend forever.

**Comment by juan131** [comment]
Hi @worldofgeese 

Sorry I'm not familiar with Terraform HCL. Is that the equivalent to the command below?

```bash
helm install metallb bitnami/metallb \
    --namespace metallb-system \
    --set configInline.address-pools.name=default \
    --set configInline.address-pools.protocol=layer2 \
    --set configInline.address-pools.addresses=$IP_RANGE_BEGIN-$IP_RANGE_END
```

Shouldn't that be sth like this:

```
helm install metallb bitnami/metallb \
    --namespace metallb-system \
    --set configInline.address-pools[0].name=default \
    --set configInline.address-pools[0].protocol=layer2 \
    --set configInline.address-pools[0].addresses[0]=$IP_RANGE_BEGIN-$IP_RANGE_END
```

**Comment by worldofgeese** [comment]
@juan131 It is, yes

I don't think so: the first invocation you posted is equivalent to what I have running with MetalLB's own manifests and that's working for me.

**Comment by CSRedRat** [comment]
Now metallb-configmap.yml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: metallb-config
data:
  config: |
      address-pools:
      - addresses:
        - 192.168.1.100-192.168.88.110
        name: default
        protocol: layer2
```
kubectl apply -f metallb-configmap.yml

**Comment by juan131** [comment]
> the first invocation you posted is equivalent to what I have running with MetalLB's own manifests and that's working for me.

@worldofgeese that's very weird. I mean, unless you treat arrays as arrays, objects as objects, etc. It's quite impossible that the generated configmap follows the right structure for this configuration.

Did you also experience the error @CSRedRat ? Or are you sharing your solution?

**Comment by worldofgeese** [comment]
@juan131 Here's what ConfigMap `config` looks like for me using the default metallb manifests:
```
address-pools:
- name: default
  protocol: layer2
  addresses:
  - 161.97.114.250-161.97.114.255
```

```
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{"config":"address-pools:\n- name: default\n 
      protocol: layer2\n  addresses:\n  -
      161.97.114.250-161.97.114.255\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"config","namespace":"metallb-system"}}
```

And it's working perfectly

**Comment by juan131** [comment]
Yes, that configmap looks good.

I'm just surprised, because of this test I did cloning the repo:

- Using your approach:

```console
$ helm template metallb bitnami/metallb \
    --namespace metallb-system \
    --set configInline.address-pools.name=default \
    --set configInline.address-pools.protocol=layer2 \
    --set configInline.address-pools.addresses=192.168.1.100-192.168.88.110 \
    -s templates/controller/configmap.yaml
---
# Source: metallb/templates/controller/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-config
  labels:
    app.kubernetes.io/name: metallb
    helm.sh/chart: metallb-2.2.1
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/managed-by: Helm
data:
  config: |
    address-pools:
      addresses: 192.168.1.100-192.168.88.110
      name: default
      protocol: layer2
```

- Using arrays:

```console
$ helm template metallb bitnami/metallb \
    --namespace metallb-system \
    --set configInline.address-pools[0].name=default \
    --set configInline.address-pools[0].protocol=layer2 \
    --set configInline.address-pools[0].addresses[0]=192.168.1.100-192.168.88.110 \
    -s templates/controller/configmap.yaml
---
# Source: metallb/templates/controller/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-config
  labels:
    app.kubernetes.io/name: metallb
    helm.sh/chart: metallb-2.2.1
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/managed-by: Helm
data:
  config: |
    address-pools:
    - addresses:
      - 192.168.1.100-192.168.88.110
      name: default
      protocol: layer2
```

**Pull request closed without merging**
