### PR TITLE
[bitnami/rabbitmq]  Fix typo in svc-headless.yaml

### PR DESCRIPTION
**Pull request by sebastien-helbert**
fix typo issue #4305 added #4243

### CODE REVIEW

**Review by alemorcuq — CHANGES_REQUESTED** [review]
Thanks for this. Can you also make the change on the `svc.yaml` file and increase the version in `Chart.yaml`?

**Comment by sebastien-helbert** [comment]
@alemorcuq. I'm confused. Linter says : 

```
Old chart version: 8.0.1
New chart version: 8.0.1
------------------------------------------------------------------------------------------------------------------------
 ✖︎ rabbitmq => (version: "8.0.1", path: "bitnami/rabbitmq") > Chart version not ok. Needs a version bump!
```

versions seems to be matching ?

**Comment by alemorcuq** [comment]
> @alemorcuq. I'm confused. Tests fails with :
> 
> ```
> Old chart version: 8.0.1
> New chart version: 8.0.1
> ------------------------------------------------------------------------------------------------------------------------
>  ✖︎ rabbitmq => (version: "8.0.1", path: "bitnami/rabbitmq") > Chart version not ok. Needs a version bump!
> ```
> 
> versions seems to be matching ?

Yes, you need to increase the version. Current version is `8.0.1`, so this PR can't be `8.0.1` as well.

**Comment by sebastien-helbert** [comment]
Of course. Error message wording misled me. That's fixed

**Review by carrodher — APPROVED** [review]
Thanks, @sebastien-helbert for your changes and @alemorcuq for the review. Everything LGTM. 

Once merged the PR our internal CI/CD pipeline need to push the chart to the Helm repository, some delay is expected between the code is merged in GitHub and the chart appears in the repository

**Pull request merged**
