### PR TITLE
[bitnami/haproxy] Fix haproxy service clusterIP configuration

### PR DESCRIPTION
**Pull request by camposdelima**
### Description of the change

Use the correct helm property "service.clusterIP" instead of the wrong "clusterIP" property outside the service section.

### Benefits
This will fix the helm chart, and the users will be able to configure the clusterIP using the helm documented property.

### Possible drawbacks
Maybe someone is hacking the helm chart and using the wrong "clusterIP" property. It will be discarded.

### Issues
n/a

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by fevisera** [comment]
Hi @camposdelima,

Thank you for submitting this pull request. Kindly increment the patch version, as this PR addresses a bug fix. For further guidance, please refer to the details outlined in https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md.

Much appreciated!

**Comment by camposdelima** [comment]
> Hi @camposdelima,
> 
> Thank you for submitting this pull request. Kindly increment the patch version, as this PR addresses a bug fix. For further guidance, please refer to the details outlined in https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md.
> 
> Much appreciated!

The original version is 0.13.0, so now I'm bumping that to 0.13.1. Does that sound good?

**Comment by fevisera** [comment]
Hi @camposdelima,

The current version is 0.13.1, as indicated in the following link: https://github.com/bitnami/charts/blob/main/bitnami/haproxy/Chart.yaml#L31. It was updated a few hours ago. Could you please update it to 0.13.2?

Thank you!

**Comment by camposdelima** [comment]
Ok, sorry for that. It's 0.13.2 now.

**Review by fevisera — APPROVED** [review]
Thank you so much for your contribution and reviewing the comments!
LGTM!

**Pull request merged**
