### PR TITLE
[bitnami/rabbitmq] Fix restart exception

### PR DESCRIPTION
**Pull request by mccj**
**Description of the change**

rabbitmq-env.conf file could not be found after restart
RABBITMQ_MNESIA_DIR  variable exception after restart

**Benefits**

Fix stuff

**Possible drawbacks**

None

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] Change 'templates/statefulset.yaml' file

### CODE REVIEW

**Comment by mccj** [comment]
Yes, I use rancher v2.5.8. I don't know how to solve this problem

**Comment by migruiz4** [comment]
I'm sorry but we may not be able to help you as it is an issue with Rancher and not related to the chart.

**Comment by mccj** [comment]
okay, thank you

**Comment by bjolivot** [comment]
It's a rancher bug, defining MY_POD_NAME value in the config.yml made the cluster to restart 
```
extraEnvVars:
- name: MY_POD_NAME
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: metadata.name
```

**Pull request closed without merging**
