### PR TITLE
[bitnami/cilium] Fix typos with clusterName and certificates

### PR DESCRIPTION
**Pull request by dgomezleon**
### Description of the change

This change allows the usage of a different cluster-name for hubble-relay configmap. Also set  `tls-hubble-client-cert-file` `tls-hubble-client-key-file` to use the client certificate.

### Benefits

* Allows setting cluster-name to a value different from 'default'.
* Use the expected certificates

### Possible drawbacks

N/A

### Applicable issues

- Related #30264

### Additional information

Upstream logic
https://github.com/cilium/cilium/blob/3a988cd59c83355891f4d61815baf260caf6bf1f/install/kubernetes/cilium/templates/hubble-relay/configmap.yaml#L36-L38
https://github.com/cilium/cilium/blob/3a988cd59c83355891f4d61815baf260caf6bf1f/install/kubernetes/cilium/templates/_extensions.tpl#L20-L38

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by fmulero — APPROVED** [review]
LGTM

**Review by fmulero — CHANGES_REQUESTED** [review]
There are some conflicts

**Comment by dgomezleon** [comment]
> There are some conflicts

Fixed

**Review by fmulero — APPROVED** [review]

**Review by juan131 — APPROVED** [review]
LGTM

**Review by juan131 — APPROVED** [review]

**Pull request merged**
