### PR TITLE
indenation issue on additional volumes

### PR DESCRIPTION
**Pull request by raffaelespazzoli**
this fixes an indentation issue when additional volumes are added.

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the PR. Could you please bump the patch version of the chart?

**Comment by raffaelespazzoli** [comment]
> Hi,
> 
> Thank you very much for the PR. Could you please bump the patch version of the chart?

what do you mean by this? can you explain what you need me to do?

**Comment by s3than** [comment]
I think you'll find this has been resolved by https://github.com/bitnami/charts/pull/2790

**Comment by dani8art** [comment]
Yes, it seems it was fixed. Thank you so much!

**Pull request closed without merging**
