### PR TITLE
[bitnami/redis] retry when get master info failed

### PR DESCRIPTION
**Pull request by haloxinyu**
Signed-off-by: Xinyu Luo <1349694179@qq.com>

### Description of the change

Add retry mechanism for getting master info from redis svc when start redis node/sentinel

### Benefits

Can integrate istio proxy, fix the issue that connect redis svc failed before istio sidecar container initialize ready

### Possible drawbacks

If istio-proxy container take more than 2 seconds to be ready, then the fix should be invalid.

### Applicable issues

- fixes #https://github.com/bitnami/charts/issues/18195

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by jotamartos — APPROVED** [review]
Thanks for contributing to this project!

**Comment by qRoC** [comment]
now the timeout is 200*2=400, but `startupProbe.initialDelaySeconds (10) + startupProbe.periodSeconds (10) * startupProbe.failureThreshold (22)`=230. So its dead loop

@jotamartos

**Comment by haloxinyu** [comment]
@qRoC Sorry, I may missed something, this command is tried up to 2 times with an interval of 1, so that the max timeout should be 2s, How you get 200*2?

**Comment by qRoC** [comment]
@haloxinyu yes, but `$sentinel_info_command = timeout {{ .Values.sentinel.getMasterTimeout }} redis-cli ...`
Where getMasterTimeout = 200 (see #17866).
So final timeout 200+1+200.

**Comment by qRoC** [comment]
Need set `getMasterTimeout` to 99 for fix, or revert this commit

**Comment by haloxinyu** [comment]
@qRoC 
Thanks for your reminder and warmly suggesstion, I will raise another PR to set it to 99

**Comment by haloxinyu** [comment]
Create a new PR to fix it:
https://github.com/bitnami/charts/pull/18321

**Pull request merged**
