### PR TITLE
[bitnami/fluentd] Bind on IPv6 and IPv4 by default

### PR DESCRIPTION
**Pull request by stv0g**
**Description of the change**

This PR will change the default bind address from `0.0.0.0` to `::`.
This will cause fluentd to listen by default on IPv4 **and** IPv6.

**Benefits**

The chart would work out of the box for IPv4-only and IPv6 only clusters.

**Possible drawbacks**

None.

**Applicable issues**

This is similar to #2401, #2386 

**Checklist**
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

### CODE REVIEW

**Comment by carrodher** [comment]
Hi, changes LGTM, I am going to test it into our CI/CD pipeline. If everything is fine we will proceed to the merge and release. Thanks for your contribution

**Comment by carrodher** [comment]
It seems the tests are not working fine with the changes:
```
2020-04-23 18:24:14 +0000 [info]: using configuration file: <ROOT>
  <match fluent.**>
    @type null
  </match>
  <source>
    @type forward
    bind "::"
    port 24224
  </source>
  <source>
    @type http
    bind "::"
    port 9880
  </source>
  <match fluentd.healthcheck>
    @type stdout
  </match>
  <match **>
    @type stdout
  </match>
</ROOT>

...

2020-04-23 17:29:41 +0000 [info]: #0 starting fluentd worker pid=38 ppid=1 worker=0
2020-04-23 17:29:41 +0000 [info]: #0 listening port port=24224 bind="::"
2020-04-23 17:29:41 +0000 [info]: #0 fluentd worker is now running worker=0
	from /opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/root_agent.rb:146:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/engine.rb:105:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/engine.rb:80:in `run_configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/supervisor.rb:551:in `run_supervisor'
	from /opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/command/fluentd.rb:330:in `<top (required)>'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /opt/bitnami/fluentd/gems/fluentd-1.10.2/bin/fluentd:8:in `<top (required)>'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `load'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
	from /opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/root_agent.rb:146:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/engine.rb:105:in `configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/engine.rb:80:in `run_configure'
	from /opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/supervisor.rb:551:in `run_supervisor'
	from /opt/bitnami/fluentd/gems/fluentd-1.10.2/lib/fluent/command/fluentd.rb:330:in `<top (required)>'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /opt/bitnami/fluentd/gems/fluentd-1.10.2/bin/fluentd:8:in `<top (required)>'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `load'
	from /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
```

Are you sure this option is supported in FluentD 1.10.2?

**Comment by stv0g** [comment]
Hi @carrodher,

oh sorry you're right the prometheus does not support the bind option.
I accidentally copied over this option.

I fixed the issue by removing the bind option for the prometheus plugin.

See also: https://github.com/fluent/fluent-plugin-prometheus/issues/151

**Comment by carrodher** [comment]
I just tried the new changes but I faced the same issue, are you able to install fluentd with your changes in your environment? Just `helm install . --generate-name`?

I installed the default one and the one with the changes in this PR:
```
▶ kubectl get pods
NAME                READY   STATUS    RESTARTS   AGE
fluentd-default-0   1/1     Running   0          13h
fluentd-ip62-0      0/1     Running   10         36m
```
Using default options except `--set rbac.create=false`

**Comment by stv0g** [comment]
@carrodher are you running an IPv6-only or Dual Stack cluster?

**Comment by carrodher** [comment]
I tried in different clusters (GKE and AKS), none of them are IPv6-only.
With respect to that, we need to ensure our charts work on top of different platforms, so in this case, in order to have it working we should add a flag or something like that to enable/disable this behavior, but `helm install` without extra-parameters should pass the different tests.

**Pull request closed without merging**
