### PR TITLE
[bitnami/keycloak]add tolerations for keycloak config cli job pod

### PR DESCRIPTION
**Pull request by cleverhu**
Fix: https://github.com/bitnami/charts/issues/12839

### Description of the change
add tolerations for keycloak config cli job pod

### Applicable issues

  - fixes https://github.com/bitnami/charts/issues/12839

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by cleverhu** [comment]
@rafariossaa PTAL.

**Review by rafariossaa — APPROVED** [review]
LGTM

**Comment by cleverhu** [comment]
The pipeline failed, how can I handle it?

**Comment by FraPazGal** [comment]
Hello @cleverhu, we have just merged a fix for the pipeline error affecting your PR in https://github.com/bitnami/charts/pull/12905. Could you please update your branch with master's changes? That should re-launch the CI with the fix. 

Sorry for the inconvenience!

**Comment by cleverhu** [comment]
> Hello @cleverhu, we have just merged a fix for the pipeline error affecting your PR in https://github.com/bitnami/charts/pull/12905. Could you please update your branch with master's changes? That should re-launch the CI with the fix. 
> 
> 
> 
> Sorry for the inconvenience!

Ok,thanks.

**Review by rafariossaa — APPROVED** [review]

**Pull request merged**
