### PR TITLE
[bitnami/postgresql] replication documentation

### LINKED ISSUE #11394: [postgresql] read-only replica is not created
### Name and Version

bitnami/postgresql 11.6.19

### What steps will reproduce the bug?

I have a k8s cluster with mater and two worker nodes.
I want to install PostgreSQL on a single worker node.
I use the following command to perform the installation:
```
helm install postgresql \
    --set global.postgresql.auth.database=postgres \
    --set metrics.enabled=true \
    --set primary.nodeSelector."role"=app \
    --set readReplicas.nodeSelector."role"=app \
    --set volumePermissions.enabled=true \
    bitnami/postgresql
```
but in the end I have only one pod `postgresql-0` and do not see any RO replicas.

### Are you using any custom parameters or values?

```
--set global.postgresql.auth.database=postgres
--set metrics.enabled=true
--set primary.nodeSelector."role"=app
--set readReplicas.nodeSelector."role"=app
--set volumePermissions.enabled=true
```

### What is the expected behavior?

I would expect besides `postgresql-0` to have also one pod for read-only replica running on the same node.

### What do you see instead?

Only one pod - `postgresql-0` is running.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alexey-anufriev**
### Description of the change

Extend the documentation for PostgreSQL setup in replicated mode.

### Benefits

No more issues like #11394

### Applicable issues

  - fixes #11394

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by fmulero** [comment]
Hi @alexey-anufriev 

Whole `Parameters` section is automatically generated from `values.yaml` file with [Readme Generator For Helm](https://github.com/bitnami-labs/readme-generator-for-helm), so these changes would be overrode with any change in the values file. You can add this information in other place or change it in the values.yaml file, for example here:

https://github.com/bitnami/charts/blob/b5fccfb8d326f53b3836da6a7e6df908efcf4b0e/bitnami/postgresql/values.yaml#L671

**Comment by alexey-anufriev** [comment]
hi @fmulero, I have changed the values, but not sure if the generator will consider this properly as I am not familiar with it. Let me know if the syntax is different.

**Comment by alexey-anufriev** [comment]
@fmulero, do you think this change can be merged?

**Review by javsalgar — APPROVED** [review]
LGTM

**Pull request merged**
