### PR TITLE
[bitnami/postgresql] MAJOR - Update to PostgreSQL 13

### PR DESCRIPTION
**Pull request by FraPazGal**
**Description of the change**

Updates the application version from PostgreSQL 11 to 13 and adds the following changes:

- Refactored authentication configuration, now under `auth.XXX`.
- Now using the `architecture` parameter to configure `standalone/replication` chart architecture.
- Removed `service.XXX`, making `primary.service.XXX` and `readReplicas.service.XXX` the default ones.
- Moved PostgreSQL pods probes under `primary.XXX` and `readReplicas.XXX`.
- Moved `replication.XXX` parameters under `readReplicas.XXX`.
- Removed `global.postgresql` parameters.
- Added several standardizations and common parameters.
- Updated `bitnami/common` to use validations for PostgreSQL 13. Created the temporary `common.validations.postgresql13` helper to avoid breaking compatibility for the charts still using the old PostgreSQL chart major. Once this is merged and a PR is created updating said charts, the helper `postgresql13` can be used as the main one. This way, we also avoid bumping the `common` chart to a new major.

Tested upgrade process using `pg_dumpall` as explained in the release notes.

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Review by juan131 — COMMENTED** [review]
It's a good chance to use the major to improve this chart.

There are clear aspects of this chart (one of the charts that has many users contributions and technical debts) that we can improve:

- Credentials are a mess. We are standardizing our charts gathering all the authentication around the `auth` parameter but here it’s spread on many different parameters. Also, `usePasswordFile` should be renamed to `usePasswordFiles`, and there’s no `forcePasswords` parameter
- Missing `architecture` parameter (as we do in other charts). Instead there’s a `replication.enabled` parameter.
- Probes parameters are shared between “primary” and “readReplicas” components. Same with “extraEnvVars”
- Abusing of “globals” (e.g why is it necessary the `global.postgresql.servicePort`?)
- Missing `clusterDomain` and other common parameters
- Missing PodDisruptionBudget parameters

**Comment by carrodher** [comment]
Please, take into once merged this PR, all the charts using postgresql as a dependency should be also bumped in a major as well.

**Comment by carrodher** [comment]
Please, note that once this PR is merged, you also need to update the _Chart.yaml_ of the charts using PostgreSQL as a subchart (airflow, concourse, discourse, harbor, jupyterhub, keycloak, kong, odoo, and redmine).

The changes in those charts should include:
- Move the postgresql major version in _Chart.yaml_ from `10.X.X` to `11.X.X`
- Bump the chart version in a major
- Update _Chart.lock_ by running `helm dep update`
- Add a note in the Upgrade section (or equivalent) from the README
You can use this PR (https://github.com/bitnami/charts/pull/6732) as an example.

The previous steps should be done if the main application (parent chart) support the new PostgreSQL 13 version, if any of the applications don't support the new version we need to do a workaround to overwrite the `postgresql.image.tag` in the _values.yaml_ to use the new Helm Chart version but with a previous tag.

As @juan131 is on vacation this week, maybe you can work on this topic while he comes back to review this PR.

**Comment by carpenike** [comment]
Hey folks,

There's some downstream apps that we track which are starting to deprecate Postgres <12. We reference this chart version for a good chunk of the k8s-at-home charts. Hoping that this PR will gain some traction!

https://github.com/k8s-at-home/charts/issues/1297

**Comment by FraPazGal** [comment]
Hello @carpenike,

Sorry for the delay, this PR was put `on-hold` as we wanted to standardize our `bitnami/postgresql` following a shared template across our catalog. This standardization is now in progress and the PSQL version will be bumped at the same time.

We'll close this PR in favor of #8827, where the new changes are being tested. Please let's continue further discussion there.

**Pull request closed without merging**
