### PR TITLE
[bitnami/redis-cluster] fix: Can't add a Slave Node when usePassword is false

### LINKED ISSUE #4303: [bitnami/redis-cluster] Can't add a Slave Node when usePassword is false
**Which chart**:
chart: redis-cluster
version: 3.3.1

**Describe the bug**
If you set "usePassword" to "false" and add a Node to the cluster, no Slave Node will be added and it will time out.

**To Reproduce**

1. `helm install example bitnami/redis-cluster --set="usePassword=false"`
2. `helm upgrade example bitnami/redis-cluster --set="usePassword=false,cluster.nodes=8,cluster.update.addNodes=true,cluster.update.currentNumberOfNodes=6"`
3. See error
```
Error: UPGRADE FAILED: post-upgrade hooks failed: timed out waiting for the condition
```

log of cluster-update job

```
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Warning: AUTH failed
Adding Node 7 10.1.0.188 as slave of ERR unknown command `myid`, with args beginning with:
```

**Expected behavior**
One master node and one slave node will be added.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by tohutohu**
**Description of the change**
Fix issue with redis-cluster chart where Slave Node could not be added if usePassword is set to false.

**Benefits**
Fix Bug.

**Applicable issues**

  - fixes #4303

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

### CODE REVIEW

**Review by rafariossaa — APPROVED** [review]
Thanks you very much for spotting this and sending a PR.

**Comment by rafariossaa** [comment]
Hi, 
  Could you solve the conflict in Chart.yaml  ?

**Comment by tohutohu** [comment]
conflict resolved.
Is my operation OK?

**Review by rafariossaa — APPROVED** [review]
LGTM

**Pull request merged**
