### PR TITLE
[bitnami/thanos] Fix bucket command

### LINKED ISSUE #2922: [bitnami/thanos] thanos: error: expected command but got "bucket"
**Which chart**:
bitnami/thanos: 
Output from helm list:
`thanos                  monitoring      1               2020-06-25 09:23:39.9358571 +0000 UTC   deployed        thanos-1.1.1                    0.13.0`

**Describe the bug**
When installing the chart, the bucketweb container fails to start and the following error is produced in the logs:
```
Error parsing commandline arguments: expected command but got "bucket"
thanos: error: expected command but got "bucket"
```

**To Reproduce**
1. Follow the [steps provided here](https://github.com/bitnami/charts/tree/master/bitnami/thanos#integrate-thanos-with-prometheus-and-alertmanager):
image

I am using the following `values.yaml` file:
```yaml
objstoreConfig: |-
  type: AZURE
  config:
    storage_account: "thanosstor"
    storage_account_key: "redacted"
    container: "thanosdata"
    endpoint: "https://thanosstor.blob.example.endpoint.com/"
    max_retries: 0
querier:
  dnsDiscovery:
    sidecarsService: prometheus-operator-prometheus-thanos
    sidecarsNamespace: monitoring
bucketweb:
  enabled: true
compactor:
  enabled: true
storegateway:
  enabled: true
ruler:
  enabled: true
  alertmanagers:
    - http://prometheus-operator-alertmanager.monitoring.svc.cluster.local:9093
  config: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="monitoring/prometheus-operator"})
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

**Expected behavior**
The helm chart deploys successfully first time without the container failing.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"bb95a3814e91321a3821d669afc3707a8f35015f", GitTreeState:"clean", BuildDate:"2020-04-28T22:50:11Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Command provided via args shown in `kubectl describe pod thanos-webbucket-* -n monitoring`:

```
    Args:
      bucket
      web
      --http-address=0.0.0.0:8080
      --log.level=info
      --objstore.config-file=/conf/objstore.yml
      --refresh=30m
      --timeout=5m
```

### PR DESCRIPTION
**Pull request by miguelaeh**
**Description of the change**
The command for the bucketweb changed, this PR fixes it

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #2922

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by dbrennand** [comment]
Thanks guys! 😄 ❤️

**Comment by beef3333** [comment]
This is great!  Any idea when this will make it to master? I would really like to start using the latest version.

**Comment by beef3333** [comment]
Sorry to comment again but how long does it normally take for the chart to get updated in the helm repo?

**Comment by arenstar** [comment]
> Sorry to comment again but how long does it normally take for the chart to get updated in the helm repo?

Was asking myself the same thing ^^

**Comment by dbrennand** [comment]
@beef3333 @arenstar https://github.com/bitnami/charts/issues/2922#issuecomment-651615171

**Comment by joancafom** [comment]
Hi! 

The latest release in the helm repo should contain the fix 🚀. Apologies on the delay, we had been actively working to release `thanos` as soon as possible.

Thanks!

**Pull request merged**
