### PR TITLE
[bitnami/*] Affinity based on common presets (v)

### PR DESCRIPTION
**Pull request by juan131**
Signed-off-by: juan131 <juanariza@vmware.com>

**Description of the change**

This PR adapts the charts below so it uses the common presets added on `bitnami/common` at https://github.com/bitnami/charts/pull/3713.

- ~bitnami/metallb~
- bitnami/metrics-server
- bitnami/minio
- bitnami/mongodb
- bitnami/mongodb-sharded

**Benefits**

- Balanced UX for both advanced Kubernetes admins and less experienced.
- Opinionated presets but users can still define their own affinity
- 100% customizable
- No backwards incompatibility

**Possible drawbacks**

- Complexity

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Review by miguelaeh — COMMENTED** [review]
Hi, 
For metallb the common is being added in this other PR: https://github.com/bitnami/charts/pull/3889 by @Cellebyte apart from other changes. Could you incorporate your changes into that PR to avoid conflicts?

**Comment by juan131** [comment]
I removed MetalLb from this PR @miguelaeh 
I'll create a different PR once #3889 is merged adding the changes for this chart

**Review by miguelaeh — COMMENTED** [review]
I think we should be including the functions to check the passwords in the upgrades. At least, for Minio and MongoDB.
WDYT?

**Review by miguelaeh — APPROVED** [review]
LGTM!

**Pull request merged**
