### PR TITLE
[bitnami/apache,postgresql,tomcat] add extraPodSpec

### PR DESCRIPTION
**Pull request by itscaro**
**Description of the change**

Add a new parameter `extraPodSpec` in order to specify other keys not yet handled by the chart
**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Review by javsalgar — COMMENTED** [review]
Thanks for the PR! I like the idea. Could you bump the minor version?

**Comment by itscaro** [comment]
@javsalgar Thanks for your review. I updated the minor version

**Review by javsalgar — APPROVED** [review]
LGTM! Thanks

**Comment by javsalgar** [comment]
Could you fix the merge issues?

**Comment by itscaro** [comment]
@javsalgar rebase done, thank you

**Comment by itscaro** [comment]
@javsalgar rebase done, thank you

**Comment by javsalgar** [comment]
It seems that there are issues with the README.md file. Could you use this tool?

https://github.com/bitnami-labs/readme-generator-for-helm/

```
readme-generator -v values.yaml -r README.md
```

**Comment by itscaro** [comment]
@javsalgar done, is there any pre-built container image?

**Comment by javsalgar** [comment]
Merged! We don't have an image for readme-generator-for-helm but I can see that it would be very useful. I will forward this to the engineering team.

**Comment by itscaro** [comment]
@javsalgar maybe an automated job to generate README & schema since now we have this wonderful tool ;-)

**Pull request merged**
