### PR TITLE
[bitnami/redis] use hostnames in sentinel

### LINKED ISSUE #1682: [bitnami/redis] Sentinel return wrong IP
**Which chart**:

bitnami/redis version 9.5.5

**Description**

Sentinel do not update his config so we have stale IP addresses

**Steps to reproduce the issue:**

I setup redis and stolon in same namespace and play with them a while. When I tried to actually use redis I found sentinel gives me address of postrges pod! As far as I understand sentinel compiles its config upon pod start and beleave addresses do not change.

```
$ telnet redis.db.svc 26379
Trying 192.168.47.226...
Connected to 192.168.47.226.
Escape character is '^]'.
sentinel get-master-addr-by-name spt-redis
*2
$14
192.168.47.214
$4
6379
```
```
$ kubectl -n db get pod -o custom-columns=NAME:.metadata.name,IP:.status.podIP
NAME                               IP
redis-master-0                     192.168.47.235
redis-slave-0                      192.168.47.234
redis-slave-1                      192.168.47.226
stolon-create-cluster-8xj76        192.168.47.209
stolon-keeper-0                    192.168.47.201
stolon-keeper-1                    192.168.47.202
stolon-proxy-c49bdd5c5-bwp2l       192.168.47.243
stolon-proxy-c49bdd5c5-wzvzb       192.168.47.214
stolon-sentinel-6cb88b84c8-gdw4r   192.168.47.198
stolon-sentinel-6cb88b84c8-m8dpn   192.168.47.250
stolon-update-cluster-spec-fpc5h   192.168.47.200
```

```
$ kubectl -n db exec -it pod/redis-master-0 -c sentinel -- cat /opt/bitnami/redis-sentinel/etc/sentinel.conf
dir "/tmp"
bind 0.0.0.0
port 26379
sentinel myid 85dd23902cf42f9b601086f5e4814f704d15937f
sentinel deny-scripts-reconfig yes
sentinel monitor spt-redis 192.168.47.214 6379 2
sentinel down-after-milliseconds spt-redis 60000
sentinel failover-timeout spt-redis 18000
# Generated by CONFIG REWRITE
protected-mode no
sentinel auth-pass spt-redis **********
sentinel config-epoch spt-redis 0
sentinel leader-epoch spt-redis 0
sentinel known-replica spt-redis 192.168.47.218 6379
sentinel known-replica spt-redis 192.168.47.215 6379
sentinel known-sentinel spt-redis 192.168.47.218 26379 f13e511bad9f51182ba73b03697126b6bf1c752f
sentinel known-sentinel spt-redis 192.168.47.215 26379 91bef7dfdfda7aadd047839cc78f5acf14ade2c5
sentinel current-epoch 0
```

```$ kubectl -n db exec -it pod/redis-master-0 -c sentinel -- ls -lt /opt/bitnami/redis-sentinel/etc/sentinel.conf
-rw-r--r-- 1 1001 1001 743 Nov 23 17:14 /opt/bitnami/redis-sentinel/etc/sentinel.conf
```
```$ date
Thu Nov 28 19:45:40 MSK 2019```

**Describe the results you received:**

<!-- What actually happens -->

**Describe the results you expected:**

<!-- What you expect to happen -->

**Additional information you deem important (e.g. issue happens only occasionally):**

<!-- Any additional information, configuration or data that might be necessary to reproduce the issue. -->


**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

### LINKED ISSUE #5418: [bitnami/redis] After failover, there will be two masters (with simple reproducible experiments included!)
**Which chart**:
redis

**Describe the bug**

Hi thanks for the lib! I do find a bug: After failover, there will be two masters.

Steps:

1. Install the helm chart. Now we will see master pod (pod A) and slave pod (pod B).
2. **Kill** (i.e. delete) the master pod (call it pod A). Kubernetes will auto recreate another master pod (call it pod A2).
3. Verify that pod A2 has **different ip** compared with pod A. (This should be the usual case since k8s never guarantee static ip)
4. Then **both A2 and B think they are masters!** (Verify by, for example: run `INFO replication` and see the roles. Or `SET k v` on both instances, and observe that they do not replicate. Or look at `SENTINEL REPLICAS mymaster`, and see sentinels do not even know the existence of pod A2.) 

Guess of why this happens:

When pod A2 is created, it is configured as a master by the bitnami startup scripts / pod spec. Moreover, it has a brand new ip. Thus, it is as if **this pod A2 is a separate unrelated brand-new redis instance** which has completely **no** relationship with the original pod A/B/sentinels. Thus, it is not recognized, and of course it is not a slave of pod B.

Thanks

### PR DESCRIPTION
**Pull request by tomislater**
**Description of the change**

Because it is a chart for Kubernetes, we should use `hostnames` instead of `IPs` (https://redis.io/topics/sentinel#ip-addresses-and-dns-names). I added more information about my case in #1682 and #5418.

**Benefits**

It should works better in dynamic environment.

**Possible drawbacks**

I don't know yet. Maybe there is a bug somewhere. I have tested on my clusters and everything works correctly. But still...

**Applicable issues**

  - fixes #1682
  - fixes #5418

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

After this change `sentinel.conf` looks like:
```
cat opt/bitnami/redis-sentinel/etc/sentinel.conf
cat opt/bitnami/redis-sentinel/etc/sentinel.conf
dir "/tmp"
port 26379
sentinel monitor mymaster my-redis-node-1.my-redis-headless.my-redis.svc.cluster.local 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 18000

# User-supplied sentinel configuration:
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
# End of sentinel configuration
sentinel myid 475427d0cefa44aff518ab6b888c3510314d882c
sentinel announce-ip "my-redis-node-1.my-redis-headless.my-redis.svc.cluster.local"

sentinel known-sentinel mymaster my-redis-node-2.my-redis-headless.my-redis.svc.cluster.local 26379 80d3b99129c4f9bb62cdcec2399499f2c4666789

sentinel known-replica mymaster my-redis-node-0.my-redis-headless.my-redis.svc.cluster.local 6379

sentinel known-sentinel mymaster my-redis-node-0.my-redis-headless.my-redis.svc.cluster.local 26379 cae9f9b5ed951299f4bdc7de1da8e996e7b7197c

sentinel known-replica mymaster my-redis-node-2.my-redis-headless.my-redis.svc.cluster.local 6379
# Generated by CONFIG REWRITE
protected-mode no
user default on nopass ~* &* +@all
sentinel config-epoch mymaster 1
sentinel leader-epoch mymaster 1
sentinel current-epoch 1
```

### CODE REVIEW

**Comment by tomislater** [comment]
I also tested it with `haproxy` as a "fronted" and this also works.

**Review by juan131 — COMMENTED** [review]
Hi @tomislater 

Thanks so much for this great contribution!!!

I agree that we shouldn't be use IPs on a Kubernetes environment since they're ephemeral, and we should rely on stable network identifiers such as the hostname. Therefore, I'm fine with your approach.

I'd like @rafariossaa to double-check this, since he has more experience with Redis & Sentinel configuration. He's currently on PTO so please expect a few days delay before he comes back to you.

**Comment by tomislater** [comment]
👋 what about this PR? It works on staging and prod since then and I don’t see any problems.

I had one problem because I had not changed **masterSet** (both deployments had the same masterSet) and two separated sentinels (in different namespaces) were thinking that they are one cluster 🤝but it is another issue.

**Comment by juan131** [comment]
Sorry @tomislater I lost the track of this one!! Please @rafariossaa take a look to this PR when possible.

**Comment by rafariossaa** [comment]
Hi,
  I am taking a look to it. For me it makes sense.
 Please, allow me a couple of days to do some testing in my side before merging.

**Comment by tomislater** [comment]
⚠️ Hmm, strange. I have two deployments (with sentinels) in different namespaces with different `masterSet`s.
Sometimes, when I delete two pods in the same time (one in namspace `A` and one in namespace `B`) sentinel from namespace `A` thinks that replica from namespace `B` belongs to him. And vice cersa.

It is very hard to reproduce. Only twice I have seen this.

Maybe is it something wrong with `announce-hostnames` or `replica-announce-ip` 🤔

**Comment by rafariossaa** [comment]
Hi,
  In that case I will wait until this is clarified before merging it.

**Comment by tomislater** [comment]
Hmm, maybe I should use only `"${HOSTNAME}"` instead of `"${HOSTNAME}.${HEADLESS_SERVICE}"`. I am going to check that.

**Comment by tomislater** [comment]
Yeah, please do not merge it. I see that there were some new changes on master.

**Comment by tomislater** [comment]
Okay, my changes are not required anymore. We can close this PR. Similar changes have been added here: https://github.com/bitnami/charts/commit/722dead229628a82558540482417ba09cfa844c6 `15.4.0` uses hostnames instead of names.

But, I have noticed the same problems. Auto-discovery seems broken. I am going to create an issue for this.

**Comment by rafariossaa** [comment]
Hi,
  In that case I am closing it.
  Thanks

**Pull request closed without merging**
