### PR TITLE
Don't declare ClusterRoleBinding of a disabled operator

### PR DESCRIPTION
**Pull request by mkuratczyk**
If the values file sets `msgTopologyOperator.enabled: false`, `ClusterRoleBinding` for the messaging topology operator should be skipped

### CODE REVIEW

**Comment by carrodher** [comment]
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

**Comment by mkuratczyk** [comment]
Done

**Comment by carrodher** [comment]
It seems the issue is still present. Apart from that, it is needed to bump the chart version in the Chart.yaml file.

**Comment by mkuratczyk** [comment]
Hi. I'd appreciate if this could be considered for merging.

**Review by andresbono — APPROVED** [review]
Thank you very much for contributing with this fix. It totally makes sense. To avoid extra delays in merging the PR, we have just pushed a new commit:

* Simplification of the if conditions with the `and` operator.
* Patch version bump instead of minor version

**Pull request merged**
