### PR TITLE
[bitnami/mongodb] Update ServiceMonitor port typo fix

### PR DESCRIPTION
**Pull request by vuonghoainam**
### Benefits
- Exporter for mongoDB can be working fine, as the port in `/bitnami/mongodb/templates/replicaset/statefulset.yaml` is currently `metrics` not `http-metrics`

### Possible drawbacks
- None

### Applicable issues

  - fixes #

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your contribution, please can you take a look at the included files? It seems there are undesired changes affecting PostgreSQL HA

**Comment by vuonghoainam** [comment]
Hi @carrodher I have pushed new version, but there is a conflict in Chart version.
What should I do to resolve this one?
Please help
Thank you

**Review by fmulero — COMMENTED** [review]
Hi @vuonghoainam , Thanks for your contribution but I don't fully understand where is the problem. The monitored service defines the port as `http-metrics`, the same name used in the monitor. Are you facing any error?

https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/troubleshooting.md#using-textual-port-number-instead-of-port-name

**Comment by vuonghoainam** [comment]
Hi @fmulero 

You may check 
1. The port name defined in [MongoDB STS replicaSet](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/servicemonitor.yaml#L29) and [MongoDB STS standalone] is `metrics`
2. The port name define in [MongoDB service monitor](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/servicemonitor.yaml#L29) is `http-metrics`

As there is difference then when we come to prometheus, mongodb metrics is stated as `Targets dropped` and cannot be used.

**Comment by fmulero** [comment]
I think there is a misunderstood here. 

As you said, the port name defined in [MongoDB STS replicaSet](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/replicaset/statefulset.yaml#L431) and [MongoDB STS standalone](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/standalone/dep-sts.yaml#L372) is `metrics` (links fixed)

The port name defined in the [metrics service](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/metrics-svc.yaml#L27) is `http-metrics` and the `targetPort` is `metrics` (the port used in the replicaset/deployment)

The `serviceMonitor` is monitoring the [metrics service](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/servicemonitor.yaml#L27) So the name of the monitored port should be `http-metrics`.

Not sure how you are getting the targets dropped in prometheus. Could you share more details or screenshot to see what is happening?

**Pull request closed without merging**
