### PR TITLE
[bitnami/kubeapps] Release Kubeapps 2.9.0 and bump bitnami/postgresql to its latest version

### PR DESCRIPTION
**Pull request by carrodher**
This PR unifies the changes from three different PRs:
- https://github.com/bitnami/charts/pull/19447
- https://github.com/bitnami/charts/pull/19531
- https://github.com/bitnami/charts/pull/19618

The first two are related to the new version of Kubeapps (2.9.0) while the third one bumps the _bitnami/postgresql_ subchart to its latest major version bundling PostgreSQL 16 (https://github.com/bitnami/charts/pull/19587).

### CODE REVIEW

**Review by absoludity — APPROVED** [review]
Great, thanks for merging those together @carrodher

**Review by juan131 — APPROVED** [review]
LGTM

**Review by gongomgra — APPROVED** [review]

**Comment by absoludity** [comment]
Thanks @juan131 , @gongomgra . So is there anything else needing to be done for this to land @carrodher ? I see the VIB Verify step is failing, but in the past, that has been fixed without my input (and the error is a warning: `Warning: Skipping execution graph summary, either the report could not be dowloaded or final state was not SUCCEEDED`).

**Comment by gongomgra** [comment]
Hi @absoludity, let me check the error below that I found in the execution

```
[pod_id=kubeapps-internal-apprepository-controller-748b849f8d-98gx4] I1009 16:23:30.848110       1 controller.go:442] Creating Job "apprepo-deployment-z7pwt-sync-bitnami-" in namespace "deployment-z7pwt" for starting syncing AppRepository "deployment-z7pwt/bitnami"
[pod_id=kubeapps-internal-apprepository-controller-748b849f8d-98gx4] W1009 16:23:31.021705       1 warnings.go:70] spec.template.spec.containers[0].env[1].name: duplicate name "DB_PASSWORD"
[pod_id=kubeapps-internal-apprepository-controller-748b849f8d-98gx4] I1009 16:23:31.022161       1 controller.go:366] The AppRepository "deployment-z7pwt/bitnami" doesn't have a finalizer yet, adding one...
[pod_id=kubeapps-internal-apprepository-controller-748b849f8d-98gx4] E1009 16:23:31.031924       1 controller.go:281] error syncing "deployment-z7pwt/bitnami": error updating the AppRepository "deployment-z7pwt/bitnami": apprepositories.kubeapps.com "bitnami" is forbidden: User "system:serviceaccount:deployment-z7pwt:kubeapps-internal-apprepository-controller" cannot update resource "apprepositories" in API group "kubeapps.com" in the namespace "deployment-z7pwt"
```

**Comment by absoludity** [comment]
> Hi @absoludity, let me check the error below that I found in the execution
> 
> ```
> [pod_id=kubeapps-internal-apprepository-controller-748b849f8d-98gx4] I1009 16:23:30.848110       1 controller.go:442] Creating Job "apprepo-deployment-z7pwt-sync-bitnami-" in namespace "deployment-z7pwt" for starting syncing AppRepository "deployment-z7pwt/bitnami"
> [pod_id=kubeapps-internal-apprepository-controller-748b849f8d-98gx4] W1009 16:23:31.021705       1 warnings.go:70] spec.template.spec.containers[0].env[1].name: duplicate name "DB_PASSWORD"
> [pod_id=kubeapps-internal-apprepository-controller-748b849f8d-98gx4] I1009 16:23:31.022161       1 controller.go:366] The AppRepository "deployment-z7pwt/bitnami" doesn't have a finalizer yet, adding one...
> [pod_id=kubeapps-internal-apprepository-controller-748b849f8d-98gx4] E1009 16:23:31.031924       1 controller.go:281] error syncing "deployment-z7pwt/bitnami": error updating the AppRepository "deployment-z7pwt/bitnami": apprepositories.kubeapps.com "bitnami" is forbidden: User "system:serviceaccount:deployment-z7pwt:kubeapps-internal-apprepository-controller" cannot update resource "apprepositories" in API group "kubeapps.com" in the namespace "deployment-z7pwt"
> ```

Thanks @gongomgra , sorry for the hassle.

Hmm, strange that we can't reproduce it locally with the same chart. Two possibilities come to mind:

1. Is this is happening during an upgrade where the image has been updated but before the new RBAC hasn't been applied yet? Unlikely, but the context of the logs or test should help? Or,
2. Is there some other reason why the clusterrole may not have been bound at this point, such as a separate error during an upgrade or something where the RBAC couldn't apply (guessing not, as we'd see that error).

Note that in the change on the [chart RBAC actually moves the RBAC permission for the finalizers from the old Role to the new ClusterRole|https://github.com/bitnami/charts/pull/19806/files#diff-65fb0b9c3d888fa3f3d2f4d141834768c6bdc30cbd063c05189cf9417a6ed108R57-R65]. So we would expect to see this error if the service account was still bound to the existing role (as it should be), but for some reason was not bound to the new clusterrole?


Also note, to reproduce it locally, it might require doing an upgrade (or otherwise, adding a 'bitnami' repository on an older version, so that it won't have finalizers, or even removing the finalizers and checking). Actually, an easier way to reproduce may be to just install, then manually remove the finalizers from the bitnami app-repository, and see if the controller logs the same error? But fwiw, the error reads as though the service account is not bound to the clusterrole for some reason (but is correctly bound to the role).

Are you able to provide more context from the logs, or the full logs? (or on the private internal ticket, if required). Thanks Gonzalo. I'll try to reproduce it and see too.

**Comment by absoludity** [comment]
> I'll try to reproduce it and see too.

I just installed Kubeapps from this chart PR (well, upgraded my existing kubeapps), then manually deleted the finalizer on the bitnami apprepository, and don't see any issue :/

```
I1011 04:52:14.162071       1 controller.go:463] Creating Job "apprepo-kubeapps-sync-bitnami-" in namespace "kubeapps" for starting syncing AppRepository "kubeapps/bitnami"
...
I1011 04:52:14.166193       1 controller.go:366] The AppRepository "kubeapps/bitnami" doesn't have a finalizer yet, adding one...
I1011 04:52:14.169706       1 controller.go:276] Successfully synced "kubeapps/bitnami"

```

**Comment by absoludity** [comment]
I also installed the chart (from this PR) in a fresh cluster and similarly had no issue (similar log to above after manually deleting the finalizer). So my suspicion is that in the test environment, the new cluster role is not bound to the service account. Is that something you can check and verify?

**Comment by gongomgra** [comment]
@absoludity we finally found the issue. The VIB pipeline is installing the chart twice in the cluster at the same time (for Goss and Cypress tests), which is causing ClusterRole's name collisions. I can't reproduce the pod's logs error either, by I think the real issue was with the ClusterRole's naming and that we got those other error messages due to other temporary issues in the testing cluster. Let me know if you agree with the suggested changes.

**Review by absoludity — APPROVED** [review]
LGTM, thanks! It will affect existing installations only marginally, and helps us support multiple Kubeapps in different namespaces :)

**Review by jotamartos — APPROVED** [review]

**Pull request merged**
