### PR TITLE
[bitnami/redis] Fix OutOfSync HPAs with ArgoCD

### LINKED ISSUE #11312: [bitnami/redis] Reorganize metrics in HPAs templates so that applications relying on it are not always OutOfSync in ArgoCD
### Name and Version

bitnami/redis 7.0.4

### What is the problem this feature will solve?

Currently deploying the bitnami/redis helm chart with ArgoCD leads to an OutOfSync application, because of the order of the metrics in the HPAs definitions not matching the one in the applied resource.

### What is the feature you are proposing to solve the problem?

Swapping the cpu and memory metrics in the HPAs templates solves the issue.

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by florentinl**
### Description of the change

Minor change that prevents the bitnami/redis helm chart to produce OutOfSync applications when deployed with ArgoCD

### Benefits

Chart can be used with or without ArgoCD

### Possible drawbacks

None

### Applicable issues

  - fixes #11312

### Additional information

It is a known limitation of ArgoCD and Kubernetes as stated in ArgoCD's documentation: https://argo-cd.readthedocs.io/en/stable/user-guide/diffing

### Checklist

- [ x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by fmulero** [comment]
Hi @florentinl Thanks a lot for your contribution!

I think something is missing in the description of the PR Could your review it? Also, Could you provide a scenario to test your changes? How could I reproduce your issue?

**Comment by florentinl** [comment]
Hi, I don't see what is missing in the PR description, could you please point out what is missing ?
As for how to reproduce the issue:  
You would need to have a Kubernetes cluster with ArgoCD deployed in it. (https://argo-cd.readthedocs.io/en/stable/#quick-start).   
The deployment in which I stumbled upon the bug is Kubernetes 1.24.2 with Argocd 2.4.4, but the issue should happend no matter the versions of both Kubernetes and ArgoCD.
Then deploy the bitnami/redis helm chart as an ArgoCD Application with autoscaling enabled for replicas:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.0.5
    chart: redis
    helm:
      values: |
        replica:
          autoscaling:
            enabled: true
            targetCPU: 80
            targetMemory: 80
          resources:
            requests:
              cpu: "25m"
              memory: "25Mi"

  destination:
    server: https://kubernetes.default.svc
    namespace: redis

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
```
Even after the Application is not progressing anymore, it appears as OutOfSync when I do a `kubectl get application -n argocd redis`.  

In the description of the application, the Status > Resources subsection show that the HPA is the only resource OutOfSync.  
 
Using the dashboard available by port-forwarding the ArgoCD server `kubectl port-forward svc/argocd-server 8080:443` (you must be logged in with the credentials "admin" and password "kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo"), you can also see the exact lines of the template that are OutOfSync through the dashboard , by clicking on the application redis and then the Horizontal Pod Autoscaler.  

To reproduce the same behavior with the sentinel HPA, simply update the helm values to something like this:
```yaml
    helm:
      values: |
        replica:
          autoscaling:
            enabled: true
            targetCPU: 80
            targetMemory: 80
          resources:
            requests:
              cpu: "25m"
              memory: "25Mi"

        sentinel:
          enabled: true
          resources:
            requests:
              cpu: "25m"
              memory: "25Mi"
```

**Comment by fmulero** [comment]
Thanks @florentinl for such detailed information, I appreciate it (a lot), but I don't fully understand where is the root cause. I understand that this little change solves the problem right now but I am worried about what will happen in the future, because something is forcing that order and I don't see what, is the bitnami code? is the metric-server? is ArgoCD?

**Comment by florentinl** [comment]
From what I understand, this looks to be an known behavior of Kubernetes, the Documentation of [ArgoCD](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing) says this:
" For Horizontal Pod Autoscaling (HPA) objects, the HPA controller is known to reorder spec.metrics in a specific order. See [kubernetes issue #74099](https://github.com/kubernetes/kubernetes/issues/74099). To work around this, you can order spec.metrics in Git in the same order that the controller prefers. "

**Comment by fmulero** [comment]
Thanks a lot @florentinl everything is clear now. I didn't see the issue in kubernetes side and I was worried about what will happen if tomorrow the order changes and we have to change it again and again

**Review by fmulero — APPROVED** [review]
LGTM

**Pull request merged**
