### PR TITLE
[bitnami/redis-cluster] When retrying to add a node, get the firstNodeIp IP address again

### LINKED ISSUE #4064: [bitnami/redis-cluster] Update script uses old node IP address
**Which chart**:
redis-cluster-3.2.8

**Describe the bug**
When helm upgrade is run with cluster scale-up all redis pods are rolled in StatefulSet because env variable with nodes is changed. Cluster update Kubernetes job resolves pod dns name to IP address only once, so when a pod is rolled and it's IP address changes, update job can no longer perform any operations

**To Reproduce**
1. `helm install redis-cluster bitnami/redis-cluster --set 'cluster.replicas=0'`
2. `helm upgrade redis-cluster bitnami/redis-cluster --set 'cluster.nodes=6,cluster.replicas=0,cluster.init=false,cluster.update.addNodes=true,cluster.update.currentNumberOfNodes=3'`
3. tail the logs of the cluster-update pod
```
>>> Adding node 172.21.233.222:6379 to cluster 172.21.190.236:6379
Add-node 5 172.21.233.222 failed, retrying
Could not connect to Redis at 172.21.190.236:6379: Connection timed out
```

**Expected behavior**
Cluster update job should account for pods IP address change during the rolling upgrade process

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T23:30:39Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.12+IKS", GitCommit:"d09005b98837bb6061c0f643a27383c02b003205", GitTreeState:"clean", BuildDate:"2020-09-16T21:47:16Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
redis-cluster-0 pod had an IP address of `172.21.190.236` before the upgrade
during the rolling upgrade of the StatefulSet it's IP address changed to `172.21.190.237`
cluster update job never finished
```
Could not connect to Redis at 172.21.190.236:6379: Connection timed out
>>> Adding node 172.21.233.222:6379 to cluster 172.21.190.236:6379
Add-node 5 172.21.233.222 failed, retrying
Could not connect to Redis at 172.21.190.236:6379: Connection timed out
>>> Adding node 172.21.233.222:6379 to cluster 172.21.190.236:6379
Add-node 5 172.21.233.222 failed, retrying
Could not connect to Redis at 172.21.190.236:6379: Connection timed out
>>> Adding node 172.21.233.222:6379 to cluster 172.21.190.236:6379
Add-node 5 172.21.233.222 failed, retrying
Could not connect to Redis at 172.21.190.236:6379: Connection timed out
>>> Adding node 172.21.233.222:6379 to cluster 172.21.190.236:6379
Add-node 5 172.21.233.222 failed, retrying
Could not connect to Redis at 172.21.190.236:6379: Connection timed out
>>> Adding node 172.21.233.222:6379 to cluster 172.21.190.236:6379
Add-node 5 172.21.233.222 failed, retrying
Could not connect to Redis at 172.21.190.236:6379: Connection timed out
>>> Adding node 172.21.233.222:6379 to cluster 172.21.190.236:6379
Add-node 5 172.21.233.222 failed, retrying
>>> Adding node 172.21.233.222:6379 to cluster 172.21.190.236:6379
Could not connect to Redis at 172.21.190.236:6379: Connection timed out
Add-node 5 172.21.233.222 failed, retrying
```

### PR DESCRIPTION
**Pull request by tohutohu**
**Description of the change**
When retrying to add a node, get the firstNodeIp IP address again.

**Benefits**

**Applicable issues**

  - fixes #4064 

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

### CODE REVIEW

**Comment by FraPazGal** [comment]
Hi @tohutohu,

Thanks for the PR! I have a couple of question regarding your solution. 

From what I understand, having another `wait_for_dns_lookup` your are giving the chart 120 seconds extras to resolve the IP address but it is not a final solution, is it? Although it would be rarer, there could be the case in which the pod doesn't resolve the IP still and we would have the same problem again.

As discussed in the issue, I think that waiting until all pods update operations are completed may be the optimal solution, what do you think?

**Comment by tohutohu** [comment]
Yes, your point is correct. This change is not a complete solution to the issue.

Now (v4.0.2) the chart always fails to add a node in my environment. This change avoids the failure in most cases.
I made this change because I found it impossible to verify the completion of the StatefulSet update from Job.

However, waiting 120 seconds on retry may be too long.

**Comment by FraPazGal** [comment]
Yes, I understand what you mean, but I'm still a bit reticent to merge this PR. Was the suggestion made by @tpolekhin of using `kubectl rollout status sts/redis-cluster -w` impossible to implement?

What are your thoughts on this @miguelaeh?

**Comment by miguelaeh** [comment]
Hi guys,
Well, I am not totally convinced about this PR since it seems to limit the issue more than solve it. 
We can create an internal task to check this in deeper and implement the changes suggested in the referenced issue in the better possible way.

**Comment by tohutohu** [comment]
Thanks, FraPazGal and miguelaeh.

I see what you guys said.
What should I do next?
Should this PR be closed?

**Comment by javsalgar** [comment]
Hi,

My 2 cents, for the time being I would put this PR as on-hold and we will see what the result of the investigation is. Sounds good?

**Comment by srfaytkn** [comment]
will merge?

**Comment by javsalgar** [comment]
Hi, for the time being, if it helps to limit the issue, let's merge it and then, perform any extra changes after the investigation.

**Review by javsalgar — APPROVED** [review]

**Pull request merged**
