### PR TITLE
[bitnami/thanos] fix receive serviceaccount ref to ruler

### PR DESCRIPTION
**Pull request by haghabozorgi**
**Description of the change**

This updates thanos chart, specifically the receive  `serviceaccount.yaml` template. I believe the `serviceaccount.yaml` template is incorrectly referencing `ruler` as opposed to `receive` https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/receive/serviceaccount.yaml#L8 

**Benefits**

`receive.serviceAccount.annotations` will work as expected

**Possible drawbacks**

N/A

**Applicable issues**

  - fixes #

**Additional information**
In testing thanos setup we ran into this issue where specifying `receive.serviceAccount.annotations` was not working as expected (the annotation was not being added to the serviceaccount). If you set `ruler.serviceAccount.annotations` though, (we set  `ruler.enabled` to false since we are not testing it) the annotation for the `receive` serviceaccount is added as expected.

request, mention that information here.-->

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Review by rafariossaa — APPROVED** [review]
Hi,
  Thank you very much for spotting this.

**Comment by rafariossaa** [comment]
There was a update in the chart.
Do you mind bumping the chart version in your PR ?

**Comment by haghabozorgi** [comment]
@rafariossaa  bump chart version to 3.9.2. Additionally, I believe the service template for receive component also has an incorrect ref to ruler, so I updated that template in this PR as well. Can you please confirm that is acceptable?

**Review by rafariossaa — APPROVED** [review]
LGTM.
Thank you very much.

**Comment by rafariossaa** [comment]
Sorry, it seems you have hit again other version change.

**Pull request merged**
