### PR TITLE
[bitnami/metallb] Provide a flag for disabling BGP speakers

### LINKED ISSUE #8742: [bitnami/metallb] enable or disable flag for speaker daemonset on MetalLB chart
**Which chart**: bitnami/metallb

**Describe the solution you'd like**
I've deployed MetalLB with BGP on Kubernetes with Calico CNI, it works fine but the speakers are no more needed because the peering is made from the Controller via Calico and not from MetalLB Speakers.
[https://projectcalico.docs.tigera.io/networking/advertise-service-ips#advertise-service-load-balancer-ip-addresses](url)

Would be nice to have a variable where we can choose to disable the Speaker's deployment.

**Describe alternatives you've considered**

Currently, I deploy the chart, and immediately after I delete the daemonset.

### PR DESCRIPTION
**Pull request by juzerali**
### Description of the change
Provide an option for disabling BGP speakers. Some CNIs (most prominent being calico) do not need speakers and Metallb recommends disabling speakers when working with calico installation.

Reference: https://metallb.universe.tf/configuration/calico/#the-easy-way

### Benefits
Clusters using Calico can disable metallb speakers and save resources

### Possible drawbacks
None

### Applicable issues

- fixes #8742

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by juzerali** [comment]
@aoterolorenzo can we please have a review on this?

**Comment by Mohammed-5253** [comment]
@aoterolorenzo please review and merge as we required this changes in our project.

**Review by aoterolorenzo — APPROVED** [review]
Hi @juzerali @Mohammed-5253,

Sorry for the delay, last week was holiday here so we just get some extra support cases back this week. 

LGTM, let's do this.

**Comment by FireballDWF** [comment]
When this flag is set to false, it will disable all speaker functionality, including the speaker functionality for L2 operating mode, thus it does not just impact BGP operating mode, correct?  If so, then the description of "Whether to enable BGP speakers or not" for the "speaker.enabled" parameter should be corrected at least by removing "BGP" from the description.

**Comment by aoterolorenzo** [comment]
Hi @FireballDWF,

That's completely true. Some aside cases could be disabled with this feature so not BGP operating mode is impacted. Would you like to contribute with a PR to fix the related documentation and remove or clarify the feature?

**Pull request merged**
