### PR TITLE
[bitnami/contour] Append the missing posfix of name for service/contour

### PR DESCRIPTION
**Pull request by izturn**
Signed-off-by: Gang Liu <gang.liu@daocloud.io>

### Description of the change
let the naming style of service/contour like the other resources (eg: service/envoy), Just the recreate of #11240 
179701789-437469bf-6fd5-4d48-9e00-01d5e48c60f5

### Applicable issues

  - fixes #

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your PR, could you add more info about the change? As a standard, we are using the common feature to set this kind of name for the services so it is rendered in a standard way across Helm charts

**Comment by izturn** [comment]
the service/envoy has the postfix,  but service/contour has not, no matter for contour or envoy, the other resources( pod/deployment) both have the postfix, so I think it's a typo, if it's my fault, pls feels free to close it

**Review by carrodher — DISMISSED** [review]
Thanks for the context. Changes LGTM.
I just rebased from the `master` branch and bumped the chart version in a minor. If all the automation works fine the PR should be automatically merged.

**Comment by izturn** [comment]
@carrodher  thx, so how to make '[CI/CD] CI Pipeline / VIB Verify (pull_request_target) ' happy?

**Comment by izturn** [comment]
@carrodher thx for your help, I checked the contour's source code and the service name ***contour*** is bind to its **bootstrap** process, if we don't change the source code first, it can't be changed too.

**Comment by izturn** [comment]
@carrodher thx for your help, I checked the contour's source code and the service name contour is bind to its bootstrap process, if we don't change the source code first, it can't be changed too.

**Pull request closed without merging**
