### PR TITLE
[bitnami/logstash] Add autoscaling for Logstash

### PR DESCRIPTION
**Pull request by brsolomon-deloitte**
Signed-off-by: Brad Solomon <81818815+brsolomon-deloitte@users.noreply.github.com>

Tested with `helm template . -s templates/hpa.yaml --set-string autoscaling.enabled=true`

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by aoterolorenzo** [comment]
Hi. 

Could you provide some functional tests proving the feature with any example values?

**Comment by aoterolorenzo** [comment]
Also, seems that the branch would need to be updated.

**Comment by brsolomon-deloitte** [comment]
Hello @aoterolorenzo - conflicts resolved.

For the tests of HPA, are you aware of any other Bitnami helm charts you can point to that have HPA tests that would serve as a good example?

**Comment by aoterolorenzo** [comment]
> Hello @aoterolorenzo - conflicts resolved.
> 
> For the tests of HPA, are you aware of any other Bitnami helm charts you can point to that have HPA tests that would serve as a good example?

I meant, something a console output with a functional example of the feature working would be great

**Pull request closed without merging**
