### PR TITLE
[bitnami/kube-prometheus] fix issue due to crds update

### PR DESCRIPTION
**Pull request by EtienneBarbier**
### Description of the change

CRDs files was duplicated due to file missnaming
New CRDs are now added in the operator clusterrole
Selectors for new CRDs are availables in config file

### Benefits

Fix the issue

### Possible drawbacks

None

### Applicable issues

None

### Additional information

None

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

**Comment by EtienneBarbier** [comment]
This PR is ready for a merge

**Comment by CeliaGMqrz** [comment]
Hi @EtienneBarbier 

Thanks for your contribution! 
However, I think this change is a minor version because it is a new feature. Could you please update the chart version?

**Review by CeliaGMqrz — APPROVED** [review]
Thanks for your contribution! LGTM

**Pull request merged**
