### PR TITLE
[bitnami/mongodb] support backups for standalone TLS-enabled instances

### PR DESCRIPTION
**Pull request by bdols**
### Description of the change

fixes command line arguments that mongodump needs to backup TLS enabled instances

run `generate-certs.sh` in the Job to follow chart convention's for TLS access

disables `--oplog` in the standalone architecture case

### Benefits

more cases covered for the provided backup solution

### Possible drawbacks

I don't know that `--oplog` is possible to run on standalone architecture, if it is, then further logic would need to be added to enable/disable its use.

### Applicable issues

N/A AFAIK

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by bdols** [comment]
PR updated with upstream changes

**Comment by fevisera** [comment]
Hi @bdols,

Sorry for the delay. Could you please give more details on the error you are trying to solve when you mention "fixes command line arguments that mongodump needs to backup TLS enabled instances"?

Also, please provide some additional details regarding why you are switching from --tls to --ssl.

Thank you.

**Comment by fevisera** [comment]
Hi @bdols,

Thank you for giving more details. Please, resolve the conflicts by updating your branch with the main branch.

**Review by fevisera — APPROVED** [review]
LGTM! Thank you very much for your contribution!

**Pull request merged**
