### PR TITLE
[bitnami/thanos] Properly name HPA for receive-distributor

### PR DESCRIPTION
**Pull request by ststefa**
Signed-off-by: Stefan Steinert ststefa@heldenzeit.net

Description of the change

The change fixes a faulty naming in the HorizontalPodAutoscaler (HPA) of the Thanos receive-distributor component, making it impossible to enable HPA for that component. K8s will reject the manifest with:

Error: HorizontalPodAutoscaler.autoscaling "thanos-receive-distributor" is invalid: spec.scaleTargetRef.name: Invalid value: "apps/v1": may not contain '/'

The change mimics the naming scheme for the other Thanos components and should be simple enough to not require any more prose.

Benefits

Ability to enable HPA for Thanos receive-distributor

Checklist

[x] Chart version bumped in Chart.yaml according to semver.
[x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
[x] All commits signed off and in agreement of Developer Certificate of Origin (DCO)

### CODE REVIEW

**Review by fmulero — CHANGES_REQUESTED** [review]
Hi @ststefa , Thanks a lot for your contibution!

LGTM, but reviewing it I've seen more failures in the file that I wouldn't like to loose. Could you have a look to ststefa/charts#1 and include those changes in your PR?

**Comment by ststefa** [comment]
Sure! I suppose you know what you're doing so I merged it into my master.

**Review by fmulero — CHANGES_REQUESTED** [review]
Hi @ststefa Sorry to disturb you again.  Please merge changes from master in your branch and increase the version of the chart. Pull request #9172 was merged yesterday and version 9.0.6 of this chart already exists

**Comment by ststefa** [comment]
@fmulero , ok, done. If you could do me the favour please have the PR merged before somebody else makes another change to it again.

**Review by fmulero — COMMENTED** [review]
LGTM

**Review by fmulero — APPROVED** [review]

**Comment by fmulero** [comment]
Thanks a lot @ststefa !

**Comment by ststefa** [comment]
:fireworks:

**Pull request merged**
