### PR TITLE
[bitnami/redis] corrected array defaults in readme

### PR DESCRIPTION
**Pull request by Mario-F**
**Description of the change**

Updated README with actual disableCommands values from values.yaml

**Checklist** 
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Review by juan131 — CHANGES_REQUESTED** [review]
Hi @Mario-F 

Are you using the [readme-generator](https://github.com/bitnami-labs/readme-generator-for-helm) tool to automatically regenerate the README.md? If not, please do so since it automatically generates the parameters tables based on the **values.yaml** metadata.

**Comment by Mario-F** [comment]
Hey @juan131 

I was digging a bit into this topic and found duplicate MR https://github.com/bitnami/charts/pull/7007 with attached issue https://github.com/bitnami-labs/readme-generator-for-helm/issues/6 that should solve this problem.

Ive cloned the readme-generator and tried on redis values.yaml but it does not work and the provides example in aspnet-core does not use the Array metadata flag and for example `startCommand` value is simply shown as string in README.

**Comment by juan131** [comment]
You're right @Mario-F .. It seems we brought up this topic before but the readme-generator tools was blocking us.. Could you please try applying the changes below in the **values.yaml** and running the tool?

```diff
index 51328722f..246b1cb31 100644
--- a/bitnami/redis/values.yaml
+++ b/bitnami/redis/values.yaml
@@ -145,7 +145,7 @@ master:
   ## ref: https://redis.io/topics/config
   ##
   configuration: ""
-  ## @param master.disableCommands [array] Array with Redis&trade; commands to disable on master nodes
+  ## @param master.disableCommands Array with Redis&trade; commands to disable on master nodes
   ## Commands will be completely disabled by renaming each to an empty string.
   ## ref: https://redis.io/topics/security#disabling-of-specific-commands
   ##
```

**Comment by Mario-F** [comment]
@juan131 yep that does the trick, i removed the [array] from values.yaml metadata and now README.md is full generated again.

**Review by juan131 — APPROVED** [review]
LGTM

**Comment by vanhoutenbos** [comment]
Thank you for adding this! We struggled setting this up so much, we eventually got it but this will definitely help people later on!

**Pull request merged**
