### PR TITLE
[biitnami/grafana] Add serviceAccount.create and serviceAccount.name to grafana chart

### PR DESCRIPTION
**Pull request by sventschui**
**Description of the change**

Adds the `serviceAccount.name` and `serviceAccount.create` config options to the grafana chart.

**Benefits**

Allows to use the grafana chart in clusters enforcing secret linking. (See #1982 )

**Possible drawbacks**

**Applicable issues**

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by juan131** [comment]
Hi @sventschui 

Thanks so much for the PR! Could you please rebase your branch for master and update the PR? There are some conflicts with master branch at this very moment.

**Comment by sventschui** [comment]
@juan131 You're welcome. Just did the rebase :)

**Comment by juan131** [comment]
Waiting for CI/CD to update image tags

**Comment by juan131** [comment]
Hi @sventschui 

In order to update the image tags to point to latest releases, our CI/CD needs to modify you PR (`bitnami-bot` will update `values.yaml` and `values-production.yaml` for you). To do so, it's necessary you allow "edits from maintainers". Find more information in the link below:

- https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by sventschui** [comment]
Hi @juan131 . Either I'm not seeing things clear or I seem not to be able to tick that checkbox. Maybe because the fork is in an organization repo. I invited `bitnami-bot` to join the repo as a collaborator. Would it work if you'd accept that invitation?

If that doesn't work out I'll fork the repo to my personal account and re-open the PR.

**Comment by juan131** [comment]
That should be enough @sventschui !! Collaboration invitation accepted 
Please revert your branch from master, and I'll trigger the CI/CD

**Comment by sventschui** [comment]
@juan131 did the rebase

**Pull request merged**
