### PR TITLE
[bitnami/vault] Only mount data volume if persistence is enabled

### PR DESCRIPTION
**Pull request by emoreth**
Current chart tries to mount data volume even if persistence is disabled.

### Description of the change

Adds a conditional to add a volumeMount for data. 

### Benefits

This is useful when we are running with `vault.server.command: ["vault", "server", "-dev"]` to install vault on dev mode only.

### Possible drawbacks

N/A

### Applicable issues

N/A
### Additional information

N/A

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your contribution! Could you please rebase from the `main` branch and bump the chart version in the Chart.yaml? Thanks

**Comment by emoreth** [comment]
@carrodher done.

FWIW, I wasn't able to make vault work with Bitnami's docker image. This is how a minimal version (least resources) of a vault deployment for dev worked for me.

```yaml
vault:
  server:
    args:
      - "server"
      - "-dev"
      - "-dev-root-token-id"
      - "VAULT_FAKE_TOKEN"
      - "-address"
      - "http://0.0.0.0:8200"
    config: ""
    image:
      debug: true
      repository: vault
      tag: 1.13.3
    persistence:
      enabled: false
    metrics:
      enabled: false
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
    networkPolicy:
      enabled: false
    serviceAccount:
      create: false
    rbac:
      create: false
    pdb:
      create: false
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
  injector:
    enabled: false
  volumePermissions:
    enabled: false
```

**Comment by javsalgar** [comment]
Hi! It seems there is an issue with the DCO. Could you fix it?

**Comment by emoreth** [comment]
Fixed

**Review by jotamartos — APPROVED** [review]
LGTM! Thank you for your contribution.

**Pull request merged**
