### PR TITLE
[bitnami/thanos] Receive, ruler & storegateway statefulsets persistentVolumeClaimRetentionPolicy support

### LINKED ISSUE #25339: [bitnami/thanos] Statefulsets persistentVolumeClaimRetentionPolicy support
### Name and Version

bitnami/thanos 15.2.1

### What is the problem this feature will solve?

It'll solve the lack of support for persistentVolumeClaimRetentionPolicy on statefulsets.

### What is the feature you are proposing to solve the problem?

Implement support for persistentVolumeClaimRetentionPolicy in statefulset resources just like it has already been done for other charts in this repo.

### What alternatives have you considered?

Using my own fork of the chart until this is addressed.

### PR DESCRIPTION
**Pull request by clarifai-fmarceau**
### Description of the change

These changes add persistentVolumeClaimRetentionPolicy support to statefulsets of the Thanos Helm chart.

### Benefits

We can now set persistentVolumeClaimRetentionPolicy.whenScaled & persistentVolumeClaimRetentionPolicy.whenDeleted for Ruler, Receive & Store Gateway individually.

### Possible drawbacks

None, the change is feature flagged and if enabled the defaults are aligned with the Kubernetes ones.

### Applicable issues

- fixes #25339 

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

**Comment by clarifai-fmarceau** [comment]
> Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).
> 
> Feel free to reach out if you have any questions or need assistance with the signing process.

Just signed an empty commit in my fork's branch, is that enough !? I'm sorry about that, I thought that having my signed on Github directly was it/ was enough.

**Comment by carrodher** [comment]
It seems it's not enough since the DCO action is still failing. [Here](https://github.com/bitnami/charts/pull/25676/checks?check_run_id=24901044812) you can see the details and how to fix the issue.

**Comment by clarifai-fmarceau** [comment]
Thank you for pointing me to that doc! Done, signed off every commit.

**Review by juan131 — CHANGES_REQUESTED** [review]
Thanks for this great contribution! Please ensure you merge latest changes from `main` branch and resolve the conflicts.

Also, please note the [PersistentVolumeClaim retention](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention) was included in Kubernetes 1.23 and therefore, we should include take it into account introducing the safeguard below:

```
{{- if semverCompare ">=1.23-0" (include "common.capabilities.kubeVersion" .) -}}
```

**Comment by juan131** [comment]
@clarifai-fmarceau did you see my last comment?

**Comment by clarifai-fmarceau** [comment]
> @clarifai-fmarceau did you see my last comment?

Fixed ! Hopefully we can now merge this !

**Review by juan131 — APPROVED** [review]
LGMT! Thanks so much for the contribution

**Pull request merged**
