### PR TITLE
[bitnami/keycloak] Fix externalDatabase property population

### PR DESCRIPTION
**Pull request by sullrich84**
#### Description of the change
The `_helper.yaml` already takes into account the `externalDatabase` fields. This exclusion in the `configmap-env-vars.yaml` seems to be unnecessary and erroneous since it wouldn't populate **any** database related environment variables when `externalDatabase` is defined.

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Please note the condition is checking `externalDatabase.existingSecret` which is used to use an existing secret file with the external PostgreSQL credentials. Configuring the external database parameters without setting `externalDatabase.existingSecret`, should render all the env. variables:
```yaml
postgresql:
    enabled: false
externalDatabase:
  host: "test"
  port: 1111
  user: "test-user"
  password: "test-pass"
  database: "test-db"
```
```console
$ helm template bitnami/keycloak --generate-name -f my-values.yaml -s templates/configmap-env-vars.yaml
# Source: keycloak/templates/configmap-env-vars.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-keycloa-env-vars
  namespace: default
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-6.1.1
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: keycloak
data:
  KEYCLOAK_CREATE_ADMIN_USER: "true"
  KEYCLOAK_ADMIN_USER: "user"
  KEYCLOAK_MANAGEMENT_USER: "manager"
  KEYCLOAK_HTTP_PORT: "8080"
  KEYCLOAK_PROXY_ADDRESS_FORWARDING: "false"
  KEYCLOAK_ENABLE_STATISTICS: "false"
  KEYCLOAK_DATABASE_HOST: "test"
  KEYCLOAK_DATABASE_PORT: "1111"
  KEYCLOAK_DATABASE_NAME: "test-db"
  KEYCLOAK_DATABASE_USER: "test-user"
  KEYCLOAK_CACHE_OWNERS_COUNT: "1"
  KEYCLOAK_AUTH_CACHE_OWNERS_COUNT: "1"
  KEYCLOAK_ENABLE_TLS: "false"
```

**Comment by sullrich84** [comment]
Thanks for reporting back @carrodher. The problem you've described is the exact setup I have right now. I have 
`externalDatabase.host`, `externalDatabase.user`, `externalDatabase.database` and `externalDatabase.port` defined in my values plus `externalDatabase.existingSecret` with a reference which contains the `postgresql-password`. The result is that this block (containing non secret data) is missing: 

```
  KEYCLOAK_DATABASE_HOST: "test"
  KEYCLOAK_DATABASE_PORT: "1111"
  KEYCLOAK_DATABASE_NAME: "test-db"
  KEYCLOAK_DATABASE_USER: "test-user"
```

Am I missing something?

**Comment by sullrich84** [comment]
> Are you setting `postgresql.enabled` to _false_ in order to disable the bundled PostgreSQL subchart?

Yes, `postgresql.enabled = false` and also `postgresql.persistence.enabled = false`.

**Comment by carrodher** [comment]
It seems the idea behind the PR where this feature was implemented was that the environment variables should be part of the secret and then, not needed to specify them in the configmap, see https://github.com/bitnami/charts/pull/5844

Can you share how the secret is being defined? Just to reproduce the exact same steps

**Comment by sullrich84** [comment]
@carrodher thanks for the feedback. I can see why #5844 was created, however I think this is counter intuitive since this kind of properties (`host`, `port`, `username`) are usually not shared in secrets (please correct me if I'm wrong). 

This is how the secret is being defined:

```
{{- if and (not .Values.auth.existingSecret) (not .Values.auth.existingSecretPerPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "existingSecret" .Values.auth.existingSecret "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.adminPassword }}
  admin-password: {{ .Values.auth.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.managementPassword }}
  management-password: {{ .Values.auth.managementPassword | b64enc | quote }}
  {{- else }}
  management-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
  postgresql-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.tls.enabled }}
  {{- if or .Values.auth.tls.keystorePassword .Values.auth.tls.autoGenerated }}
  tls-keystore-password: {{ (.Values.auth.tls.keystorePassword | default (randAlphaNum 10)) | b64enc | quote }}
  {{- end }}
  {{- if or .Values.auth.tls.truststorePassword .Values.auth.tls.autoGenerated }}
  tls-truestore-password: {{ (.Values.auth.tls.truststorePassword | default (randAlphaNum 10)) | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
```

**Review by carrodher — APPROVED** [review]
Thanks for the explanations, I'm launching some internal tests; if everything works as expected, this PR will be automatically merged

**Comment by sullrich84** [comment]
Thanks for your support @carrodher

**Pull request merged**
