### PR TITLE
[bitnami/kubeapps] Kubeapps vmware tanzu

### PR DESCRIPTION
**Pull request by absoludity**
**Description of the change**

The first commit updates all links to our main kubeapps repo to use the new organization (vmware-tanzu).

The second commit updates the links to our documentation to use the new locations after a recent documentation restructure.

**Benefits**

Uses the new GH org and links are correct to the new doc locations.

**Possible drawbacks**

**Applicable issues**

  - https://github.com/vmware-tanzu/kubeapps/issues/4532

**Additional information**

@castelblanque I think I remember you mentioning the doc updates in the standup yesterday - but couldn't see any PR so maybe you just mentioned that they needed doing? Hopefully I'm not doubling up.

@migruiz4 or @carrodher : I see I just accidentally pushed this to a branch on the bitnami/charts repo . Let me know if that's an issue and I'll recreate it on my own org, but longer term, I don't think I need write access here, so might be better to remove it?

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [N/A] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by absoludity** [comment]
Woah - cool! I was just checking the diff and thought "I didn't update the image tags?!" then saw the extra commit: "Update README.md with the readme-generator-for-helm"! It just keeps getting better... well done content team!

**Comment by carrodher** [comment]
> @migruiz4 or @carrodher: I see I just accidentally pushed this to a branch on the bitnami/charts repo. Let me know if that's an issue and I'll recreate it on my own org, but longer term, I don't think I need write access here, so might be better to remove it?

Thanks, @absoludity, it is not a problem, we don't have any restrictions regarding branches, in fact, the branch is automatically removed once the PR is merged. It's not strictly necessary to fork the repo, no problem.

**Review by carrodher — DISMISSED** [review]
LGTM

**Comment by castelblanque** [comment]
> maybe you just mentioned that they needed doing? Hopefully I'm not doubling up

@absoludity No changes had been done, so no worries. I just mentioned that it needed to be done, your changes are not doubling up 😄

**Review by carrodher — APPROVED** [review]

**Comment by absoludity** [comment]
Thanks!

**Pull request merged**
