### PR TITLE
[bitnami/keycloak] Fix broken theme assets by append the httpRelativeURL to the KC-HOSTNAME

### LINKED ISSUE #28161: [bitnami/keycloak] new hostname env var does not add httpRelativePath
### Name and Version

bitnami/keycloak:21.7.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install the chart with a httpRelativePath configured

### Are you using any custom parameters or values?

```yaml
keycloak:
  enabled: true
  httpRelativePath: /auth/
  ingress:
    enabled: true
    hostname: myHost.local
 ```

### What is the expected behavior?

The env var KC_HOSTNAME_URL should match the full URL: https://myHost.local/auth

### What do you see instead?

The variable only contains the hostname, but not the path:
```
KC_HOSTNAME_URL:              https://myHost.local
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gtudan**
### Description of the change

This fixes broken theme links and admin console when a httpRelativeURL is configured. Problem was that the KC_HOSTNAME variable did not take that path into account.

I rearranged the URL concatenating a bit, as the line was getting very long and hard to read. Hope that's okay :-)

Also covers the KC_ADMIN_HOSTNAME variable

### Benefits

Exposing the full URL should ensure that all assets are resolved probably. This also follows the new Hostname v2 configuration semantics of keycloak.

### Possible drawbacks

The ingress has a couple of additional options (extraPath) that might also be relevant to this. I did not include them, as I don't fully understand the scenario for which they are intended.

### Applicable issues

- fixes #28161 #25963

### Additional information

Current behavior is breaking every installation that uses a relative path - so I think this fix is rather critical

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

**Comment by rblaine95** [comment]
I believe this PR will also address bitnami/charts#25963,

**Comment by gtudan** [comment]
@carrodher Thanks for looking into this! I've updated the PR and fixed the sign-off

**Review by andresbono — APPROVED** [review]
LGTM, thank you so much for your contribution!!

**Pull request merged**
