### PR TITLE
[bitnami/mysql] Add service account for mysql

### PR DESCRIPTION
**Pull request by sventschui**
**Description of the change**

Adds a service account to the mysql helm chart that is linked to the secrets created

**Benefits**

Chart runs in a cluster where secret linking is required

**Possible drawbacks**

**Applicable issues**

  - none

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

Thanks for the PR. Could you elaborate in the use case and which clusters require this kind of linking?

**Comment by sventschui** [comment]
This is required if the cluster is configured with `serviceAccountConfig.limitSecretReferences=true` (see https://docs.openshift.com/container-platform/3.11/dev_guide/service_accounts.html#managing-allowed-secrets). As our cluster is operated by our international OpenShift team I can not really elaborate why they chose to configure the cluster this way. If you insist I can try to ask them tomorrow.

**Comment by javsalgar** [comment]
Thanks for the context. Yes, that flag would be helpful

**Comment by javsalgar** [comment]
Hi,

Just a quick note to ask if you could add the flag and fix the merge issues. Thanks!

**Comment by sventschui** [comment]
Yes I‘ll do so ASAP. Latest on monday

**Comment by sventschui** [comment]
@javsalgar there you go :) Added the `serviceAccount.create` and `serviceAccount.name` config options while the former defaults to `true`

**Comment by javsalgar** [comment]
Thanks! Merged it

**Pull request merged**
