### PR TITLE
[bitnami/kafka] Update lock file to get latest version of Zookeeper chart

### PR DESCRIPTION
**Pull request by mehta-ankit**
**Description of the change**

Updates the Chart.lock file to get latest version of Zookeeper chart.
From 6.5.4 to 6.7.0

**Benefits**

I believe without this change, if Chart A has kafka chart as dependency and uses latest version of kafka chart (12.16.0) and tries to use `helm dep update`, zookeeper chart version pulled is 6.5.4 instead of the latest (6.7.0). 

**Possible drawbacks**

Should be no side-effects.

**Applicable issues**

  - fixes #

**Additional information**

Related converstation: https://github.com/bitnami/charts/pull/5996#issuecomment-814332142

**Checklist** 

- [] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by alvneiayu** [comment]
Hi @mehta-ankit 

You are having a conflict with the master branch. Seems that the Chart.lock is already updated. However thanks for the PR and do not hesitate to contact me if you need something else.

Thanks

Álvaro

**Comment by mehta-ankit** [comment]
> Hi @mehta-ankit
> 
> You are having a conflict with the master branch. Seems that the Chart.lock is already updated. However thanks for the PR and do not hesitate to contact me if you need something else.
> 
> Thanks
> 
> Álvaro

Haha nice, so now it got updated automatically 😅. Closing this PR 

@alvneiayu just to confirm, should i have updated the lock file myself in my previous PR or waited for the bot to do it. What is the right way to do it  ??

**Comment by alvneiayu** [comment]
hi @mehta-ankit

It depends. I prefer to wait the automatic update by the bot. This kind of automation avoids problems.

I hope that I helped you. Thanks again

Álvaro

**Comment by mehta-ankit** [comment]
Thank you!

**Pull request closed without merging**
