### PR TITLE
[bitnami/common] Fix typo in README

### PR DESCRIPTION
**Pull request by CaptainPatate**
**Description of the change**

Fix a typo.

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by bl-ue** [comment]
Hi @CaptainPatate! I recently opened [a PR](https://github.com/bitnami/charts/pull/4699) that fixes [this same typo](https://github.com/bitnami/charts/pull/4699/files#diff-da48a313c10dac005517380f474b8c887401ffbe04e241593f80a69403b61548L104-R104), along with many others.  Would you consider closing this one in favor of mine, to avoid introducing conflicts?

**Comment by CaptainPatate** [comment]
@bl-ue I forgot to check opened PR. Yes sure, I'll close it as yours fix a lot more typos.

**Comment by bl-ue** [comment]
>I forgot to check opened PR

I make that mistake all the time too :smile: ...hopefully I didn't this time...

**Comment by miguelaeh** [comment]
Thank you for fixing this guys! We are already taking care of the referenced PR!

**Pull request closed without merging**
