### PR TITLE
[bitnami/mongodb] Network policy review

### LINKED ISSUE #25340: Allow templating NetworkPolicy ingressNSMatchLabels values?
### Name and Version

bitnami/mongodb 15.1.5

### What is the problem this feature will solve?

I'm looking to lock down NetworkPolicies to only allow ingress traffic from the same namespace as the deployment.

### What is the feature you are proposing to solve the problem?

Conceptually, I was thinking I could configure the chart like so:
```yaml
networkPolicy:
  allowExternal: false
  ingressNSMatchLabels:
    kubernetes.io/metadata.name: "{{ .Release.Namespace }}"
```

However the chart [takes the raw](https://github.com/bitnami/charts/blob/288a544c640bd8850b6e2b40c254d246952524a9/bitnami/mongodb/templates/networkpolicy.yaml#L82) `ingressNSMatchLabels` values, so I cannot use `{{ .Release.Namespace }}` here.

Is it possible to render these values to accommodate this use case?  Is there another way already possible in the chart to do this that I'm not seeing?

The verbiage in the README is a little confusing I also think. `allowExternal` is a value, but if I understand correctly it's not really about external so much as requiring the pod to have a specific label, regardless of the namespace.  Similarly on the description for `ingressNSMatchLabels`:  `Labels to match to allow traffic from other namespaces` but it doesn't look like the namespace restriction is in place to begin with.

This issue is specific to the MongoDB chart but it looks like most NetworkPolicies in this repository follow the same template, so for consistency sake, it may be scoped to more charts than just this.

### PR DESCRIPTION
**Pull request by fmulero**
### Description of the change

Review network policy features to allow users cover their needs without forcing specific labels.

### Benefits

Users can restrict access to their deployments in a cleaner way, without leaving open doors to specific labeled pods.

### Possible drawbacks

None

### Applicable issues

- fixes #25340

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Users in the past have reported that using templates inside values.yaml may potentially break argo-cd deployments: https://github.com/bitnami/charts/issues/19173

If we went on with this change we may add issues to all charts in argo-cd. I would add an if-else or something similar to avoid adding that templated values. We may need to see what happens in other charts that we currently use templated values.

**Review by rafariossaa — APPROVED** [review]
LGTM

**Comment by fmulero** [comment]
@javsalgar I've just applied a possible solution. It works but the templates are becoming more complicated. Any thoughts?

**Review by rafariossaa — DISMISSED** [review]
LGTM

**Review by javsalgar — APPROVED** [review]

**Pull request merged**
