### PR TITLE
[rabbitmq] Add service account to rabbitmq chart

### PR DESCRIPTION
**Pull request by sventschui**
**Description of the change**

Add service account to rabbitmq chart

**Benefits**

**Possible drawbacks**

**Applicable issues**

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by rafariossaa** [comment]
Hi @sventschui ,
  Thank you very much for you PR, we are testing it in our CI/CD.

**Comment by sventschui** [comment]
@rafariossaa did a rebase to resolve conflicts

**Comment by marcosbc** [comment]
The changes are fine to merge.

However, in order to update the image tags to point to latest releases, our CI/CD needs to modify you PR (`bitnami-bot` will update `values.yaml` and `values-production.yaml` for you). To do so, it's necessary you allow "edits from maintainers". Find more information in the link below: 
- https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Let us know if you find issues doing so.

**Comment by sventschui** [comment]
As discussed in one of my previous PRs (https://github.com/bitnami/charts/pull/2109#issuecomment-604256578) this is not possible for an organization repo but the bitnami-bot is an outside collaborator of our repo. Is that enough?

**Comment by marcosbc** [comment]
OK. In that case I will launch our CI, it won't publish this version (6.26.0) but instead the fix will appear in a posterior release (i.e. 6.26.1, 6.27.0 or 7.0.0).

**Comment by marcosbc** [comment]
Sorry for the delay. Yesterday it seems like another release happened for the chart so there are conflicts again. Would you mind rebasing again to resolve conflicts? Thanks!

**Comment by sventschui** [comment]
@dansailer can you take over?

**Comment by carrodher** [comment]
I'm closing this PR since those options are already part of the Helm chart, see
```console
$ ag 'serviceAccount'
values.yaml
652:serviceAccount:
653:  ## @param serviceAccount.create Enable creation of ServiceAccount for RabbitMQ pods
656:  ## @param serviceAccount.name Name of the created serviceAccount
660:  ## @param serviceAccount.automountServiceAccountToken Auto-mount the service account token in the pod

templates/_helpers.tpl
54:{{- define "rabbitmq.serviceAccountName" -}}
55:{{- if .Values.serviceAccount.create -}}
56:    {{ default (include "rabbitmq.fullname" .) .Values.serviceAccount.name }}
58:    {{ default "default" .Values.serviceAccount.name }}

templates/serviceaccount.yaml
1:{{- if .Values.serviceAccount.create }}
5:  name: {{ include "rabbitmq.serviceAccountName" . }}
11:automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}

templates/statefulset.yaml
46:      serviceAccountName: {{ template "rabbitmq.serviceAccountName" . }}

templates/rolebinding.yaml
1:{{- if and .Values.serviceAccount.create .Values.rbac.create }}
13:    name: {{ template "rabbitmq.serviceAccountName" . }}

README.md
195:| `serviceAccount.create`                       | Enable creation of ServiceAccount for RabbitMQ pods | `true` |
196:| `serviceAccount.name`                         | Name of the created serviceAccount                  | `""`   |
197:| `serviceAccount.automountServiceAccountToken` | Auto-mount the service account token in the pod     | `true` |
549:  - New parameters: `serviceAccount.create`, and `serviceAccount.name`.
```

**Pull request closed without merging**
