### PR TITLE
[bitnami/postgres] Transition to Primary/Replica terminology

### PR DESCRIPTION
**Pull request by kav**
**Description of the change**
Replaces master and slave with primary and readReplicas respectively. I've coalesced the respective values so existing configurations will continue to work but have updated all the docs to point to the newer terms.

**Benefits**
Let's use more inclusive language. Honestly it's more clear with primary and read replica terms what the actual difference is. Happy to tweak further of course. Just saw in my comment on the linked issue it perhaps should be standby?

**Possible drawbacks**
We currently use master and slave in pod names and labels and I've transitioned that. This may break custom scripts that are looking for those markers. I've bumped as non-breaking since values will still work fine but this might justify amending that.

I've not changed environment variables or anything that may require work on the image itself. Yet.

**Applicable issues**

  - related https://github.com/bitnami/bitnami-docker-postgresql/issues/175

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the PR. However, I'm still not fully convinced that this may not need a major bump. Could you confirm that there are no issues with immutable fields when upgrading (for example, with a deployed networkpolicy)?

**Comment by kav** [comment]
Oh good point, let me verify. If we need a major bump would you propose keeping the coalesce or moving to new terms completely?

**Comment by javsalgar** [comment]
If we need a major bump I would not maintain the coalesce, but I would also add an extra set of standard parameters to the chart. We are in the process of adding these standardizations to all of our charts so I think that we can hold this PR and integrate everything in one major version bump (instead of having two that would be very painful for users).

**Comment by kav** [comment]
Should we start a branch for the breaking changes, I'll update and PR to that or something else? What's the standard y'all are using here?

**Comment by javsalgar** [comment]
Hi,

I just created this branch: `postgres-chart-v10`. Could you point to the PR to this branch?

**Comment by javsalgar** [comment]
It seems there are some conflicts, could you check them?

**Comment by kav** [comment]
I've merged but the changes in that branch don't lint successfully so I wasn't able to confirm I got a clean merge. Fairly certain but...

**Comment by javsalgar** [comment]
However, before merging, could you fix this?

```
[ERROR] templates/: template: postgresql/templates/statefulset.yaml:35:22: executing "postgresql/templates/statefulset.yaml" at <.Values.master.podLabels>: nil pointer evaluating interface {}.podLabels
```

**Comment by kav** [comment]
Hey @javsalgar looks like the postgres v10 branch is gone and not merged. Do you want me to reopen this?

**Comment by javsalgar** [comment]
Hi! Sorry, there was a remote branch cleanup and it was accidentally deleted. We should restore that branch or re-create it again.

**Pull request merged**
