### PR TITLE
[bitnami/influxdb] influx CLI command issues

### PR DESCRIPTION
**Pull request by jcalvarado1965**
Signed-off-by: Juan Alvarado <jcalvarado1965@gmail.com>

**Description of the change**

The influx CLI commands used to generate the backup files were broken (the --host parameter appeared before the actual commands which caused the affected commands to error out). Maybe this used to work in an earlier version of the CLI but it is definitely broken now. Now the commands have the right form.

**Benefits**

The format of the commands is correct.

**Possible drawbacks**

The backup procedure is still somewhat broken for azure, because the azure CLI tries to install azcopy when the az storage blob sync command is issued, and this fails for non-root users. This can be addressed in a future change.

**Applicable issues**

I did not enter an issue for this. Not sure if there is one.

**Additional information**

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by marcosbc** [comment]
Hi @jcalvarado1965, for legal reasons, I'm afraid we will be unable to merge this request for now. If we need to use the `azcopy` command it should be packaged in the `azure-cli` container image. Therefore, we'd encourage you to open a new issue in the respective `bitnami-docker-azure-cli` repository to add the package.

(Something else that could be tried in the `azure-cli` container image could be to grant write privileges for non-root users (`g+rwX /bin`) so that the `az storage` command does not fail.)

**Comment by jcalvarado1965** [comment]
Thanks for the feedback. I can take out the azcopy changes and open the the issue on azure cli, but can I leave the fixes for the influx CLI commands? As it stands they are broken.

**Comment by marcosbc** [comment]
Sure! That would be great

**Comment by jcalvarado1965** [comment]
Ok I've pruned back the release so only the influx commands are fixed. Let me know if there is anything else. Thanks!

**Review by marcosbc — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
