### PR TITLE
[bitnami/airflow]Update statefulset-worker.yaml

### PR DESCRIPTION
**Pull request by wsxiaoys**
Fix nindent to be 12 when extraEnvVars is set

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by alemorcuq** [comment]
Thanks for the fix, @wsxiaoys !

**Comment by wsxiaoys** [comment]
Great! How long does it take to release the change to chart repo?

**Comment by alemorcuq** [comment]
> Great! How long does it take to release the change to chart repo?

Looks like it's already updated:

```
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.

$ helm search bitnami/airflow
NAME           	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/airflow	4.0.18       	1.10.6     	Apache Airflow is a platform to programmatically author, ...
```

**Comment by wsxiaoys** [comment]
Great, thanks!

**Pull request merged**
