### PR TITLE
[bitnami/rabbitmq-cluster-operator] Fix indentation typo in msgTopologyOperator metrics service selector

### PR DESCRIPTION
**Pull request by sviatlo**
### Description of the change

Fix identation typo in msgTopologyOperator metrics service selector

### Benefits

Fixes `Error: YAML parse error on rabbitmq-cluster-operator/templates/messaging-topology-operator/metrics-service.yaml: error converting YAML to JSON: yaml: line 29: mapping values are not allowed in this context`.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by sviatlo** [comment]
In order to reproduce the issue I have with 3.7.2, deploy the operator with the following values:
```
msgTopologyOperator:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
```

**Comment by sviatlo** [comment]
Hello @javsalgar, I understand that you are very busy, but maybe you can find a few minutes to help me push this through? Thank you!

**Comment by aschleifer** [comment]
This basically makes the chart unusable after version 3.7.0. I would appreciate a fast fix.

**Review by joancafom — APPROVED** [review]
LGTM! Thanks for the changes 🚀

**Pull request merged**
