### PR TITLE
[bitnami/mysql]  feat: adds any extraPorts entries into the NetworkPolicy's ingress config

### LINKED ISSUE #23893: [bitnami/mysql] Automatically Add Any `extraPorts` to `NetworkPolicy` Ingress
### Name and Version

bitnami/mysql 9.21.2

### What is the problem this feature will solve?

There may be a good reason why this isn't done, but I thought I'd suggest it anyway in order to save people a few hours of hunting around. (If I've missed something, please feel free to let me know and close this request.)

Currently, if any `extraPorts` are added (e.g. exposing 33060 for `mysqlx` and the X plugin), the relevant service still can't be reached unless `networkPolicy.extraIngress` is added with the corresponding port(s).

I'd assume (perhaps incorrectly) that if people are using `extraPorts` to expose new ports, then they are probably looking to access the pods/services from outside the MySQL pod/container itself.

### What is the feature you are proposing to solve the problem?

One of two things:

- Automatically add or map `extraPorts` to an additional `ingress` block in the `NetworkPolicy`; or,
- Update the `extraPorts` docs to indicate that people should probably add those same ports to the `networkPolicy.extraIngress` setting if they want to be able to access those ports externally.

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by BHSDuncan**
### Description of the change

Ports specified in the settings below will be automatically added to the `NetworkPolicy`'s `ingress` block:

- `primary.extraPorts`
- `primary.service.extraPorts`
- `secondary.extraPorts`
- `secondary.service.extraPorts`

### Benefits

Since users who make use of specifying `*.extraPorts` are likely to be looking to access the pod/service from outside of the deployed pods themselves, it makes sense to automatically add the ports specified into the `ingress` config of the `NetworkPolicy`, potentially saving the user time in having to track down why those pods/services remain inaccessible despite having made entries into the relevant `*.extraPorts` settings.

### Possible drawbacks

None at present.

### Applicable issues

- fixes #23893 

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by BHSDuncan** [comment]
Just giving this a quick bump so it doesn't go from 'stale' to 'closed'.

**Comment by CeliaGMqrz** [comment]
Hi @BHSDuncan 

Sorry for the delay. Thanks for your contribution!

Could you resolve the conflicts?

**Comment by BHSDuncan** [comment]
Done. I further updated the version number using what I believe are your guidelines.

Thanks again!

**Review by CeliaGMqrz — APPROVED** [review]
Thanks @BHSDuncan , LGTM!

**Pull request merged**
