### PR TITLE
[bitnami/prometheus-operator] Add new CRD for Probes from upstream

### LINKED ISSUE #3297: [bitnami/prometheus-operator] Missing CRDs for Synthetic Probes
**Which chart**: bitnami/prometheus-operator: 0.27.1

**Describe the bug**
Prometheus pod doesn't start.

**Additional context**
Prometheus operator v0.41.0 has added [Synthetic Probes](https://github.com/coreos/prometheus-operator/pull/2832) support which requires CRDs update.

### PR DESCRIPTION
**Pull request by joancafom**
Signed-off-by: joancafom <jcarmona@bitnami.com>

**Description of the change**
Add a new CRD introduced in upstream since version v0.41.0. Update CRD `prometheuses` to support this new feature as well

**Benefits**
A new CRD is supported

**Possible drawbacks**
Not really, as we are adding a new feature including in an upstream minor. 

**Applicable issues**

  - fixes #3297 

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by dani8art** [comment]
LGTM

**Comment by ahmgeek** [comment]
When this supposed to get into the registry?

**Comment by beltran-rubo** [comment]
Usually 2-3 hours to pass our tests but we are currently finding issues with our K8s clusters and the versions we are using. We are working on it.

**Comment by beltran-rubo** [comment]
@ahmgeek We fixed the testing errors we detected. There is already a new Prometheus Operator version available into the Helm repository 0.29.3 with those changes.

**Comment by ahmgeek** [comment]
@beltran-rubo thanks a Beltran 😽

**Pull request merged**
