### PR TITLE
Keycloak: fix truststore typos in Keycloak chart

### PR DESCRIPTION
**Pull request by cshields**
**Description of the change**

When using an existingSecret in the Keycloak chart there are a number of references to "truestore" when referring to "truststore".

That's pretty much it, fix the references to all be truststore.

**Benefits**

Keeps the terminology of keystore and truststore consistent..

**Possible drawbacks**

would require a change for anyone who implemented as "tls-truestore-password"

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by cshields** [comment]
See also https://github.com/bitnami/charts/issues/7796#issuecomment-945435456

**Comment by alemorcuq** [comment]
Thanks for filling a PR! I'm no entirely sure about this change, though. Yes, they are typos, but unless I'm missing something the chart works properly, right? Changing the keys now to `truststore` will break the chart for people using a secret with the `truestore` key. What are your thoughts?

**Comment by q-b** [comment]
Hi, we'd like to see this "fixed" as well.

**Comment by alemorcuq** [comment]
We are now working on the standardization of the Keycloak chart. As it will require a new major, we will take that as an opportunity to fix this typo.

**Pull request closed without merging**
