### PR TITLE
[bitnami/zookeeper] Fix: randomly failing readiness/liveness probes

### PR DESCRIPTION
**Pull request by bramk**
### Description of the change

Delay readiness/liveness probe netcat calls sending FIN by 1 second to prevent occasional empty response to ruok request.

### Benefits

No more occasionally failing readiness/liveness probes

### Possible drawbacks

OSx BSD netcat does not support the q option. Is that a problem?

### Applicable issues

- fixes bitnami/charts#20564

### Additional information

I do not think it makes sense to make the dealyt configurable.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by fmulero — COMMENTED** [review]
Hi @bramk, thanks a lot for your contribution!

QQ, Does it have any impact in `probeCommandTimeout` ? Here you are adding a delay of 1s and the default value for the `probeCommandTimeout` is 2s. Should it be increased in 1 second also?

**Comment by bramk** [comment]
Hi @fmulero 

> QQ, Does it have any impact in probeCommandTimeout ? Here you are adding a delay of 1s and the default value for the probeCommandTimeout is 2s. Should it be increased in 1 second also?

Hard to say.. 

I do not think the `-w 2` is affected by `-q 1`  and under normal circumstances zookeeper should still respond within single digit millisecond range anyway. Also because `.Values.probeCommandTimeout` is already used for both the `timeout` and the `-w` I guess it  is just about a sane default. Therefore IMHO 2 secs is still fine. In any case I see a major improvement over the old situation on our systems.

**Review by fmulero — APPROVED** [review]
LGTM

**Comment by mveitas** [comment]
What would the process be to get this backported to an older version of the zookeeper chart. I am using `11.4.11` and running into this issue

**Comment by mveitas** [comment]
I just added this to our existing chart as an override using the `customLivenessProbe` and the pods are restarting immediately. I am running with an older version of the chart (11.4.11)

```
  customLivenessProbe:
    exec:
      command:
        - /bin/bash
        - -c
        - echo "ruok" | timeout 2 nc -w 2 -q 1 localhost 2181 | grep imok
  customReadinessProbe:
    exec:
      command:
        - /bin/bash
        - -c
        - echo "ruok" | timeout 2 nc -w 2 -q 1 localhost 2181 | grep imok
```

**Pull request merged**
