### PR TITLE
[bitnami/mongodb] Change tag for a svc of mongo with replicaset enable 

### LINKED ISSUE #2304: MongoDB replicaset service
Hi, 

This is a doubt about the bitnami/mongodb chart. When I exec the chart with replicaset=true, the chart create two services: 

my-release-mongodb
my-release-mongodb-headless

On the first service (my-release-mongodb) there is only one endpoint to mongodb-primary pod. The second service (my-release-mongodb-headless) there are 3 endpoints (1 pod arbiter, 1 pod slave and 1 primary pod).

I want to expose this service from outside the cluster, if I expose the first service, the only pod that will receive connection is the "mongodb-primary".  If I expose the second service, all the pod will receive connections, including arbiter pod. It's correct?

There is a way to create a service only with the primary's and secondary's pods, without arbiters?

### PR DESCRIPTION
**Pull request by Mauraza**
**Description of the change**
Change in the tag component

**Benefits**
If the primary is dropped and becomes primary, the secondary can still access the Mongodb cluster

**Possible drawbacks**

**Applicable issues**

  - fixes #2304

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by marcosbc** [comment]
I think this can be problematic; the Bitnami MongoDB chart will not work properly when the master is down, and I think that is to be expected as failover is not implemented into the chart (even though MongoDB supports that) due to lack.

This change seems to be associating a secondary node to the 'primary' service, but the 'primary' service is only meant for the primary node, in the same way the 'secondary' service is meant for secondary nodes.

However, I might be wrong so I'm going to request a review from someone else.

**Comment by derom** [comment]
Pls consider this kind of connection string as a replacement for this pr:
mongodb://root:password@my-service-mongodb-primary-0.my-service-mongodb-headless.default.svc.cluster.local:27017,my-service-mongodb-secondary-0.my-service-mongodb-headless.default.svc.cluster.local:27017/

**Comment by marcosbc** [comment]
I asked more folks to check this and they did not like the approach. What @derom suggests should be enough to fix this issue, requiring no changes to the chart.

**Comment by Mauraza** [comment]
If for whatever reason you lose the `mongodb-primar-0` node, the PRIMARY role is adopted by other nodes. If you now add a new node to the cluster, it is going to register to `mongodb-primary-0`, but this node is not longer alive or it is not the PRIMARY, so the new node won't be added to the cluster

**Comment by emrahcetiner** [comment]
> This change seems to be associating a secondary node to the 'primary' service, but the 'primary' service is only meant for the primary node, in the same way the 'secondary' service is meant for secondary nodes.

I agree. This change may confuse primary reachability.

**Comment by alankwon** [comment]
I initially was using the 2 headless services like how @derom suggested. Then, I saw the comment from @juan131 about following the direction from "helm status my-release" command. I'm accessing it from the cluster and according to the notes, I should be using my-release-mongodb.default.svc.cluster.local, rather than the headless service. 

So, the notes, the comments, all seem to suggest: use the primary-0. When it goes down, wait 'till it comes back up as it will take over the primary role. Otherwise, I don't see the point of my-release-mongodb service definition. So, if that's the case, what exactly is the secondary node created for? I get that the minimum recommendation in a replica set is 3 nodes, but if you are not taking advantage of secondary nodes taking over the primary role, why deploy this as replica set? Just trying to understand the reasoning of this deployment logic.

**Comment by marcosbc** [comment]
Thanks for your input @alankwon. I agree that the current logic does not make much sense, and instead of having "mongodb-primary" and "mongodb-secondary" services, we should try to merge them into one (i.e. "mongodb-node" excluding arbiters). That way the failover would work properly.

**Comment by vpapadopoulos** [comment]
Primary & Secondary are  2 of many ephemeral  mongodb nodes states , not properties.
All mongodb replica nodes are just nodes, elligible to become Primary of Secondar during their lifecycle. There is no preference  to one over the others to become Primary. (priority field is by default 1 to all)
The first node that creates the replica set becomes the first Primary node. But you can not predict or make assumptions over which one will be the Primary at any time in the future.

This is why clients need to include ALL replica nodes in their connection URI, in order to automaticaly connect to the Primary node after each replica set election.

So having separate Primary and Secondary stateful sets makes no sense. And there is no use to put a load balancer in front of the replica set.

**Comment by marcosbc** [comment]
You're right @vpapadopoulos. It looks like the MongoDB Helm chart may require some refactor. @Mauraza is that something you will be able to do?

**Comment by Mauraza** [comment]
This PR is closed since this has been done https://github.com/bitnami/charts/pull/2918

**Pull request closed without merging**
