### PR TITLE
[bitnami/rabbitmq] Updating the tls certs through values.yaml not restarting the pods

### PR DESCRIPTION
**Pull request by rahulsadanandan**
### Description of the change

1) Moved the ingress tls secrets to a new file (aligned  with how it is done in bitnami/elasticsearch)
2) `tls-secret` now only contains the secret for rabbitmq certs
3) Added checksum tag to the `tls-secret` file  to restart the pods if there are changes to it

### Benefits

If the certs are changed in the secret it will automatically restart the pods

### Possible drawbacks

None

### Checklist

- [ x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
The failing action should be solved by rebasing from _main_, could you please do that? Thanks!

**Comment by aoterolorenzo** [comment]
Hi @rahulsadanandan 

Could you explain the changes proposed a little deeper? Thank you.

**Comment by rahulsadanandan** [comment]
@aoterolorenzo Sure.
When working with rabbitmq tls (amqps) and changing certificate via [values.yaml](https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/values.yaml#L188-L190), the rabbitmq pod should get restarted to pick the new certs. It not happening now, and we need to restart manually. 

So adding the checksum, in sts make sure there is a change and it restarts the pods.
Since the ingress certs are not related here, I split them into another file (similar like in bitnami/elasticsearch)

**Review by aoterolorenzo — APPROVED** [review]
LGTM!

**Comment by dyvol777** [comment]
after this change, there are 2 same annotations [here](https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/templates/statefulset.yaml#L36), that isn't acceptable by kubernetes, and installation failed. i think it should be different name for annotation

but also, as i know rabbitmq automatically reread certificates, so i am not sure, that this annotation required

@aoterolorenzo  if you want me to open different issue, say it

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Pull request merged**
