### PR TITLE
[bitnami/nats] Fix monitoring ingress endpoint

### LINKED ISSUE #6166: [bitnami/nats] nats-monitoring ingress 503 Service Unavailable
**Which chart**:
chart: bitnami/nats
version: 6.2.5

**Describe the bug**

When the ingress is enabled, the ingress backend is pointing to the wrong service name.

The monitoring service name is `{{ printf "%s-monitoring" (include "common.names.fullname" .) }}`,
however, the ingress service name is `(dict "serviceName" (include "common.names.fullname" $)`.

The inconsistent name will cause an ingress `endpoints not found` error.

**To Reproduce**

1. Enable `ingress.enabled` and set the hostname.
2. After the chart has finished installing, check http://hostname on the browser, it will show 503 Service Unavailable.

**Expected behavior**

The monitoring page should be able to access via the ingress.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by benjamin658**
**Description of the change**

Fixed the monitoring ingress endpoint.

**Benefits**

The monitoring page will work properly with nginx ingress.

**Possible drawbacks**

N/A

**Applicable issues**

  - fixes #6166

**Additional information**

N/A

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by alvneiayu** [comment]
hi @benjamin658 

Thanks for your PR and your time. LGTM.

Álvaro

**Comment by benjamin658** [comment]
Hi @alvneiayu , You're welcome.

I'm wondering that when will the Artifacthub <https://artifacthub.io/packages/helm/bitnami/nats> update the version to 6.2.6?

**Comment by alvneiayu** [comment]
hi @benjamin658  

I am checking internally. Please, I will come back with some feedback soon.

Thanks

Álvaro

**Comment by benjamin658** [comment]
No problem, thanks for your reply.

**Pull request merged**
