### PR TITLE
[bitnami/kafka] Allowing for customize dnsPolicy and dnsConfig for Kafka

### LINKED ISSUE #21319: [bitnami/kafka] Allowing for customize dnsPolicy and dnsConfig for Kafka & ZK
### Name and Version

bitnami/kafka 20.4.3

### What is the problem this feature will solve?

In the intranet K8S cluster, we have a server ip dedicated for DNS resolution, so we need to modify the dnsPolicy and dnsConfig to make the dns resolution work.

I would like to submit a patch for kafka and zookeeper.

### What is the feature you are proposing to solve the problem?

Like the config example in [this post](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config)

I have a patch for my own repo, and I wonder if this could be officially supported. https://github.com/siyuan0322/GraphScope/commit/f23b92f4573c407abc78e4073cac1cf90b16924d

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by siyuan0322**
### Description of the change

This PR add options to configure dnsPolicy and dnsConfig for Kafka charts.
### Benefits

It would allow users to fine grain their dns resolution process, especially useful in a intranet environment.
This is an example:
settings.yaml
```yaml
dnsService:
  enabled: true
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 192.0.2.1 # this is an example
    searches:
      - ns1.svc.cluster-domain.example
      - my.dns.search.suffix
    options:
      - name: ndots
        value: "2"
      - name: edns0
```

```bash
❯ helm template ./kafka -f settings.yaml | grep dnsPolicy -C 20
      securityContext:
        fsGroup: 1001
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 192.0.2.1
        options:
        - name: ndots
          value: "2"
        - name: edns0
        searches:
        - ns1.svc.cluster-domain.example
        - my.dns.search.suffix
```

### Possible drawbacks

I only add this to the controller statefulset of kafka.
 
### Applicable issues

- fixes #21319

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by fevisera** [comment]
Hi @siyuan0322,

Thank you for your contribution! Kindly split the implementation of this feature into two separate PRs. For more details, please refer to our [contribution guidelines](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#how-to-contribute).

Thanks!

**Comment by siyuan0322** [comment]
@fevisera Hi, do you mean to separate the implementation of Kafka and ZK into two PRs?

**Comment by fevisera** [comment]
Hi, 

Please do not create that new PR yet, I found an error.

I will give some more details.

**Comment by fevisera** [comment]
Hi @siyuan0322,

I have just double-checked and there is no red flag. Apologies for any inconvenience.

Please, go ahead and create a separate PR for ZK and Kafka.

Thank you!

**Comment by siyuan0322** [comment]
Hi @fevisera I have separated implementations into this PR (for Kafka) and #21519 (for ZooKeeper)

**Comment by fevisera** [comment]
Hi @siyuan0322,

Thank you for applying the changes. Kindly resolve the conflicts in `bitnami/kafka/Chart.yaml` by updating from `main` branch and bumping the version.

**Comment by siyuan0322** [comment]
@fevisera Hi, I have updated the param description according to zookeeper side's review.

**Review by fevisera — APPROVED** [review]
Thank you applying the changes!
LGTM!

**Pull request merged**
