### PR TITLE
[bitnami/memcached] Add optional emptyDir medium configuration

### PR DESCRIPTION
**Pull request by nhh**
### Description of the change

This change adds the ability to define the emptyDir configuration of memcache to be "Memory"

### Benefits

People can decide to configure their tmp directory to be tmpfs (RAM-backed filesystem)

### Possible drawbacks
See k8s docs for memory impact on tmpfs volumes: https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by andresbono — APPROVED** [review]
Hi @nhh, thank you for your contribution! The changes look good to me.

Could you explain a bit further what is your use case to configure emptyDir in memory?

**Comment by nhh** [comment]
@andresbono Thx for having a look! Sure, we deployed the bitnami chart with the default empty dir configuration. During a ddos, our system experienced increased load and kept crashing due to pods having issues connecting to memcached. 

Our on call team identified that, beneath other options tweaked, setting the emptydir config to memory significantly reduced crashes and stabilized the system.

Atm we have that option configured without being saved in our helm charts. Hope that helps :)

**Comment by andresbono** [comment]
Thank you very much for the additional context

**Comment by nhh** [comment]
Thank you all for your effort!

**Pull request merged**
