### PR TITLE
[bitnami/external-dns] docs: update registry doc url

### PR DESCRIPTION
**Pull request by hongbo-miao**
### Description of the change

Just a small update, fixed a dead link. ☺️

### Checklist

- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting. Could you bump the chart patch version? This is necessary for the automation to work

**Comment by hongbo-miao** [comment]
Done, thanks @javsalgar !

**Comment by carrodher** [comment]
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

**Comment by hongbo-miao** [comment]
Thanks @carrodher for reminding! Signed off. 😃

**Review by carrodher — APPROVED** [review]
LGTM

**Comment by hongbo-miao** [comment]
Hmm

**Pull request merged**
