### PR TITLE
[bitnami/kafka] Add egress custom rules

### PR DESCRIPTION
**Pull request by madrisan**
Signed-off-by: Davide Madrisan <davide.madrisan@gmail.com>

**Description of the change**

This PR add the possibility to define custom Egress rules.

**Benefits**

This feature is required in strict kubernetes environments where by default the Egress traffic is denied.

**Possible drawbacks**

This PR is backward compatible because in the default values the Egress custom rules are disabled.
The `.Values.networkPolicy.egressRules.denyConnectionsToExternal` is not implemented in this PR because I found it very complex for this chart. There are several components (kafka, zookeeper, metrics, jmx metrics) all of that must be configured in a default Egress rule.

**Applicable issues**

None

**Additional information**

None 

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Comment by rafariossaa** [comment]
Hi,
  Thanks you very much for adding this.

**Review by rafariossaa — APPROVED** [review]
LGTM.

**Review by rafariossaa — CHANGES_REQUESTED** [review]
Do you mind running this tool to regenerate the REAMDE ? https://github.com/bitnami-labs/readme-generator-for-helm/

**Comment by madrisan** [comment]
I've already run `readme-generator-for-helm` @rafariossaa

**Comment by rafariossaa** [comment]
Thanks.

**Pull request merged**
