### PR TITLE
[bitnami/grafana-operator] New major version

### PR DESCRIPTION
**Pull request by juan131**
Signed-off-by: juan131 <juanariza@vmware.com>

**Description of the change**

This PR bumps the major version since a new version of the operator was released (3.10.4) that updates the apiVersion of the CRDs.

**Benefits**

Bring latest features in Grafana Operator to the chart.

**Possible drawbacks**

Breaks backwards compatibility unless CRD(s) are uninstalled before upgrading.

**Applicable issues**

  - fixes https://github.com/bitnami/charts/issues/7704

**Additional information**

N/A

**Checklist** 

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Comment by carrodher** [comment]
@juan131 I just saw there are two PRs (this one) and https://github.com/bitnami/charts/pull/8059 (created by @Cellebyte) adapting the chart for the new major version, can you check/sync for those changes?

In the same way, it seems some internal work is required to support the new major branch in our internal test & release pipeline cc @joancafom

**Comment by Cellebyte** [comment]
@carrodher I think it makes sense to first merge @juan131 i will rebase then and then we will wait until v4.0.x get released which will support the new feature for AlertManager.

**Comment by juan131** [comment]
Sure @Cellebyte !! We're just waiting for the team to release the `4.x` image first and update this PR. After that, we can continue in your PR and implement any required update.

**Comment by joancafom** [comment]
Hi @Cellebyte 

I was working on updating the chart to support the new `4.0.1` major released some days ago, but stumbled upon an issue that makes our chart fail with it.

It seems that CRDs released in this version do not fully support all the features our chart offers, which eventually leads to validation failures. I created a new upstream ticket to inform about those missing features: https://github.com/grafana-operator/grafana-operator/issues/603

As these features are not currently supported, we discussed removing them from the chart to unblock this by now. In a similar manner, I have noticed that you have created a PR to adapt the chart to this new version. As `4.0.1` was officially released, I think the way to go here is to move some of the work @juan131 carried out in this PR (changes that are not related to the CRDs, which belong to a previous version) to yours. Then, we may drop the aforementioned features and the chart should be ready to be compatible with the latest release.

Finally, I have also noticed that your PR is in Draft waiting for some upstream features to be implemented. IMHO (and as I mentioned), I'd adapt the chart to be compatible with the **latest available release**. Should new features arrive in future releases, we may then open new PRs implementing them 🙂

Does it sound good to you? Can you move the changes in this PR to yours? I can also help you with that and dropping the unsupported features.

**Comment by Cellebyte** [comment]
@joancafom I created another PR which fixes the missing `security` flag.

Most of the other things which are not working could be moved to the correct layer in the Grafana CRD and should work again.

**Comment by FraPazGal** [comment]
Hello @Cellebyte,

We just released the grafana-operator container packaging version `4.0.2`, which includes your changes merged at https://github.com/grafana-operator/grafana-operator/pull/601. Thanks for the wait and great work here!

**Comment by Cellebyte** [comment]
@FraPazGal @juan131 I incorporated this PR together with my changes into the Merge Request #8059.
It bumps the chart and the app version to the new release.

The new v4.0.3 release should fix the throtteling bug in the grafana-operator as well.

**Comment by juan131** [comment]
Thanks @Cellebyte !! Let's close this PR then since you already included the changes at #8059

**Pull request closed without merging**
