### PR TITLE
[bitnami/redis] Add Topology Spread Constraint support for redis

### PR DESCRIPTION
**Pull request by jonstelly**
**Description of the change**

This adds support for specifying [topology spread constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) to ensure that redis pods are reasonably distributed across a cluster.

**Benefits**

In the simplest case, can be used to encourage better pod distribution across cluster nodes.  The `topologyKey` can be any node label, so for cloud providers you can spread across [region or zone](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#topologykubernetesiozone), etc...

**Possible drawbacks**

Since this redis chart uses two stateful sets, the topology spread applies to each stateful set independently.  So it's still possible to have master and slave pods end up on the same node, but that could be fixed by combining with other affinity/taints if needed.

**Applicable issues**

  - fixes #

**Additional information**

***Examples***

Node Spread

```yaml
master|slave:
  spreadConstraints:
    - maxSkew: 1
      topologyKey: node
      whenUnsatisfiable: DoNotSchedule
```

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by andresbono** [comment]
Hi @jonstelly, thanks for your contribution! :tada: we will review the PR shortly.

**Comment by andresbono** [comment]
@jonstelly, in order to update the image tags to point to latest releases, our CI/CD needs to modify you PR (`bitnami-bot` will update `values.yaml` and `values-production.yaml` for you). To do so, it's necessary you allow "edits from maintainers". Find more information in the link below: 
- https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

I already checked the changes using `helm template`,  but we would like to check the PR with our CI/CD as well.

**Comment by jonstelly** [comment]
> To do so, it's necessary you allow "edits from maintainers".

It doesn't look like I can do that.  I forked this repo into an organization and I don't see any option to do that like mentioned in the link even though I'm the organization owner.  I'll fork again into my personal account and resubmit this PR from there.

> Suggestions:
>  ...

Makes sense.  I'll get both of those changes made too before I resubmit.  I'll get things moved around and resubmitted tomorrow.  Thanks.

**Comment by andresbono** [comment]
Thanks, @jonstelly!

**Comment by jonstelly** [comment]
Resubmitted this PR - https://github.com/bitnami/charts/pull/2582

**Pull request closed without merging**
