### PR TITLE
[bitnami/fluent-bit] Fix typo daemonset.enable

### LINKED ISSUE #30539: [bitnami/fluent-bit] PodDisruptionBudget/fluent-bit gets created despites we deploy as DaemonSet
### Name and Version

bitnami/fluent-bit 2.3.24

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. Deploy fluent-bit as a DaemonSet (`daemonset.enabled: true`)
2. ...see the spamming event like `Failed to calculate the number of expected pods: daemonsets.apps does not implement the scale subresource`

### Are you using any custom parameters or values?

```
config:
  customParsers: ""
  extraFiles: {}
  filters: |-
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        Buffer_Size 0
        Kube_Meta_Cache_TTL 300s
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Kube_Tag_Prefix    kube.var.lib.docker.containers.
  inputs: |-
    [INPUT]
        Name              tail
        Path              /var/lib/docker/containers/*.log
        Exclude_Path      *.gz,*.zip
        multiline.parser  docker, cri
        DB                /var/log/fluent-bit/flb_kube.db
        Tag               kube.*
        Threaded          true
        Read_From_Head    On
        Refresh_Interval  10
        Rotate_Wait       30
        Mem_Buf_Limit     45MB
        Buffer_Max_Size   66k
        Skip_Long_Lines   On
        Skip_Empty_Lines  On
  outputs: '@INCLUDE /opt/bitnami/fluent-bit/conf/output.conf'
  service: |-
    [SERVICE]
        Daemon            Off
        Flush             1
        Log_Level         info
        Config_Watch      On
        HTTP_Server       On
        HTTP_Listen       0.0.0.0
        HTTP_Port         2020
        Health_Check      On
        Parsers_File      /opt/bitnami/fluent-bit/conf/custom_parsers.conf
daemonset:
  enabled: true
  hostPaths:
    containerLogs: /var/log/containers
    logs: /var/log
    machineId: /etc/machine-id
extraVolumeMounts:
- mountPath: /opt/bitnami/fluent-bit/conf/output.conf
  name: aws-logging
  subPath: output.conf
extraVolumes:
- configMap:
    name: aws-logging
  name: aws-logging
initContainers:
- command:
  - /bin/sh
  - -cx
  - |-
    mkdir -p /var/log/fluent-bit/
    chown -R 1001:1001 /var/log/fluent-bit/
  image: bitnami/os-shell
  imagePullPolicy: IfNotPresent
  name: folder-permission
  resources:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 50m
      memory: 16Mi
  securityContext:
    runAsUser: 0
    seLinuxOptions: {}
  volumeMounts:
  - mountPath: /var/log
    name: varlog
nodeSelector:
  kubernetes.io/os: linux
rbac:
  create: true
  nodeAccess: true
resources:
  limits:
    cpu: 150m
    memory: 192Mi
  requests:
    cpu: 100m
    memory: 128Mi
serviceAccount:
  automountServiceAccountToken: true
  create: false
  name: aws-logger-sa
tolerations:
- key: CriticalAddonsOnly
  operator: Exists
```

### What is the expected behavior?

PDB is not created

### What do you see instead?

PDB is created :/

### Additional information

The reason is a typo here:
https://github.com/bitnami/charts/blob/e9951e3c9022560eaea85da02882441811e9017f/bitnami/fluent-bit/templates/pdb.yaml#L6

There should be something like this here:
```
{{- if and .Values.pdb.create (not .Values.daemonset.enabled) }}
```
...so `enabled` instead of `enable`

### PR DESCRIPTION
**Pull request by eugene70**
There is a typo in the condition for generating pdb as described in issue #30539. We need to change enable to enabled.
The issue closed, but not solved.
```
{{- if and .Values.pdb.create (not .Values.daemonset.enabled) }}
```

- Fixes #30539

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your contribution! Could you please bump the chart version in the _Chart.yaml_? This is necessary to test the changes and cut a new release.

**Comment by eugene70** [comment]
Changed `Chart.yaml`.

**Comment by eugene70** [comment]
Fixed all and changed title.

**Review by carrodher — DISMISSED** [review]
LGTM, thanks

**Review by alvneiayu — APPROVED** [review]

**Comment by alvneiayu** [comment]
hi @eugene70

Could you bump it again to 2.4.2, please?

It seems that you are having conflicts :S, sorry for the inconveniences.

Thanks

Álvaro

**Review by alvneiayu — APPROVED** [review]

**Pull request merged**
