### PR TITLE
Fixing HPA resource.target format to be compatible with Api autoscaling/v2

### PR DESCRIPTION
**Pull request by ETisREAL**
The change is very simple and straightforward, I updated the hpa resource.target format to be compatible with the autoscaling/v2 API. 

When I tried to launch the schema registry enabling autoscaling, I got this error message:
```
failed to create resource: HorizontalPodAutoscaler.autoscaling "schema-registry" is invalid: [spec.metrics[0].resource.target.type: Required value: must specify a metric target type, spec.metrics[0].resource.target.type: Invalid value: "": must be either Utilization, Value, or AverageValue, spec.metrics[0].resource.target.averageUtilization: Required value: must set either a target raw value or a target utilization, spec.metrics[1].resource.target.type: Required value: must specify a metric target type, spec.metrics[1].resource.target.type: Invalid value: "": must be either Utilization, Value, or AverageValue, spec.metrics[1].resource.target.averageUtilization: Required value: must set either a target raw value or a target utilization]
```
the current format of the autoscaling target is not correct for this API version

I tested the code, and in a GKE cluster with Kubernetes version 1.27.3-gke.100 it now works as expected.

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your PR, could you please bump the chart version in the _Chart.yaml_ file? See https://github.com/bitnami/charts/actions/runs/6200973223/job/16836726452?pr=19301

**Comment by ETisREAL** [comment]
Just did, sorry I forgot

**Comment by carrodher** [comment]
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Feel free to reach out if you have any questions or need assistance with the signing process.

**Comment by ETisREAL** [comment]
I have to open a new PR. It's impossible for me to sign those old commits.

**Pull request closed without merging**
