### PR TITLE
[bitnami/wordpress] feature: add www subdomain to ingress.tls.hosts

### PR DESCRIPTION
**Pull request by macmoritz**
### Description of the change
Adds flag to add www subdomain to tls hosts in ingress.

### Benefits
Valid cert for www subdomain

### CODE REVIEW

**Comment by benedikt-bartscher** [comment]
This allows (in combination with the nginx-ingress www-redirect feature) to redirect www. to non-www with valid SSL.

**Comment by carrodher** [comment]
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

Apart from that, please note you need to bump the chart version in the _Chart.yaml_

**Comment by macmoritz** [comment]
Fixed the contributing issues.
Also implemented auto enable if nginx-ingress www-redirect is used. Thanks @benedikt-bartscher.

**Review by corico44 — APPROVED** [review]
LGTM

**Pull request merged**
