### PR TITLE
[bitnami/thanos] fix Deprecation Warning of thanos

### PR DESCRIPTION
**Pull request by Moep90**
- Describe the scope of your change - i.e. what the change does.
 - Describe any known limitations with your change.
 - Please run any tests or examples that can exercise your modified code.

### Description of the change

Replaced `--store=` with `--endpoint=`

### Benefits

Users will not have to worry when the "deprecation" happens.

### Possible drawbacks

Older versions (before adding `--endpoint` flag might not work

### Applicable issues

fixes:
```
      --store=<store> ...        Deprecation Warning - This flag is deprecated
                                 and replaced with `endpoint`. Addresses of
                                 statically configured store API servers
                                 (repeatable). The scheme may be prefixed with
                                 'dns+' or 'dnssrv+' to detect store API servers
                                 through respective DNS lookups.
      --store-strict=<staticstore> ...
                                 Deprecation Warning - This flag is deprecated
                                 and replaced with `endpoint-strict`. Addresses
                                 of only statically configured store API servers
                                 that are always used, even if the health check
                                 fails. Useful if you have a caching layer on
                                 top.
```

### Additional information

https://thanos.io/tip/components/query.md/#flags

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)]

### CODE REVIEW

**Comment by recena** [comment]
@Moep90 You marked _All commits signed off and in agreement of [Developer Certificate of Origin (DCO)]_ but is not true 😄

**Comment by Moep90** [comment]
@recena I'm sorry. Fixed it.

**Comment by recena** [comment]
@Moep90 It is not fixed yet.

**Comment by Moep90** [comment]
> @Moep90 It is not fixed yet.

Sorry then I dont get whats missing.

**Comment by recena** [comment]
@Moep90 Review the checkers https://github.com/bitnami/charts/pull/11178/checks?check_run_id=7323324050

**Review by alemorcuq — APPROVED** [review]
Thanks!

**Pull request merged**
