### PR TITLE
[bitnami/postgresql] Version the helper functions

### LINKED ISSUE #15753: [bitnami/postgresql] Idea: prefix/suffix helper functions with the chart
### Name and Version

bitnami/postgresql 12.2.6

### What is the problem this feature will solve?

Please read https://github.com/helm/helm/issues/11933

### What is the feature you are proposing to solve the problem?

To ensure postgresql helper functions don't override each other, I propose we place the version number (major should be enough hopefully) in the names of the helper functions. That way, no issue will occur when subcharts all use `bitnami/postgresql` with different versions.

For example:

```diff
 Create a default fully qualified app name for PostgreSQL Primary objects
 We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
 */}}
-{{- define "postgresql.primary.fullname" -}}
+{{- define "postgresql-12.primary.fullname" -}}
 {{- if eq .Values.architecture "replication" }}
     {{- printf "%s-%s" (include "common.names.fullname" .) .Values.primary.name | trunc 63 | trimSuffix "-" -}}
 {{- else -}}
@@ -16,7 +16,7 @@ We truncate at 63 chars because some Kubernetes name fields are limited to this
 Create a default fully qualified app name for PostgreSQL read-only replicas objects
 We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
 */}}
-{{- define "postgresql.readReplica.fullname" -}}
+{{- define "postgresql-12.readReplica.fullname" -}}
 {{- printf "%s-%s" (include "common.names.fullname" .) .Values.readReplicas.name | trunc 63 | trimSuffix "-" -}}
 {{- end -}}
 
@@ -24,7 +24,7 @@ We truncate at 63 chars because some Kubernetes name fields are limited to this
 Create the default FQDN for PostgreSQL primary headless service
 We truncate at 63 chars because of the DNS naming spec.
 */}}
-{{- define "postgresql.primary.svc.headless" -}}
+{{- define "postgresql-12.primary.svc.headless" -}}
 {{- printf "%s-hl" (include "postgresql.primary.fullname" .) | trunc 63 | trimSuffix "-" }}
 {{- end -}}
 
@@ -32,42 +32,42 @@ We truncate at 63 chars because of the DNS naming spec.
 Create the default FQDN for PostgreSQL read-only replicas headless service
 We truncate at 63 chars because of the DNS naming spec.
 */}}
-{{- define "postgresql.readReplica.svc.headless" -}}
+{{- define "postgresql-12.readReplica.svc.headless" -}}
 {{- printf "%s-hl" (include "postgresql.readReplica.fullname" .) | trunc 63 | trimSuffix "-" }}
 {{- end -}}
 
 {{/*
 Return the proper PostgreSQL image name
 */}}
-{{- define "postgresql.image" -}}
+{{- define "postgresql-12.image" -}}
 {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
 {{- end -}}
 
 {{/*
 Return the proper PostgreSQL metrics image name
 */}}
-{{- define "postgresql.metrics.image" -}}
+{{- define "postgresql-12.metrics.image" -}}
 {{ include "common.images.image" (dict "imageRoot" .Values.metrics.image "global" .Values.global) }}
 {{- end -}}
 
 {{/*
 Return the proper image name (for the init container volume-permissions image)
 */}}
-{{- define "postgresql.volumePermissions.image" -}}
+{{- define "postgresql-12.volumePermissions.image" -}}
 {{ include "common.images.image" (dict "imageRoot" .Values.volumePermissions.image "global" .Values.global) }}
 {{- end -}}
 
 {{/*
 Return the proper Docker Image Registry Secret Names
 */}}
-{{- define "postgresql.imagePullSecrets" -}}
+{{- define "postgresql-12.imagePullSecrets" -}}
 {{ include "common.images.pullSecrets" (dict "images" (list .Values.image .Values.metrics.image .Values.volumePermissions.image) "global" .Values.global) }}
 {{- end -}}
 
 {{/*
 Return the name for a custom user to create
 */}}
-{{- define "postgresql.username" -}}
+{{- define "postgresql-12.username" -}}
 {{- if .Values.global.postgresql.auth.username }}
     {{- .Values.global.postgresql.auth.username -}}
 {{- else -}}
@@ -78,7 +78,7 @@ Return the name for a custom user to create
 {{/*
 Return the name for a custom database to create
 */}}
-{{- define "postgresql.database" -}}
+{{- define "postgresql-12.database" -}}
 {{- if .Values.global.postgresql.auth.database }}
     {{- printf "%s" (tpl .Values.global.postgresql.auth.database $) -}}
 {{- else if .Values.auth.database -}}
@@ -89,7 +89,7 @@ Return the name for a custom database to create
 {{/*
 Get the password secret.
 */}}
-{{- define "postgresql.secretName" -}}
+{{- define "postgresql-12.secretName" -}}
 {{- if .Values.global.postgresql.auth.existingSecret }}
     {{- printf "%s" (tpl .Values.global.postgresql.auth.existingSecret $) -}}
 {{- else if .Values.auth.existingSecret -}}
@@ -102,7 +102,7 @@ Get the password secret.
 {{/*
 Get the replication-password key.
 */}}
-{{- define "postgresql.replicationPasswordKey" -}}
+{{- define "postgresql-12.replicationPasswordKey" -}}
 {{- if or .Values.global.postgresql.auth.existingSecret .Values.auth.existingSecret }}
     {{- if .Values.global.postgresql.auth.secretKeys.replicationPasswordKey }}
         {{- printf "%s" (tpl .Values.global.postgresql.auth.secretKeys.replicationPasswordKey $) -}}
@@ -119,7 +119,7 @@ Get the replication-password key.
 {{/*
 Get the admin-password key.
 */}}
-{{- define "postgresql.adminPasswordKey" -}}
+{{- define "postgresql-12.adminPasswordKey" -}}
 {{- if or .Values.global.postgresql.auth.existingSecret .Values.auth.existingSecret }}
     {{- if .Values.global.postgresql.auth.secretKeys.adminPasswordKey }}
         {{- printf "%s" (tpl .Values.global.postgresql.auth.secretKeys.adminPasswordKey $) -}}
@@ -134,7 +134,7 @@ Get the admin-password key.
 {{/*
 Get the user-password key.
 */}}
-{{- define "postgresql.userPasswordKey" -}}
+{{- define "postgresql-12.userPasswordKey" -}}
 {{- if or .Values.global.postgresql.auth.existingSecret .Values.auth.existingSecret }}
     {{- if or (empty (include "postgresql.username" .)) (eq (include "postgresql.username" .) "postgres") }}
         {{- printf "%s" (include "postgresql.adminPasswordKey" .) -}}
@@ -153,7 +153,7 @@ Get the user-password key.
 {{/*
 Return true if a secret object should be created
 */}}
-{{- define "postgresql.createSecret" -}}
+{{- define "postgresql-12.createSecret" -}}
 {{- if not (or .Values.global.postgresql.auth.existingSecret .Values.auth.existingSecret) -}}
     {{- true -}}
 {{- end -}}
@@ -162,7 +162,7 @@ Return true if a secret object should be created
 {{/*
 Return PostgreSQL service port
 */}}
-{{- define "postgresql.service.port" -}}
+{{- define "postgresql-12.service.port" -}}
 {{- if .Values.global.postgresql.service.ports.postgresql }}
     {{- .Values.global.postgresql.service.ports.postgresql -}}
 {{- else -}}
@@ -173,7 +173,7 @@ Return PostgreSQL service port
 {{/*
 Return PostgreSQL service port
 */}}
-{{- define "postgresql.readReplica.service.port" -}}
+{{- define "postgresql-12.readReplica.service.port" -}}
 {{- if .Values.global.postgresql.service.ports.postgresql }}
     {{- .Values.global.postgresql.service.ports.postgresql -}}
 {{- else -}}
@@ -184,7 +184,7 @@ Return PostgreSQL service port
 {{/*
 Get the PostgreSQL primary configuration ConfigMap name.
 */}}
-{{- define "postgresql.primary.configmapName" -}}
+{{- define "postgresql-12.primary.configmapName" -}}
 {{- if .Values.primary.existingConfigmap -}}
     {{- printf "%s" (tpl .Values.primary.existingConfigmap $) -}}
 {{- else -}}
@@ -195,7 +195,7 @@ Get the PostgreSQL primary configuration ConfigMap name.
 {{/*
 Return true if a configmap object should be created for PostgreSQL primary with the configuration
 */}}
-{{- define "postgresql.primary.createConfigmap" -}}
+{{- define "postgresql-12.primary.createConfigmap" -}}
 {{- if and (or .Values.primary.configuration .Values.primary.pgHbaConfiguration) (not .Values.primary.existingConfigmap) }}
     {{- true -}}
 {{- else -}}
@@ -205,7 +205,7 @@ Return true if a configmap object should be created for PostgreSQL primary with
 {{/*
 Get the PostgreSQL primary extended configuration ConfigMap name.
 */}}
-{{- define "postgresql.primary.extendedConfigmapName" -}}
+{{- define "postgresql-12.primary.extendedConfigmapName" -}}
 {{- if .Values.primary.existingExtendedConfigmap -}}
     {{- printf "%s" (tpl .Values.primary.existingExtendedConfigmap $) -}}
 {{- else -}}
@@ -216,14 +216,14 @@ Get the PostgreSQL primary extended configuration ConfigMap name.
 {{/*
 Get the PostgreSQL read replica extended configuration ConfigMap name.
 */}}
-{{- define "postgresql.readReplicas.extendedConfigmapName" -}}
+{{- define "postgresql-12.readReplicas.extendedConfigmapName" -}}
     {{- printf "%s-extended-configuration" (include "postgresql.readReplica.fullname" .) -}}
 {{- end -}}
 
 {{/*
 Return true if a configmap object should be created for PostgreSQL primary with the extended configuration
 */}}
-{{- define "postgresql.primary.createExtendedConfigmap" -}}
+{{- define "postgresql-12.primary.createExtendedConfigmap" -}}
 {{- if and .Values.primary.extendedConfiguration (not .Values.primary.existingExtendedConfigmap) }}
     {{- true -}}
 {{- else -}}
@@ -233,7 +233,7 @@ Return true if a configmap object should be created for PostgreSQL primary with
 {{/*
 Return true if a configmap object should be created for PostgreSQL read replica with the extended configuration
 */}}
-{{- define "postgresql.readReplicas.createExtendedConfigmap" -}}
+{{- define "postgresql-12.readReplicas.createExtendedConfigmap" -}}
 {{- if .Values.readReplicas.extendedConfiguration }}
     {{- true -}}
 {{- else -}}
@@ -243,7 +243,7 @@ Return true if a configmap object should be created for PostgreSQL read replica
 {{/*
  Create the name of the service account to use
  */}}
-{{- define "postgresql.serviceAccountName" -}}
+{{- define "postgresql-12.serviceAccountName" -}}
 {{- if .Values.serviceAccount.create -}}
     {{ default (include "common.names.fullname" .) .Values.serviceAccount.name }}
 {{- else -}}
@@ -254,7 +254,7 @@ Return true if a configmap object should be created for PostgreSQL read replica
 {{/*
 Return true if a configmap should be mounted with PostgreSQL configuration
 */}}
-{{- define "postgresql.mountConfigurationCM" -}}
+{{- define "postgresql-12.mountConfigurationCM" -}}
 {{- if or .Values.primary.configuration .Values.primary.pgHbaConfiguration .Values.primary.existingConfigmap }}
     {{- true -}}
 {{- end -}}
@@ -263,7 +263,7 @@ Return true if a configmap should be mounted with PostgreSQL configuration
 {{/*
 Get the initialization scripts ConfigMap name.
 */}}
-{{- define "postgresql.initdb.scriptsCM" -}}
+{{- define "postgresql-12.initdb.scriptsCM" -}}
 {{- if .Values.primary.initdb.scriptsConfigMap -}}
     {{- printf "%s" (tpl .Values.primary.initdb.scriptsConfigMap $) -}}
 {{- else -}}
@@ -274,7 +274,7 @@ Get the initialization scripts ConfigMap name.
 {/*
 Return true if TLS is enabled for LDAP connection
 */}}
-{{- define "postgresql.ldap.tls.enabled" -}}
+{{- define "postgresql-12.ldap.tls.enabled" -}}
 {{- if and (kindIs "string" .Values.ldap.tls) (not (empty .Values.ldap.tls)) }}
     {{- true -}}
 {{- else if and (kindIs "map" .Values.ldap.tls) .Values.ldap.tls.enabled }}
@@ -285,7 +285,7 @@ Return true if TLS is enabled for LDAP connection
 {{/*
 Get the readiness probe command
 */}}
-{{- define "postgresql.readinessProbeCommand" -}}
+{{- define "postgresql-12.readinessProbeCommand" -}}
 {{- $customUser := include "postgresql.username" . }}
 - |
 {{- if (include "postgresql.database" .) }}
@@ -301,7 +301,7 @@ Get the readiness probe command
 {{/*
 Compile all warnings into a single message, and call fail.
 */}}
-{{- define "postgresql.validateValues" -}}
+{{- define "postgresql-12.validateValues" -}}
 {{- $messages := list -}}
 {{- $messages := append $messages (include "postgresql.validateValues.ldapConfigurationMethod" .) -}}
 {{- $messages := append $messages (include "postgresql.validateValues.psp" .) -}}
@@ -316,7 +316,7 @@ Compile all warnings into a single message, and call fail.
 {{/*
 Validate values of Postgresql - If ldap.url is used then you don't need the other settings for ldap
 */}}
-{{- define "postgresql.validateValues.ldapConfigurationMethod" -}}
+{{- define "postgresql-12.validateValues.ldapConfigurationMethod" -}}
 {{- if and .Values.ldap.enabled (and (not (empty .Values.ldap.url)) (not (empty .Values.ldap.server))) }}
 postgresql: ldap.url, ldap.server
     You cannot set both `ldap.url` and `ldap.server` at the same time.
@@ -328,7 +328,7 @@ postgresql: ldap.url, ldap.server
 {{/*
 Validate values of Postgresql - If PSP is enabled RBAC should be enabled too
 */}}
-{{- define "postgresql.validateValues.psp" -}}
+{{- define "postgresql-12.validateValues.psp" -}}
 {{- if and .Values.psp.create (not .Values.rbac.create) }}
 postgresql: psp.create, rbac.create
     RBAC should be enabled if PSP is enabled in order for PSP to work.
@@ -339,7 +339,7 @@ postgresql: psp.create, rbac.create
 {{/*
 Return the path to the cert file.
 */}}
-{{- define "postgresql.tlsCert" -}}
+{{- define "postgresql-12.tlsCert" -}}
 {{- if .Values.tls.autoGenerated }}
     {{- printf "/opt/bitnami/postgresql/certs/tls.crt" -}}
 {{- else -}}
@@ -350,7 +350,7 @@ Return the path to the cert file.
 {{/*
 Return the path to the cert key file.
 */}}
-{{- define "postgresql.tlsCertKey" -}}
+{{- define "postgresql-12.tlsCertKey" -}}
 {{- if .Values.tls.autoGenerated }}
     {{- printf "/opt/bitnami/postgresql/certs/tls.key" -}}
 {{- else -}}
@@ -361,7 +361,7 @@ Return the path to the cert key file.
 {{/*
 Return the path to the CA cert file.
 */}}
-{{- define "postgresql.tlsCACert" -}}
+{{- define "postgresql-12.tlsCACert" -}}
 {{- if .Values.tls.autoGenerated }}
     {{- printf "/opt/bitnami/postgresql/certs/ca.crt" -}}
 {{- else -}}
@@ -372,7 +372,7 @@ Return the path to the CA cert file.
 {{/*
 Return the path to the CRL file.
 */}}
-{{- define "postgresql.tlsCRL" -}}
+{{- define "postgresql-12.tlsCRL" -}}
 {{- if .Values.tls.crlFilename -}}
 {{- printf "/opt/bitnami/postgresql/certs/%s" .Values.tls.crlFilename -}}
 {{- end -}}
@@ -381,7 +381,7 @@ Return the path to the CRL file.
 {{/*
 Return true if a TLS credentials secret object should be created
 */}}
-{{- define "postgresql.createTlsSecret" -}}
+{{- define "postgresql-12.createTlsSecret" -}}
 {{- if and .Values.tls.autoGenerated (not .Values.tls.certificatesSecret) }}
     {{- true -}}
 {{- end -}}
@@ -390,7 +390,7 @@ Return true if a TLS credentials secret object should be created
 {{/*
 Return the path to the CA cert file.
 */}}
-{{- define "postgresql.tlsSecretName" -}}
+{{- define "postgresql-12.tlsSecretName" -}}
 {{- if .Values.tls.autoGenerated }}
     {{- printf "%s-crt" (include "common.names.fullname" .) -}}
 {{- else -}}
```

### What alternatives have you considered?

Solve it upstream in https://github.com/helm/helm/issues/11933

### PR DESCRIPTION
**Pull request by yardenshoham**
### Description of the change

To allow multiple versions of this chart to coexist as subcharts we shouldn't only separate the helper functions by prefixing the chart name but also by suffixing incrementing function versions.

### Benefits

It will allow multiple versions of this chart to coexist as subcharts.

### Possible drawbacks

People relying on the broken behavior of using templating logic from other versions would get different templating results.

### Applicable issues

- fixes #15753

### Additional information

This is officially recommended by Helm in https://helm.sh/docs/chart_template_guide/named_templates/. Please read the discussion in #15753.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by aoterolorenzo** [comment]
Hi @yardenshoham,

Sorry for the delayed response. We are internally discussing the best approach to apply this changes. Please let's wait till the team decides about it. Will leave the PR as on hold.

**Review by aoterolorenzo — CHANGES_REQUESTED** [review]
Hi @yardenshoham ,

We've decided follow this approach but scoping the versioning to the application version (and not versioning the helper itself), as seen in our latest release [Deepspeed](https://github.com/bitnami/charts/blob/main/bitnami/deepspeed/templates/_helpers.tpl):

`deepspeed.v0.this.that`

So instead of `postgresql.userPasswordKey.v1`, we would use `postgresql.v1.userPasswordKey`

Could you update the pull request to match this pattern? Thank you!

**Comment by yardenshoham** [comment]
Sure, does it look OK now?

**Review by aoterolorenzo — DISMISSED** [review]
LGTM

**Review by aoterolorenzo — APPROVED** [review]

**Comment by kd7lxl** [comment]
This is a breaking change and should increment the major version number.

**Pull request merged**
