### PR TITLE
[bitnami/grafana-operator] Watch only the current namespace if using `namespaceScope=true`

### LINKED ISSUE #21288: [bitnami/grafana-operator] Namespace scope to current namespace bugged
### Name and Version

bitnami/grafana-operator 3.5.6+

### What architecture are you using?

None

### What steps will reproduce the bug?

- Try installing helm chart to scope to current namespace.

In version 3.5.5, by setting `operator.namespaceScope=true`, we could scope the chart to **just** the current namespace or custom namespace using the field `operator. watchNamespace` values.

But with the change introduced in #20962 , it uses the same variable `operator. watchNamespace` to check whether the namespace has to be restricted and as an input to which namespaces needs to be watched, which mandates specifying a namespace if we want to restrict it. For users who want to restrict it to just the current namespace, its no longer possible.

### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

We should be able to watch just the current namespace where the operator is being deployed.

### What do you see instead?

We are not able to watch just the current namespace and can only specify statically defined namespaces or all namespaces.

### Additional information

Can be fixed by simply reverting the PR.

### PR DESCRIPTION
**Pull request by dazoakley**
### Description of the change

This fixes #21288, whilst retaining the ability of `watchNamespace` to be used independently for watching multiple/all namespaces.

### Benefits

This allows the grafana-operator to be used correctly in a restricted mode (just watching its own namespace), and in a more complete mode when you need it to watch more cluster wide resources.

### Possible drawbacks

None.

### Applicable issues

- fixes #21288

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by aoterolorenzo — DISMISSED** [review]
LGTM

**Comment by dazoakley** [comment]
Hi @aoterolorenzo @carrodher,

What do I/we need to do to get this merged?

Thanks,
Darren

**Comment by aoterolorenzo** [comment]
Sorry @dazoakley, I just left the auto-merge active waiting for CI, but without actually approving (I'm back from holidays today). It's merged now, thanks for the contribution!

**Comment by dazoakley** [comment]
No problem at all @aoterolorenzo, thanks for merging. 😃

**Pull request merged**
