### PR TITLE
[bitnami/common] Add option to remove empty seLinuxOptions from securityContext in non OpenShift environment

### LINKED ISSUE #28934: [bitnami/common] Add a possibility to omit empty seLinuxOptions property from non-OpenShift environments
### Name and Version

bitnami/common 2.21.0

### What is the problem this feature will solve?

Today many (all?) Bitnami Helm charts set empty object for `seLinuxOptions` within `containerSecurityPolicy`, e.g. https://github.com/bitnami/charts/blob/main/bitnami/mongodb/values.yaml#L585 

Empty `seLinuxOptions` property is only removed in OpenShift compatibility mode https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_compatibility.tpl#L28-L35

There are scenarios where OpenShift compatibility mode is not desired, but `seLinuxOptions` should be removed.
Running on Azure Kubernetes Service (AKS) and using built-in Azure Policy definition: https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/SELinux.json at the same time having to set one of "fsGroup" "runAsUser" "runAsGroup" properties with security context.

With scenario mentioned above built-in Azure Policy definition for SELinux fails with the message: "SELinux options is not allowed".

image

### What is the feature you are proposing to solve the problem?

Similarly to `global.compatibility.openshift.adaptSecurityContext` add `global.compatibility.omitEmptySeLinuxOptions` value and use this value in `common.compatibility.renderSecurityContext` helper to conditionally omit `seLinuxOptions` when it is empty/falsy.

Default value for `global.compatibility.omitEmptySeLinuxOptions` should be `false` making the change non-breaking.

### What alternatives have you considered?

Alternatives to overcome mentioned issue are only local "workarounds":
- Wrapping Helm chart with kustomize to remove unwanted options
- Modifying built-in Azure Policy definition
- Manually removing `seLinuxOptions` in runtime

### PR DESCRIPTION
**Pull request by minijus**
### Description of the change

Adding new `global.compatibility.omitEmptySeLinuxOption` option to conditionally remove empty/falsy `seLinuxOptions`property.

### Applicable issues

- fixes #28934

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by minijus** [comment]
Not sure when/how values/README files should be updated on all charts that use `bitnami/common`. I suppose `global.compatibility.omitEmptySeLinuxOption` with description on every other chart should only be added when updating `bitnami/common`?

**Review by migruiz4 — COMMENTED** [review]
Thank you for your contribution @minijus!

I would like to request a change, could you please move the new code block our of the `{{- if (((.context.Values.global).compatibility).openshift) -}}` conditional?

Additionally, I think it would be good to add the extra parenthesis `()`. Those parenthesis prevent errors when the parent value does not exist.

Suggestion:
```
{{- if (((.context.Values.global).compatibility).openshift) -}}
  {{- if or (eq .context.Values.global.compatibility.openshift.adaptSecurityContext "force") (and (eq .context.Values.global.compatibility.openshift.adaptSecurityContext "auto") (include "common.compatibility.isOpenshift" .context)) -}}
    {{/* Remove incompatible user/group values that do not work in Openshift out of the box */}}
    {{- $adaptedContext = omit $adaptedContext "fsGroup" "runAsUser" "runAsGroup" -}}
    {{- if not .secContext.seLinuxOptions -}}
    {{/* If it is an empty object, we remove it from the resulting context because it causes validation issues */}}
    {{- $adaptedContext = omit $adaptedContext "seLinuxOptions" -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- if and (((.context.Values.global).compatibility).omitEmptySeLinuxOptions) (not .secContext.seLinuxOptions) -}}
  {{- $adaptedContext = omit $adaptedContext "seLinuxOptions" -}}
{{- end -}}
```

**Comment by minijus** [comment]
> Thank you for your contribution @minijus!
> 
> I would like to request a change, could you please move the new code block our of the `{{- if (((.context.Values.global).compatibility).openshift) -}}` conditional?
> 
> Additionally, I think it would be good to add the extra parenthesis `()`. Those parenthesis prevent errors when the parent value does not exist.
> 
> Suggestion:
> 
> ```
> {{- if (((.context.Values.global).compatibility).openshift) -}}
>   {{- if or (eq .context.Values.global.compatibility.openshift.adaptSecurityContext "force") (and (eq .context.Values.global.compatibility.openshift.adaptSecurityContext "auto") (include "common.compatibility.isOpenshift" .context)) -}}
>     {{/* Remove incompatible user/group values that do not work in Openshift out of the box */}}
>     {{- $adaptedContext = omit $adaptedContext "fsGroup" "runAsUser" "runAsGroup" -}}
>     {{- if not .secContext.seLinuxOptions -}}
>     {{/* If it is an empty object, we remove it from the resulting context because it causes validation issues */}}
>     {{- $adaptedContext = omit $adaptedContext "seLinuxOptions" -}}
>     {{- end -}}
>   {{- end -}}
> {{- end -}}
> {{- if and (((.context.Values.global).compatibility).omitEmptySeLinuxOptions) (not .secContext.seLinuxOptions) -}}
>   {{- $adaptedContext = omit $adaptedContext "seLinuxOptions" -}}
> {{- end -}}
> ```

Thanks for the review!

I did the change.

**Comment by minijus** [comment]
@migruiz4 would you be able to have a look at this PR again?

**Review by migruiz4 — COMMENTED** [review]
Thank you for applying my suggestions!

I'm sorry for my late response.

I tested your changes and the new feature works as expected.

```yaml
# global.compatibility.omitEmptySeLinuxOptions: false
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
```

```yaml
# global.compatibility.omitEmptySeLinuxOptions: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
```

**Review by migruiz4 — APPROVED** [review]
I have updated this PR by adding a comment in the `_compatibility.tpl` and adding the new global value in the template chart.

**Pull request merged**
