### PR TITLE
[bitnami/redis] Reuse certs from existing secrets 

### LINKED ISSUE #9785: Redis TLS autoGenerated certs doesn't work well with helm upgrade
### Name and Version

bitnami/redis latest (or 16.5.0)

### What steps will reproduce the bug?

Deploy the Redis bitnami chart with `tls.autoGenerated=true` and then after successful deployment, do;

```
helm upgrade --install debug-cluster bitnami/redis --values ~/tmp/helm-redis-values.yaml
```

The `helm upgrade` succeeds but then the Redis and Sentinel containers proceed to crash 2-3 times as the pods roll.  We see lots of these logs on the nodes before they crash:

```
1:S 13 Apr 2022 11:49:37.278 # Error accepting a client connection: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
1:S 13 Apr 2022 11:49:37.278 # Error accepting a client connection: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
1:S 13 Apr 2022 11:49:38.280 # Error accepting a client connection: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
```

This is because the `helm upgrade` command is re-creating the certificates which can be seen by inspecting the cert validFrom timestamps.  This is further confirmed by copying the secret before the `helm upgrade` and doing something like:

```
helm upgrade --install debug-cluster bitnami/redis \
--set tls.autoGenerated=false \
--set tls.certificatesSecret=certificates-tls-secret \
--set tls.certFilename="tls.crt" \
--set tls.certKeyFilename="tls.key" \
--set tls.certCAFilename="ca.crt" \
--values ~/tmp/helm-redis-values.yaml
```

... which results in the expected seamless upgrade.

We wanted to confirm the expected behaviour for the `tls.autoGenerated` flag

### Are you using any custom parameters or values?

```yaml
global:
  redis:
    password: "xxxxxx"
  imageRegistry: xxxxx.dkr.ecr.xxxxx.amazonaws.com
auth:
  enabled: true
  sentinel: true
  password: "xxxxx"
image:
  repository: thirdparty
  tag: bitnami-redis-6.2.6-debian-10-r146
  pullPolicy: Always
master:
  persistence:
    enabled: false
replica:
  persistence:
    enabled: false
  startupProbe: # https://github.com/bitnami/charts/issues/9227
    enabled: true
    failureThreshold: 22
    periodSeconds: 10
sentinel:
  enabled: true
  image:
    repository: thirdparty
    tag: bitnami-redis-sentinel-6.2.6-debian-10-r144
    pullPolicy: Always
  masterSet: mymaster
  startupProbe: # https://github.com/bitnami/charts/issues/9227
    enabled: true
    failureThreshold: 22
    periodSeconds: 10
tls:
  enabled: true
  authClients: false
  autoGenerated: true
metrics:
  enabled: true
  image:
    repository: thirdparty
    tag: bitnami-redis-exporter-1.35.1-debian-10-r16
    pullPolicy: Always
```

### What is the expected behavior?

We would like to confirm the following behaviour for `helm upgrade` and the `tls.autoGenerated`:

 1. We were expecting the `helm upgrade` to be a noop however all the pods are rolled even though all the values are unchanged.
 2. We were expecting that `tls.autoGenerated` would only generate certs if the required k8s secret is missing and not update the secret/cert values when doing `helm upgrade`.

### What do you see instead?

The cert secret is updated with new certificates and all pods in the statefulSet are rolled which causes significant disruption during `helm upgrade`.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cunningr**
**Description of the change**

Ref issue #9785 to reuse existing secrets for X509 certificates where they have been previously created using the `tls.autoGenerated=true` values option.

**Benefits**

Currently when using the `tls.autoGenerated=true` a subsequent `helm upgrade` on the chart causes all nodes in the cluster to roll and causes a significant period of down time until all the nodes pick up the new certificates.

**Possible drawbacks**

A new workflow will be required to replace the certificates for the cluster such as (for example) first deleting the existing `*-crt` secret from kubernetes in order to have the certificates regenerated. 

**Applicable issues**

  - fixes #9785 

**Additional information**

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

I see it is currently in draft. Please let us know when it is ready for review.

**Comment by cunningr** [comment]
Thanks @javsalgar - Is there an easy way I can reference this PR as a chart version in a helm repo so I can test it as a dependency in my environment?

**Comment by cunningr** [comment]
This appears to resolve the issue to updating certificates on every `helm upgrade`.

**Comment by cunningr** [comment]
> Hi,
> 
> I see it is currently in draft. Please let us know when it is ready for review.

Ok.  This is my first PR so please let me know if something else needs to be done.  I did very basic tests my end.

**Comment by rafariossaa** [comment]
Hi,
  Could you rebase your changes from master ? There was some updates in the `.vib` folder that are needed in your branch in order to pass the tests.

**Review by rafariossaa — APPROVED** [review]
LGTM.

**Pull request merged**
