### PR TITLE
[bitnami/keycloak] Make sure truststore files not exist before creation

### PR DESCRIPTION
**Pull request by EinavDanielDX**
Description of the change
1. In init container, delete keystore and truststore files before creating new self-singed certificates.
2. In init container, use env variables for keystore and truststore files

Benefits
Prior to this change - In init container, keystore and truststore files path was hard coded instead of taken from env variables, this could cause future misconfiguration.
In addition, if these files exist while the init container gets into action - the init container will fail and the keycloak pod wont start untill pod is restarted.
This is crucial on standalone deployments, such as K3S, where in case of host restart - the init container wont start until the pod is killed.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Could you please provide a descriptive title? Thanks

**Review by migruiz4 — DISMISSED** [review]
Thank you very much for your contribution @EinavDanielDX! Looks good to me!

**Review by migruiz4 — APPROVED** [review]
Sorry for the delay.
Our CI pipeline detected fixable vulnerabilities in the Keycloak image during the Trivy scan, and we had to release the fixed version before we could merge this PR.
I will merge this now, thanks for your contribution!

**Comment by EinavDanielDX** [comment]
Great news, thanks!

**Pull request merged**
