### PR TITLE
[bitnami/opencart] Adjust the naming style for resources

### PR DESCRIPTION
**Pull request by izturn**
Signed-off-by: Gang Liu <gang.liu@daocloud.io>

### Description of the change
adjust the naming style for resources` name to make them not pass the length limit

### Applicable issues

  - fixes #

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by migruiz4 — CHANGES_REQUESTED** [review]
Hi @izturn,

Thank you for your contribution, but I don't think we should rename the PersistentVolume and PersistenVolumeClaim names in a patch release and although adjusting the naming style is a nice to have feature, don't think think it is worth releasing a new major.

Could you please revert the ones that affect persistence? The others are fine as the other resources would be recreated on a regular upgrade.

**Comment by izturn** [comment]
> Hi @izturn,
> 
> Thank you for your contribution, but I don't think we should rename the PersistentVolume and PersistenVolumeClaim names in a patch release and although adjusting the naming style is a nice to have feature, don't think think it is worth releasing a new major.
> 
> Could you please revert the ones that affect persistence? The others are fine as the other resources would be recreated on a regular upgrade.

done, PTAL

**Comment by izturn** [comment]
PTAL

**Review by migruiz4 — APPROVED** [review]
Looks good to me, thank you for applying the suggested changes!

**Pull request merged**
