### PR TITLE
[bitnami/mariadb-galera] Fix pod labels

### PR DESCRIPTION
**Pull request by srueg**
**Description of the change**
* Don't use the chart as pod label

**Benefits**
Otherwise this will cause a pod restart on every release, even if the pod didn't change.

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by marcosbc** [comment]
Hi @srueg, it is my understanding that this would cause a breaking change due to immutable fields in StatefulSets.

There is a related discussion to adding labels to StatefulSets in #4455, so let's block this PR until we decide what approach to follow there.

**Comment by srueg** [comment]
Nice, I didn't see this issue before. As I commented there, the `.spec.template.metadata.labels` of a StatefulSet is mutable and therefore shouldn't be a problem.

**Comment by marcosbc** [comment]
It seems like you are correct. In any case, for now, let's block this PR until we decide how to approach these changes in #4455.

**Comment by srueg** [comment]
@marcosbc  Any update on this?

**Review by marcosbc — APPROVED** [review]
Hi @srueg, I'm so sorry for the long delay. In the end we did not reach any conclusion in #4455 so we didn't add any update here.

After checking with the team, this PR looks good for everyone and there are no concerns, as it does not affect immutable fields (like you mentioned earlier).

Therefore, I'm going to accept this and merge now. Thanks a lot for the contribution!

**Comment by srueg** [comment]
Thanks @marcosbc 
For some reason it seems the chart wasn't released properly. The latest version of it which is being served on `https://charts.bitnami.com/bitnami` is still `5.6.2`.

**Comment by marcosbc** [comment]
@srueg We have been working on fixing an issue that appeared with this change. It seems to be working now so a new chart release should happen soon, hopefully today.

**Pull request merged**
