### PR TITLE
[bitnami/tomcat] Removed enforcement of tomcatPassword variable on upgrades

### LINKED ISSUE #12296: [bitnami/tomcat] Unclear enforcement of tomcatPassword on upgrades
### Name and Version

bitnami/tomcat 10.4.3

### What steps will reproduce the bug?

1. Install the bitnami/tomcat chart onto a cluster with a values.yaml that contains an empty `tomcatPassword` value (which is the default)
2. Attempt an upgrade of this deployment

### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

The upgrade should proceed without and error. In the described case (`tomcatPassword` is empty) the Helm Chart auto generates a password for the Tomcat Manager User.

See: https://github.com/bitnami/charts/blob/master/bitnami/tomcat/templates/secrets.yaml#L18

This secret is should be technically enough to attempt subsequent upgrades without an manual input by the user. The password based on my knowledge of the Chart is only used in the `libtomcat.sh` during startup: https://github.com/bitnami/containers/blob/6b0581771bf13be39df66a372508d195b6367464/bitnami/tomcat/10/debian-11/rootfs/opt/bitnami/scripts/libtomcat.sh#L89

This alters the `tomcat-users.xml` that is only persisted in the containers ephemeral storage (nothing is saved to a PV). This fact contradicts with the reasoning in the link that should provide further information regarding the error (see below). There the following is stated:
> Bitnami containers configure/initialize applications the first time they are deployed. However, they skip this configuration/initialization step and reuse persisted data if detected on subsequent deployments or upgrades.

From my perspective this doesn't seem to be the case with the tomcat chart. Here the secret is exported as environment variable on every startup. Additionally the `tomcat-users.xml` needs to be generated on every container startup as it is located in the ephemeral storage.

The PV (per default mounted under `/bitnami/tomcat`) only contains the tomcats `webapps` directory.

### What do you see instead?

A error is present to the user claiming that the `tomcatPassword` must be set in order to proceed.

For further information the error points to: https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

### Additional information

From my understanding this enforcement of the `tomcatPassword` being set on subsequent upgrades is not necessary as the password is stored properly inside a Kubernetes Secret that is evaluated automatically on every container startup.

I would vote for the removal of this check in https://github.com/bitnami/charts/blob/master/bitnami/tomcat/templates/NOTES.txt

This might be related to #6250

### LINKED ISSUE #13048: [bitnami/tomcat] Unclear enforcement of tomcatPassword on upgrades
### Name and Version

bitnami/tomcat 10.4.3

### What steps will reproduce the bug?

Dear Maintainers, this is another attempt to bring the unfortunately closed issue #12296 and associated PR #12401 back to live.

Sadly due an office absence on my side I didn't notice in time that the `bitnami-bot` marked the issue as stale and closed it afterwards.

Multiple pings towards the maintainers haven't been answered yet.

Currently, the PR #12401 is pending a review from the maintainers. I'm happy to pick the work back up on this if anything needs to be change before this change can be considered and hopefully merged.

### PR DESCRIPTION
**Pull request by danielhass**
Signed-off-by: Daniel Haß <danielhass@users.noreply.github.com>

### Description of the change

https://github.com/bitnami/charts/issues/12296 https://github.com/bitnami/charts/issues/13048

Removing the enforced check of the `tomcatPassword` value on subsequent upgrades and moving the secret generation from an in chart conditional to the commons `common.secrets.passwords.manage` function.

### Benefits

From my understanding this enforcement of the `tomcatPassword` being set on subsequent upgrades is not necessary as the password is stored properly inside a Kubernetes Secret that is evaluated automatically on every container startup.

### Applicable issues

  - fixes #13048
  - fixes #12296

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by danielhass** [comment]
@javsalgar as discussed over in #13048 I recreated this PR with a fresh and rebased version towards `main`.

Let me know if anything else is needed.

**Comment by carrodher** [comment]
Thanks! If you consider this PR is ready for review, could you please move it from "Draft PR" to a regular PR?

**Comment by danielhass** [comment]
@carrodher just pushed the bump of the chart version to get all checklist items ticked.

Ready for review now!

**Review by marcosbc — CHANGES_REQUESTED** [review]
Thanks for the contribution! Since this would be adding a new feature to the chart, could you increase the version's minor instead? e.g. `10.5.0`.

**Comment by danielhass** [comment]
@marcosbc thanks for your comment. I forced pushed my changes and bumped the chart version to `10.5.0`. I wasn't sure about the version increment in the first place as my contribution leaves the current chart functionality pretty much intact. But as the interface changes (e.g. the password variable is not needed on upgrades) a minor version bump makes sense I guess.

Another thing I'm not sure about is the password length for the auto generation: https://github.com/bitnami/charts/pull/13101/files#diff-f02386c7290429bcd15dcc3fef3ebf26794f97484000e760f060fdb365b3e847R15

I just copied the existing length of `10`. Is there any Bitnami internal best-practice for the length of such auto generated secrets? In my opinion `10` seems a bit short for modern security standards.

**Review by marcosbc — APPROVED** [review]
LGTM, thanks!

Note that default value for `length` is 10 so it could even be skipped.

**Pull request merged**
