### PR TITLE
[bitnami/keycloack] Add validation for Keycloack admin password

### LINKED ISSUE #4411: Keycloak (re)setting admin password isn't working
**Which chart**:
keycloak-0.1.2	

**Describe the bug**
It's not possible to login with provided credentials in the UI

Keycloak is accesses via externaly configured Ingress, the only value give to the chart are

```
auth:
  adminUser: admin
  adminPassword: <notWorkingPassword>

proxyAddressForwarding: true
```

**To Reproduce**

1. helm install keycloak -f values-keycloak.yaml bitnami/keycloak
2. Go to Addmin UI
3. Try to login with user: admin, password: <notWorkingPassword>

"Invalid username or password." is shown..

**Expected behavior**

Login is possible

**Version of Helm and Kubernetes**:
Helm Version:
```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"archive", BuildDate:"2020-07-28T00:00:00Z", GoVersion:"go1.15rc1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

### PR DESCRIPTION
**Pull request by miguelaeh**
**Description of the change**
Add validation to show an error when upgrading if you are not setting the old keycloack admin password.

**Benefits**

Avoid users confusions

**Possible drawbacks**

**Applicable issues**

  - fixes #4411

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Review by juan131 — CHANGES_REQUESTED** [review]
I don't think we need this. It's a stateless app that reconfigures the password on every restart

**Comment by miguelaeh** [comment]
Sorry, I was wrong, I assumed the case was similar to others, but it seems it doesn't.

**Comment by miguelaeh** [comment]
After some testing, I think this PR actually applies and avoids confusion to the users and inconsistencies between the secret and the actual password stored in postgresql.

**Review by juan131 — APPROVED** [review]
LGTM

**Comment by juan131** [comment]
Approving since it affects the password stored in the database.

**Pull request merged**
