### PR TITLE
[bitnami/redis] Fix Sentinel Redis with TLS

### PR DESCRIPTION
**Pull request by haljin**
**Description of the change**

Fix the startup of the pods when `sentinel.enabled=true` and `tls.enabled=true`. Removed a duplicate variable that breaks on TLS enabled.

**Benefits**

It actually makes the chart work with TLS.

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Review by marcosbc — CHANGES_REQUESTED** [review]
Hi, thanks for contributing to our repo.

Those changes were implemented in #4478 (issue #3700) fixing a major issue when restarting a pod.

If these lines are causing TLS to break, then it's probably happening because we didn't think of TLS support in #4478. It is probably failing because of not specifying SSL options, so if you could adapt the existing logic to also support SSL, that would be awesome. Thanks!

**Comment by haljin** [comment]
Ooops, I was convinced I did that, didn't notice the tiny little difference between the command I removed and the one before. Should be good now!

**Comment by haljin** [comment]
Also tested that with our TLS deployment and it's good :+1:

**Review by marcosbc — APPROVED** [review]
Awesome! LGTM now, thanks!!!

**Pull request merged**
