### PR TITLE
[bitnami/mongodb] Add common labels to PVC Template

### LINKED ISSUE #20264: [bitnami/mongodb] StatefulSet PVC template does not set common labels
### Name and Version

bitnami/mongodb 14.0.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. With config
```yaml
architecture: replicaset
useStatefulSet: true
persistence:
  enabled: true
commonLabels:
  mylabel: "mylabelvalue"
```
2. Run the `helm template mongodb`
3. Statefulset Persistence Volume Claims template does dot include the common labels

### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

The stateful set should have rendered the common labels for the PVC template:
```yaml
spec:
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: datadir
        labels:
          app.kubernetes.io/component: mongodb
          mylabel: mylabelvalue
```

### What do you see instead?

```yaml
spec:
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: datadir
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silvamb**
### Description of the change

Add common labels to the `StatefulSet` Persistent Volume Claim template.

### Benefits

Labels help organize the resources and also filtering. The labels are added for the other resources templates, they should also be added for the Persistent Volume Claims.

### Possible drawbacks

No impacts.

### Applicable issues

- fixes #20264 

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by fmulero — CHANGES_REQUESTED** [review]
Hi @silvamb, thanks a lot for your contribution!

This change seems simple but it will imply a major change because helm can not upgrade the statefulset. If we try to upgrade a cluster from 14.0.10 to your version we will face an error like this one:

```console
$ helm upgrade mongodb bitnami/mongodb --set architecture=replicaset
Error: UPGRADE FAILED: cannot patch "mongodb" with kind StatefulSet: StatefulSet.apps "mongodb" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

My suggestion would be:
* Bump to version 15.0.0
* Include notes in the README file to upgrade safely an existing cluster to version 15.0.0 (something similar to [this example](https://github.com/bitnami/charts/blob/main/bitnami/etcd/README.md#to-900))

**Comment by silvamb** [comment]
Hi @fmulero,

That was a good catch, I did not test updating an existing release but creating for scratch only. I will test updating a previous version chart and will update the PR with the suggested changes.

**Review by fmulero — COMMENTED** [review]
Sorry to bother you again, there is a little typo.

**Comment by fmulero** [comment]
Hi @silvamb,

[DCO](https://github.com/bitnami/charts/runs/18442169565) check is failing and it seems there is a conflict. Could you review it? I'll merge it when everything is green.

**Pull request closed without merging**
