### PR TITLE
[grafana-operator] fix: move sidecar definition to deployment section

### PR DESCRIPTION
**Pull request by arnecls**
### Description of the change

With the latest version of the operator, the sidecar container section has been removed.
As of this, all additional containers have to be placed into the `deployment.spec.template.spec.containers` section.

The readiness and liveness probe definition also had a couple of issue:

- It was put at the end of a section that actually is an array (rendering error)
- It was not indented correctly, and even if it was, it would only affect the last sidecar
- The main container was not affected by the probes, but the location in the value file somewhat implied that

This PR moves the probe to the main grafana container, as the sidecars can (and should) define this section inline.

### Benefits

- The resource is correctly rendered when using sidecars
- Readiness and Liveness probe can be configured for the grafana instance

### Possible drawbacks

There should be none

### Applicable issues

- relates to #17863

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by arnecls** [comment]
I added another fix I found while rolling out these changes (note: this fix alone does not make the chart work).
The liveliness and readiness probe need to be "complete" now, as the CRD now expects a proper deployment definition.
There's other places in the chart where this is also an issue, but this is out of scope for this specific fix.

**Review by juan131 — DISMISSED** [review]
Thanks for the fix! LGTM

**Comment by juan131** [comment]
@arnecls we merged another PR affecting the Grafana Operator, could you please merge `main` in your branch, resolve the conflicts and update the PR? Thanks in advance.

**Comment by arnecls** [comment]
@juan131 merged-in the latest changes

**Pull request merged**
