### PR TITLE
bitnami/elasticsearch: add externalTrafficPolicy to coordinating-only service

### PR DESCRIPTION
**Pull request by antonmatsiuk**
**Description of the change**

PR adds an option to configure `externalTrafficPolicy` for coordintaing-only service of type `LoadBalancer` in elasticsearch chart. Without this feature an internal LoadBalancer on Azure does not work properly with coordinating-only service and external clients. External clients receive connection timeouts with default `externalTrafficPolicy`: `Cluster`

**Benefits**

* externalTrafficPolicy is configurable to preserve ClientIP
* avoid issues with internal load balancers on AKS clusters

**Possible drawbacks**

not known

**Applicable issues**
no

**Additional information**

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Review by miguelaeh — APPROVED** [review]
LGTM!

**Comment by antonmatsiuk** [comment]
> LGTM! Please fix the conflicts

fixed

**Comment by antonmatsiuk** [comment]
> LGTM! Please fix the conflicts

Could we get it into mainstream, if there are no other conflicts? This really stops us from using elasticsearch chart in production on Azure.

**Comment by javsalgar** [comment]
Merged, thanks!

**Pull request merged**
