### PR TITLE
[bitnami/redis] Fix podSecurityPolicy creation

### PR DESCRIPTION
**Pull request by javsalgar**
**Description of the change**

We created the containerSecurityContext parameter but did not adapt the `podSecurityPolicy` creation. This PR fixes that.

**Benefits**

Can create PSP

**Possible drawbacks**

n/a

**Applicable issues**

  - fixes https://github.com/bitnami/charts/issues/3996

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Review by carrodher — APPROVED** [review]
LGTM

**Comment by zackijack** [comment]
Hi @javsalgar, in me, the last version is still 11.1.3, is there any delay?

**Comment by carrodher** [comment]
Hi @zackijack, thanks for letting us know. Once a PR is merged in GH our internal test & release pipeline needs to do some extra steps in order to test the changes in different clusters and perform the release into the Bitnami Charts repository, in this case, something doesn't work as expected and the release was not fully done, we'll look into it

**Comment by carrodher** [comment]
@zackijack there is a new minor version `11.2.0` that should contain all the previous changes, please note the version `11.1.4` is not present in the helm repo but only in GitHub:
```console
$ helm search repo bitnami/redis -l
NAME                 	CHART VERSION	APP VERSION    	DESCRIPTION
bitnami/redis        	11.2.0       	6.0.8          	Open source, advanced key-value store. It is of...
bitnami/redis        	11.1.3       	6.0.8          	Open source, advanced key-value store. It is of...
```

**Comment by zackijack** [comment]
Ok noted, thanks @carrodher

**Pull request merged**
