### PR TITLE
bitnami/keycloak Safer variable set of KC_HOSTNAME_URL

### LINKED ISSUE #27911: KC_HOSTNAME_URL is set when it should not be (regression)
### Name and Version

bitnami/keycloak 21.6.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Used the chart with:
I am using `proxy=edge,production=true`, `ingress.enabled=true`, `ingress.hostname=`, and `ingress.extraHosts[0].name=,ingress.extraHosts[0].path`

The chart does not work properly (pod goes into crashloop)

The `KC_HOSTNAME_URL` in my environment is resolving to `https://`.

This is due to the proxy hostname being used by Keycloak when proxy=edge is enabled.

This causes Keycloak to not start:
```
Invalid base URL for FrontEnd URLs: https://
2024-07-11T12:41:49.937012733-04:00 ERROR: Expected scheme-specific part at index 6: https:
2024-07-11T12:41:49.937043946-04:00 For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```
### Are you using any custom parameters or values?

Yes.
```
proxy=edge, production=true, ingress.enabled=true, ingress.hostname=, and ingress.extraHosts[0].name=,ingress.extraHosts[0]
```
### What is the expected behavior?

pod comes up and works properly.

### What do you see instead?

pod goes into crash loop

### PR DESCRIPTION
**Pull request by wkbrd**
### Description of the change

Bug fix for KC_HOSTNAME_URL being set when ingress.hostname is undefined.  It should not output the variable in this case.

### Benefits

Restores regression from recent change in this PR: https://github.com/bitnami/charts/pull/27867

### Possible drawbacks

N/A

### Applicable issues

- fixes #27911 
- related to #25233

### Additional information

See issue for more details.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by singhbaljit** [comment]
For what use-case would the hostname be empty? I think the hostname is required when the ingress is enabled.

**Comment by wkbrd** [comment]
With the proxy=edge value set, Keycloak will determine use the provided proxy headers to determine the fully URL that is used in web links/etc.  This can be paired with ingress.enabled=true,ingress.extraHosts[0].name=,ingress.extraHosts[0].path=/someprefix to allow an Ingress rule that is created without a hostname being defined in the Ingress object.

Therefore, I don't think the hostname is required.

**Comment by wkbrd** [comment]
The use of extraHosts for this scenario was recommended in #25233 previously

**Comment by singhbaljit** [comment]
Got it, I think the same should also apply for the admin ingress too then.

**Comment by wkbrd** [comment]
Likely so, though I was not using it.  Would you like me to update the PR to add that check to the admin ingress?

**Comment by singhbaljit** [comment]
I'm not using the `extraHosts`, it doesn't impact me. But for consistency between the ingresses, I think we should add it, unless @javsalgar disagrees.

**Comment by singhbaljit** [comment]
I guess this was another miss from #25386 😄

**Comment by wkbrd** [comment]
PR updated to add a check for admin ingress, too.  Thanks for your review!

**Comment by wkbrd** [comment]
> I'm not using the `extraHosts`, it doesn't impact me. But for consistency between the ingresses, I think we should add it, unless @javsalgar disagrees.

Done now :-)

**Comment by singhbaljit** [comment]
Just a side note, this might all have to be revisited with [v2 hostname](https://www.keycloak.org/server/hostname) and proxy headers (#27890). Based on the defaults, I think the recommended approach is to use full URLs in in `hostname`/`hostname-admin` since `hostname-strict` is enabled and `hostname-backchannel-dynamic` is disabled by default.

**Comment by wkbrd** [comment]
Hi @rafariossaa, please let me know if you have questions regarding this PR. It restores functionality that regressed with a previous merge. Thanks!

**Review by rafariossaa — APPROVED** [review]
LGTM

**Pull request merged**
