### PR TITLE
[bitnami/kafka] Add init containers to the Kafka exporter pods

### PR DESCRIPTION
**Pull request by yevgeny-z**
**Description of the change**
Add init containers to the Kafka exporter pods from `metrics.kafka.initContainers` value

**Benefits**
Allow configure `initContainers` for Kafka exporter deployment

**Possible drawbacks**
none

**Applicable issues**
none

**Additional information**
none

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Review by juan131 — COMMENTED** [review]
Thanks for this contribution @yevgeny-z !
Just curious: what is the use case you want to cover by adding init containers to the exporter deployment?

**Comment by yevgeny-z** [comment]
@juan131 we need prevent restarts of kafka-exporter before kafka started

**Review by juan131 — APPROVED** [review]
LGTM

**Comment by juan131** [comment]
> we need prevent restarts of kafka-exporter before kafka started

Very interesting! At some point we'll aso include our own solution for waiting for dependencies to be ready on init containers.

**Pull request merged**
