### PR TITLE
[bitnami/valkey] Fix default kukbectl.command when sentinel.service.createPrimary is true

### PR DESCRIPTION
**Pull request by walf443**
### Description of the change

When I tested bitnami/valkey v2.0.0 with sentinel.service.createPrimary is "true", `kubectl-shared` container fails to start.

https://github.com/bitnami/charts/commit/75cc62d9caf28c6f522042cd0f94cb9aca877837#diff-eb284f204448e760305c61ac01175a784e9916a2e59e8a5f0b37eddcf7842249L779 
changes the script name for `kubectl-shared` container. But kubectl.command default value is remained.

So I change the default value for kubectl.command value.

### Benefits

When you use this chart with sentinel.service.createPrimary is "true", you do not need to change kubectl.command value to `["/opt/bitnami/scripts/kubectl-scripts/update-primary-label.sh"]`

### Applicable issues

- fixes #

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by walf443** [comment]
I also create https://github.com/bitnami/charts/pull/30091

**Comment by walf443** [comment]
I rebased with https://github.com/bitnami/charts/pull/30091 changes.

**Comment by koalalorenzo** [comment]
I was about to open a similar PR, ran in the same issue! Thank you :)

**Review by migruiz4 — APPROVED** [review]
Thank you for your contribution @walf443! Looks good to me!

**Pull request merged**
