### PR TITLE
[bitnami/sealed-secrets] Bump sealed secrets

### PR DESCRIPTION
**Pull request by farodin91**
Signed-off-by: Jan Jansen <jan.jansen@gdata.de>

### Applicable issues

  - fixes #

### Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thanks for the PR! Could you explain this bump?

**Comment by farodin91** [comment]
My last pr was merged without a version bump.

**Comment by farodin91** [comment]
https://github.com/bitnami/charts/pull/12970

Others Pr shortly merged before.

**Comment by migruiz4** [comment]
Hi @farodin91,

I'm closing this PR. 
Version 1.1.8 was already released, and it should include the changes from your PR that weren't included because of the version conflict: https://github.com/bitnami/charts/blob/main/bitnami/sealed-secrets/Chart.yaml

**Pull request closed without merging**
