### PR TITLE
[bitnami/mongodb] Try to seed mongodb with pss-restricted

### PR DESCRIPTION
**Pull request by jcpunk**
### Description of the change

Enhance default security controls for mongodb pods

### Benefits

Greater compliance with kubernetes pod security best practices

### Possible drawbacks

Users doing custom things may need to adjust their settings.

### Applicable issues

- fixes #

### Additional information

https://kubernetes.io/docs/concepts/security/pod-security-standards/

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thank you so much for the PR! Could you fix the merge and README medatada issues?

**Comment by jcpunk** [comment]
Is there a script I can run to fixup the readme?

**Comment by jcpunk** [comment]
I'll confess I have no idea what the verify errors mean...

**Review by fmulero — COMMENTED** [review]
Hi @jcpunk, thanks a lot for your contribution

I have a mix of feelings about your PR. I like the initiative but it is not working. Have you give it try using the default values? If you try it you will see an error about permissions:
```console
mongodb 11:19:12.72 DEBUG ==> Starting MongoDB in background...
Error opening config file: Permission denied
```

This is happening because the config file (`mongodb.conf`) was created by the root user and these are its permissions:
```console
I have no name!@d63e0182e132:/$ ls -ltr /opt/bitnami/mongodb/conf/
total 4
-rw-rw---- 1 root root 1018 Dec  3  2022 mongodb.conf
```

With these new values the group is 1001 instead of root, so the main process in the container can not read the config file. To fix this issue we should change the container code to amend those permissions.

Keeping in mind that the main goal of the PR is change the default values to make it more secure, we cannot accept the PR in this way until the `bitnami/mongdb` container is changed

**Comment by jcpunk** [comment]
I'll confess, I'd thought the `fsGroup` parameter set the group automatically and I was just being extra explicit in the flags.

I've set the group to an explicit `0` now in hopes that this helps.

**Comment by jcpunk** [comment]
I'd still like to get a version of this merged in.

**Review by fmulero — APPROVED** [review]
LGTM. Thanks @jcpunk  and sorry about the delay

**Pull request merged**
