### PR TITLE
[bitnami/keycloak] Revert "Drop unnecessary secret moint in Keycloak container (#16013)"

### LINKED ISSUE #16256: Drop secret mounts from keycloak
### Name and Version

bitnami/keycloak 14.2.0

### What architecture are you using?

None

### What steps will reproduce the bug?

You drop [secrets mount](
https://github.com/bitnami/charts/commit/dc83778c2e40c9f7f011a2b747407e3f12aa2b54)

but in values [keys exists](https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml#L1021)

and its needed feature, ex i start spilo with keycloak and uses created operator secret

ex

```yaml
externalDatabase:
  host: io-keycloak
  port: 5432
  user: io_keycloak
  database: io_keycloak
  password: ""
  existingSecret: io-keycloak.io-keycloak.credentials.spilo
  existingSecretPasswordKey: password
```

### What do you see instead?

revert changes in[ commit](https://github.com/bitnami/charts/commit/dc83778c2e40c9f7f011a2b747407e3f12aa2b54)

@dalbani :question:

### PR DESCRIPTION
**Pull request by aoterolorenzo**
### Description of the change

This reverts changes from #16013, and fixes #16256

### Applicable issues

- fixes #16256

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by marcosbc — APPROVED** [review]
LGTM!

**Comment by dalbani** [comment]
I'm curious why this MR has actually been merged, given that the original issue was closed last week.
In other words: this revert is wrong in my opinion.

**Comment by aoterolorenzo** [comment]
Hi @dalbani ,

Based on #16256, the secret would be needed in the example case provided.

**Comment by dalbani** [comment]
Which secret are you referring to exactly?
As I explained in https://github.com/bitnami/charts/pull/16013#issue-1662081120 and again in https://github.com/bitnami/charts/issues/16256#issuecomment-1545698126 with an example, the existing secret `io-keycloak.io-keycloak.credentials.spilo` is mounted *twice*.
Producing 2 environment variables in the Keycloak container:
```
...
KEYCLOAK_DATABASE_PASSWORD=the-database-secret-password
password=the-database-secret-password
...
```
That can't be right, can it?

As for the cryptic reaction of the OP at https://github.com/bitnami/charts/issues/16256#issuecomment-1549676302, who closed the issue before you merged the "fix", I took it as an acknowledgement that there was nothing wrong to being with the chart.

**Comment by dalbani** [comment]
Thanks for your feedback @aoterolorenzo, I've just created a new PR.

**Pull request merged**
