### PR TITLE
Fixes bitnami/charts #10106

### LINKED ISSUE #10106: [bitnami/elasticsearch] Ingress: bad indentation for labels
### Name and Version

bitnami/elasticsearch 18.0.1

### What steps will reproduce the bug?

To reproduce the bug, you just need to enable the ingress:
```yaml
elasticsearch:
  ingress:
    enabled: true
```

### Are you using any custom parameters or values?

Yes, `elasticsearch.ingress.enabled=true`

### What is the expected behavior?

No error, templates can compile.

### What do you see instead?

The error when trying to parse the template:
```
Error: YAML parse error on .../charts/elasticsearch/templates/ingress.yaml: error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context
helm.go:84: [debug] error converting YAML to JSON: yaml: line 11: mapping values are not allowed in this context
```

With `helm template --debug`:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch
  namespace: "..."
  labels:
    app.kubernetes.io/name: elasticsearch
    helm.sh/chart: elasticsearch-18.0.1
    app.kubernetes.io/instance: ...
    app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/component: elasticsearch # <--------------------- Wrong indentation
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Moep90**
Fixes #10106

### CODE REVIEW

**Review by adaumann — CHANGES_REQUESTED** [review]
fixed signature

**Review by adaumann — COMMENTED** [review]
add signed

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the PR! Could you bump the chart patch version?

**Comment by jcculli** [comment]
[ingress.zip](https://github.com/bitnami/charts/files/8734077/ingress.zip)

There were additional errors in the ingress.yaml file. I attached a modified version that didn't throw any errors, but you'll definitely want to verify my changes were correct.

**Comment by carrodher** [comment]
Thanks for creating this PR. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

**Review by carrodher — APPROVED** [review]

**Pull request merged**
