### PR TITLE
[bitnami/jenkins]Add resources configuration to reload-configuration-as-code sidecar container

### PR DESCRIPTION
**Pull request by SylivanKenobi**
### Description of the change

Add resources configuration to reload-configuration-as-code sidecar container.

### Benefits

The reload-configuration-as-code can now be configured in a production ready way with resources.

### Possible drawbacks

None

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by SylivanKenobi** [comment]
@aoterolorenzo is there anything I can do to help with merging this PR?

**Review by aoterolorenzo — APPROVED** [review]

**Comment by aoterolorenzo** [comment]
All good @SylivanKenobi,

Could you update the branch? There was a major bump in between.

**Comment by SylivanKenobi** [comment]
I updated the branch and adjusted the version accordingly.

**Review by migruiz4 — APPROVED** [review]
Looks good to me!

**Pull request merged**
