### PR TITLE
[bitnami/elasticsearch] Remove obsolete parameters from README

### PR DESCRIPTION
**Pull request by RobAtticus**
nodeAffinity and antiAffinity appear to have been replaced with
just passing in `affinity` values for coordinating/data/master/ingest.
Therefore to avoid confusion, these parameters should be removed
from the README. There may be more obsolete parameters, but these
were the few I discovered in my course of using the chart.

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your contribution! Before continuing you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

In this case bumping the patch version is fine.

**Comment by RobAtticus** [comment]
I didn't bump the chart since nothing in the code part of the chart actually changed. Happy to bump it up if you think its worth it though.

**Comment by carrodher** [comment]
Yes, the chart version should be bumped even in the case of changes in the README; in the end, everything is packed in the same tarball so it should be considered a new version.
Thanks!

**Comment by RobAtticus** [comment]
Sure thing, done.

**Pull request merged**
