### PR TITLE
[bitnami/clickhouse] Cluster authentication fix

### PR DESCRIPTION
**Pull request by clintz**
Signed-off-by: Christopher Lintz <chlintz@twilio.com>

### Description of the change
Added a non-empty remote_servers/default/secret in values.yaml.

This utilizes a Clickhouse feature that uses the initial
user as the current user for the inter-cluster queries. All nodes with the same non-empty secret string will trust each other.  The value can be any non-empty string.

For more info, see https://github.com/ClickHouse/ClickHouse/pull/13156

### Benefits

Resolves the cluster authentication issue securely without user/pass exposed in remote_server shards.

### Possible drawbacks

N/A

### Applicable issues

https://github.com/bitnami/charts/issues/13541

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by clintz** [comment]
Sorry missed moving to draft earlier. This is good now - no need for draft.

**Review by fmulero — COMMENTED** [review]
Thank you so much @clintz for taking care of this topic.

I've been taken a look and I have some concerns about the implementation. Having a hard coded default password is not a good practice and I am not sure about the impact of this change in existing installations, have you tested an upgrade from previous version?

**Comment by trennepohl** [comment]
Hey @clintz  thanks for this, I've spent a good chunk of time trying to figure out why I was having issues with distributed queries even though I had users with enough permissions for that.

Regarding @fmulero  comment you can use the `from_env` flag available in the config and set the password as a Kubernetes secret and mount it as an environment variable.

**Comment by fmulero** [comment]
> Regarding @fmulero comment you can use the from_env flag available in the config and set the password as a Kubernetes secret and mount it as an environment variable.

Good point! that's very useful. In addition, we should avoid the use of hardcoded passwords, we should autogenerate it during the installation. Here is my proposal:
* Add a new key to the [secret](https://github.com/bitnami/charts/blob/main/bitnami/clickhouse/templates/secret.yaml) using the [common.secrets.passwords.manage](https://github.com/bitnami/charts/blob/610f860fd8197f6f1dc1906511b56a96df42dac9/bitnami/common/templates/_secrets.tpl#L61-L85) template to create a new secret if the value is not provided by the user.
* Load the secret in a new env var like is already done for the [admin password](https://github.com/bitnami/charts/blob/610f860fd8197f6f1dc1906511b56a96df42dac9/bitnami/clickhouse/templates/statefulset.yaml#L202-L206)
* Use `env_from` in the configuration file to load the secret from the env var created in the previous step.

**Comment by fermuch** [comment]
hey @clintz ! Thanks for the PR, I didn't know what was wrong with the cluster settings.

Are you still able to update the PR to accomodate what @fmulero proposed? If not, is it ok if I continue from where you've left it?

**Comment by clintz** [comment]
Hi @fermuch - sorry for the long delay. Please feel free to pick up where I left off.

**Comment by fermuch** [comment]
hey @clintz ! Thanks! Sadly, at $WORK we're already setting this configuration manually, so I won't have that much time anymore to implement this.

@fmulero is there someone who can implement this available? If not, I'll try to make some time next month.

**Comment by fmulero** [comment]
We're a small team and our capacity is not too high. This is currently in our radar but the priority is not too high. Said that, we can not guarantee any ETA.

**Comment by yasha-dev1** [comment]
what's the status of this PR? as a hotfix we are creating a `default` user and granting all privilleges. I can contribute with this PR if any help is needed.

**Comment by fmulero** [comment]
Thanks @yasha-dev1  for your interest in this PR.

The status is what you can see here. @clintz couldn't continue with my suggestions and @fermuch expressed his interest follow up but it seems doesn't have enough time also.

From my side there is no problem if you want to continue working on this.

**Pull request closed without merging**
