### PR TITLE
[bitnami/*] test: fixed bump detection

### PR DESCRIPTION
**Pull request by marpontes**
Uses data from the API response used for files list to detect bumps.

Before, using the `git diff`, the head repository was checked out and the diff ran against its master.

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #9062

**Additional information**

**Checklist**

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi! I'm not sure what the exact difference is right now. We also changed to use the GH API to check the changed files.

**Comment by marpontes** [comment]
Hi, @javsalgar 👋 

The issue is with the bump detection.

The workflow checks out the head repository, so **marpontes/charts**. The `origin/master` during the script run will be `https://github.com/marpontes/charts/tree/master`.

Then it goes:
```
num_version_bumps="$(echo "$files_changed" | grep Chart.yaml | xargs git diff origin/master | grep -c "+version" || true)"
```

It's comparing with my master, not bitnami's. 

It was especially problematic on the README.md PR #9062 because I've used the `master` branch to submit, so basically it was comparing to itself during the workflow run and no bumps were detected.

This PR
---

Here, I'm using the same call you did before (`curl ...`) to also get the diffs and calculate the amount of version bumps, because it's included in the returning payload.

**Comment by javsalgar** [comment]
Ok, thanks for sharing.

Could you also do the following:

 - Merge from the latest upstream so the action checks do not fail
 - Provide examples of PRs that work well with the `get-chart` job? (You don't have to test the package lint and trivy scan as you don't have the proper tokens)

**Comment by marpontes** [comment]
OK, I've updated from bitnami/charts:master.

I also ran tests:

<details>
  <summary>Test results</summary>
  
```
Testing PR #9160 "[bitnami/postgresql] docs: :memo: Add note about using the container entrypoint" https://github.com/bitnami/charts/pull/9160
---
https://api.github.com/repos/bitnami/charts/pulls/9160/files
::set-output name=chart::bitnami/postgresql
::set-output name=result::ok



Testing PR #9155 "[bitnami/nginx] Add hostIPC option for NGINX Deployment" https://github.com/bitnami/charts/pull/9155
---
https://api.github.com/repos/bitnami/charts/pulls/9155/files
::set-output name=chart::bitnami/nginx
::set-output name=result::ok



Testing PR #9151 "bitnami/zookeeper Allow users to provide tls.key/tls.crt/ca.crt in a secret" https://github.com/bitnami/charts/pull/9151
---
https://api.github.com/repos/bitnami/charts/pulls/9151/files
::set-output name=chart::bitnami/zookeeper
::set-output name=result::ok



Testing PR #9149 "[bitnami/kafka] Fix rendering of topologySpreadConstraints" https://github.com/bitnami/charts/pull/9149
---
https://api.github.com/repos/bitnami/charts/pulls/9149/files
::set-output name=error::Detected changes in charts without version bump in Chart.yaml.
Charts changed: 1
bitnami/kafka
Version bumps detected: 0
::set-output name=result::fail



Testing PR #9148 "[bitnami/postgresql] Add hostIPC option for PostgreSQL StatefulSets" https://github.com/bitnami/charts/pull/9148
---
https://api.github.com/repos/bitnami/charts/pulls/9148/files
::set-output name=chart::bitnami/postgresql
::set-output name=result::ok



Testing PR #9147 "bitnami/wordpress - simple fix w3 cache post init wp-config save path" https://github.com/bitnami/charts/pull/9147
---
https://api.github.com/repos/bitnami/charts/pulls/9147/files
::set-output name=error::Detected changes in charts without version bump in Chart.yaml.
Charts changed: 1
bitnami/wordpress
Version bumps detected: 0
::set-output name=result::fail



Testing PR #9122 "[bitnami/kong] feat!: :arrow_up: Bump PostgreSQL subchart" https://github.com/bitnami/charts/pull/9122
---
https://api.github.com/repos/bitnami/charts/pulls/9122/files
::set-output name=chart::bitnami/kong
::set-output name=result::ok



Testing PR #9072 "[bitnami/kafka] Enable SSL for kafka privisioning job" https://github.com/bitnami/charts/pull/9072
---
https://api.github.com/repos/bitnami/charts/pulls/9072/files
::set-output name=chart::bitnami/kafka
::set-output name=result::ok



Testing PR #9070 "[bitnami/logstash] Adding serviceaccount configuration for Workload Identity usage" https://github.com/bitnami/charts/pull/9070
---
https://api.github.com/repos/bitnami/charts/pulls/9070/files
-e ::set-output name=error::Changes detected in more than one chart directory:
bitnami/airflow
bitnami/apache
bitnami/argo-workflows
bitnami/aspnet-core
bitnami/cassandra
bitnami/consul
bitnami/contour
bitnami/dataplatform-bp2
bitnami/drupal
It is strongly advised to change only one chart in a PR. The rest of the tests will be skipped.
::set-output name=result::skip



Testing PR #9068 "[bitnami/thanos] Properly name HPA for receive-distributor" https://github.com/bitnami/charts/pull/9068
---
https://api.github.com/repos/bitnami/charts/pulls/9068/files
::set-output name=chart::bitnami/thanos
::set-output name=result::ok



Testing PR #9065 "[bitnami/mongodb] Selector support for PVC in non-STS deployment" https://github.com/bitnami/charts/pull/9065
---
https://api.github.com/repos/bitnami/charts/pulls/9065/files
::set-output name=error::Detected changes in charts without version bump in Chart.yaml.
Charts changed: 1
bitnami/mongodb
Version bumps detected: 0
::set-output name=result::fail



Testing PR #9062 "[bitnami/common] README: Fixed the desscription for `common.labels.matchLabels`" https://github.com/bitnami/charts/pull/9062
---
https://api.github.com/repos/bitnami/charts/pulls/9062/files
::set-output name=chart::bitnami/common
::set-output name=result::ok



Testing PR #9058 "[bitnami/kiam] MAJOR - Update Kiam to v4 + agent root permissions" https://github.com/bitnami/charts/pull/9058
---
https://api.github.com/repos/bitnami/charts/pulls/9058/files
::set-output name=chart::bitnami/kiam
::set-output name=result::ok



Testing PR #9039 "[bitnami/keycloak] Add support for PEM certificates" https://github.com/bitnami/charts/pull/9039
---
https://api.github.com/repos/bitnami/charts/pulls/9039/files
::set-output name=chart::bitnami/keycloak
::set-output name=result::ok



Testing PR #9025 "bitnami/thanos: Remove replica count if HPA is enabled on Thanos Query and Query Front-End" https://github.com/bitnami/charts/pull/9025
---
https://api.github.com/repos/bitnami/charts/pulls/9025/files
::set-output name=chart::bitnami/thanos
::set-output name=result::ok



Testing PR #8973 "[bitnami/Keycloak] Improve documentation for tls ingress" https://github.com/bitnami/charts/pull/8973
---
https://api.github.com/repos/bitnami/charts/pulls/8973/files
::set-output name=error::Detected changes in charts without version bump in Chart.yaml.
Charts changed: 1
bitnami/keycloak
Version bumps detected: 0
::set-output name=result::fail



Testing PR #8542 "[bitnami/rabbitmq] Error on network policy definition" https://github.com/bitnami/charts/pull/8542
---
https://api.github.com/repos/bitnami/charts/pulls/8542/files
::set-output name=chart::bitnami/rabbitmq
::set-output name=result::ok



Testing PR #8523 "bitnami/databunker" https://github.com/bitnami/charts/pull/8523
---
https://api.github.com/repos/bitnami/charts/pulls/8523/files
::set-output name=chart::bitnami/databunker
::set-output name=result::ok



Testing PR #8108 "[bitnami/keycloak] Feature/keycloak external databases" https://github.com/bitnami/charts/pull/8108
---
https://api.github.com/repos/bitnami/charts/pulls/8108/files
::set-output name=chart::bitnami/keycloak
::set-output name=result::ok



Testing PR #7880 "bitnami/dataplatform-bp3 chart with rabbitmq-geode-postgresql" https://github.com/bitnami/charts/pull/7880
---
https://api.github.com/repos/bitnami/charts/pulls/7880/files
::set-output name=chart::bitnami/dataplatform-bp3
::set-output name=result::ok



Testing PR #6762 "[bitnami/zookeeper] Rework security context" https://github.com/bitnami/charts/pull/6762
---
https://api.github.com/repos/bitnami/charts/pulls/6762/files
::set-output name=chart::bitnami/zookeeper
::set-output name=result::ok



Testing PR #6709 "[bitnami/geoipupdate] Add geoipupdate chart" https://github.com/bitnami/charts/pull/6709
---
https://api.github.com/repos/bitnami/charts/pulls/6709/files
::set-output name=chart::bitnami/geoipupdate
::set-output name=result::ok



Testing PR #6295 "[bitnami/thanos] Update bucketweb probe's paths for v0.20.0+ (#6293)" https://github.com/bitnami/charts/pull/6295
---
https://api.github.com/repos/bitnami/charts/pulls/6295/files
::set-output name=chart::bitnami/thanos
::set-output name=result::ok



Testing PR #6109 "[bitnami/charts] add periodic volumesnapshots for CSI drivers" https://github.com/bitnami/charts/pull/6109
---
https://api.github.com/repos/bitnami/charts/pulls/6109/files
::set-output name=error::Detected changes in charts without version bump in Chart.yaml.
Charts changed: 1
bitnami/mongodb
Version bumps detected: 0
::set-output name=result::fail



Testing PR #5627 "[bitnami/external-dns] Fix reference to TransIP API secret" https://github.com/bitnami/charts/pull/5627
---
https://api.github.com/repos/bitnami/charts/pulls/5627/files
::set-output name=chart::bitnami/external-dns
::set-output name=result::ok



Testing PR #5433 "[bitnami/netbox] Introuce new Netbox Chart [WiP]" https://github.com/bitnami/charts/pull/5433
---
https://api.github.com/repos/bitnami/charts/pulls/5433/files
::set-output name=chart::bitnami/netbox
::set-output name=result::ok

```
</details>

Script used for testing
```bash
REPOSITORY=${1:-bitnami/charts}

check_pr () {
    PULL_REQUEST=${1:-9999999}

    # Using the Github API to detect the files changed as git merge-base stops working when the branch is behind
    # and jitterbit/get-changed-files does not support pull_request_target
    URL="https://api.github.com/repos/$REPOSITORY/pulls/$PULL_REQUEST/files"
    files_changed_data=$(curl -s --header 'authorization: Bearer '$GITHUB_TOKEN -X GET -G "$URL" | sed 's/\\/\\\\/g')
    files_changed="$(echo $files_changed_data | jq -r '.[] | .filename')"
    # Adding || true to avoid "Process exited with code 1" errors
    charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "bitnami/[^/]*" | sort | uniq || true)"
    # Using grep -c as a better alternative to wc -l when dealing with empty strings."
    num_charts_changed="$(echo "$charts_dirs_changed" | grep -c "bitnami" || true)"
    num_version_bumps="$(echo "$files_changed_data" | jq -r '[.[] | select(.filename|endswith("Chart.yaml")) | select(.patch|contains("+version")) ] | length' )"


    if [[ "$num_charts_changed" -ne "$num_version_bumps" ]]; then
    # Changes done in charts but version not bumped -> ERROR
    echo "::set-output name=error::Detected changes in charts without version bump in Chart.yaml.\nCharts changed: ${num_charts_changed}\n${charts_dirs_changed}\nVersion bumps detected: ${num_version_bumps}"
    echo "::set-output name=result::fail"
    elif [[ "$num_charts_changed" -eq "1" ]]; then
    # Changes done in only one chart -> OK
    echo "::set-output name=chart::${charts_dirs_changed}"
    echo "::set-output name=result::ok"
    elif [[ "$num_charts_changed" -le "0" ]]; then
    # Changes done in the bitnami/ folder but not inside a chart subfolder -> SKIP
    echo "::set-output name=error::No changes detected in charts. The rest of the tests will be skipped."
    echo "::set-output name=result::skip"
    else
    # Changes done in more than chart -> SKIP
    echo -e "::set-output name=error::Changes detected in more than one chart directory:\n${charts_dirs_changed}\nIt is strongly advised to change only one chart in a PR. The rest of the tests will be skipped."
    echo "::set-output name=result::skip"
    fi


}


PULLS_URL="https://api.github.com/repos/${REPOSITORY}/pulls"
PRS=$(curl -s --header 'authorization: Bearer '${GITHUB_TOKEN} -X GET -G "$PULLS_URL" | jq -r '[.[] | {number, title} | select(.title|test("bitnami/\\w"))]')

echo $PRS | jq -r '.[] | [.number, .title] | @tsv' |
  while IFS=$'\t' read -r prnum prtitle; do
    echo "Testing PR #$prnum \"$prtitle\"" https://github.com/$REPOSITORY/pull/$prnum
    echo "---"
    check_pr "$prnum"
    echo "\n\n"
    sleep 1
  done
```

**Comment by javsalgar** [comment]
Thanks! Merging

**Comment by javsalgar** [comment]
It seems that the change broke the action. I created a fix #9164

**Pull request merged**
