### PR TITLE
[bitnami/external-dns] Added Openshift Routes support

### PR DESCRIPTION
**Pull request by aelbarkani**
**Description of the change**

Added permissions on OpenShift Routes in ClusterRole and Role.

**Benefits**

Adds support for OpenShift Routes (external-dns itself supports it already: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/openshift.md)

**Possible drawbacks**

None

**Applicable issues**

N/A

**Additional information**

N/A

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by WebSpider** [comment]
Shouldn't this be dependant on a flag indicating you're using openshift?

**Comment by migruiz4** [comment]
Hi @aelbarkani ,

Thank you for your contribution, your PR looks good to me.

Answering your question @WebSpider, I think adding flags could be interesting, but we haven't received that feature request so we consider it is not a common use case, probably because it doesn't have any impact if you are not using OpenShift.

I'm approving this PR because, as you can see, other API groups are configured without control flags and other assets including this same feature don't have it either:
https://github.com/bitnami/charts/blob/71fb99f541e971b1daafaa20ffb7d18b153b8d60/bitnami/grafana-operator/templates/rbac.yaml#L62-L75

**Review by migruiz4 — APPROVED** [review]

**Comment by migruiz4** [comment]
Before we proceed to merge, could you please resolve branch conflicts?

**Comment by aelbarkani** [comment]
@migruiz4 great, thanks ! the conflict has been resolved.

**Comment by migruiz4** [comment]
Thank you for your contribution!

**Pull request merged**
