### PR TITLE
[bitnami/discourse] Move plugins installation to init-container

### PR DESCRIPTION
**Pull request by juan131**
### Description of the change

This PR moves the Discourse plugins installation to a init-container and ensure the plugins are properly shared between Discourse and Sidekiq container regardless they're persisted or not.

### Benefits

Plugins can be installed with no persistence enabled.

### Possible drawbacks

None

### Applicable issues

- fixes https://github.com/bitnami/charts/issues/29169

### Additional information

N/A

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by migruiz4 — APPROVED** [review]
LGTM!

**Comment by netdata-be** [comment]
I tried upgrading to the latest helm chart and this commit seems to break the plugin handling.
Whatever we try the plugin is not extracted from the init container and thus not injected in the discours / sidekiq containers.

What I'm I doing wrong here?
Tried to play with persistPlugins ( default, true, false) but none of them seem to get this sorted.

It looks like this is a bug

**Comment by notz** [comment]
@juan131 Are sure this is working as expected? 

See https://github.com/bitnami/charts/issues/29169#issuecomment-2402005428

**Comment by juan131** [comment]
Let's follow the conversation at https://github.com/bitnami/charts/issues/29169

**Pull request merged**
