### PR TITLE
[bitnami/nopcommerce] Add nopCommerce to bitnami

### PR DESCRIPTION
**Pull request by skoshelev**
Signed-off-by: Koshelev Sergey <sergey.k@nopcommerce.com>

### Description of the change

A few months ago we discussed with you the possibility of adding our product to your system. Here is the topic - https://community.bitnami.com/t/how-do-we-submit-suggest-a-new-application-to-bitnami-application-catalog/104416

So we've just created a PR as you've suggested. Please check it out and let me know if it works for you.

### Possible drawbacks

Please note that for testing purposes we've used our image in the dockerhub - https://hub.docker.com/r/nopcommerceteam/nopcommerce. We understand that this does not meet your requirements to have a docker image in your own repository. So we're ready to discuss with you the details of adding our image in your dockerhub.

### Checklist

- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your PR! We will check it internally and evaluate the feasibility but due to limited resources that could take some time. 

Please note that the container images included in this chart are not part of the Bitnami catalog at this moment which is a mandatory requirement for us to accept the chart (see [CONTRIBUTING.md](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository)).
I'm afraid it's not as simple as creating a new container repo based on existing ones. Creating an image for the Bitnami catalog implies several changes in our internal repositories so we can automate the whole process of tracking new releases in the upstream project, downloading the source code, compiling the binaries, creating the containers, testing them on different scenarios, publishing them, etc.

**Comment by skoshelev** [comment]
@carrodher Thank a lot you for response. Of course, we understand that creating an image is not so easy, and we are ready to provide you with any assistance with this task.
We also have the basic instructions for creating a [docker image](https://github.com/nopSolutions/nopCommerce/blob/4.50-bug-fixes/Dockerfile) from our source code, which we have updated to run successfully through Kubernetes.

**Comment by skoshelev** [comment]
Hi @carrodher. Could you please share the current status of this pull request? It would be great if you also can share some estimate

**Comment by carrodher** [comment]
It's being evaluated by the Product team which is a required step before the Engg team works on adding new assets to the catalog. Unfortunately, this is something that could take some time and since it is out of our scope I can't provide an ETA.

**Comment by AndreiMaz** [comment]
@carrodher Any progress on the check? It's been already two months since we've submitted this pull request

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your contribution and suggestion!

**Comment by AndreiMaz** [comment]
@carrodher Originally you asked whether you can add nopCommerce to Bitnami (on your community website), and your team suggested us to create a pull request. We've spent a lot of time to create this pull request and created this PR.

Could you please clarify why exactly you decide not to add it now?

**Comment by carrodher** [comment]
Before adding a new Helm chart into the catalog it should be accepted by Product Management. This team uses their own decision framework (which is not only based on technical aspects) in order to determine if a new product is added to the catalog or not. Adding a new product not only merges the PR but it is also needed to maintain it, provide support, etc. That's why all the requests should be analyzed based on that decision framework.

In the [CONTRIBUTING guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository), there is a warning about this evaluation, not all the PRs adding new products can be accepted:
> Please, note we will need to check internally and evaluate the feasibility of adding the new solution to the catalog. Due to limited resources this step could take some time.

**Pull request closed without merging**
