### PR TITLE
[bitnami/rabbitmq] Load definition volume secret name should consider prepend release name

### PR DESCRIPTION
**Pull request by DanielFran**
### Applicable issues

- fixes https://github.com/bitnami/charts/issues/18061

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by DanielFran** [comment]
@fmulero The seccret name created [here](https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/templates/secrets.yaml#L38) is not matching the name in the volume.

This PR fix it.

**Comment by fmulero** [comment]
Hi Daniel,

In the pictures you shared, you can see how the value `extraSecretsPrependReleaseName` works with `extraSecrets` not with `loadDefinition.existingSecret` value. Don't get me wrong but I think you are mixing both values. Please correct if I am wrong sharing an scenario to test it.

**Comment by DanielFran** [comment]
> Hi Daniel,
> 
> In the pictures you shared, you can see how the value `extraSecretsPrependReleaseName` works with `extraSecrets` not with `loadDefinition.existingSecret` value. Don't get me wrong but I think you are mixing both values. Please correct if I am wrong sharing an scenario to test it.

@fmulero No problem.
To instantiate a rabbitmq with a load definition, we should use load-definition properties, and in my case I want that the secret prepend with the instance name (example: rabbitmq-example).

So the config to use is:
- @param loadDefinition.enabled Enable loading a RabbitMQ definitions file to configure RabbitMQ
loadDefinition.enabled: true
- @param loadDefinition.existingSecret Existing secret with the load definitions file
loadDefinition.existingSecret: "load-definition"
- @param extraSecrets Optionally specify extra secrets to be created by the chart. This can be useful when combined with load_definitions to automatically create the secret containing the definitions to be loaded.
````yaml
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        ...
      }
````
- @param extraSecretsPrependReleaseName Set this flag to true if extraSecrets should be created with <release-name> prepended.
extraSecretsPrependReleaseName: true

[secrets.yaml](https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/templates/secrets.yaml#L33-L49) will create an a secret example like:

````yaml
# Source: rabbitmq-example/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-example-load-definition
  namespace: "dev"
  labels:
    app.kubernetes.io/name: rabbitmq-example
    helm.sh/chart: rabbitmq-example-12.0.7
    app.kubernetes.io/instance: rabbitmq-example
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  load-definition.json: |-
      {
        ...
      }
````

[statefulset.yaml](https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/templates/statefulset.yaml#L414-L417) will create an a volume with wrong secret name:

````yaml
# Source: rabbitmq-example/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-example
  namespace: "dev"
  labels:
    app.kubernetes.io/name: rabbitmq-example
    helm.sh/chart: rabbitmq-example-12.0.7
    app.kubernetes.io/instance: rabbitmq-example
    app.kubernetes.io/managed-by: Helm
spec:
  ...
      volumes:
        - name: load-definition-volume
          secret:
            secretName: load-definition
````

**Comment by DanielFran** [comment]
@fmulero I realize that extraSecrets can be used to create the load-definition secret as per the readme information, but it is not mandatory, so the volume secret name can be handled using the templating.
Closing the PR

**Pull request closed without merging**
