### PR TITLE
[bitnami/fluent-bit] Add Fluent Bit OCI links

### PR DESCRIPTION
**Pull request by aoterolorenzo**
### Description of the change

Replace charts repo with oci registry links

### Checklist

- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by fmulero — COMMENTED** [review]
Hi @aoterolorenzo, I know this is a small change, but could bump the chart version?

**Review by fmulero — APPROVED** [review]
LGTM

**Comment by NeckBeardPrince** [comment]
@fmulero @aoterolorenzo @Mauraza Just a fyi `helm repo add my-repo oci://registry-1.docker.io/bitnamicharts` is not valid. You can't add an oci registry with `helm repo add`. You can use `oci://` with `pull` `show` `template` `install` or `upgrade`. You can read the helm docs for this [here](https://helm.sh/docs/topics/registries/#other-subcommands).

**Comment by carrodher** [comment]
You're totally right, I just created [this PR](https://github.com/bitnami/charts/pull/16728) to fix it.

**Pull request merged**
