### PR TITLE
[bitnami/zookeeper] feat(zookeeper) Added tls support for zookeeper

### PR DESCRIPTION
**Pull request by fsniper**
**Description of the change**

This adds support for adding TLS for client connections and quorum to zookeeper.
Also extra env variables section is added. 

**Benefits**

Production cluster can have the benefit of tls communications.

**Possible drawbacks**

Keystore and Truststore files need to be created and mounted into the pods. 

**Applicable issues**

**Additional information**

This will require an update to the https://github.com/bitnami/bitnami-docker-zookeeper/ container. A PR will follow.

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by rafariossaa** [comment]
Hi @fsniper ,
  Thank you very much for your PR !! 
  Currently we are working in a similar task, so some changes will be needed but I can't tell you right now.
  We will let you know how all fit together as we have something to share.

**Comment by zemmet** [comment]
Hi @rafariossaa. Thanks for the quick response on this. Is there any timeline you can provide?

**Comment by rafariossaa** [comment]
Hi @zemmet ,
  I not yet, but it shouldn't take long.

**Comment by bergerx** [comment]
@rafariossaa any news on this? I saw you added an on-hold label to this one.

We'd be happy if we can get rid of our internal fork and can use this feature from upstream.

**Pull request merged**
