### PR TITLE
[bitnami/sonarqube] wrong secret name called in deployment

### PR DESCRIPTION
**Pull request by gabo89**
hello i woud like to contribute at fixing a small error, the error happens when existing secret is not provided and plain password are used in the chart the secret named is generated correctly but is being called with wrong name caused by this error , the variable affected is  SONARQUBE_DATABASE_PASSWORD in the deployment.yaml for sonarqube

https://github.com/bitnami/charts/blob/master/bitnami/sonarqube/templates/deployment.yaml

```- name: SONARQUBE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonarqube.database.secretName" . }}
                  key: password
```

**Benefits**

Secret  for sonarqube database password will be called correctly when user doesnt set existing secret 

**Possible drawbacks**

NONE

**Applicable issues**

NONE

**Additional information**

it can help deploying the chart easily when you cant write secret to the cluster due to not enough privileges 

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your contribution, could you please bump the chart version in the Chart.yaml file?

**Comment by gabo89** [comment]
hello @carrodher i just bump the chart version

**Comment by gabo89** [comment]
hello @carrodher i just bump the chart version

**Review by FraPazGal — APPROVED** [review]
Thanks for the PR @gabo89! LGTM

**Pull request merged**
