### PR TITLE
[bitnami/influxdb] - add nodeSelector, affinity and tolerations to the backup container(s)

### LINKED ISSUE #6765: Helm InfluxDB - backup pod ignores nodeSelectors
Hi there guys,

unfortunately the pod triggered by [cronjob-backup.yam](https://github.com/bitnami/charts/blob/master/bitnami/influxdb/templates/influxdb/cronjob-backup.yaml) ignores the nodeSelectors defined inside values.yaml.

### PR DESCRIPTION
**Pull request by bartlomiejwulff**
- [X ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ X] Variables are documented in the README.md
- [ X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

It seems that the chart.yaml needs to be changed again, could you check it?

**Comment by javsalgar** [comment]
One question, does it make sense for the cronjob pods to use the same affinity settings as influxdb, or it should have its own settings? From what I see, it has its own `backup.cronjob` set of values, so I'd rather create a `backup.cronjob.affinity` settings there

**Comment by bartlomiejwulff** [comment]
> One question, does it make sense for the cronjob pods to use the same affinity settings as influxdb, or it should have its own settings? From what I see, it has its own `backup.cronjob` set of values, so I'd rather create a `backup.cronjob.affinity` settings there

Agree, I have just updated the PR. Please review

**Review by javsalgar — APPROVED** [review]
LGTM

**Pull request merged**
