### PR TITLE
[bitami/mariadb] fix replication password #3909

### LINKED ISSUE #3909: [mariadb] <.Values.rauth.replicationPassword>: nil pointer evaluating interface {}.replicationPassword
**Which chart**:

mariadb 8.0.1

**Describe the bug**

There is typo in secrets.yaml and also logocal error related to replication password. 

```
  Error: Failed to render chart: exit status 1: Error: template: mariadb/templates/secrets.yaml:35:97: executing "mariadb/templates/secrets.yaml" at <.Values.rauth.replicationPassword>: nil pointer evaluating interface {}.replicationPassword
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error
```

**To Reproduce**
1. Just try to install

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
**(paste your output here)**
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

### PR DESCRIPTION
**Pull request by acim**
**Description of the change**

- fixed typo rauth to auth
- fixed logical error which caused error "A MariaDB Replication Password is required!" when architecture=replication and auth.replicationPassword is empty.

**Benefits**

Fix problems.

**Possible drawbacks**

Not known.

**Applicable issues**

  - fixes #3909 

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Review by rafariossaa — APPROVED** [review]
LGTM

**Comment by rafariossaa** [comment]
Hi,
  Thank you very much for fixing this.

Best regards,

**Comment by acim** [comment]
You are welcome. I am using several charts from bitnami, so this is fair :)

**Comment by rafariossaa** [comment]
Hi,
  Thanks !

**Pull request merged**
