### PR TITLE
[bitnami/metrics-server] Add probes, SecurityContext and command config

### PR DESCRIPTION
**Pull request by mkilchhofer**
**Description of the change**

This change adds the ability to configure:
- liveness and readiness probes
- container and pod level SecurityContext
- command (useful when using custom images)

Probes and containerSecurityContext are turned on by default, as used in upstream (https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.4.2/components.yaml).

**Benefits**

Probes, SecurityContext (pod and container level) and command can be configured.

**Possible drawbacks**

`-`

**Applicable issues**

`-`

**Additional information**

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by mkilchhofer** [comment]
Do your local CI system need the file `values-with-rbac.yaml` inside the `ci` directory, or what's the intent for this file?

I symlinked this file since CI here on github uses Kind to test the chart. And the metrics server also need the argument `kubelet-insecure-tls=true` for talking to the kind control-plane, otherwise it cannot connect:
```logs
I0220 18:39:35.203528       1 serving.go:325] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
E0220 18:39:35.626723       1 server.go:132] unable to fully scrape metrics: unable to fully scrape metrics from node kind-control-plane: unable to fetch metrics from node kind-control-plane: Get "https://kind-control-plane:10250/stats/summary?only_cpu_and_memory=true": x509: certificate signed by unknown authority
(..)
I0220 18:39:35.741374       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
```

Maybe this only pops up because I introduce probes.

**Review by marcosbc — COMMENTED** [review]
Thanks for the contribution! In princple these changes look good to me, but I would like for @juan131 to review these as well, in case he knows what happens with the `ct-values.yaml`.

**Review by juan131 — APPROVED** [review]
Thanks so much for the PR! LGTM

**Comment by juan131** [comment]
Regarding the `values-with-rbac.yaml` vs `ct-values.yaml`, there are some basic differences:

- All the `values-XXXX.yaml` you find under the `ci/` directories of this chart are intended to test combinations using the `githooks` defined at https://github.com/bitnami/charts/tree/master/githooks. That requires the developer to have them installed (see https://github.com/git-hooks/git-hooks/#install) and it's optional.
- The `ct-values.yaml` is used by the GitHub actions (the automatic tests) that are based on https://github.com/kubernetes-sigs/kind

**Comment by mkilchhofer** [comment]
Alright, thanks for clarify that, @juan131. For now we use the same values for the GitHub action and these optional local tests as the file is symlinked now.

**Comment by chadlwilson** [comment]
Hi @mkilchhofer - any reason from your perspective that the default is `readOnlyRootFilesystem: false` here? We run a PSP that restricts this to to `readOnly` by default and haven't noticed any issues with this.

**Comment by mkilchhofer** [comment]
Hi @chadlwilson,
I am not 100% sure if it works without setting other values. Especially adding a scratch directory for `/tmp` is needed for my config: https://github.com/mkilchhofer/k8s-gitops/blob/main/clusters/k3s/kube-system/metrics-server.yaml#L31-L41

Maybe it is due to the `--cert-dir=/tmp` argument I use in my config as the upstream manifest examples are like this.

**Pull request merged**
