### PR TITLE
[bitnami/pinniped] Update pinniped CRDs

### LINKED ISSUE #20507: [bitnami/pinniped] Incorrect CRD versions in use
### Name and Version

bitnami/pinniped 1.3.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

While testing the bitnami/pinniped helm chart I ran into an issue which required some troubleshooting.

On a base install, check the federationdomains CRD with this command:

`kubectl get crd federationdomains.config.supervisor.pinniped.dev -o 'jsonpath={.spec.versions[0].additionalPrinterColumns[?(@.name=="Status")]}'`

### Are you using any custom parameters or values?

None required.

### What is the expected behavior?

We're expecting output to be: 
`{"jsonPath":".status.phase","name":"Status","type":"string"}`

### What do you see instead?

Currently with the helm chart we get this incorrect response:

`{"jsonPath":".status.status","name":"Status","type":"string"}`

This response is incorrect for v0.27.0 of Pinniped.

### Additional information

This doesn't appear to affect authentication, but means checking status of the federationdomain configuration shows a blank space instead of the actual status. It's worth getting the CRDs aligned in case any other functionality is affected.

I believe the Pinniped devs are looking to version their CRDs in future to help keep this aligned.

### PR DESCRIPTION
**Pull request by CeliaGMqrz**
### Description of the change

According with [upstream](https://github.com/vmware-tanzu/pinniped/tree/main/generated/1.28/crds) this PR updates the pinniped CRDs to `v0.13.0`

### Applicable issues

- fixes #20507 

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by fmulero — APPROVED** [review]
LGTM

**Review by fmulero — CHANGES_REQUESTED** [review]
Hi @CeliaGMqrz

I've just seen several errors in the pods about the access to custom resources. Roles should be revisited also to avoid those issues

**Review by fmulero — APPROVED** [review]

**Review by javsalgar — APPROVED** [review]

**Review by fmulero — APPROVED** [review]
LGTM

**Comment by fmulero** [comment]
CRDs has been updated in the PR https://github.com/bitnami/charts/pull/21600

**Pull request closed without merging**
