### PR TITLE
[bitnami/external-dns] Add support for traefik ingressroutes in clust…

### PR DESCRIPTION
**Pull request by Atoms**
### Description of the change

as of version 0.13.6 external-dns supports reading traefik ingress resources for dns, for external dns to be able to read them additional scopes in clusterrole are needed.

### Benefits

possibility to configure as per external-dns docs, as currently it's failing

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your contribution, please note there was a new chart version during this time and it is needed to bump the version in the _Chart.yaml_ again. Sorry for the inconvenience

**Comment by Atoms** [comment]
bumped version

**Comment by trunet** [comment]
@carrodher @CeliaGMqrz is there anything else holding this PR to be merged? If it takes too long, the version will need to be bumped again. I'm closing the duplicate PR I submitted in favor of this one.

**Review by aoterolorenzo — DISMISSED** [review]
Thanks for the contribution! LGTM

**Review by aoterolorenzo — APPROVED** [review]

**Pull request merged**
