### PR TITLE
Updated README, added animated screencast

### PR DESCRIPTION
**Pull request by vikram-bitnami**
**Description of the change**

Removed manual list of charts, added screencast of basic usage

**Benefits**

Quicker understanding of how to use our charts

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [ ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by vikram-bitnami** [comment]
> I would do the gif with a smaller size so there are not breaking lines.

The size seems to be auto-generated depending on the width. However I fixed the extra long lines so it looks better.
 
> I would remove all repos you currently have and only have the bitnami one. Executing "helm search" you will show all of the Charts in the repo

Done. Please see if OK now.

**Comment by vikram-bitnami** [comment]
When merging, note there will be a conflict between this `demo.gif` and the one in `origin`. I accidentally uploaded an older copy of the file to `origin`. For conflict resolution, the one in this PR is the correct one.

**Comment by juan131** [comment]
@vikram-bitnami I think you need to solve the conflict even if there are no conflicts with the one in `origin`. GitHub won't allow as to merge the PR unless you solve it.

**Comment by vikram-bitnami** [comment]
Closing this without merge in favour of https://github.com/bitnami/charts/pull/1470

**Pull request closed without merging**
