### PR TITLE
[bitnami/several] Simplify image definition logic removing duplications

### PR DESCRIPTION
**Pull request by carrodher**
**Description of the change**

In this version, the `image` block is defined once and is used in the different templates, while in the previous version, the `image` block was duplicated for every component

```yaml
image:
  registry: docker.io
  repository: bitnami/xxx
  tag: A.B.C
```
VS
```yaml
foo:
  image:
    registry: docker.io
    repository: bitnami/xxx
    tag: A.B.C
...
bar:
  image:
    registry: docker.io
    repository: bitnami/xxx
    tag: A.B.C
```

**Possible drawbacks**

The chart version was bumped in a major

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Review by javsalgar — APPROVED** [review]

**Comment by kingvip** [comment]
Is there a version of helm solr cloud 8.4.1?  thank you

**Comment by kingvip** [comment]
Cloud > ZK Status For input string: "null" How to solve

**Comment by kingvip** [comment]
@carrodher

**Comment by kingvip** [comment]
@carrodher

**Pull request merged**
