### PR TITLE
[bitnami/mysql] Added support for MySQL volume subPath

### PR DESCRIPTION
**Pull request by janario**
MySQL chart, in some scenarios with a more controlled Volume, we may need to use a custom path for it.

This will provide a new parameter to the MySQL helm chart to use a custom subPath for persistence volume

### Applicable issues

  - fixes #

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by CeliaGMqrz** [comment]
Hi @janario, 

Thanks for your contribution!

Looks good to me, but this chart also supports [secondary deployment](https://github.com/bitnami/charts/tree/main/bitnami/mysql/templates/secondary), which defines its own entry for persistence. Could you add it there too?

**Comment by janario** [comment]
Hi @CeliaGMqrz 

Very good point, I've gone over the persistence values for the secondary and it was a bit different, so I've added two new values for it (existingClaim and subPath) so now they have a pretty similar template, except for the values

pls give it another look and let me know if you think something else can be changed ;-)

**Comment by janario** [comment]
Hey @CeliaGMqrz any updates here?

Looking forward to have this :-)

**Review by CeliaGMqrz — APPROVED** [review]
LGTM! Thanks for the contribution!

**Pull request merged**
