### PR TITLE
fix error converting YAML to JSON: yaml: line 2628: did not find expe…

### PR DESCRIPTION
**Pull request by qlu1990**
…cted key

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist**

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [ ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [ ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by juan131 — CHANGES_REQUESTED** [review]
Thanks so much for the fix @qlu1990 !! Could you please bump the patch version in the Chart.yaml? Please also ensure to sign your commits, otherwise the DCO check will fail.

**Comment by qlu1990** [comment]
> Also could you please merge from master? It's necessary for the Github action to work

i just copy master and fix config don't change version and other things

**Comment by juan131** [comment]
Hi @qlu1990 

My colleague @javsalgar is just asking to **rebase** from master, you don't need to copy anything.

**Comment by qlu1990** [comment]
> Hi @qlu1990
> 
> My colleague @javsalgar is just asking to **rebase** from master, you don't need to copy anything.



> 

you mean i just need pull  this master and fix then push back ?

**Comment by juan131** [comment]
You need to sync your fork repo, see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Pull request closed without merging**
