### PR TITLE
[bitnami/mongodb-sharded] Replace "configMapRef" with "secretRef" when configuring extra variables

### PR DESCRIPTION
**Pull request by zraul123**
**Description of the change**

Replace "configMapRef" with "secretRef" when configuring extra variables, so that it correctly points to a secret instead of a config map.

**Benefits**

The configuration is working correctly now

**Possible drawbacks**

-

**Applicable issues**

  - fixes #

**Additional information**

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by zraul123** [comment]
Any idea why the early feedback pipeline step still isn't recognizing the version bump? Should I close and re-open the PR?

**Comment by javsalgar** [comment]
We just merged this. https://github.com/bitnami/charts/commit/8a68afc4c7f9c3027a95a537f348ad0accd88fef

Could you merge from master again?

**Comment by zraul123** [comment]
> We just merged this. [8a68afc](https://github.com/bitnami/charts/commit/8a68afc4c7f9c3027a95a537f348ad0accd88fef)
> 
> Could you merge from master again?

Done! Still getting some weird errors..

**Comment by javsalgar** [comment]
@marpontes  It seems that the issue is because of this ` sed 's/\\/\\\\/g`. Any reason why it was necessary to add that? How is it that it did not fail in the tests?

**Comment by javsalgar** [comment]
@zraul could you merge and try again?

**Comment by zraul123** [comment]
> @zraul could you merge and try again?

It works, thank you! :-)

**Comment by marpontes** [comment]
> @marpontes It seems that the issue is because of this ` sed 's/\\/\\\\/g`. Do you recall the reason why it was necessary to add that? How is it that it did not fail in the tests?

The reason was that storing the outputs of the curl on a variable on my terminal wasn't escaping new lines correctly. I should've tested on the `ubuntu-latest`. 🤦 

I ran tests again now using ubuntu-latest and it's looking good. Will open a new PR.

**Review by juan131 — APPROVED** [review]
LGTM

**Pull request merged**
