### PR TITLE
[bitnami/wordpress] Non-manual chart upgrades

### PR DESCRIPTION
**Pull request by mamiu**
**Description of the change**

> **IMPORTANT:** Only merge this PR once https://github.com/bitnami/charts/pull/9268 is merged.

Automatically get the correct wordpress password on wordpress chart upgrade.

Currently the following error message is shown when a user wants to upgrade the [bitnami/wordpress] helm chart without having specified an `existingSecret` or the `wordpressPassword`, `mariadb.auth.password` and `mariadb.auth.rootPassword` value:

```
Error: UPGRADE FAILED: template: wordpress/templates/NOTES.txt:108:4: executing "wordpress/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" $passwordValidationErrors "context" $)>:
error calling include: template: wordpress/charts/common/templates/_errors.tpl:21:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail: HELM_ERR_START

PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'mariadb.auth.rootPassword' must not be empty, please add '--set mariadb.auth.rootPassword=$MARIADB_ROOT_PASSWORD' to the command. To get the current value:

        export MARIADB_ROOT_PASSWORD=$(kubectl get secret --namespace "the-wp-namespace" wordpress-test-mariadb-prod -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)

    'mariadb.auth.password' must not be empty, please add '--set mariadb.auth.password=$MARIADB_PASSWORD' to the command. To get the current value:

        export MARIADB_PASSWORD=$(kubectl get secret --namespace "the-wp-namespace" wordpress-test-mariadb-prod -o jsonpath="{.data.mariadb-password}" | base64 --decode)
```

**Benefits**

The upgrade won't fail and the user doesn't have to retrieve and specify the secrets manually.
This change allows the user to upgrade the chart without worrying.

**Possible drawbacks**

None.

**Applicable issues**

  - similar to #7403 

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by mamiu** [comment]
@marcosbc Sure thing, no worries! I'll let you know once #9268 is merged.

**Comment by mamiu** [comment]
@marcosbc PR #9268 is merged now. So this one is ready to be reviewed.

**Comment by marcosbc** [comment]
Thanks @mamiu! Could you fix the conflicts with the `master` branch? Apart from that, it LGTM!

**Comment by mamiu** [comment]
@marcosbc Thanks for the review! The conflicts are resolved now.

**Review by marcosbc — APPROVED** [review]
LGTM! Thanks!!!

**Pull request merged**
