### PR TITLE
bitnami/dataplatform-bp1 and bitnami/dataplatform-bp2 charts updated with extra set of affinity rules.

### PR DESCRIPTION
**Pull request by yogesh-reddy**
**Description of the change**
The pod affinity and anti affinity rules were updated for bitnami/dataplatform-bp1 , bitnami/dataplatform-bp2 charts because when we have two deployments from both the blueprints on the same cluster the affinity rules would conflict each other, as two blueprints have some pods in common. To overcome this extra set of affinity rules were added on the release name for both the blueprints.  

**Benefits**
Two blueprints can be added on the same cluster and namespace without conflicts if provided with the sufficient resources.

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by yogesh-reddy** [comment]
@gkulkarni32 Try to review the code .

**Comment by gkulkarni32** [comment]
@miguelaeh Yogesh is from my team at OCTO Cloud Architecture. We need a small change to be done in the affinity and anti-affinity rules to include the release name as well so it doesnt apply the affinity across a different release of the data platform. Please review this from your side.

**Review by miguelaeh — CHANGES_REQUESTED** [review]
Hi @yogesh-reddy ,
Thank you very much for the PRs.
I see you bumped the versions in a different way while the change seems to be the same for both charts.
Apart from that, modifying the default `values.yaml` usually requires bumping the major version since updating a release could end in unexpected behaviors. 
Bumping the major, we need to add to both READMEs a note in the `# Upgrading` section.
Also, I see you are using the `{{ .Release.Name }}` in the affinity rules, I am not sure if this is going to be templatized properly, could you confirm, please?

**Comment by gkulkarni32** [comment]
Thank you @miguelaeh 

We will change the versions to the following major versions in both the charts and add a section in README for upgrade. 

dataplatform-bp1: 2.0.0
dataplatform-bp2: 1.0.0

Thanks
Geeta

**Comment by miguelaeh** [comment]
Hi @gkulkarni32 ,

>Also, I see you are using the {{ .Release.Name }} in the affinity rules, I am not sure if this is going to be templatized properly, could you confirm, please?

What about this? Could you re-check it works please?

**Review by miguelaeh — APPROVED** [review]
Thank you very much for addressing all the changes.
LGTM!

**Pull request merged**
