### PR TITLE
[bitnami/redis] Add commonLabels also to pods: master, replicas, sentinel

### LINKED ISSUE #14245: [bitnami/redis] Add commonLabels also to redis pods when deploying master, replicas or sentinel
### Name and Version

bitnami/redis 7.0.7

### What steps will reproduce the bug?

1. Deploy Redis with a label set via the values.yaml commonLabels

### Are you using any custom parameters or values?

```
commonLabels:
    someLabel: "someLabel"
```

### What is the expected behavior?

As stated in the documentation, I would expect all deployed resources to have the label:

Add labels to all the deployed resources (sub-charts are not considered). Evaluated as a template

### What do you see instead?

Redis pods do not get the label

### Additional information

Maybe I misunderstand the documentation, but I would expect the redis pods also to have the label. This would be easily achievable by adding the commonLabels to the pods and not only the podLabels here: 

- https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/master/application.yaml#L35
- https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/replicas/statefulset.yaml#L34
- https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/sentinel/statefulset.yaml#L33

If you agree I could prepare a PR for this.

### PR DESCRIPTION
**Pull request by byroncollins**
### Description of the change

Add commonLabels also to the pods in master, replicas and sentinel.

### Benefits

Add labels via setting only one value instead of needing to set a value for each separately.

### Possible drawbacks

None known so far, previous behaviour can still be applied by using the specific values.

### Applicable issues

  - fixes #14245 

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your contribution. Please note you bumped the app version instead of the chart version, could you please fix that?

**Comment by byroncollins** [comment]
> Thanks for your contribution. Please note you bumped the app version instead of the chart version, could you please fix that?

done!
thanks

**Review by fmulero — COMMENTED** [review]
Hi @byroncollins Thanks for your contribution.

Keeping in mind the standardisation of our charts, I did a quick review of our charts and I didn't see any other using the `commonLabels` in the pod templates. To be honest I don't justification for this change keeping in mind that you have other values (`master.podLabels` or `replica.podLabels`) to set the pod labels and you can use yaml anchors to avoid repeat yourself.

**Comment by byroncollins** [comment]
> 
Thanks @fmulero for you comment.
I based my PR on this [mongoDB PR](https://github.com/bitnami/charts/pull/13501) which looks similar.
If like you say I can achieve the same with master.podLabels and replica.podLabels then that works for us. We just want the same labels added to the statefulset, replicaset and pods.

**Review by fmulero — APPROVED** [review]
Ok, LGTM

**Pull request merged**
