### PR TITLE
Add allowRemoteManagement as a parameter for the Tomcat Helm Chart

### PR DESCRIPTION
**Pull request by dbarranco**
This PR is intended to add the parameter to remotely get access to the Tomcat management services and make us able to test all the services in our CI/CD systems.

### CODE REVIEW

**Comment by dbarranco** [comment]
@sameersbn I've been trying to enable the management services in my minikube cluster but it seems adding the value it is not enough, cause I still don't have access to the management services.

According to the parameters of [the Tomcat container](https://github.com/bitnami/bitnami-docker-tomcat/blob/master/8.5/rootfs/tomcat-inputs.json)

```
  "allowRemoteManagement": "{{$global.env.TOMCAT_ALLOW_REMOTE_MANAGEMENT}}",
```
That is the parameter we should add here, but I'm unsure if I'm missing something.

**Comment by sameersbn** [comment]
@dbarranco can you check now. I amended a commit that adds `TOMCAT_ALLOW_REMOTE_MANAGEMENT` to the container environment.

**Comment by dbarranco** [comment]
@sameersbn Tested and working as it should. 
Looks good to merge

**Comment by sameersbn** [comment]
we're you able to login as the manager? I can't seem to login

**Comment by dbarranco** [comment]
@sameersbn proceeding to land along with the changes in the Tomcat nami module

**Pull request merged**
