### PR TITLE
[bitnami/nginx-ingress-controller] Ingress controller upgrade

### LINKED ISSUE #11192: Breaking Change with Ingress Controller 1.3.0
### Name and Version

bitnami/nginx-ingress-controller 9.2.20

### What steps will reproduce the bug?

1. Install the nginx ingress controller chart version 9.2.20 with the default values

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

The controller pod should log that the leader election occurred without issue.

### What do you see instead?

The leader election is failing due to a change in the upstream app version 1.3.0

> leaderelection.go:330] error retrieving resource lock nginx/ingress-controller-leader: leases.coordination.k8s.io "ingress-controller-leader" is forbidden: User "system:serviceaccount:nginx:nginx-nginx-ingress-controller" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "nginx"

### Additional information

https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.3.0

### PR DESCRIPTION
**Pull request by fmulero**
### Description of the change

Update Role and ClusterRole objects to be aligned with nginx-ingress-controller 1.3.0 requirements. Also that version Kubernetes 1.19 was deprecated. More information: https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.3.0

### Benefits

Keep us aligned with the upstream project

### Possible drawbacks

No support for Kubernetes 1.19

### Applicable issues

  - fixes #11192

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by carrodher — CHANGES_REQUESTED** [review]
Thanks for the PR, please see below some comments related to the README:
- You need to update the k8s version in the [prerequisites section](https://github.com/bitnami/charts/tree/master/bitnami/nginx-ingress-controller#prerequisites) as well
- Since it is a new major, we should add a new entry in the [Upgrading section](https://github.com/bitnami/charts/tree/master/bitnami/nginx-ingress-controller#upgrading)

**Comment by aeimer** [comment]
I would love to see this MR merged. Thanks for the work!

**Comment by adestis-ds** [comment]
Would be great if this could be merged. Had to rollback to previous version...

**Comment by adestis-ds** [comment]
The problem was meanwhile fixed by another Pull request (nginx-ingress-controller version 9.2.27).

**Comment by fmulero** [comment]
Closed in favor of #11454

**Pull request closed without merging**
