### PR TITLE
[bitnami/wordpress] Remove wordpressAutoUpdateLevel parameter during WordPress Chart verification

### PR DESCRIPTION
**Pull request by jotamartos**
**Description of the change**

Remove the usage of the `wordpressAutoUpdateLevel` parameter (disabled by default in the Bitnami WordPress container and Chart) when verifying the chart as this modifies (updates) the version of the solution and the action won't be testing what we have built.

**Benefits**

Remove uncertainties when testing the solution

**Possible drawbacks**

We won't be testing the upgrades (or the latest version) in the solution

**Applicable issues**

  - fixes "chmod(): Operation not permitted" warning messages when verifying the Bitnami WordPress solution

**Additional information**

**Checklist**

- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by marcosbc — DISMISSED** [review]

**Comment by superaleks** [comment]
Please also add a set of test results to the PR before merging.. If you need help with this, let me know.

**Comment by recena** [comment]
Why is `wordpressAutoUpdateLevel` enabled by default? I don't know if this is the expected behavior.

**Comment by superaleks** [comment]
> Why is `wordpressAutoUpdateLevel` enabled by default? I don't know if this is the expected behavior.

It is not. We are not testing the default WordPress chart here. 
For context: When I joined the team, one of the first applications I had to test was WordPress so I played with modifying the default values and verifying the behaviour of the chart.
This was before we adapted the minimalist test strategy. 
This parameter stayed enabled in our testing pipeline. However, due to the peculiarities of the docker image settings, if we enable the autoUpdate parameter, there will be a lot of warning messages. So, we've thought it makes more sense to disable this parameter.
Also, in the context of the Helm chart there is no need to test autoUpdate, since if a pod goes down, the version will reinitiate to the original one.

**Comment by jotamartos** [comment]
Tests passed successfully in this fork: https://github.com/superaleks/charts/pull/48/checks. Thanks @superaleks

**Review by superaleks — DISMISSED** [review]
LGTM!

**Review by joancafom — DISMISSED** [review]

**Pull request merged**
