### PR TITLE
[bitnami/contour] Append the missing posfix of name for service/contour

### PR DESCRIPTION
**Pull request by izturn**
Signed-off-by: Gang Liu <gang.liu@daocloud.io>

### Description of the change
 let the naming style of **service/contour** like the other resources (eg: **service/envoy**) 

snapshot

### Applicable issues

  - fixes #

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your PR, in order to make the GH actions work and to be able to verify the changes, could you rebase from `master`? Thank you

**Comment by izturn** [comment]
done

**Comment by carrodher** [comment]
It seems a mess has been made in this PR, if you are not able to fix it, feel free to close this and create a new one

**Comment by izturn** [comment]
ok, thx, recreate as #11439

**Pull request closed without merging**
