### PR TITLE
[bitnami/common] Add possibility to pull images without giving registry name

### PR DESCRIPTION
**Pull request by EtienneBarbier**
**Description of the change**

Add possibility to pull images without giving registry name by removing `/` between registryName and repositoryName whan registryName is empty.

**Benefits**

If we set `image.registry: ""` in Values.yaml, we can now have field image in k8s manifest like this:
```
containers:
- image: repositoryName:tag
```
before it was necessary
```
containers:
- image: /repositoryName:tag
```

**Possible drawbacks**

None

**Applicable issues**

None

**Additional information**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Review by juan131 — COMMENTED** [review]
Hi @EtienneBarbier 

Thanks so much for your contribution! 

I can see what you mean but I'm curious about the use case. Why would you want to omit the registry? I mean, overwrite with an empty string `""`.

---

Please also rebase your branch from master and solve the conflicts when you have a chance.

**Comment by EtienneBarbier** [comment]
Hi @juan131 

I want to use the automatic resolution via the search-registries configuration.
Example: In docker when omit the registry, the image will be pull from docker.io registry.

**Comment by juan131** [comment]
I can see your point. You basically want to use whatever default registry your cluster uses.
@javsalgar what do you think about this?

**Comment by javsalgar** [comment]
I took a look and see no harm in this. LGTM

**Review by juan131 — APPROVED** [review]

**Pull request merged**
