### PR TITLE
[bitnami/common] new macro to merge a list of values with rendering 

### LINKED ISSUE #18888: [bitnami/redis] fail to render when commonLabels or podLabels is a string
### Name and Version

bitnami/redis 18.0.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

podLabels or commonLabels is a string (see below).

helm template -f str-pod-labels.yaml bitnami/redis

### Are you using any custom parameters or values?

``` 
master:
  podLabels: |
    toto: tutu
``` 

### What is the expected behavior?

before e3c23350ca2a96918c40265674cb53e58ff42183, commonLabels & podLabels could be strings containing go-template and would be rendered correctly.

After said commit, this is not working anymore because of various use of `merge` that only accepts dicts :
```
   {{- $podLabels := merge .Values.master.podLabels .Values.commonLabels }}
``` 

 

### What do you see instead?

fail

### Additional information

this impacts all charts upgraded to bitnami/common 2.9.0

### PR DESCRIPTION
**Pull request by jouve**
### Description of the change

new macro to merge a list of values with rendering 

### Benefits

support for fixing #18888

after this is integrated, all charts will be fixed by applying diffs like this one for labels  :
```diff
-{{- $podLabels := merge .Values.master.podLabels .Values.commonLabels }} 
+{{- $podLabels := include "common.tplvalues.merge" (dict "values" .Values.master.podLabels .Values.commonLabels "context" .) | fromYaml }} 
   selector:
     matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
```
 and annotations
```diff
-  {{- $annotations := merge .Values.master.service.annotations .Values.commonAnnotations }}
+  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.master.service.annotations .Values.commonAnnotations ) "context" . ) | fromYaml }}
```

the issues in charts can be found by searching :
* `$podLabels := merge`
* `$claimLabels := merge`
* `$labels := merge`
* `$annotations := merge`

### Applicable issues

- fixes #18888

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by jouve** [comment]
another use case is merging for annotations (commonAnnotations can be both str template or yaml):
```diff
-  {{- if or .Values.master.service.annotations .Values.commonAnnotations }}
-  {{- $annotations := merge .Values.master.service.annotations .Values.commonAnnotations }}
-  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
+  {{ with "common.tplvalues.merge" (dict "values" .Values.master.service.annotations .Values.commonAnnotations "context" . }}
+  annotations: {{- . | toYaml | nindent 4 }}
   {{- end }}

**Review by juan131 — CHANGES_REQUESTED** [review]
Thanks so much for this!

We need to find an approach compatible with the current charts so we don't need to do the replacements below on every single chart:

```diff
-{{- $podLabels := merge .Values.XXX.podLabels .Values.commonLabels }} 
+{{- $podLabels := list .Values.XXX.podLabels .Values.commonLabels }} 
```

That would require a very important effort.

Couldn't we keep the use of "merge" using "one-line" dict statements?

**Comment by juan131** [comment]
Hi @jouve 

I'm afraid it's not that simple as applying a regexp to substitute every reference. We need to create a PR per chart bumping the version and ensure the CI/CD works successfully for each of them.

Also, we need to merge the PRs in certain order since some charts are dependencies of others. The reason? As you can see on [this issue](https://github.com/helm/helm/issues/11561), when several charts have the same library chart as dependency but using different versions, the same template is declared twice with the same name but you can't tell which one will be loaded last and, therefore, used.

> For instance, given a chart like Magento (see its [Chart.lock](https://github.com/bitnami/charts/blob/main/bitnami/magento/Chart.lock)), we need to release MariaDB & ElasticSearch using the new `bitnami/common` library before releasing Magento. And, given that ElasticSearch [has Kibana as dependency](https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/Chart.lock), we need to release Kibana prior to that.

By the way, I was able to use `merge` with a `.Values.podLabels` that contained templates, see:

```console
$ helm template dokuwiki bitnami/dokuwiki -f values.yaml -s templates/deployment.yaml
---
# Source: dokuwiki/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dokuwiki
  namespace: "default"
  labels:
    app.kubernetes.io/instance: dokuwiki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dokuwiki
    helm.sh/chart: dokuwiki-14.2.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: dokuwiki
      app.kubernetes.io/name: prefix-dokuwiki
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dokuwiki
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: prefix-dokuwiki
        foo: bar
        helm.sh/chart: dokuwiki-14.2.0
    (...)
```

This is the `values.yaml` I used:

```yaml
podLabels:
  foo: "bar"
  app.kubernetes.io/name: "{{ join \"-\" (list \"prefix\" .Release.Name)  }}"
```

**Comment by jouve** [comment]
@juan131 I agree simple a relative terms :)

you are not reproducing my use case which would be for your example (note the whole podLabels is a string):
```yaml
podLabels: |
  foo: "bar"
  app.kubernetes.io/name: {{ join "-" (list "prefix" .Release.Name)  }}
```

example use case is a macro to include several labels:
```yaml
podLabels: |
  {{ include "my-company.labels". }}
```

**Comment by jouve** [comment]
as a alternative, we can keep only the new macro, then
```
{{- $podLabels := merge .Values.XXX.podLabels .Values.commonLabels }} 
```
become 
```
{{- $podLabels := include "common.tplvalues.merge" (dict "values" .Values.XXX.podLabels .Values.commonLabels "context" .) | fromYaml }} 
```

as it is strictly a new macro, it may be introduced to the various charts in any order.

**Comment by juan131** [comment]
That's a very good idea!! I'd rather go that way!! It's much easier to implement and we're positive we won't include backwards incompatibilities.

**Comment by jouve** [comment]
I updated the diff, PR description, and CHART_TEMPLATE.

**Review by juan131 — APPROVED** [review]
LGTM!! Thanks so much for updating the PR

**Comment by juan131** [comment]
@jouve let's sync about the changes on whole catalog to adopt the new standard. As you know, we need to apply [these changes](https://github.com/bitnami/charts/pull/18889#issuecomment-1702437259) on every chart, bump the version, ensure the CI/CD is successful, fix possible issues, etc. etc.

This is kinda tedious work, so I offer myself to do it. That said, let me know if you have any particular interest on doing so since this is your initiative and I don't want meddle in.

**Comment by jouve** [comment]
Thanks for the review !

As for offering doing the rest of the integration, I'd gladly agree :)

**Comment by juan131** [comment]
I'll keep you updated about my progress

**Pull request merged**
