### PR TITLE
[bitnami/chart] Support setting of Pgpool Load-Balancing mode

### PR DESCRIPTION
**Pull request by estliberitas**
**Description of the change**

This change brings ability to switch PgPool Load-Balancing mode on/off.

This change relies on the PR in Bitnami's PgPool docker image repo: https://github.com/bitnami/bitnami-docker-pgpool/pull/8.

**Benefits**

In scenarios, where we want to be in control of Load-Balancing mode without using our own `pgpool.conf` (tho it's not supported in this chart either afaik), since it's being nicely-generated by the PgPool Docker image.

**Possible drawbacks**

\-

**Applicable issues**

\-

**Additional information**

\-

**Checklist**
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by andresbono** [comment]
Thanks for the contribution, @estliberitas!! We will do some testing of the changes and we will get back to you.

Thanks again!

**Comment by estliberitas** [comment]
@andresbono sweet 👍

**Comment by estliberitas** [comment]
Any news? :)

**Comment by rafariossaa** [comment]
Sorry for the delay.

**Pull request merged**
