### PR TITLE
[bitnami/harbor] Escape a pipe that broke the markdown table

### PR DESCRIPTION
**Pull request by lindhe**
**Description of the change**

Escape a pipe that broke the markdown table.

**Benefits**

Markdown renders correctly.

**Possible drawbacks**

None.

**Applicable issues**

None, I think.

**Additional information**

I'd recommend using `markdownlint` to identify issues with your README files. :)

**Checklist**

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by lindhe** [comment]
Is bumping chart version required for README.md changes?

**Comment by lindhe** [comment]
I guess not. :)

**Comment by carrodher** [comment]
Not at all 😄

**Comment by lindhe** [comment]
Come to think about it, should I have changed it in [`values.yaml`](https://github.com/bitnami/charts/blob/dcc152147c6387e02ba5f40c2ee4711360b874cf/bitnami/harbor/values.yaml#L124) instead? It looks like the README may be generated from those `@param` decorators...

There's a similar situation with [`logLevel`](https://github.com/bitnami/charts/blob/dcc152147c6387e02ba5f40c2ee4711360b874cf/bitnami/harbor/values.yaml#L95)...

**Comment by carrodher** [comment]
Yes sorry, you're totally right, this is being autogenerated from the values.yaml using this tool: https://github.com/bitnami-labs/readme-generator-for-helm

**Comment by lindhe** [comment]
I'll give it a shot to fix it in a new PR!

**Pull request merged**
