### PR TITLE
[bitnami/clickhouse] feat: configure https port

### LINKED ISSUE #14023: Configure HTTPS port when `tls.enabled` is true.
### Name and Version

bitnami/clickhouse

### What is the problem this feature will solve?

Right now, when you enable TLS the HTTPS port in not configured.

There are three places that I think of that need to change:

- https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#http-porthttps-port
- The Service objects(internal and external)
-  The container ports

### What is the feature you are proposing to solve the problem?

HTTPS

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by ooraini**
Signed-off-by: Omar Aloraini <ooraini.dev@gmail.com>

### Applicable issues

  - fixes #14023

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by corico44** [comment]
Hello @ooraini, could you provide me how you have tested these changes to reproduce it, please?

**Comment by ooraini** [comment]
@corico44 Hi, in my own values.yaml file I already had `tls.enabled` set to true, but Clickhouse wasn't configured with an HTTPS port and it wasn't exposed in the Service. So, I wasn't able to connect using HTTPS.

To test the actual change, I'm using Datagrip, so I changed the port in the connection settings and enabled SSL, then I was able to connect successfully.

**Comment by corico44** [comment]
Hello @ooraini,
Sorry, I've been out of the office until today. I have tried modifying the value of tls.enabled to true and I get this error:
`Error: INSTALLATION FAILED: execution error at (clickhouse/templates/statefulset.yaml:94:27): Certificate Key filename is required when TLS in enabled`

**Comment by ooraini** [comment]
@corico44  Hi, that's really not a problem with the change. If you use the latest release(without this patch) and run:
```
helm template clickhouse bitnami/clickhouse --set tls.enabled=true
```

You will get the same error:
```
helm template clickhouse bitnami/clickhouse --set tls.enabled=true
```

**Review by corico44 — APPROVED** [review]
LGTM

**Pull request merged**
