### PR TITLE
[bitnami/nats] fix nats networkpolicy

### LINKED ISSUE #11749: nats networkpolicy chart issue
### Name and Version

bitnami/nats 2.8.6

### What steps will reproduce the bug?

service.ports.cluster is not added in the networkpolicy.yaml, but instead there are duplication of service.ports.client.
https://github.com/bitnami/charts/blob/master/bitnami/nats/templates/networkpolicy.yaml#L18-L27
This was creating issue for me when testing nats upgrade in my company's k8s environment. 

### Are you using any custom parameters or values?

No

### What is the expected behavior?

cluster port should be configurable here

### What do you see instead?

duplication of client port

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by RuiGuo34**
### Description of the change

Fix cluster port in nats networkpolicy resource

- Fixes #11749

### CODE REVIEW

**Comment by recena** [comment]
⚠️ _Detected changes in charts without version bump in Chart.yaml._

**Comment by carrodher** [comment]
Thanks for creating this PR. Please can you take a look at the failing action? You need to 

1. Bump the chart version in the _Chart.yaml_
2. Please, note it is needed to sign the commits. Your signature certifies that you wrote the patch or otherwise have the right to contribute the material. You can find more info about this topic, in [the “Sign your work” section from the contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

**Comment by RuiGuo34** [comment]
@carrodher thanks for the comments, I bumped chart version and signed off commit

**Comment by rafariossaa** [comment]
Hi,
  The DCO still complains, could you take a look to [this information](https://github.com/bitnami/charts/pull/11750/checks?check_run_id=7869855335) ? Most probably is that you missed to sign one of the commits.

**Comment by RuiGuo34** [comment]
recreated pr: https://github.com/bitnami/charts/pull/11845

**Comment by rafariossaa** [comment]
Hi,
  Thanks

**Pull request closed without merging**
