### PR TITLE
[bitnami/grafana-loki] Removed containers mount point for fixing GKE autopilot errors

### PR DESCRIPTION
**Pull request by Duplo-Yashwant**
### Description of the change

 grafana-loki is chart is getting failed on the gke autopilot when promtail is enabled, so just added the mount point based on the condition.

### Benefits

 This change will fix the gke autopilot issues with promtail configs in grafana-loki chart.

### Applicable issues

- fixes #

### Additional information

{"[denied by autogke-no-write-mode-hostpath]":["hostPath volume run in container promtail is accessed in write mode; disallowed in Autopilot.","hostPath volume containers used in container promtail uses path /var/lib/docker/containers which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/]."]}

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by Duplo-Yashwant** [comment]
Is there anything else needs to be done ?

**Review by Duplo-Yashwant — COMMENTED** [review]
Is below message is required in commit message?
Signed-off-by: Yashwant Bokadia <yashwant@duplocloud.net>

**Review by rafariossaa — APPROVED** [review]
LGTM

**Comment by Duplo-Yashwant** [comment]
my changes will not work directly, need to update the configuration to change the path also. As this PR is not 100% correct so closing the PR.

**Pull request closed without merging**
