### PR TITLE
[bitnami/argo-cd] fix: Add namespace to service account's bindings

### LINKED ISSUE #27884: [bitnami/argo-cd] Applicationset throws error when enabling clusterAdminAccess
### Name and Version

bitnami/argo-cd 6.5.8

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. In eks cluster 1.28
2. setting applicationSet.clusterAdminAccess: 'true'

### Are you using any custom parameters or values?
```
applicationSet:
      # Enable if you would like applicationSets to be used, default false
      enabled: true
      replicaCount: 2
      defaultArgs:
        enableLeaderElection: 'true'
      # Default is false
      clusterAdminAccess: 'true'
      serviceAccount:
        create: true
        name: argocd-applicationset-controller"
        automountServiceAccountToken: 'true'
```
### What is the expected behavior?

should create applicationSet with ClusterAdmin access

### What do you see instead?

Error: 1 error occurred:
│ 	* ClusterRoleBinding.rbac.authorization.k8s.io "argocd-applicationset-controller" is invalid: subjects[0].namespace: Required value

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fmulero**
### Description of the change

Add missing namespace to ServiceAccount subjects in Role and ClusterRole bindings.

### Benefits

Fix issues on ClusterRoleBindings because this resources is cluster wide and it needs the namespace to identify the ServiceAccount associated.
Keep our code aligned with our chart template.

### Possible drawbacks

None

### Applicable issues

- fixes #27884

### Additional information

Namespace is not mandatory in RoleBindings because this resource is namespace scoped, but I added the namespace to keep the same convention used in other charts.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by migruiz4 — DISMISSED** [review]
LGTM!

**Review by raghavanrrs — COMMENTED** [review]
LGTM

**Review by migruiz4 — APPROVED** [review]
Looks good to me! In this case, although the kubescape score has slightly decreased I don't think the content of the PR actually includes any bad practice.

**Comment by fmulero** [comment]
> Looks good to me! In this case, although the kubescape score has slightly decreased I don't think the content of the PR actually includes any bad practice.

Seems a problem in kubescape side. Now that we have added the namespace in the RoleBindings kubescape is blaming about the pemissions assigned to the ServiceAccounts. Likely kubescape were not resolving the relationship before this change.

**Pull request merged**
