### PR TITLE
[bitnami/contour] Support namespace-scoped leader election

### LINKED ISSUE #8975: Changes to Contour chart for new namespaced-Role (next Contour release)
### Name and Version

contour/next release

### What is the problem this feature will solve?

The next release of Contour will switch from using a ClusterRole to a namespace-scoped Role to configure RBAC for leader election resources (Leases and Events). This is a small security change to limit Contour's access footprint in a cluster.

As this change adds a new resource (a new Role) to Contour's base deployment configuration, some steps will need to be taken in the Contour chart to accommodate this.

See https://github.com/projectcontour/contour/pull/4204

### What is the feature you are proposing to solve the problem?

- Ensure the correct namespace is set on the new Role resource
- etc.

### What alternatives have you considered?

N/A

### PR DESCRIPTION
**Pull request by mmalecki**
**Description of the change**

This creates resources necessary for Contour to pick a leader via the
new mechanism planned for 1.21.1.

**Benefits**

Users will be able to use Contour's new leader election mechanism.

**Possible drawbacks**

**Applicable issues**

* Fixes #8975.

**Additional information**

**Checklist**

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by juan131** [comment]
Thank you for the PR @mmalecki ! Let's wait until the new version is released before proceeding with your changes

- https://github.com/projectcontour/contour/releases

**Comment by pablo-ruth** [comment]
@juan131 it seems that we already need RBAC for lease on Contour 1.20 -> https://github.com/bitnami/charts/issues/9047

**Comment by mmalecki** [comment]
Whew. This was also our experience, I thought we had an experimental feature turned on or something.

**Comment by juan131** [comment]
Hi @mmalecki 

You'll have to rebase your branch from master.

**Comment by mmalecki** [comment]
That did the trick (although I could swear I did that before :sweat_smile:), thanks @juan131.

**Review by juan131 — APPROVED** [review]
LGTM

**Pull request merged**
