### PR TITLE
[bitnami/airflow]  Fix LDAP configuration

### LINKED ISSUE #30619: Unquoted .Values.ldap.basedn in bitnami/airflow:22.2.0 causing fatal error during startup
### Name and Version

bitnami/airflow:22.2.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Deploy bitnami/airflow:22.2.0 chart.
2. Configure LDAP settings in values.yaml especially ldap.basedn.
3. Start the airflow-web container.

### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

Successful web container startup 

### What do you see instead?

```
/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/configuration.py:859 FutureWarning: section/key [core/sql_alchemy_conn] has been deprecated, you should use[database/sql_alchemy_conn] instead. Please update your `conf.get*` call to use the new name
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/gunicorn/__main__.py", line 10, in <module>
    run(prog="gunicorn")
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 66, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 235, in run
    super().run()
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
    ^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 57, in __init__
    self.setup(app)
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 117, in setup
    self.app.wsgi()
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/gunicorn/util.py", line 423, in import_app
    app = app(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/www/app.py", line 196, in cached_app
    app = create_app(config=config, testing=testing)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/airflow/www/app.py", line 85, in create_app
    flask_app.config.from_pyfile(webserver_config, silent=True)
  File "/opt/bitnami/airflow/venv/lib/python3.12/site-packages/flask/config.py", line 185, in from_pyfile
    exec(compile(config_file.read(), filename, "exec"), d.__dict__)
  File "/opt/bitnami/airflow/webserver_config.py", line 10, in <module>
    AUTH_LDAP_SEARCH = DC=saf,DC=lan
                                 ^^^
NameError: name 'lan' is not defined. Did you mean: 'len'?
```

### Additional information

Suggested Fix:
In the [bitnami/airflow/templates/web/configmap.yaml](https://github.com/bitnami/charts/blob/main/bitnami/airflow/templates/web/configmap.yaml) file, quote the .Values.ldap.basedn as follows:
```
[..]
AUTH_TYPE = AUTH_LDAP
AUTH_LDAP_SERVER = {{ .Values.ldap.uri | squote }}
AUTH_LDAP_SEARCH = {{ .Values.ldap.basedn | squote }}
AUTH_LDAP_UID_FIELD = {{ .Values.ldap.searchAttribute | squote }}
AUTH_LDAP_BIND_USER = {{ .Values.ldap.binddn | squote }}
[..]
````

### PR DESCRIPTION
**Pull request by JoeriHermans**
### Description of the change

This small change contains a fix to the Airflow LDAP configuration in the Helm chart. In particular, it fixes https://github.com/bitnami/charts/issues/30619 . 

### Benefits

LDAP functionality in the Airflow chart is functional again.

### Possible drawbacks

Not applicable.

### Applicable issues

- fixes #30619 

### Additional information

The chart has been tested with LDAP on my lab environment.

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by JoeriHermans** [comment]
@carrodher The fix has been implemented.

**Comment by carrodher** [comment]
Thanks for your contribution! Please note you need to invite @bitnami-bot as collaborator in your fork so the automation can add a commit in your branch updating the CRDs, README and CHANGELOG

**Comment by JoeriHermans** [comment]
@carrodher My organisation does not allow PATs, causing the error. I temporarily disabled them. Would it be possible to retrigger the pipeline? 

```
remote: Personal access tokens (classic) are forbidden from accessing this repository.
```

**Comment by carrodher** [comment]
Thanks! The bot was able to write, see https://github.com/bitnami/charts/pull/30911/commits/e825010911082dad8b487f9f517df70058ba157a.

Now it's time for the team to review the PR!

**Review by carrodher — APPROVED** [review]

**Pull request merged**
