### PR TITLE
[bitnami/cassandra] set sizeLimit only for certs-shared emptyDir

### PR DESCRIPTION
**Pull request by jmederer**
### Description of the change

In our Production Environment we had to limit every emptyDir Volume. And the certs-shared emptyDir is the only one without sizeLimit. In this PR i hardcoded the Limit to 1Gi I think this should be enough for two certificate files ;-) 

### Applicable issues

- fixes #

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by corico44** [comment]
Hello @jmederer,

Thank you for opening this PR. Did the value given to emptyDir come from a consulted source or how did you set that value?

**Comment by jmederer** [comment]
Hi @corico44 

Did you mean the value sizeLimit? This is documented by https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

Or did you mean the 1Gi? The 1Gi is a random value from my side. I don't think that so mach space will be ever used by certificates and this value with 1Gi should never cause problems. 

Do you have any concerns with this change?

**Comment by corico44** [comment]
Hi @jmederer,

In the [example provided in the documentation](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir-configuration-example) they use the value **500Mi**. I think that as a default value it would be advisable to use the one indicated in the documentation.

**Review by corico44 — APPROVED** [review]
LGTM

**Pull request merged**
