### PR TITLE
[bitnami/postgresql] Do not create a NetworkPolicy for "read" instance  when "standalone"

### PR DESCRIPTION
**Pull request by titou10titou10**
In "standalone" mode, no component is created for "read" instances except an extra "NetworkPolicy" object 
This PR disables the creation of the NetworkPolicy for the "read" instances in "standalone" mode, ie without "read" instances

### Applicable issues

- fixes #

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by Mauraza** [comment]
Hi @titou10titou10, 

This PR https://github.com/bitnami/charts/pull/23328 just merged. Could you check if that resolves the issue?

**Comment by titou10titou10** [comment]
> It doesn't -- #23328 missed this part of the fix. This NetworkPolicy is still being deployed when replication is disabled.

Yes I can confirm it does not the problem

**Comment by Mauraza** [comment]
Hi @titou10titou10,

Could you resolve the conflicts?

**Review by Mauraza — APPROVED** [review]
LGTM!

**Pull request merged**
