### PR TITLE
[bitnami/janusgraph] Fix storage password secretName helper function

### LINKED ISSUE #26354: [bitnami/janusgraph] Helm Pod start in failure caused by secret not found
### Name and Version

bitnami/janusgraph 0.3.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. in Minikube 1.33.1 with Kubernetes 1.30.0 kubectl on MacOs Monterey version 12.7.5
2. After added Bitnami helm repository
3. from command line, execute command "helm instal knr-system oci://registry-1.docker.io/bitnamicharts/janusgraph" as written in project documentation for installation ont the Minikube cluster already started and in stable status
4. I see that: knr-system-cassandra-0 Pod is started and running with success
5. but the knr-system-janusgraph-xxxxxxxx Pod stay in "CreateContainerConfig" status with a logs that say ".... is waiting to start: PodInitializing"
6. on the janusgraph Pod in failure, I see a permanent event that give failure cause equals to "knr-system-janusgraph-cassandra" not found message
7. another type of event that appear for "Pulled" message cause regarding the Sub-object "spec.initContainers(wait-for-storage)" is shown confirming that "Container image "docker.io/bitnami/janusgraph:1.0.0-debian-12-r4" already present on machine"
8. the system stay permanently in this unstable status without deployment object (named knr-system-janusgraph) in success
9. and the replicat sets "knr-system-janusgraph-xxxx" blocke on status equals to "Init:CreateContainerConfig" regarding not found secret "knr-system-janusgraph-cassandra"

### Are you using any custom parameters or values?

Yes only a defined nodeSelector defined into the Cassandra and Janusgraph values.yaml files (I downloaded the origin Helm project source codes for try a Helm full installation since original code... but without success start of Pods because have the same error)

### What is the expected behavior?

Start with success of each PODS (janusgraph, cassandra) and finalized deployment with success into a Minikube cluster ready for use

### What do you see instead?

- In janusgraph Pod console, event is show regarding cause of failure equals to:
Error: secret "knr-system-janusgraph-cassandra" not found
- In Minikube Secret object, I see that a secret named "knr-system-cassandra" is existing, but that have not the same name of the Pod failure cause which talk about "knr-system-janusgraph-cassandra"

### Additional information

Perhaps that the different name of searched secret attempted to be read ("knr-system-cassandra") by the Janusgraph Pod in place of the "knr-system-janusgraph-cassandra" defined in the secrets is a problem.
I am blocked since 2 days on this problem to have a success deployed Helm project but I am not find the root cause.
Thanks for your help. Regards

### PR DESCRIPTION
**Pull request by andresbono**
### Description of the change

This PR fixes an issue resolving the storage password secretName when the release name is not "janusgraph".

### Applicable issues

- fixes #26354

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] n/a ~Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)~
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by olivierlemee** [comment]
Hi, thanks for your action and I will try the new version Wednesday to give you my feedback. Regards

**Comment by olivierlemee** [comment]
Hi,
I did try to install the 0.3.7 version on my minikube and it was a failure.

Find here the test scenario:

### TEST 1: install on nodes with nameoverrided

#### WHAT I EXECUTED
- values-simple.yaml file used mainly for assigning of pods on a same Node of my empty cluster:
```
nodeSelector:
  cybnity.io/domains-area: "true"

cassandra:
  nameOverride: "knr-system-cassandra"
  nodeSelector:
    cybnity.io/domains-area: "true"
  ## Init containers parameters:
  ## volumePermissions: Change the owner and group of the persistent volume mountpoint to runAsUser:fsGroup values from the securityContext section.
  ##
  volumePermissions:
    enabled: true

nameOverride: "knr-system"
```

- Helm command line for install executed:
```helm install my-release oci://registry-1.docker.io/bitnamicharts/janusgraph --values ./janusgraph/values-simple.yaml --version 0.3.7```

#### WHAT BEHAVIOR I SAW
- STEP 1: execute the helm install command from command line
- STEP 2: Cassandra pod started with success

#### WHAT FINAL STATE IS REACHED
Situation: permanent **BLOCKED** state for cause **containers with incomplete status: [wait-for-storage]**

- Janusgraph pod started but blocked in a 'not initialized status' (pod logs: container "janusgraph" in pod "my-release-knr-system-5645fd54fb-tdhrm" is waiting to start: PodInitializing)

janusgraph-pod-conditions-state-blocked

janusgraph-helm-0 3 7-end-status

### TEST 2 : without pods name redefinition

#### WHAT I EXECUTED
- values-simple.yaml file is simplified only for:
```
nodeSelector:
  cybnity.io/domains-area: "true"

cassandra:
  nodeSelector:
    cybnity.io/domains-area: "true"

```
- same command line is executed

#### WHAT BEHAVIOR I SAW
- Cassandra pod is started with success and is named by default
- Janusgraph pod is in permanent **BLOCKED** situation for cause of "Error: secret "my-release-janusgraph-cassandra" not found"

test2-pods-final-status-in-error

### REVIEW RESULT
This version 0.3.7 does not correct the problem.
When the default pod's names values are executed without redefinition by values.yaml, the error for secret access resource is always a blocking cause between the 2 pods.
When the pod names are redefined, this is solve the secret resource access between pods, BUT the initialization of the Janusgraph pod is not finalized with success and stay in failure for cause of wait-for-storage status during its initialization process

**Comment by olivierlemee** [comment]
When I try to search in resources started by the helmified project, I see that the ConfigMap instance created for the Janusgraph pod (and generated by the helm project) is:

```
{
	"janusgraph.properties": "storage.backend=cql
		storage.hostname=my-release-cassandra
		storage.port=9043
		cache.db-cache=true"
}
```

but the statefull state that have been by default created is named [my-release-knr-system-cassandra]

So is it normal value created into the janusgraph properties because I think that could be an issue during the Janusgraph pod initialization which does not find the storage.hostname using a unexisting real name deployed in the cluster.

A potential way of issue resolution regarding the pod blocked status for cause of "waiting-for-storage" ?

**Review by migruiz4 — APPROVED** [review]

**Comment by olivierlemee** [comment]
@andresbono Hello, I am sorry but I just try to execute the new version 0.3.8 and I see that failure this time is also on cassandra pods. So the situation is worse than before because the cassandra pods is not not starting with success for cause of "CrashLoopBackOff
Message
back-off 1m20s restarting failed container=cassandra pod=my-release-knr-system-cassandra-0_default(cdd4f1e2-7bcb-43e9-a742-eb6eb7d4c8cb)"
So the ticket have been closed, but the issue is always existing

**Comment by andresbono** [comment]
Hi @olivierlemee, please, it will be better if we keep the conversation in the associated issue: #26354 where I see you already described the new situation.

It is true that this PR is not fully resolving #26354 by itself. The issue has been reopened for that reason.

Thank you!

**Pull request merged**
