### PR TITLE
[bitnami/postgresql-ha] Mitigate brain split situations

### PR DESCRIPTION
**Pull request by rafariossaa**
Signed-off-by: Rafael Rios Saavedra <rafael.rios.saavedra@gmail.com>

**Description of the change**

- Change default settings for Reconnect. This will make to fail sooner in the case of primary lost
- Fix the preStop logic. It was not detecting the case of being the primary node hence it was not waiting for a new primary to be promoted before stopping. 

**Benefits**

This should make much harder to get into a brain split situation. 
In any case, the best way to reduce the risk is to have more nodes that can decide on which is the new primary node. Three nodes is the very minimum for a cluster, so if you get the node failing continuously (eg. chaos testing) there are chances that in a moment in time there is not primary to join to.

**Possible drawbacks**

**Applicable issues**

This should help with: 
- #6555
- #5589 
- #7464 
- #7163
- #2610

**Additional information**

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [-] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by miguelaeh — COMMENTED** [review]
Thank you @rafariossaa !!!

Strictly talking, changing the default parameters would be a major bump of the chart version, since updating could unexpectedly change the default behavior of already installed releases.

Checking the changes, it seems these shouldn't cause any kind of unexpected behavior but just to confirm with you, is there any scenario where these changes could affect someone that deployed the chart with some custom configuration?

**Comment by vishrantgupta** [comment]
Hi @rafariossaa thanks for the PR.

> This should make much harder to get into a brain split situation.

Which scenarios are not being covered by this PR which will still lead to the split-brain issue?

> In any case, the best way to reduce the risk is to have more nodes that can decide on which is the new primary node. > Three nodes is the very minimum for a cluster, so if you get the node failing continuously (eg. chaos testing) there are chances that in a moment in time there is not primary to join to.

Even with the 3 node postgres cluster the split-brain issue is reproducible.

The preStop hook will not be called when the kubernetes node suddenly dies or when the postgres pod is killed and it was leading to split-brain issue.

**Comment by rafariossaa** [comment]
> @rafariossaa your fork is behind bitnami:master and the GH Action is failing
> 
> image

Thanks. 
I have rebased my branch.

**Comment by rafariossaa** [comment]
> Checking the changes, it seems these shouldn't cause any kind of unexpected behavior but just to confirm with you, is there any scenario where these changes could affect someone that deployed the chart with some custom configuration?

There is no one that came to my mind. But, of course, I can not guarantee 100% that for any user with any custom configuration.

**Comment by vishrantgupta** [comment]
> not able to reproduce it in a consistent way. 3 nodes are the base minimum

This might be true that the issue is not reproducible in a consistent way, but it does occur and this adds a possibility of data loss. Have you tried the steps that you performed with the 3 node cluster?

> Sure, for this the decrease in the other setting should help.

Which "other setting" you are referring to?

**Review by miguelaeh — COMMENTED** [review]
>There is no one that comes to my mind, but I can not guarantee 100% that for any user with any custom configuration. There is a myriad of combinations of parameters and scenarios.

Then, should we consider bumping the major?

**Comment by rafariossaa** [comment]
@vishrantgupta 
> This might be true that the issue is not reproducible in a consistent way, but it does occur and this adds a possibility of data loss. Have you tried the steps that you performed with the 3 node cluster?

I not telling that this not might occur. I am asking for a way to reproduce the issue in my side so I can try to look for a better solution. Also, any proposals are welcome.
The minimum size I tried is the one that the chart deploys by default, 3 nodes in this case. I was not able to reproduce it with this PR, 
You need to check you production scenario and how resilient you need to be to add nodes accordingly.
Have into account that postgresql, repmgr and pgpool are not designed for a k8s scenario, so what we have here is a translation of what is done in a scenario with VMs or baremetal servers. 



> 
> > Sure, for this the decrease in the other setting should help.
> 
> Which "other setting" you are referring to?

**Comment by javsalgar** [comment]
I don't believe that two changes in the values.yaml should be considered a major. I expect that production workloads would not rely on default values but in configured and managed values. If there is no a value structure change I don't believe it deserves a major bump.

**Review by miguelaeh — APPROVED** [review]
LGTM!

**Comment by vishrantgupta** [comment]
> Have into account that postgresql, repmgr and pgpool are not designed for a k8s scenario, so what we have here is a translation of what is done in a scenario with VMs or baremetal servers.

Could you please include this in the Postgresql chart readme?

**Comment by juan131** [comment]
Hi @vishrantgupta 

Thank you for your feedback! Please free to contribute with a PR improving the README.md or the [Bitnami documentation](https://docs.bitnami.com/kubernetes/infrastructure/postgresql-ha) which is based on the repository below:

- https://github.com/bitnami/charts-docs/tree/main/charts/postgresql-ha

**Pull request merged**
