### PR TITLE
[bitnami/mysql] Fix: remove added pass

### PR DESCRIPTION
**Pull request by bergemalm**
**Description of the change**

Fix to recently merged PR. Don't introduce another secret.

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by bergemalm** [comment]
@javsalgar :)

**Comment by bergemalm** [comment]
Rebased/refactored, remove the unnecessary added fourth secret.

**Review by andresbono — APPROVED** [review]
LGTM

**Comment by bergemalm** [comment]
This is still not available in chart repo?

**Comment by marcosbc** [comment]
Like with #4600, the same thing happened causing our CI tests to fail. I've just pushed a fix (88da3be9898a6e06929bde34e8b812fdd9080475) for the tests to pass and the release to happen.

**Pull request merged**
