### PR TITLE
[bitnami/nginx-ingress-controller] Add fullnameOverride for default backend

### PR DESCRIPTION
**Pull request by T1loc**
Enable fullnameOverride for the default-backend

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the contribution, before continue, you should increment the chart version in the `Chart.yml` according to [semver](http://semver.org/):

> Given a version number `MAJOR.MINOR.PATCH`, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by T1loc** [comment]
Thanks for your answer, 
So if I understand properly the new chart version should be 5.1.0, right ?
I will edit the name of the MR also, it's about the fullnameOverride and not the nameoverride

**Comment by carrodher** [comment]
Yes, a minor version bump works fine in this case. Thanks

**Pull request merged**
