### PR TITLE
[bitnami/argo-cd] Missing namespace in ArgoCD known-hosts cm

### PR DESCRIPTION
**Pull request by banshee86vr**
### Description of the change

Inside the ArgoCD helm chart, the field `namespace` is missing from the configmap `argocd-ssh-known-hosts-cm`.

### Benefits

The installation of that configmap will follow the same installation process of the other resources provided by the ArgoCD Helm chart. 

The location of that resource will be the same as the others.

### Possible drawbacks

Nothing to notice.

### Applicable issues

I haven't found any issue with it

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by dgomezleon — DISMISSED** [review]
LGTM. Thanks for contributing.

**Review by dgomezleon — DISMISSED** [review]

**Comment by banshee86vr** [comment]
@dgomezleon, it seems some conflicts need to be resolved. Could you check it? Can I help you in any way?

**Comment by dgomezleon** [comment]
Hi @banshee86vr ,

I marked the auto-merge option, but some other versions were released before that. I am fixing the conflicts now.

**Review by dgomezleon — APPROVED** [review]

**Comment by banshee86vr** [comment]
@dgomezleon Thanks for your support!

**Pull request merged**
