### PR TITLE
[bitnami/elasticsearch] Implemented custom annotations for all Elasticsearch statefulsets

### PR DESCRIPTION
**Pull request by Laurianti**
> ### Description of the change
> Implemented custom annotations for all Elasticsearch statefulsets.
> 
> ### Benefits
> Possibility to add some custom annotations for each statefulsets.
> 
> ### Possible drawbacks
> N/A.
> 
> ### Applicable issues
> N/A
> 
> * [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is _not necessary_ when the changes only affect README.md files.
> * [x]  Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
> * [x]  Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
> * [x]  All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by javsalgar — APPROVED** [review]
The changes LGTM. We need to see how to fix the trivy issue. Let me check if there is a new image being released.

**Comment by javsalgar** [comment]
It seems there are CVEs in some system packages. I'm forcing another container release to see if it gets fixed.

**Comment by javsalgar** [comment]
Hi!

There is a new image available that should fix the trivy issue. Could you fix the merge issue?

**Comment by Laurianti** [comment]
@javsalgar The merge was done, thank you.

**Review by FraPazGal — APPROVED** [review]
LGTM, thanks for the contribution @Laurianti!

**Pull request merged**
