### PR TITLE
[bitnami/rabbitmq] Fix high CPU usage while idle

### LINKED ISSUE #11116: [bitnami/rabbitmq] RabbitMQ high CPU usage while idle
### Name and Version

bitnami/rabbitmq 10.1.11

### What steps will reproduce the bug?

Just run it and watch the CPU usage.

### Are you using any custom parameters or values?

_No response_

### What is the expected behavior?

_No response_

### What do you see instead?

High CPU usage while idle

### Additional information

The liveness and readiness probe execute a separate erlang process, which is very expensive.

This was reported (and fixed) in https://github.com/helm/charts/issues/3855 but not to bitnami.

### PR DESCRIPTION
**Pull request by orgads**
### Description of the change

Use REST APIs for liveness/readiness probes, instead of spawning expensive erlang processes.

### Benefits

CPU usage will drop.

### Possible drawbacks

Not that I'm aware of.

### Applicable issues

- fixes #11116
- Reapply of #11117 and #11180.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by jotamartos** [comment]
Hi @orgads,

Thank you for taking the time to create this PR. When working on getting more details about the issue, I found out this conversation about the same topic in the RabbitMQ's official GitHub repository 

https://github.com/rabbitmq/discussions/issues/151

As you can see there, they mentioned that this is expected, and taking into account that you mention that your changes wouldn't work in all situations, I will not approve it. However, as mentioned there, there are some actions you can perform and they are documented in the RabbitMQ's official documentation 

https://www.rabbitmq.com/runtime.html#cpu-reduce-idle-usage

You can set the RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS env var by setting the extraEnvVars parameter in the values file 

```
  extraEnvVars:
    - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
      value: "YOUR_VALUE_HERE"
```

I hope this helps reduce the CPU utilization. 

Thanks

**Review by jotamartos — APPROVED** [review]

**Comment by nc-mcarter** [comment]
A potential issue with the fix that has been merged appears to be that the liveness and readiness probes will now always fail in a deployment where `loadDefinition.enabled` is false and `rabbitmq_management` plugin is disabled.

I have an application deployment where `loadDefinition.enabled` remains at the default value of `false` and we explicitly install the bitnami RabbitMQ Helm chart without the management interface as it is not needed for our application to function. Is this no longer a supported install?

**Comment by orgads** [comment]
> A potential issue with the fix that has been merged appears to be that the liveness and readiness probes will now always fail in a deployment where `loadDefinition.enabled` is false and `rabbitmq_management` plugin is disabled.
> 
> I have an application deployment where `loadDefinition.enabled` remains at the default value of `false` and we explicitly install the bitnami RabbitMQ Helm chart without the management interface as it is not needed for our application to function. Is this no longer a supported install?

Thanks for reporting. Can you check if #16567 solves the issue for you?

**Comment by nc-mcarter** [comment]
> > A potential issue with the fix that has been merged appears to be that the liveness and readiness probes will now always fail in a deployment where `loadDefinition.enabled` is false and `rabbitmq_management` plugin is disabled.
> > I have an application deployment where `loadDefinition.enabled` remains at the default value of `false` and we explicitly install the bitnami RabbitMQ Helm chart without the management interface as it is not needed for our application to function. Is this no longer a supported install?
> 
> Thanks for reporting. Can you check if #16567 solves the issue for you?

I have tested the RabbitMQ chart from the link in my scenario and can confirm that it solves the issue for me. Thank you for the incredibly speedy response and resolution!

**Comment by Jojoooo1** [comment]
Not sure it is related, but i had to downgrade from 11.15.1 to 11.14.3 because I had idle CPU peak usage.

**Pull request merged**
