### PR TITLE
[bitnami/argo-cd] Persistent autogenerated admin password on upgrade

### LINKED ISSUE #10974: [bitnami/argo-cd] Admin password changed unexpectly after each upgrade.
### Name and Version

bitnami/argo-cd 3.3.5

### What steps will reproduce the bug?

```bash
$ helm install -n argocd argo-cd bitnami/argo-cd 
Error: INSTALLATION FAILED: create: failed to create: namespaces "argocd" not found
$ helm install -n argocd --create-namespace argo-cd bitnami/argo-cd 
NAME: argo-cd
LAST DEPLOYED: Thu Jun 30 18:37:12 2022
NAMESPACE: argocd
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: argo-cd
CHART VERSION: 3.4.2
APP VERSION: 2.4.2

** Please be patient while the chart is being deployed **

1. Access your Argo CD installation:
  Execute the following commands:

  kubectl port-forward --namespace argocd svc/argo-cd-server 8080:80 &
  export URL=http://127.0.0.1:8080/
  echo "Argo CD URL: http://127.0.0.1:8080/"

2. Execute the following commands to obtain the Argo CD credentials:

  echo "Username: \"admin\""
  echo "Password: $(kubectl -n argocd get secret argocd-secret -o jsonpath="{.data.clearPassword}" | base64 -d)"
$ echo "Password: $(kubectl -n argocd get secret argocd-secret -o jsonpath="{.data.clearPassword}" | base64 -d)"
Password: MvRrGx13MR
$ helm -n argocd upgrade argo-cd                                                                                 
Error: "helm upgrade" requires 2 arguments

Usage:  helm upgrade [RELEASE] [CHART] [flags]
$ helm -n argocd upgrade argo-cd bitnami/argo-cd 
Release "argo-cd" has been upgraded. Happy Helming!
NAME: argo-cd
LAST DEPLOYED: Thu Jun 30 18:37:47 2022
NAMESPACE: argocd
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
CHART NAME: argo-cd
CHART VERSION: 3.4.2
APP VERSION: 2.4.2

** Please be patient while the chart is being deployed **

1. Access your Argo CD installation:
  Execute the following commands:

  kubectl port-forward --namespace argocd svc/argo-cd-server 8080:80 &
  export URL=http://127.0.0.1:8080/
  echo "Argo CD URL: http://127.0.0.1:8080/"

2. Execute the following commands to obtain the Argo CD credentials:

  echo "Username: \"admin\""
  echo "Password: $(kubectl -n argocd get secret argocd-secret -o jsonpath="{.data.clearPassword}" | base64 -d)"
$ echo "Password: $(kubectl -n argocd get secret argocd-secret -o jsonpath="{.data.clearPassword}" | base64 -d)"
Password: xqMnqhvLUN
$ # The admin password changes after each upgrade, which expected consistence like postgres ot ther db.
```

### Are you using any custom parameters or values?

None

### What is the expected behavior?

The admin password is changed after every upgrade, this should be consistent like postgres or other databases.

It's confusing when I'm referencing the password secret in other services. 

### What do you see instead?

It changed！！！

### Additional information

The `$password=...` excuted each time on render even password set. A pre-check `lookup` may be required
https://github.com/bitnami/charts/blob/65387009cf266b900b52898c1457d1625d2434f8/bitnami/argo-cd/templates/argocd-secret.yaml#L46-L49

 I can help improve this if needed.

### PR DESCRIPTION
**Pull request by cnfatal**
### Description of the change

do not change autogenerated admin password during upgrade.

### Applicable issues

  - fixes #10974 

### Checklist
 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by alemorcuq — CHANGES_REQUESTED** [review]
Thanks! This is a very nice feature to have! We are already including this in some of our charts, could you please use the same format?

We are using [a helper defined in the common chart](https://github.com/bitnami/charts/blob/2a00e6c8361531eff6992bbaf489087bee78a6b3/bitnami/common/templates/_secrets.tpl#L61). You can see an example in the [postgresql chart](https://github.com/bitnami/charts/blob/2a00e6c8361531eff6992bbaf489087bee78a6b3/bitnami/postgresql/templates/secrets.yaml#L17).

**Comment by cnfatal** [comment]
I had tried it:
```yaml
  {{- $encodeAndQuotedPassword := (include "common.secrets.passwords.manage" (dict "secret" "argocd-secret" "key" "clearPassword" "providedValues" (list "config.secret.argocdServerAdminPassword" ) "context" $)) }}
  #  b64enc: {{ $encodeAndQuotedPassword }}
  #  decode: {{ $encodeAndQuotedPassword | b64dec }}
  {{- $password := (trimAll "\"" $encodeAndQuotedPassword) | b64dec }}
  #   plain: {{ $password }}
  # The password needs to be bcrypt hashed
  admin.password: {{ (split ":" (htpasswd "" $password))._1 | b64enc }}
```

after render:

```yaml
  #  b64enc: "RFE4aDdkRXlPTQ=="
  #  decode: illegal base64 data at input byte 0
  #   plain: DQ8h7dEyOM
  # The password needs to be bcrypt hashed
  admin.password: JDJhJDEwJDR3N0xpNzExVENIbm9uNnQuU2Y1b2U2SjI1bktwVlBBbW4yQTFKRFFXazBvc2pVOUszVEpx
```

`admin.password` field need a plain password,the helper "common.secrets.passwords.manage" returned a `|b64enc | quote` password.  

To get a plain password  i must use `{{- $password := (trimAll "\"" $encodeAndQuotedPassword) | b64dec }}` ，it's not very elegant.  so i choosed my "directly" .

Let me know if i should keep using "common.secrets.passwords.manage"

**Comment by alemorcuq** [comment]
Thank you! Nice analysis. Unfortunately, we have to quote the base64 string for those cases in which the encoded string could be interpreted by Helm as a number. See #9804 for the full discussion on this.

However, I think we should use the `common.secrets.passwords.manage` helper to keep things as standard as possible. Your `trimAll` proposal looks good to me.

**Review by alemorcuq — APPROVED** [review]
Great! Thank you!

**Pull request merged**
