### PR TITLE
[bitnami/sealed-secrets] add port name to sealed secrets service

### PR DESCRIPTION
**Pull request by mateuszdrab**
Signed-off-by: Mateusz Drab <mateuszd@outlook.com>

### Description of the change

Add port name in service ports spec.
Resolves an issue with servicemonitor not working due to a reference to the port name which was missing in the service:
```yaml
spec:                                                                                                                            
  endpoints:
   - port: {{ .Values.service.ports.name }}
```

### Benefits

Fixes servicemonitor

### Possible drawbacks

N/A

### Applicable issues

N/A

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by mateuszdrab** [comment]
I reworded the description as it made no sense, I have no idea how it went through my proof reading... 😂

**Review by Mauraza — COMMENTED** [review]
If you check that is used in the `targetPort` so is no need to add the name.

**Comment by mateuszdrab** [comment]
Hi @Mauraza 

If you check the service monitor.yaml file you'll notice it refers to a port by name, a name which is not assigned to any port in the service.yaml file.

**Comment by mateuszdrab** [comment]
> Hi @mateuszdrab,
> 
> Do you mean these lines ⬇️?
> 
> https://github.com/bitnami/charts/blob/5656d04fa3827fe049ed673b3a7293ed9dac3ded/bitnami/sealed-secrets/templates/servicemonitor.yaml#L32-L33
> 
> In this case, is using the same value (by default 'http'). You can check it by running `helm template bitnami/sealed-secrets`
> 
> If there is any error you could indicate it to take a look at it.

That's correct, it's referring to the port by name. 
Now, once you take a look at the service, you will find the port does not have a name assigned, so prometheus does not discover the target.

**Comment by Mauraza** [comment]
Hi @mateuszdrab,

I have updated the tests according to your change if all goes well we will merge them.

**Review by Mauraza — APPROVED** [review]
LGTM!

**Pull request merged**
