### PR TITLE
[bitnami/airflow]:  Issue with LDAP variables

### PR DESCRIPTION
**Pull request by HorusTheSonOfOsiris**
### Description of the change

This change includes changes to default values of following LDAP variables:

1. AIRFLOW_LDAP_USER_REGISTRATION
2. AIRFLOW_LDAP_ROLES_SYNC_AT_LOGIN
3. AIRFLOW_LDAP_USE_TLS

Due to recent changes in the airflow container, the values are checked for yes or no instead of True or False. An [issue](https://github.com/bitnami/containers/issues/74359) was raised by me to report the problem. 

### Benefits

This will enable users to use LDAP properly with the new values.

### Possible drawbacks

None as due to this issue people were no able to use LDAP.

### Applicable issues

- fixes https://github.com/bitnami/containers/issues/74359

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by juan131 — CHANGES_REQUESTED** [review]
Thanks for the fix @HorusTheSonOfOsiris ! This change won't be any longer required after https://github.com/bitnami/charts/pull/30349

As you can see in that PR, related changes to LDAP will be managed at `bitnami/airflow/templates/web/configmap.yaml` and we don't need to rely no longer on container setup logic.

**Comment by HorusTheSonOfOsiris** [comment]
Hey @juan131, I don’t think this fix will work anyway. This morning I checked the containers/airflow logic, as well. I think it is improperly configured to check some LDAP variables as yes or no. They are supposed to be True or False from Airflow webserver config’s perspective. I think that needs some fixing too.

**Comment by juan131** [comment]
You're right! However, changes on the PR I shared do actually fix it so let's wait for it to be reviewed/merged.

**Comment by HorusTheSonOfOsiris** [comment]
Thanks! Hoping it will be merged soon.

**Comment by juan131** [comment]
@HorusTheSonOfOsiris the new chart version `21.6.0` is now available

**Pull request closed without merging**
