### PR TITLE
[bitnami/harbor] - Fix docs

### PR DESCRIPTION
**Pull request by schnatterer**
**Description of the change**

The docs mentioned a `updateStrategy.type` whereas in the deployments a `strategy` value is read. 
In addition `posgresql` was mentioned instead of `postgresql`.

**Benefits**

Truthful docs

**Possible drawbacks**

-

**Applicable issues**
-

**Additional information**

-

**Checklist** 
- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
  This only changes the docs, so is this worth a new release? I'd say no.
- [x ] Variables are documented in the README.md
- [x ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by schnatterer** [comment]
Done. Didn't think change in docs would justify a new version :-)

**Comment by schnatterer** [comment]
It so happened that I found another typo regarding postgres. I took the liberty of adding it to this PR.

**Comment by miguelaeh** [comment]
Hi @schnatterer ,
Could you rebase master and solve the conflicts?

**Comment by schnatterer** [comment]
Hi @miguelaeh, Done.

**Pull request merged**
