### PR TITLE
[bitnami/kube-prometheus] Standardize Ingress in Chart

### LINKED ISSUE #8779: Issue in Kube Prometheus Chart with TLS config for ingress
**Which chart**:

kube-prometheus

**Describe the bug**

There are 3 ingress objects that can be created via the helm chart:
1. prometheus
2. thanos
3. alert manager
  
The Helm chart has a different mechanism for configuring the tls for these ingress resources which makes the usage horrible!  
For Thanos it is done correctly by enabling the user to use cert manager via annotations or to add a tls section of yaml pointing to an existing secret.  
For prometheus and Alert Manager you cant point it at an existing secret making the use of a wildcard cert nearly impossible (would require copying the same cert details into the values.yaml multiple times which is not a good idea as multiple secrets will be created with the same cert and when the cert expires updating it will be horrific as it will exist in too many places.).
  
The chart needs to be standardized as currently i need to:
1. create a secret in advance for thanos
2. Get my TLS Key and certs and place those in plain text in a values yaml for prometheus
3. Get my TLS Key and certs and place those in plain text in a values yaml for Alert Manager

Is this a known issue and is it being worked on?

**To Reproduce**

Deploy with TLS for all components with pre created certs
**Expected behavior**

The same UX for ingress TLS config for all components of a single chart

**Additional context**

### PR DESCRIPTION
**Pull request by vrabbi**
**Description of the change**
This Change standardizes the ingress configuration for the three ingress objects created via this chart.
it makes it possible to utilize pre existing secrets like what the thanos configuration allowed also for prometheus and alert manager.

**Benefits**
Standardization and support for a very common use case where secrets are already present in the cluster with the TLS certs for the ingress objects.

**Possible drawbacks**
may be viewed as a breaking change as we have changed the values.yaml structure for ingress objects

**Applicable issues**

  - fixes #8779 

**Additional information**

**Checklist**

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by vrabbi** [comment]
@carrodher this is a clean new PR which was easier to do then cleanup the old one and deal with merge conflicts. same changes as before but have addressed the issue of versioning of the chart and followed the DCO requirement.

**Comment by migruiz4** [comment]
Hi @vrabbi,

I'm sorry but we can not accept these changes, as the Ingress for Kube Prometheus and Alert manager are already standardized to be in line with the rest of the charts in our catalog.

All of the configurations that would be done with the suggested changes can be done by using the existing values `ingress.extraTls` (equivalent to using `ingress.tls` in your PR) and `ingress.extraHosts` (equivalent to `ingress.hosts`):

https://github.com/bitnami/charts/blob/96f9d6b7d6536b0d8fb9144859b8929aad870977/bitnami/kube-prometheus/templates/alertmanager/ingress.yaml#L33-L42
https://github.com/bitnami/charts/blob/96f9d6b7d6536b0d8fb9144859b8929aad870977/bitnami/kube-prometheus/templates/alertmanager/ingress.yaml#L50-L52

The additional code that is being removed by this PR, is intended to make Ingress configuration easier for users looking for more simple deployments.

Indeed, we have plans to standardize the `thanos.ingress` to include the missing features, present in Alert Manager and Kube Prometheus Ingress templates.

If you have any questions about how to move from `ingress.tls` to `ingress.extraTls`, feel free to let us know.

**Comment by vrabbi** [comment]
i had not seen the extraTLS before which seems it should work however the description is very misleading on the variable as it is not for additional hostnames rather it replaces tls section from my understanding of the chart

**Comment by migruiz4** [comment]
I'm sorry the description for `extraTls` was not clear enough. 
Maybe something more simple like "Extra TLS settings for the ingress" would be clearer and not mislead users to confusion?

In any case, I will close this PR since it no longer applies. Thank you for your understanding.

**Comment by vrabbi** [comment]
Or something like manualTls as it isnt extra its either or from my understanding. ExtraTls even in the name implies it is additional to tls not another option instead of tls

**Pull request closed without merging**
