### PR TITLE
[bitnami/harbor] Bump PostgreSQL version to 13.x branch

### PR DESCRIPTION
**Pull request by gongomgra**
### Description of the change

Bumps PostgreSQL version used in Harbor chart to branch 13.x as suggested officially in https://goharbor.io/docs/2.4.0/install-config/

### Benefits

Harbor Chart uses most recent supported version of PostgreSQL.

### Possible drawbacks

Upgrades between major versions of the chart requires using the previous PostgreSQL version to avoid errors as explained at [docs.bitnami.com](https://docs.bitnami.com/kubernetes/infrastructure/harbor/administration/upgrade/)

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by FraPazGal** [comment]
Thanks for the PR @gongomgra! Given that the `helm upgrade` won't work out-of-the-box (PSQL requires manual steps to upgrade the database for it to work with a new major), I would include an entry in our [upgrade doc](https://github.com/bitnami/charts-docs/blob/main/charts/harbor/_upgrade.md.erb) referring to [PSQL's upgrading doc](https://www.postgresql.org/docs/current/upgrading.html).

**Comment by FraPazGal** [comment]
Thanks for the PR @gongomgra! Given that the `helm upgrade` won't work out-of-the-box (PSQL requires manual steps to upgrade the database for it to work with a new major), I would include an entry in our [upgrade doc](https://github.com/bitnami/charts-docs/blob/main/charts/harbor/_upgrade.md.erb) referring to [PSQL's upgrading doc](https://www.postgresql.org/docs/current/upgrading.html).

**Comment by gongomgra** [comment]
@FraPazGal yes, I'm also adding a new entry in the chart-docs repo (sending a new PR in a while), but thank you for the reminder! I will also fix the signature error, it is only missing the `signed off by...` message, but it is GPG signed.

**Review by carrodher — DISMISSED** [review]

**Review by joancafom — APPROVED** [review]
LGTM! Please, make sure the Upgrade section is already in the README by the time this gets merged

**Pull request merged**
