### PR TITLE
[bitnami/postgresql] fix parsing of cronjob yaml template when using tls

### LINKED ISSUE #20546: postgresql: cronjob backup not working with tls
### Name and Version

bitnami/postgresql

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Running the following Helm command.

```console
$ helm install mypostgres bitnami/postgresql -f values.yaml
Error: INSTALLATION FAILED: YAML parse error on postgresql/templates/backup/cronjob.yaml: error converting YAML to JSON: yaml: line 53: mapping values are not allowed in this context
```

### Are you using any custom parameters or values?

Values file `values.yaml`. This is the simplest version to reproduce the error.

```yaml
tls:
  enabled: true
  autoGenerated: true
backup:
  enabled: true
```

### What is the expected behavior?

I expect the deployment to be installed.

### What do you see instead?

I see the above error message.
```
Error: INSTALLATION FAILED: YAML parse error on postgresql/templates/backup/cronjob.yaml: error converting YAML to JSON: yaml: line 53: mapping values are not allowed in this context
```

### Additional information

I also tried by manually setting a TLS certificate via a Kubernetes secret, but that also fails.

I also tried different versions of the chart, but they all seem to have the same problem.

### PR DESCRIPTION
**Pull request by mrlhansen**
### Description of the change
Fixing yaml parsing error for cronjob backup template

### Benefits
Template will not fail to be generated.

### Possible drawbacks
None

### Applicable issues
- fixes #20546

### Additional information
None

### Checklist
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by farthinder** [comment]
For what it is worth, I just ran in to this problem :)

**Comment by cernockyd** [comment]
Hello, @aoterolorenzo is there any chance of this review? For some reason, it got closed for inactivity, there are already two issues mentioning the problem, see #20546 and #21750.

**Comment by carrodher** [comment]
Hi, sorry for the inconvenience. It seems the branch is not here anymore so the PR needs to be recreated.

**Comment by cernockyd** [comment]
@mrlhansen Hello, are you currently in a position to recreate the issue as the reviewer above mentioned?

**Comment by mrlhansen** [comment]
@cernockyd I created a new pull request.

**Comment by carrodher** [comment]
Thank you for opening this new Pull Request. Our team will review and provide feedback.
Your contribution is greatly appreciated!

**Comment by cernockyd** [comment]
> @cernockyd I created a new pull request.

woo hoo 🎉!

**Pull request closed without merging**
