### PR TITLE
[bitnami/elasticsearch] Bump version to pull in latest kibana subchart

### PR DESCRIPTION
**Pull request by jerryharrow**
**Description of the change**

Just change version so that the kibana subchart is updated to the latest.

**Benefits**

Pulls in bug fixes available in kibana 8.1.3 chart.

**Possible drawbacks**

none.

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for the PR, the update process is automated, a new version containing the latest kibana was released automatically some hours ago, see https://github.com/bitnami/charts/commit/c19845f976e91ce7d4e8bd3b249f8e7ba8449ec4

I am closing this PR since it is not needed. Thanks again.

**Comment by jerryharrow** [comment]
Love that automation!  Thanks.

**Review by javsalgar — COMMENTED** [review]
I'm missing changes in the Chart.lock file as well. Could you confirm you executed helm dep update?

**Comment by javsalgar** [comment]
Never mind, just saw it was automated

**Pull request closed without merging**
