### PR TITLE
[bitnami/postgresql] metrics.collectors applies to read replicas

### LINKED ISSUE #30125: [bitnami/postgresql] metrics.collectors ignored for read replica
### Name and Version

bitnami/postgresql 16.0.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. deploy bitnami postgres with `architecture: replication` and at least 1 custom metrics collector enabled. For example like this: `helm install --set architecture=replication,metrics.enabled=true,metrics.collectors.postmaster=true my-release oci://registry-1.docker.io/bitnamicharts/postgresql`
2. observe that the metrics container for the primary postgres container starts with the startup arguments correctly set to `--collector.postmaster` while the metrics container for the read replica is missing this flag

### Are you using any custom parameters or values?
```
architecture: replication
metrics.enabled: true
metrics.collectors.postmaster: true
```
### What is the expected behavior?

Both the StatefulSet for the postgresql primary as well as the StatefulSet for the postgresql read replica should start their metrics containers with the extra arguments for the enabled or disabled collectors from the helm values.

### What do you see instead?

Only the StatefulSet of the postgresql primary uses settings defined at `metrics.collectors`.

### Additional information

The responsible line in the template for the primary StatefulSet is [here](https://github.com/bitnami/charts/blob/0868c633cc6b2f16efcbbd86e0dce126ac0fdcd1/bitnami/postgresql/templates/primary/statefulset.yaml#L530). Any equivalent is missing for the read replica StatefulSet [here](https://github.com/bitnami/charts/blob/0868c633cc6b2f16efcbbd86e0dce126ac0fdcd1/bitnami/postgresql/templates/read/statefulset.yaml#L432).

### PR DESCRIPTION
**Pull request by dklenke**
### Description of the change

When `architecture: replication` as well as `metrics.enabled: true` and `metrics.collectors.postmaster: true` are set (any collector works here, postmaster used as example) this change makes the read replicas metrics containers start with the relevant collector args.

### Benefits

Consistent behavior when enabling metrics collectors in replication mode.

### Applicable issues

- fixes #30125

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by dklenke** [comment]
I see that the github actions were unable to push to my fork but I am missing the knowledge of how to fix that. I invited the bitnami-bot to the project but the invite is pending

**Comment by carrodher** [comment]
Thanks for your contribution! As you rightly said, inviting bitnami-bot to your fork is enough, we just accepted the invitation.
At this moment, please note GitHub is reporting some conflicts that must be resolved before merging the PR, could you please rebase from `main` resolving the conflicts?

**Comment by dklenke** [comment]
Hi, I resolved the merge conflict but now the changelog for some reason has moved the 16.1.0 update to the 30.10 instead of the 29.10. I tried to revert my changes to the file but the bot reintroduced them. I hope this is not an issue

**Review by juan131 — APPROVED** [review]
Thanks for the fix! LGTM

**Comment by robcresswell** [comment]
This is giving me the following issue, I think:

```
/opt/bitnami/scripts/libpostgresql.sh: line 395: POSTGRESQL_REPLICATION_USE_PASSFILE: unbound variable
```

pinning to 16.1.0 makes the issue go away

**Pull request merged**
