### PR TITLE
bitnami/databunker

### PR DESCRIPTION
**Pull request by stremovsky**
**Description of the change**

New project.

**Additional information**

- https://databunker.org/
- https://databunker.org/doc/start/
- https://github.com/securitybunker/databunker

Related to https://github.com/bitnami/charts/pull/8365

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Comment by juan131** [comment]
Hi @stremovsky 

Thanks for your PR! As my colleague @miguelaeh mentioned in the original PR, we have to evaluate the feasibility for this solution but due to limited resources that could take some time.

Please note that the container images included in this chart are not part of the Bitnami catalog at this moment which is a mandatory requirement for us to accept the chart (see [CONTRIBUTING.m](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository))

**Comment by stremovsky** [comment]
Hello @juan131 @miguelaeh

I understand you have many tasks.

I will love to port the Databunker Dockerfile and docker-compose to the Bitnami catalog.

I can create one for example based on WordPress:
https://github.com/bitnami/bitnami-docker-wordpress

Let me know if that can work from your side?

Best
Yuli

**Comment by juan131** [comment]
Hi @stremovsky 

Thanks so much for your offering! We really appreciate it.

I'm afraid it's not that simple as creating a new container repo based on existing ones. Creating an image for the Bitnami catalog implies several changes in our internal repositories so we can automate the whole process of tracking new releases in the upstream project, downloading the source code, compiling the binaries, creating the containers, testing them on different scenarios, publishing them, etc.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!

**Pull request closed without merging**
