### PR TITLE
Elasticsearch master nodes persistency

### PR DESCRIPTION
**Pull request by tzachalon**
This is a small fix regarding the inability to attach a persistence storage for elasticsearch master nodes, as described on: https://github.com/bitnami/charts/issues/1509

Adding double-quotes to the volumeMount's name fixed the issue on my kubernetes cluster and now I'm able to take the entire elasticsearch cluster down and up without any issues with differences in cluster uuid.

This is my first contribution on Github, let me know if anything else is needed.

### CODE REVIEW

**Comment by carrodher** [comment]
mmm I am not sure if this fixed the issue because other parallel reason, but I was taking a look at the rest of Bitnami charts and in all of them we're using
```yaml
- name: whatever
```
without double quotes, I can't understand why it makes a difference in this case.

Do you have any idea about that @juan131 @sameersbn?

**Comment by sameersbn** [comment]
@carrodher I don't think is should make a difference, but if it does then it's probably a kubernetes issue. From #1509 I see that nobody has been able to reproduce this issue.

@tzachalon can you please share some information about you k8s cluster? are you using gke, version, etc?

**Comment by tzachalon** [comment]
> @carrodher I don't think is should make a difference, but if it does then it's probably a kubernetes issue. From #1509 I see that nobody has been able to reproduce this issue.
> 
> @tzachalon can you please share some information about you k8s cluster? are you using gke, version, etc?

Sure.
I'm using GKE. tried the installation on master version 1.12.10-gke.17 and also 1.13.11-gke.14. All I'm trying to say is that if on some k8s types we do see some issues when the quotes are not aligned, why not adding it anyway?

**Comment by sameersbn** [comment]
@tzachalon of course there isn't any issue adding the quotes. I we are trying to ascertain is where the quotes actually made a difference. Cause if it did then we may have to do the same for every single chart published by us.  

I will follow you report and see if I am able to reproduce this issue.

**Comment by tzachalon** [comment]
@sameersbn any update? Can I assist in any way?

**Comment by sameersbn** [comment]
@tzachalon Please allow me some time to report back

**Comment by tzachalon** [comment]
@sameersbn Sure thing. Thanks a lot!

**Comment by javsalgar** [comment]
Hi,

Just like my colleagues, I think this is a very weird issue. Could you try checking the kubectl describe pod to see the issue mounting the volume?

**Comment by carrodher** [comment]
Closing this PR due to lack of activity

**Pull request closed without merging**
