### PR TITLE
bitnami/oauth2-proxy Add common oauth2-proxy args as chart values

### LINKED ISSUE #13195: Add common oauth2-proxy args as chart values
### Name and Version

bitnami/oauth2-proxy 3.3.3

### What is the problem this feature will solve?

A typical oauth2-proxy configuration may include a few arguments that point to environment specific hosts.  These could include the `--oidc-issuer-url`,  `--redirect-url`, and the `--whitelist-domain` oauth2-proxy command line arguments.  Currently the only way to provide these values is to add them to the extraArgs chart variable.  When trying to reuse the chart in multiple environments this means that all extraArgs chart variables need to be redefined in environment specific values files, which makes the management of non-host based extraArgs more difficult.

## Current Setup
values.yaml
```yaml
oauth2-proxy:
  extraArgs:
    - --provider=keycloak-oidc
    - --show-debug-on-error=true
    - --silence-ping-logging=true
    - --upstream=static://200
    - --skip-provider-button=true
    - --reverse-proxy=true
    - --set-xauthrequest=true
    - --pass-access-token=true
    - --set-authorization-header=true
    - --pass-authorization-header=true
    - --pass-user-headers=true
    - --pass-host-header=true
    - --cookie-name=session  
    - --redirect-url: https://dev.test.com/oauth2/callback
    - --oidc-issuer-url: https://dev.test.com/auth/realms/test
    - --white-list: dev.test.com,auth.dev.test.com
```
qa-values.yaml
```yaml
oauth2-proxy:
  extraArgs:
    - --provider=keycloak-oidc
    - --show-debug-on-error=true
    - --silence-ping-logging=true
    - --upstream=static://200
    - --skip-provider-button=true
    - --reverse-proxy=true
    - --set-xauthrequest=true
    - --pass-access-token=true
    - --set-authorization-header=true
    - --pass-authorization-header=true
    - --pass-user-headers=true
    - --pass-host-header=true
    - --cookie-name=session  
    - --redirect-url: https://qa.test.com/oauth2/callback
    - --oidc-issuer-url: https://qa.test.com/auth/realms/test
    - --white-list: qa.test.com,auth.qa.test.com
```

values.yaml
```yaml
oauth2-proxy:
  extraArgs:
    - --provider=keycloak-oidc
    - --show-debug-on-error=true
    - --silence-ping-logging=true
    - --upstream=static://200
    - --skip-provider-button=true
    - --reverse-proxy=true
    - --set-xauthrequest=true
    - --pass-access-token=true
    - --set-authorization-header=true
    - --pass-authorization-header=true
    - --pass-user-headers=true
    - --pass-host-header=true
    - --cookie-name=session  
  configuration:
    redirectUrl: https://dev.test.com/oauth2/callback
    oidcIssuerUrl: https://dev.test.com/auth/realms/test
    whiteList: dev.test.com,auth.dev.test.com
```
qa-values.yaml
```yaml
oauth2-proxy:
  configuration:
    redirectUrl: https://dev.test.com/oauth2/callback
    oidcIssuerUrl: https://dev.test.com/auth/realms/test
    whiteList: dev.test.com,auth.dev.test.com
```

#### Dev
```shell
helm install oauth2-proxy .
``` 
#### QA
```shell
helm install -f qa-values.yaml oauth2-proxy .
``` 

### What is the feature you are proposing to solve the problem?

Use the new configuration chart values to populate specific args in the oath2-proxy deployment template.

PR will be submitted with the change.

### What alternatives have you considered?

The alternative is to redefine the entire extraArgs chart variable for each environment which makes it harder to keep the non-environment specific value in sync.

### PR DESCRIPTION
**Pull request by cmbaatz**
Closes #13195 

Added new configuration values that will be added to the args passed to the oauth2-proxy container:

1. redirectUrl
2. oidcIssuerUrl
3. whiteList

Signed-off-by: Chadwick Baatz <cbaatz@gosecure.net>

### Applicable issues

  - fixes #

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by marcosbc — CHANGES_REQUESTED** [review]

**Review by marcosbc — APPROVED** [review]
LGTM! Thanks for the contribution!

**Review by marcosbc — CHANGES_REQUESTED** [review]
@cmbaatz I cannot merge because there is a conflict. Could you fix it?

**Comment by cmbaatz** [comment]
@marcosbc I will look at this today

**Comment by cmbaatz** [comment]
@marcosbc looks like the only conflict was on the version in the Chart.yaml file.  This has been fixed.

**Review by marcosbc — APPROVED** [review]
Thanks!

**Pull request merged**
