### PR TITLE
[bitnami/redis] label slave pod using sentinel masterService

### PR DESCRIPTION
**Pull request by BernardBerenes**
### Description of the change

- Add the pod label **app.kubernetes.io/role: slave** to every pod created by the StatefulSet when sentinel.masterService.enabled is set to true.
- Add a script to remove the **app.kubernetes.io/role: slave** label when the pod is a master.

### Benefits

We can specify service for slave only

### Applicable issues

- fixes #

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by carrodher** [comment]
Thank you for initiating this pull request. We appreciate your effort. Just a friendly reminder that it's important to sign your commits. Adding your signature certifies that you either authored the patch or have the necessary rights to contribute the changes. You can find detailed information on how to do this in the [“Sign your work” section of our contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work).

In the same way, please note that the chart version needs to be bumped in the _Chart.yaml_. I suggest you to rebase from `main` applying the changes on top of it

Feel free to reach out if you have any questions or need assistance with the signing process.

**Comment by BernardBerenes** [comment]
I've updated the version and signed my commit

**Comment by carrodher** [comment]
Unfortunately, the signature is still failing, see https://github.com/bitnami/charts/pull/29121/checks?check_run_id=29648536492

Could you please take a look?

**Comment by BernardBerenes** [comment]
is it okay rn?

**Comment by carrodher** [comment]
Hi @BernardBerenes, it seems the latest commit (https://github.com/bitnami/charts/pull/29121/commits/af605acced95e482758f51a76747ec7908dccb2c) didn't include the version bump.

Could you please sync your fork with the latest changes and then bump the chart version in the _Chart.yaml_ file?

**Review by dgomezleon — APPROVED** [review]
LGTM. Thanks for contributing!

**Pull request merged**
