### PR TITLE
[bitnami/wildfly] Allow definition of additional container ports

### PR DESCRIPTION
**Pull request by devjeff**
Signed-off-by: Evgenij Shyshkin <kontakt@shyshkin-it.de>

### Description of the change

Added new property "extraContainerPorts" to define additional container ports. These can be defined similarly to "extraEnvVars", e. g.:

```yaml
extraContainerPorts:
   - name: additional-port
     value: 8888
```

This feature is necessary for our setup. We use version [0.9.3 of the KubePing protocol](https://github.com/jgroups-extras/jgroups-kubernetes/tree/0.9.3). This protocol requires that Port 8888 (s. project Readme) is defined as a "containerPort". Otherwise, the node discovery for cluster building will not work.

Till now, there was no way to define additional container ports in the bitnami Wildfly chart.  

### Benefits

It is possible to define additional ports exposed by the Wildfly container (e. g. JGroups ports).

### Possible drawbacks

None identified

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by talbx** [comment]
in my current project we also faced issues with the chart, since we wanted to expose additional ports for the wildfly. would love to see this feature!

**Comment by devjeff** [comment]
@jotamartos I checked the failed pipeline, but I can't see the actual cause. Can you please help? There are following error messages, but without additional information:
```
  Error: Task deployment ( cypress ) has failed. Error: Completed with invalid status.
  Error: Task deployment ( health-check ) has failed. Error: Completed with invalid status.
  Error: Task deployment ( goss ) has failed. Error: Completed with invalid status.
```
I wanted to check the pipeline details via the logged [link ](https://cp.bromelia.vmware.com/v1/execution-graphs/62cb26b7-83b4-4be6-811b-ebfc4b9874e2), but I don't have permissions to access this page.

**Comment by jotamartos** [comment]
I think the errors are not related to your changes as you are not editing the default configuration. I'll take a look and provide more info.

**Comment by jotamartos** [comment]
Hi @devjeff,

Please rebase your branch and resolve the conflict

**Review by jotamartos — APPROVED** [review]

**Pull request merged**
