### PR TITLE
[bitnami/mariadb-galera] fix: add extra condition to password validation

### LINKED ISSUE #3825: [bitnami/mariadb-galera] existingSecret is not honoured
**Which chart**:
bitnami/mariadb-galera 4.4.1

**Describe the bug**
If `existingSecret` is set, the deployment fails at the value validation because the passwords have not been set directly.
```
helm install mariadb -f values-production.yaml bitnami/mariadb-galera
Error: template: mariadb-galera/templates/NOTES.txt:62:3: executing "mariadb-galera/templates/NOTES.txt" at <include "mariadb-galera.validateValues" .>: error calling include: template: mariadb-galera/templates/_helpers.tpl:187:51: executing "mariadb-galera.validateValues" at <fail>: error calling fail: 
VALUES VALIDATION:
mariadb-galera: rootUser.password
    A MariaDB Database Root Password is required ("rootUser.forcePassword=true" is set)
    Please set a password (--set rootUser.password="xxxx")
mariadb-galera: db.password
    A MariaDB Database Password is required ("db.forcePassword=true" is set)
    Please set a password (--set db.password="xxxx")
mariadb-galera: galera.mariabackup.password
    A MariaBackup Password is required ("galera.mariabackup.forcePassword=true" is set)
    Please set a password (--set galera.mariabackup.password="xxxx")

```
Additionally, the README.md does not document the data values to be used in the `existingSecret`, while the `bitnami/mariadb` README.md does next to `existingSecret`.

I believe these values to be `mariadb-root-password`, `mariadb-galera-mariabackup-password` and `mariadb-password.

**To Reproduce**
1. Start with `values-production.yaml` uncomment `existingSecret`
2. Set a value for `existingSecret` e.g. mariadbgalerasecrets
3. Create a secret with the data values listed above, and name it the same as the value set for `existingSecret`
4. Do NOT set password values in `values-production.yaml`
4. Deploy bitnami/mariadb-galera using modified the `values-production.yaml`
5. Validation error occurs

**Expected behavior**
Chart should deploy using secrets from `existingSecret`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

### PR DESCRIPTION
**Pull request by dani8art**
**Description of the change**

- Add `(not .Values.existingSecret)` to password requirement validations
- Add secret data structure to the README.md

**Benefits**

We will be able to use `existingSecret`

**Possible drawbacks**

N/A

**Applicable issues**

  - fixes #3825

**Additional information**

N/A

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Review by juan131 — APPROVED** [review]
LGTM

**Comment by hamid-elaosta** [comment]
Hi @dani8art . Thank you for the quick response. I'm having unrelated issue with deploying the chart at the moment so unfortunately can't confirm it is fixed at this time.

**Comment by hamid-elaosta** [comment]
@dani8art  After some testing today, I'm not sure the issue is resolved by the PR. I am unable to deploy the chart using existingSecret because root authentication fails;

```
  Warning  Unhealthy               1s (x7 over 61s)    kubelet                  Readiness probe failed: mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: YES)'
```
I have spent most of the day trying to understand if the issue is on my end but I'm now convinced it is not.

If I set forcePassword to false as suggested, the modified chart deploys, presumably using randomly generated passwords. If I don't set forcePasswords to false, and provide existingSecret, the chart fails with the authentication error. It's as if the passwords are randomly being generated anyway and then when it tries to startup using the secret provided ones, they don't match.

**Comment by dani8art** [comment]
Hi @hamid-elaosta, I was unable to reproduce your environment, I was following these steps

```console
$ kubectl create secret generic my-galera-existingsecret \
  --from-literal="mariadb-root-password=rootpassword" \
  --from-literal="mariadb-galera-mariabackup-password=mariabackup" \
  --from-literal="mariadb-password=password"

$ helm install galera bitnami/mariadb-galera --set existingSecret=my-galera-existingsecret
```

```console
$ kubectl get pod
NAME                      READY   STATUS    RESTARTS   AGE
galera-mariadb-galera-0   1/1     Running   0          4m8s
galera-mariadb-galera-1   1/1     Running   0          3m7s
galera-mariadb-galera-2   1/1     Running   0          2m6s
```

If you look at the pods they have been created pointing to the right value.

```console
$ kubectl get pods galera-mariadb-galera-0 -o yaml
...
    - name: MARIADB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mariadb-root-password
          name: my-galera-existingsecret
...
```

BTW, you should take into account the persistence, I mean, if you have previously installed an instance of mariadb-galera you have to remove the PVC's created. 

```console
$ kubectl get pvc --show-labels
NAME                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE    LABELS
data-galera-mariadb-galera-0   Bound    pvc-ef5d4fe2-8e5f-4c0b-9060-ee19b90748df   8Gi        RWO            standard       10m    app.kubernetes.io/instance=galera,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=mariadb-galera
data-galera-mariadb-galera-1   Bound    pvc-60a28d98-1c48-4c57-ab28-90930dce05a2   8Gi        RWO            standard       9m4s   app.kubernetes.io/instance=galera,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=mariadb-galera
data-galera-mariadb-galera-2   Bound    pvc-476b6a4c-af33-4973-83ae-8845c264b655   8Gi        RWO            standard       8m3s   app.kubernetes.io/instance=galera,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=mariadb-galera
```

```console
$ kubectl delete pvc -l "app.kubernetes.io/instance=galera"
```

**Comment by hamid-elaosta** [comment]
@dani8art I'm very sorry to have taken up your time with this. It was user error, I had base64 encoded the passwords in my `secrets.yaml` with newline characters at the end, which is not so easy to spot but caused the permission denied errors!

Thank you for writing out those steps, it was creating the secret on the command line which helped me to find the issue. The good news is that I can now confirm that the PR change and my deployment are now working as expected.

Again, thank you for your time and effort!

**Pull request merged**
