### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by trburgess**
Fix typo

### CODE REVIEW

**Comment by carrodher** [comment]
Thanks for your contribution. Even for those small changes, it is needed to increase the chart version in the _Chart.yaml_ file, can you increase the patch number?

**Comment by trburgess** [comment]
@carrodher I don’t seem to be able to locate that file.

**Comment by rafariossaa** [comment]
Hi @trburgess ,
  The file is this: https://github.com/bitnami/charts/blob/master/upstreamed/wordpress/Chart.yaml

**Comment by trburgess** [comment]
Thanks @rafariossaa

**Comment by carrodher** [comment]
Thank you!

**Pull request merged**
