### PR TITLE
[bitnami/elasticsearch] Add support for single-node

### PR DESCRIPTION
**Pull request by andresbono**
### Description of the change

This PR adds the option to deploy a single-node cluster that assumes all the roles. The following inputs should be provided:

```yaml
master:
  masterOnly: false
  replicaCount: 1
data:
  replicaCount: 0
coordinating:
  replicaCount: 0
ingest:
  replicaCount: 0
```

The single-node cluster will be configured with [single-node discovery](https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html#single-node-discovery) in that case.

### Benefits

- Cover more use cases.

### Possible drawbacks

- Scaling the replicas up requires reloading the configuration in the existing node. A warning was added in the `NOTES.txt`.

### Applicable issues

- Originated in #18996, thank you @fabiocastagnino!

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] (n/a) ~Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)~
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by andresbono** [comment]
Manual testing results:

```shell
$ cat >/tmp/values.yaml <<EOF
master:
  masterOnly: false
  replicaCount: 1
data:
  replicaCount: 0
coordinating:
  replicaCount: 0
ingest:
  replicaCount: 0
EOF
$ helm install elasticsearch . --values /tmp/values.yaml --wait
$ kubectl logs sts/elasticsearch-master
# Looks good
$ kubectl port-forward svc/elasticsearch 9200:9200

$ curl -s localhost:9200/_cluster/health | jq .
{
  "cluster_name": "elastic",
  "status": "green",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "active_primary_shards": 0,
  "active_shards": 0,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100
}
$ curl -s -X PUT localhost:9200/someindex | jq .
{
  "acknowledged": true,
  "shards_acknowledged": true,
  "index": "someindex"
}
$ curl -s -X GET localhost:9200/someindex | jq .
{
  "someindex": {
    "aliases": {},
    "mappings": {},
    "settings": {
      "index": {
        "routing": {
          "allocation": {
            "include": {
              "_tier_preference": "data_content"
            }
          }
        },
        "number_of_shards": "1",
        "provided_name": "someindex",
        "creation_date": "1695716992224",
        "number_of_replicas": "1",
        "uuid": "L0HDoohtRbqZv5pYbofcBA",
        "version": {
          "created": "8100099"
        }
      }
    }
  }
}

$ curl -s -H 'Content-Type: application/json' localhost:9200/theindex/_create/theid -d '{"foo": "bar"}' | jq .
{
  "_index": "theindex",
  "_id": "theid",
  "_version": 1,
  "result": "created",
  "_shards": {
    "total": 2,
    "successful": 1,
    "failed": 0
  },
  "_seq_no": 0,
  "_primary_term": 1
}
$ curl -s localhost:9200/theindex/_source/theid
{"foo": "bar"}
$ curl -s localhost:9200/_cluster/health | jq .
{
  "cluster_name": "elastic",
  "status": "yellow",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "active_primary_shards": 2,
  "active_shards": 2,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 2,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 50
}
```

Status is `yellow` after populating some data. [Cluster health API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html#cluster-health-api-response-body):
> `yellow`: All primary shards are assigned, but one or more replica shards are unassigned. If a node in the cluster fails, some data could be unavailable until that node is repaired.

```

$ kubectl scale statefulset elasticsearch-master --replicas=0
$ helm upgrade elasticsearch oci://docker.io/bitnamicharts/elasticsearch --reset-values --set master.masterOnly=false --wait

$ kubectl logs elasticsearch-master-0
# Looks good
$ kubectl logs elasticsearch-master-1
# Looks good

$ kubectl port-forward elasticsearch-master-1 9201:9200
$ curl -s -X GET localhost:9200/someindex | jq .
# Looks good
$ curl -s -X GET localhost:9201/someindex | jq .
# Looks good
$ curl -s localhost:9200/theindex/_source/theid
# Looks good
$ curl -s localhost:9201/theindex/_source/theid
# Looks good

$ curl -s localhost:9201/_cluster/health | jq .
{
  "cluster_name": "elastic",
  "status": "green",
  "timed_out": false,
  "number_of_nodes": 8,
  "number_of_data_nodes": 4,
  "active_primary_shards": 2,
  "active_shards": 4,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100
}

**Review by rafariossaa — DISMISSED** [review]

**Review by migruiz4 — COMMENTED** [review]
Looks good to me, but could you please add a section in the README.md on 'How to deploy a single node'?

**Review by migruiz4 — APPROVED** [review]
Looks good to me!

**Comment by andresbono** [comment]
@fabiocastagnino, this PR is now merged. Please, feel free to start using it 🎉

**Comment by aabouzaid** [comment]
@andresbono Do you know how this change was released?
I cannot find [any PR](https://github.com/bitnami/charts/pulls?q=is%3Apr++is%3Aclosed+%27%5Bbitnami%2Felasticsearch%5D+Release%27) that released PostgreSQL chart v19.12.0 (with your changes) :thinking:

**Comment by carrodher** [comment]
Elasticsearch 19.12.0 was released 6 days ago in the [DockerHub OCI registry](https://hub.docker.com/layers/bitnamicharts/elasticsearch/19.12.0/images/sha256-82ee01ecdb7a503de4e1074c454c07e7a28fdd55bd0efff771467c9003d88a6d?context=explore).

This PR where we are commenting right now is the one triggering the release, it does not need a different one.

**Pull request merged**
