### PR TITLE
[bitnami/kafka] Configure Kraft mode by default

### PR DESCRIPTION
**Pull request by jotamartos**
### Description of the change

This PR updates the chart to use Kraft mode by default. Before merging these changes, we need to release the container configuring Kraft mode by default too. 

### Benefits

Kraft mode is the default one now. https://cwiki.apache.org/confluence/display/KAFKA/KIP-833%3A+Mark+KRaft+as+Production+Ready

### Possible drawbacks

None from what I tested. Will update the descriptions with all the tests I perform. 

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by dgomezleon — APPROVED** [review]
LGTM

**Review by marcosbc — CHANGES_REQUESTED** [review]
Could you add some upgrade notes to the [Upgrading](https://github.com/bitnami/charts/tree/main/bitnami/kafka#upgrading) section in the README?

**Review by dgomezleon — APPROVED** [review]
LGTM

**Review by marcosbc — DISMISSED** [review]
LGTM! (with comments)

**Review by dgomezleon — APPROVED** [review]

**Comment by OneCricketeer** [comment]
Has it been tested running a controller as a standalone container? And brokers separately? There's another issue where people are having issues with this for the bitnami image

**Comment by fmulero** [comment]
Hi @OneCricketeer, Could you share the issue?

**Comment by OneCricketeer** [comment]
There's several issues with Kraft, not only those I mentioned. The container issues are here https://github.com/bitnami/containers/labels/kafka

**Pull request merged**
