### PR TITLE
[bitnami/postgresql] Add Storage Class Configuration to Templates

### PR DESCRIPTION
**Pull request by 3schwartz**
### Description of the change

Add configurations to the template.

### Benefits

It is possible to define a storage class.

### Applicable issues

Currently not able to define the storage class even though the configuration in the `values.yaml` file is there.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by 3schwartz** [comment]
> Thanks for your contribution! Please note to test the Helm charts it is needed to split the changes of each chart into separate PRs

Made a second PR
https://github.com/bitnami/charts/pull/30993

**Review by fmulero — CHANGES_REQUESTED** [review]
Thanks a lot @3schwartz for your contribution!

Just a quick suggestion, Could you add this change to read replicas also? the value `readReplicas.persistence.storageClass` already exists so the change should be the same for the read replicas statefulset

**Comment by 3schwartz** [comment]
> `readReplicas.persistence`

✅

**Review by fmulero — APPROVED** [review]
Great!!. Thanks @3schwartz LGTM

**Pull request merged**
