### PR TITLE
[bitnami/cassandra] Add Prometheus Operator support

### PR DESCRIPTION
**Pull request by raehik**
Adds a ServiceMonitor for PrometheusOperator, and a separate Service to expose the
metrics for pods.

**Description of the change**

Adds easy Prometheus Operator integration for the chart. Metrics come built-in (if enabled), so a relatively trivial change.

**Benefits**

Easy setup for Prometheus Operator, which generates scrape configs for Services automatically. Should work just the same when scaling up and down, without any intereference required, I believe.

**Possible drawbacks**

  * Metrics port and path are hardcoded (8080 and `/metrics`), as in the StatefulSet. Not sure this is best practice.
  * Prometheus resource requires editing to select the ServiceMonitor (if "use all" isn't configured). I haven't found a good workaround for this. Might be intended ^^
  * Created a separate Service for the metrics port. Should it instead be another open port in `service.yaml` ?
  * Dependent on `metrics.create == true`. It'll run if not, but of course no metrics will be scraped.

**Applicable issues**

None.

**Additional information**

Thanks for this chart, it's saving us a lot of time and I hope we can give back a bit :)

### CODE REVIEW

**Comment by raehik** [comment]
As of yet untested.

**Comment by raehik** [comment]
Seems to work with a local `helm install .` I can share my values if it's useful.

**Comment by javsalgar** [comment]
Hi,

Thanks for sharing the PR, we will take a look and let you know any changes. I think that sharing your values could help

**Comment by javsalgar** [comment]
Ping @raehik , could you share your values.yaml?

**Pull request closed without merging**
