### PR TITLE
bitnami/Keycloak] Allow manual override fo KC_HOSTNAME_URL and KC_ADMIN_HOSTNAME_URL

### LINKED ISSUE #28357: [bitnami/keycloak] Cannot load AdminUI with gce based ingress
### Name and Version

bitnami/keycloak:21.7.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I am trying to deploy Keycloak with APISIX as the ingress-controller. APISIX requires the path to be specified as /* instead of / in the ingress definition.

Due to this, post-deployment, the KC_HOSTNAME_URL env var gets specified as https://keycloak.docker.internal/* instead of https://keycloak.docker.internal/
Source: https://github.com/bitnami/charts/blob/2b15502a03c16d5c38877244650ff0d1f8f764b9/bitnami/keycloak/templates/statefulset.yaml#L230

Appears, it will also affect the KC_HOSTNAME_ADMIN_URL env var
Source: https://github.com/bitnami/charts/blob/2b15502a03c16d5c38877244650ff0d1f8f764b9/bitnami/keycloak/templates/statefulset.yaml#L223

### Are you using any custom parameters or values?

```
auth:
  adminUser: admin
  adminPassword: 2ewF79kM0R

ingress:
  enabled: true
  ingressClassName: apisix
  hostname: keycloak.docker.internal
  path: /*
  annotations:
    cert-manager.io/cluster-issuer: my-issuer
  tls: true

proxyAddressForwarding: true
proxy: edge
proxyHeaders: xforwarded
production: true

service:
  type: ClusterIP
```

### What is the expected behavior?

Keycloak UI should load successfully

### What do you see instead?

The Keycloak UI is forever stuck in **Loading the Admin UI** state.
Various static requests on the browser are appended with /* in the URI which causes a 404 error.

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by djas19**
### Description of the change

Allow users to provide their own value of the KC_HOSTNAME_URL and KC_ADMIN_HOSTNAME_URL parameters.

### Benefits

Currently a lot of assumptions are made when constructing these environment variables. This behaviour can be wanted in simple setups but it is impossible to foresee all possible scenarios. To accommodate this we can allow users to override this themselves but fallback on autogeneration if not provided.

### Possible drawbacks

The change is backwards compatible so no drawbacks are expected.

### Applicable issues

- fixes #28357 

### Additional information

Inspired out of discussions in issues: #28357 #28121 and #28161 

Closes: #28520 

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by djas19** [comment]
I don't see how to fix the CI issue. Could somebody give me some pointers on how to setup this fork to successfully run the CI?

**Comment by EC-Sol** [comment]
> I don't see how to fix the CI issue. Could somebody give me some pointers on how to setup this fork to successfully run the CI?

According to the PR checklist:
- [ ] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)

The README.md file is automatically generated and updated if the variables are properly documented in the values.yaml. If you have directly modified the README.md file, you should remove those changes.

**Comment by carrodher** [comment]
Thanks for your contribution! The issue is that the automation trying to update the README is not able to do it due to the lack of permissions in your branch/fork. Could you please add @bitnami-bot as developer/maintainer in your fork so it can update the README?

**Comment by djas19** [comment]
Hi @carrodher, the bitnami-bot is added as a maintainer on the repo (invite pending) but the pipeline still fails.

**Comment by carrodher** [comment]
Thanks! The changelog was properly updated!
The problem now seems to be conflicts caused by recent PRs such as https://github.com/bitnami/charts/pull/28519.

Could you please rebase from `main` and solve the conflicts?

**Comment by singhbaljit** [comment]
Chart v22 and Keycloak v25 was released. I don't these variables are still [supported anymore](https://www.keycloak.org/docs/25.0.2/release_notes/#new-hostname-options):

> Hostname v2 options are supported by default, as the old hostname options are deprecated and will be removed in the following releases. You should migrate to them as soon as possible. New options are activated by default, so Keycloak will not recognize the old ones.

**Comment by singhbaljit** [comment]
Can't we move these env vars to the config map instead of being defined directly on the statefulset? If you want to override them, you still can by defining them directly on the statefulset.

**Comment by djas19** [comment]
@singhbaljit As this is blocking our updates/releases I wanted to get a fix out quickly hence why the implementation is presented this way. also providing these via `extraEnvVars` doesn't work in the current setup and caused errors for duplicate keys. Maybe that would be possible if it would be on the in the config map but I didn't look into that. Looking at #28611 it doesn't look like this would solve the issue for us and a similar approach to this or moving those variables to the config map too would be needed as it still doesn't take into account wildcards in the ingress path and/or `httpRelativePath`

**Comment by singhbaljit** [comment]
@djas19 the `extraEnvVars` won't work currently because those variables get rendered on the statefulset, and there are already these variables defined, hence the duplicate key error. However, if you revise this PR to instead just move the definition of these two variables into the config map instead of adding the conditional logic to override, it will allow you to still meet your need (which to override these variables), without the conditional logic or extra parameters to the chart. I understand the need for a quick solution; to me, the moving of the variables is less code/quicker. Introducing new parameters has long term impact, because they can't be easily removed without breaking change. You can see how the override works already with the database variables. There are values being defined in the config map, and overrides defined in the statefulset. This is an established pattern in the chart/Kubernetes in general.

**Comment by singhbaljit** [comment]
see alternative, https://github.com/bitnami/charts/pull/28838

**Comment by jotamartos** [comment]
Sorry for the late reply. As #28838 is already merged, I understand this PR is not necessary anymore. Could you please confirm so we close it? 

Thanks

**Comment by djas19** [comment]
Confirmed

**Comment by djas19** [comment]
closing as #28838 is merged

**Pull request closed without merging**
