### PR TITLE
[bitnami/airflow] add resources to loaddags initcontainer

### LINKED ISSUE #28952: [bitnami/airflow] load dags initcontainer does not have resources section
### Name and Version

bitnami/airflow 19.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. for a cluster that mandates all containers have resources declared
2. deploy bitnami/airflow with dags.existingConfigmap defined
3. the cluster rejects the deployment of scheduler, web and worker because initContainer 'load-dags' does not declare resources

### Are you using any custom parameters or values?

dags.existingConfigmap=xxx

### What is the expected behavior?

succesfull deployment

### What do you see instead?

Getting error
``` 
Error from server (Forbidden): error when creating "xxxxx": admission webhook "validation.gatekeeper.sh" denied the request: [container-must-have-limits-and-requests] container <load-dags> does not have <{"cpu", "memory"}> limits defined
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bbakker2**
### Description of the change

This changes adds a resources section to the Load DAGs init container.

### Benefits

This makes the chart compatible with clusters that mandate that every container has resources defined.
 
### Possible drawbacks

None.

### Applicable issues

- fixes #28952

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by dgomezleon — APPROVED** [review]
LGTM. Thanks for contributing!

**Comment by dgomezleon** [comment]
Hi @bbakker2 , 
Could you please bump the version again to fix current conflicts?

**Comment by bbakker2** [comment]
I don't know why github closed this request on my behalf, I just wanted to bump the version as requested. Reopening...

**Comment by bbakker2** [comment]
> Hi @bbakker2 , Could you please bump the version again to fix current conflicts?

Sorry for asking, what is the recommend workflow for this?

**Pull request closed without merging**
