### PR TITLE
[bitnami/odoo] Fixed the spelling of 'running'

### PR DESCRIPTION
**Pull request by evjan**
**Description of the change**
Fix misspelling in NOTES.txt

**Benefits**
Release information is displayed without errors now.

**Possible drawbacks**
None

**Applicable issues**
N/A

**Additional information**
None

**Checklist**
- [x] Chart version bumped in Chart.yaml according to semver.
- [x] Title of the PR starts with chart name (e.g. [bitnami/chart])

⚠️ Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the kubeapps repository. This is only a synchronized mirror.

### CODE REVIEW

**Comment by evjan** [comment]
@joancafom done!

**Review by joancafom — APPROVED** [review]
LGTM! Thanks for your PR

**Comment by joancafom** [comment]
Hi @evjan 

I see you are a first time contributor to Bitnami repositories, thanks very much! Just to let you know that our PRs do always follow some standardized template in order to ease the reading and comprehension:

> 
> 
> **Description of the change**
> 
> 
> 
> **Benefits**
> 
> 
> 
> **Possible drawbacks**
> 
> 
> 
> **Applicable issues**
> 
> 
>   - fixes #
> 
> **Additional information**
> 
> 
> 
> **Checklist** 
> - [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
> - [ ] Variables are documented in the README.md
> - [ ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
> - [ ] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files
> 
> :warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

As this change is not a complex one this should not be a blocking issue, but it should be something like this 😄 :



**Description of the change**



Fix mispelling in NOTEs.txt

**Benefits**
Release information is displayed without errors now.


**Possible drawbacks**


None

**Applicable issues**

NA

**Additional information**
None

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

Thanks very much!

**Comment by evjan** [comment]
Ah, sorry about that! Do I need to do anything?

**Comment by joancafom** [comment]
Hi @evjan 

If you could update the [description](https://github.com/bitnami/charts/pull/3553#issue-475829766) to use this template that would be awesome! 👍

**Comment by evjan** [comment]
@joancafom I think I did the right thing now, I've become so used to Bitbucket that I've forgotten how to do everything in Github :joy:

**Comment by joancafom** [comment]
Thanks so much!

**Pull request merged**
