### PR TITLE
[bitnami/argo-cd] Calculate password Mtime using always UTC

### PR DESCRIPTION
**Pull request by miguelaeh**
**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])

### CODE REVIEW

**Review by alemorcuq — COMMENTED** [review]
Could you add some context on why this change?

**Comment by miguelaeh** [comment]
Basically, you need to calculate the time in the same timezone used by the Argo CD application, if not it will interpret the password has changed and you will be unable to login

**Comment by alemorcuq** [comment]
> Basically, you need to calculate the time in the same timezone used by the Argo CD application, if not it will interpret the password has changed and you will be unable to login

I assume Argo CD is configured to use UTC by default, right? Can users change this? What would happen if a user changes the timezone?

**Comment by miguelaeh** [comment]
The timezone cannot be changed, the sync windows are hardcoded to UTC: https://github.com/argoproj/argo-cd/blob/bb88a1c975b43a94da34c4516deaec44f32ac790/pkg/apis/application/v1alpha1/types.go#L1698

**Review by alemorcuq — APPROVED** [review]

**Pull request merged**
