### PR TITLE
[bitnami/memcached] Add securityContext to memcached metrics in STS

### LINKED ISSUE #15449: [bitnami/memcached] metrics containerSecurityContext missing from STS
### Name and Version

bitnami/memcached 6.3.11

### What architecture are you using?

amd64

### What steps will reproduce the bug?

The `metrics.containerSecurityContext` configuration is missing from the stateful set template.

### Are you using any custom parameters or values?

```yaml
metrics:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
```

### What is the expected behavior?

Security context applied to `metrics` container

### What do you see instead?

Security context missing from `metrics` container

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dszakallas**
The containerSecurityContext configuration is missing from the StatefulSet template, which I believe is in error. Such configuration is required for restrictive PSS compliance.

### Description of the change

Add securityContext to memcached metrics container in STS too. It already exists in the Deployment.

### Benefits

Such configuration is required e.g. for restrictive PSS compliance.

### Applicable issues

- fixes #15449 

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by dszakallas** [comment]
Hi! Done.

**Comment by javsalgar** [comment]
Hi!

It seems there are issues with the DCO as well, could you fix them?

**Comment by dszakallas** [comment]
Done.

**Review by fmulero — APPROVED** [review]
Great! thanks a lot @dszakallas for your contribution. LGTM

**Pull request merged**
