### PR TITLE
[bitnami/harbor] Removal of hardcoded Google Key in ChartMuseum template for GCS Storage Backend

### PR DESCRIPTION
**Pull request by sameer-m-dev**
Signed-off-by: Sameer Dev <sameer.devv@gmail.com>

### Description of the change

The main objective of this PR is to remove the hardcoded Google Key config for GCS Storage Backend in ChartMuseum when using GKE. 
- The current mechanism adds the key GOOGLE_APPLICATION_CREDENTIALS by default even when no secrets for the same are provided. 
- This causes ChartMuseum to go into a CrashBackLoop state since it expects to parse the json provide in GOOGLE_APPLICATION_CREDENTIALS

### Benefits

- Removal of hardcoded Google Key config in ChartMuseum

### Possible drawbacks

NA

### Applicable issues

NA

### Additional information

NA

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by corico44** [comment]
Hello @sameer-m-dev, 

For it to make sense, shouldn't the default value of **.Values.persistence.imageChartStorage.gcs.encodedkey** in the values.yaml file be removed? If not, it is always set by default.

**Comment by sameer-m-dev** [comment]
hi @corico44 thanks for pointing this out, I have changed the value of **.Values.persistence.imageChartStorage.gcs.encodedkey** from base64-encoded-json-key-file to "". Hope this resolves your query

**Comment by sameer-m-dev** [comment]
hi @corico44 I have signed off my commit

**Comment by corico44** [comment]
Thank you @sameer-m-dev. Finally, can you resolve the conflicts related to the version of the Chart, please?

**Comment by sameer-m-dev** [comment]
@corico44 That's done too, hope its all good now :)

**Comment by sameer-m-dev** [comment]
Hi @corico44 can I know when will this PR be merged to master?

**Pull request merged**
