### PR TITLE
 [bitnami/rabbitmq] RabbitMQ adds MQTT ports.

### LINKED ISSUE #21686: [bitnami/rabbitmq] RabbitMQ MQTT ports
### Name and Version

bitnami/rabbitmq 12.6.0

### What is the problem this feature will solve?

Hi there,

we wanted to enable the MQTT Port on the Service to enable the communication over 1883 from other Pods or other Services
unfortunately its not possible to enable the MQTT Port by default

it would be easier if it gets backed into the chart as there could be potentially issues with newer version

### What is the feature you are proposing to solve the problem?

As a workaround for us we modified the yaml files in the Template to fit our needs

svc-headless.yaml
```yaml
    {{- if .Values.service.mqttPortEnabled }}
    - name: {{ .Values.service.portNames.mqtt }}
      port: {{ .Values.service.ports.mqtt }}
      targetPort: mqtt
    {{- end }}
```
statefulset.yaml
```yaml
          ports:
            - name: amqp
              containerPort: {{ .Values.containerPorts.amqp }}
            - name: dist
              containerPort: {{ .Values.containerPorts.dist }}
            - name: stats
              containerPort: {{ .Values.containerPorts.manager }}
            - name: epmd
              containerPort: {{ .Values.containerPorts.epmd }}
            - name: mqtt
              containerPort: {{ .Values.containerPorts.mqtt }}
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.containerPorts.metrics }}
            {{- end }}
            {{- if .Values.auth.tls.enabled }}
networkpolicy.yaml
    - ports:
        - port: {{ .Values.service.ports.epmd }}  # EPMD
        - port: {{ .Values.service.ports.amqp }}
        - port: {{ .Values.service.ports.amqpTls }}
        - port: {{ .Values.service.ports.dist }}
        - port: {{ .Values.service.ports.manager }}
        - port: {{ .Values.service.ports.mqtt }}
      {{- if not .Values.networkPolicy.allowExternal }}
svc.yaml (under ports)
    {{- if .Values.service.mqttPortEnabled }}
    - name: {{ .Values.service.portNames.mqtt }}
      port: {{ .Values.service.ports.mqtt }}
      targetPort: mqtt
      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.mqtt)) }}
      nodePort: {{ .Values.service.nodePorts.mqtt }}
      {{- end }}
    {{- end }}
```
as also in the values.yaml under service
```
mqttPortEnabled: true
ports:
mqtt: 1883
portnames:
mqtt "mqtt"
nodeports:
mqtt: ""
```

### PR DESCRIPTION
**Pull request by im-jinxinwang**
### Description of the change

RabbitMQ adds MQTT ports.
### Applicable issues

- fixes #21686 

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by christf** [comment]
so, what now?

**Comment by carrodher** [comment]
This PR was automatically closed due to the lack of activity, if you would like to command those changes, feel free to create a new PR, the team will be happy to review it

**Comment by christf** [comment]
What was the missing bit? It seems to me, code was provided, not merged and then stalebot axed it for the maintainers not acting within the allotted time. Was anything missing from the  code?

**Comment by carrodher** [comment]
Checks were failing when testing the changes

**Comment by voycey** [comment]
I cant see any failed checks on this- it seems the review wasnt actioned in time?

**Pull request closed without merging**
