### PR TITLE
[bitnami/kafka] set KAFKA_ENABLE_KRAFT=false if we don't use kraft

### PR DESCRIPTION
**Pull request by cloud-66**
### Description of the change

If kraft.enabled: false  we should set variable KAFKA_ENABLE_KRAFT=false  

### Benefits

Don't need to investigate how to disable kraft in kafka image because by default KAFKA_ENABLE_KRAFT=yes
[https://github.com/bitnami/containers/blob/96404a3b3e6c2990f20cdbc377d2724d8e502c70/bitnami/kafka/3.4/debian-11/rootfs/opt/bitnami/scripts/kafka-env.sh#LL109C29-L109C29](url)

### Possible drawbacks

no

### Applicable issues

#16275

### Additional information

Yes we can  set env var, but it takes time to find this solution. I spend some time. I think obvius if we set kraft.enabled: true, we  set env vars for kraft to be work automatically, but if set kraft.enabled: false  we also can set parameters to work with zookeeper
```
extraEnvVars:
  - name: KAFKA_ENABLE_KRAFT
    value: "false"
```

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Comment by kimxogus** [comment]
+1

**Comment by corico44** [comment]
Hello @cloud-66,

When testing the chart with this change, I get the following error:
```
$ k describe po sp-ka-kafka-0
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  91s                default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
  Normal   Scheduled         90s                default-scheduler  Successfully assigned default/sp-ka-kafka-0 to minikube
  Normal   Pulled            13s (x4 over 89s)  kubelet            Container image "docker.io/bitnami/kafka:3.4.0-debian-11-r22" already present on machine
  Normal   Created           13s (x4 over 89s)  kubelet            Created container kafka
  Normal   Started           13s (x4 over 89s)  kubelet            Started container kafka
  Warning  BackOff           4s (x6 over 71s)   kubelet            Back-off restarting failed container

$ k logs sp-ka-kafka-0
[2023-05-04 10:40:21,959] INFO Opening socket connection to server localhost/127.0.0.1:2181. (org.apache.zookeeper.ClientCnxn)
[2023-05-04 10:40:21,962] WARN Session 0x0 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
```

**Comment by cloud-66** [comment]
Do you have any custom values in your test ?
I tried without any values and it works.
```
helm pull  oci://registry-1.docker.io/bitnamicharts/kafka
tar xfvz kafka-22.0.1.tgz
vim kafka/templates/statefulset.yaml
```
paste to line 387-389
```
            {{- else }}
            - name: KAFKA_ENABLE_KRAFT
              value: "false"
```
install and it looks healthy
```
helm install kafka ./kafka --set persistence.enabled=false --set zookeeper.persistence.enabled=false
```
изображение

And for my configuration with 3 node zookeeper + 3 node kafka cluster works properly

**Review by corico44 — APPROVED** [review]
LGTM!

**Comment by HerbertYiga** [comment]
hi here, i notice that the introducing KAFKA_ENABLE_KRAFT: "false"  doesn't work , i get a timed out error  as per the logs here https://pastebin.com/h9ENd130  NOTE:Things were working they only started to break after pulling the latest changes, any support on this is welcome!

**Pull request merged**
