### PR TITLE
[bitnami/rabbitmq] Attach existing volume as persistence storage

### LINKED ISSUE #3219: [bitnami/rabbitmq] Attach existing volume as persistence storage
**Which chart**:
rabbitmq

**Describe the bug**
How can I attach existing volume as persistence storage without using `persistence.existingClaim` param (because I am not using dynamic PersistentVolumeClaim)? Currently, I am using the below settings but, it's not working. and it creates dynamic volume everytime. I want to use existing volume from Azure cloud.

    persistence:
      enabled: true
    extraVolumes:
      - name: data-rabbitmq-0
        azureDisk:
          kind: Managed
          diskName: RABBITMQ_DISK_NAME
          diskURI: RABBITMQ_DISK_URI

**To Reproduce**
Create helm chart using above helm values. I am using AKS cluster and Azure storage class.

**Expected behavior**
It should mount volume on existing volume (Managed Disk by Azure).

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"ec831747a3a5896dbdf53f259eafea2a2595217c", GitTreeState:"clean", BuildDate:"2020-05-29T19:56:10Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by ronakthamor**
**Description of the change**

If volume is exist, there should be an option to attach using disk name and disk URI. Volumes can be assigned directly to the pod without creating / using existing PersistentVolumeClaim.

It can be used on azure like this (https://docs.microsoft.com/en-us/azure/aks/azure-disk-volume):

    persistence:
      enabled: true
      volumes:
        - name: data
          azureDisk:
             kind: Managed
             diskName: "static-rabbitmq"
             diskURI: "/subscriptions/*****/resourceGroups/storage-rg/providers/Microsoft.Compute/disks/static-rabbitmq"

**Benefits**

One can attach existing volume without creating PVC directly to the `statefulset`.

**Possible drawbacks**

None. Existing feature is still there. This is an improvement.

**Applicable issues**

  - fixes #3219 

**Checklist**
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

### CODE REVIEW

**Comment by ronakthamor** [comment]
Not sure why the tests are not passing. But, I tested with the use case and it's working perfectly fine and chart is using existing disk on Azure instead of creating PVC.

**Comment by carrodher** [comment]
Thanks for creating this PR, as it is a feature addition can you bump the MINOR version instead of PATCH? In the same way, there are some issues with the `requirements.lock` file, this file shouldn't be updated here

**Comment by ronakthamor** [comment]
@carrodher Thanks for pointing out issues. Now, it's good. Can you please let me know when this feature will be on master branch?

**Review by carrodher — APPROVED** [review]
LGTM

**Pull request merged**
