### PR TITLE
[bitnami/external-dns] Fix Email for Cloudflare

### PR DESCRIPTION
**Pull request by miguelaeh**
**Description of the change**
Fix issue with https://github.com/bitnami/charts/pull/2572

**Benefits**

**Possible drawbacks**

**Applicable issues**

  - fixes #

**Additional information**

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [x] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by lukasmrtvy** [comment]
Is this again waiting for ci ?

**Comment by dani8art** [comment]
Waiting for CI/CD

**Comment by dani8art** [comment]
@miguelaeh Could you update the chart version?

**Comment by miguelaeh** [comment]
Let's launch again the CI/CD after push the version the tags has been removed

**Comment by lukasmrtvy** [comment]
@miguelaeh oh, will it take again 1 day?

**Comment by miguelaeh** [comment]
We cannot provide the exact time, our internal pipeline makes a really big bunch of releases every day, and it depends on which is the current load.

**Pull request merged**
