### PR TITLE
[bitnami/mongodb] Add startup probe

### LINKED ISSUE #4979: [bitnami/mongodb] Add support for startup probe
**Which chart**:
Mongodb

**Is your feature request related to a problem? Please describe.**
I had a mongodb replicaset running on GKE without an explicit cache size or ram limit set. After the replicaset started taking too much ram, I set the limit explicitly. After this, mongodb would not start due to a long running oplog truncation process that would prevent mongodb from getting ready, and thus being killed by the liveness and readiness probes.

**Describe the solution you'd like**
Kubernetes official docs suggest using startup probes to protect pods that might have long running initialization processes. Adding startup probe support to the chart will be useful imo.

### PR DESCRIPTION
**Pull request by krtk6160**
**Description of the change**

Add a startupProbe, so that a slow starting container gets enough time to initialize without getting killed.

**Benefits**

Slow starting containers are often killed by the readiness and liveness probes before they've gotten a chance to fully initialize. Startup probes mitigate that.

**Possible drawbacks**

Available only from Kubernetes 1.16 onwards

**Applicable issues**

  - fixes #4979 

**Additional information**

**Checklist** 

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Review by rafariossaa — APPROVED** [review]
Hi,
  Thanks you very much for providing this !.
  LGTM.

**Comment by rafariossaa** [comment]
Could you provide more info on the scenario you are running mongo ? I am curious about the slowness.

**Comment by krtk6160** [comment]
> Could you provide more info on the scenario you are running mongo ? I am curious about the slowness.

It's a 3 replicaset setup with the wiredTigerCache big enough to accommodate the entire db. I do not remember the exact lines in the logs, but it was a long operation that lasted about (~3-5 mins) and mostly occurred after upgrades.

**Comment by rafariossaa** [comment]
Hi @krtk6160 ,
  Thanks for providing feedback.

**Pull request merged**
