### PR TITLE
[bitnami/spark] Allow release namespace to be overridden through global parameter

### PR DESCRIPTION
**Pull request by rajan123456**
**Description of the change**

Allow users of the chart to override the release namespace through global parameters

**Benefits**

Users will be able to override the release namespace of the chart by passing a global parameter.
In case this chart is used as a sub-chart in an umbrella chart - the parent chart would be able to override the namespace parameter for this chart without affecting other sub-charts directly.

**Possible drawbacks**

None. The --namespace directive would still take precedence if specified.

**Applicable issues**

NA

**Additional information**

NA

**Checklist** 
- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
- [X] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files

:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized mirror.

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the PR! Could you let us know the use case of this and why the `--namespace` of helm install wouldn't work here?

**Comment by rajan123456** [comment]
> Hi,
> 
> Thank you very much for the PR! Could you let us know the use case of this and why the `--namespace` of helm install wouldn't work here?

I am working on an umbrella chart which depends on multiple sub-charts. I would like to install one of the sub-charts (cert-manager) in a different namespace compared to other resources. By passing the '--namespace' directive as part of the install command, all namespaces are set to the same value.

Also, I noticed some of the other charts in this repo provide this setting (mongodb, kafka, etc.),  hence wanted to extend it to the spark chart as well.

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the explanation. So, from what I understand, if we change `global.namespaceOverride` all the subcharts that use this value would be affected, am I right? Would it make sense to allow it as a non-global parameter as well?

**Comment by rajan123456** [comment]
> Hi,
> 
> Thank you very much for the explanation. So, from what I understand, if we change `global.namespaceOverride` all the subcharts that use this value would be affected, am I right? Would it make sense to allow it as a non-global parameter as well?

Hi,

I am not sure if that would be useful. The global parameter is within the scope of the spark chart, so a parent chart can override the global parameter within the spark sub-chart's context; thereby avoiding affecting other sub-charts.

Ex.

umbrella
|- charts
|- |- spark-x.x.x

values.yaml (umbrella)
spark:
  global:
    namespaceOverride: customNamespace

**Comment by javsalgar** [comment]
Hi,

As far as I know, the global parameter is in the scope of all the charts and sub-charts. That's what we use for example for modifying a repository so our charts work with the Azure or AWS marketplaces.

**Comment by rajan123456** [comment]
Hi,

Sorry for the confusion. I was able to work around this requirement for my use case, so I no longer need this change in the chart.

**Pull request closed without merging**
