### PR TITLE
[bitnami/grafana-mimir] Replacing serviceMonitor targetPorts with the right port

### PR DESCRIPTION
**Pull request by valleedelisle**
### Description of the change

`grafana-mimir` charts are configuring some of the servicemonitors with the wrong port.

For example, `mimir-distributor` has its [service configured using a port named http](https://github.com/bitnami/charts/blob/bdfe8ddbeb1bd64316bfb3696caf732884775ca7/bitnami/grafana-mimir/templates/distributor/service.yaml#L39), while its [servicemonitor is pointing on tcp-metrics](https://github.com/bitnami/charts/blob/bdfe8ddbeb1bd64316bfb3696caf732884775ca7/bitnami/grafana-mimir/templates/distributor/servicemonitor.yaml#L30). Because of this, the servicemonitor is not getting discovered by prometheus-operators.

By changing the port to `http`, we're aligning it with the other services like `ingester` and `compactor`.

### Benefits

servicemonitors for all mimir services will be discoverable by prometheus-operators

### Possible drawbacks

AFAIK, none.

### Checklist

- [X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

### CODE REVIEW

**Review by jotamartos — DISMISSED** [review]
LGTM, thank you for your contribution

**Review by jotamartos — APPROVED** [review]

**Comment by priyaGokul** [comment]
Hi. Is the above change part of version - 1.0.2?

**Comment by carrodher** [comment]
This change was included in version 0.9.6 and above, see https://github.com/bitnami/charts/pull/22525/files#diff-acff25531ddaca92e300adc57a4303adb0ab545b8f3e9a33fd25c9271ef95cf1R62

**Comment by priyaGokul** [comment]
@valleedelisle Hi. Thank you for your contribution on the fix. I'm curious why the change doesn't include store-gateway servicemonitors? Is the /path field exposed in metrics section?

**Pull request merged**
