### PR TITLE
[bitnami/grafana-loki] fix for issue# 12195, updated gateway.ingress backend service name/po…

### LINKED ISSUE #12195: [bitnami/grafana-loki] gateway.ingress backend is pointing to wrong serviceName and servicePort
### Name and Version

bitnami/grafana-loki 2.6.1

### What steps will reproduce the bug?

1. create aws eks cluster and have alb-controller running in cluster
2. deploy bitnami/grafana-loki helm-chart of version 2.6.1 with following overridden values
```
    gateway:
      ingress:`
	   enabled: true`
		pathType: ImplementationSpecific
		hostname: <domain_name>.com
		path: /*
		annotations:
			kubernetes.io/ingress.class: alb
			alb.ingress.kubernetes.io/load-balancer-name: your-load-balancer-name
			alb.ingress.kubernetes.io/scheme: internal
			alb.ingress.kubernetes.io/target-type: ip
			alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:<region>:<account_number>:certificate/<id_string>"
			external-dns.alpha.kubernetes.io/hostname: "<domain_name>.com"
```

3. check gateway-ingress object created in eks cluster. you will notice it is not pointing to gateway service.. for example, if deployed helm-chart name is grafana-loki. then gateway-ingress object backend service name is 'grafana-loki' and port is 'http'.  correct backend service name should be 'grafana-loki-gateway' and service port should be '80' (default)

### Are you using any custom parameters or values?

```
gateway:
	ingress:
	   enabled: true
		pathType: ImplementationSpecific
		hostname: <domain_name>.com
		path: /*
		annotations:
			kubernetes.io/ingress.class: alb
			alb.ingress.kubernetes.io/load-balancer-name: your-load-balancer-name
			alb.ingress.kubernetes.io/scheme: internal
			alb.ingress.kubernetes.io/target-type: ip
			alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:<region>:<account_number>:certificate/<id_string>"
			external-dns.alpha.kubernetes.io/hostname: "<domain_name>.com"


```
### What is the expected behavior?

deployed gateway.ingress  object should have backend service name as 'grafana-loki-gateway' and service port should be '80' (default value).
and when we try to access loki using http/https url, we should not get error message 'backend service is not available'

### What do you see instead?

deployed gateway.ingress  object should have backend service name as 'grafana-loki-gateway' and service port should be '80' (default value).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sandeeprohokale**
### Description of the change
Change are limited to bitnami/grafana-loki chart. and these changes are applicable grafan-loki chart is configured to use gateway-ingress. changes are to have gateway.ingress object to point to correct backend service and port which is gateway service

### Benefits
With these changes when granafa-loki chart is deployed with ingress enabled, loki data-source url will not get error message "backend service is not available." and user will be able to successfully configure loki datasource in grafana.

### Possible drawbacks

no brawbacks i can think of.

### Applicable issues
  - fixes #12195 

### Additional information
Tested the changes in aws eks cluster and its working fine

### CODE REVIEW

**Comment by javsalgar** [comment]
Hi!

Thanks for the PR! Could you fix the DCO issue?

**Comment by sandeeprohokale** [comment]
what is DCO ? and exactly what do you expect to fix. please can you
elaborate more.

**Comment by sandeeprohokale** [comment]
Hi,
Updated commit with DCO.

**Comment by sandeeprohokale** [comment]
> Hi!
> 
> Thanks for the PR! Could you fix the DCO issue?

Updated previous commit with DCO

**Comment by javsalgar** [comment]
Hi,

It seems that it is still not working, could you try again?

**Comment by fmulero** [comment]
Hi @sandeeprohokale 

[Here](https://github.com/bitnami/charts/pull/12197/checks?check_run_id=8100289484) you can find concrete instructions to solve the DCO issue.

Also, please increase the version of the helm chart, [this check](https://github.com/bitnami/charts/actions/runs/2959071066/jobs/4733125030) is blaming about that

**Comment by fmulero** [comment]
Hi @sandeeprohokale, sorry to say this but I think we can close this PR, the problem you are trying to fix was already sorted out.

**Pull request closed without merging**
